(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { rows: [], result: null, map: null, layer: null };
  const example = `id,ref_lon,ref_lat,obs_lon,obs_lat,grupo\nP-01,-3.7038,40.4168,-3.70355,40.41695,GNSS\nP-02,-3.6980,40.4182,-3.69762,40.41800,GNSS\nP-03,-3.7120,40.4145,-3.71192,40.41418,GNSS\nP-04,-3.6901,40.4200,-3.69038,40.42012,Cartografía\nP-05,-3.7210,40.4114,-3.72082,40.41168,Cartografía\nP-06,-3.6824,40.4230,-3.68230,40.42292,GNSS\nP-07,-3.6750,40.4190,-3.67456,40.41874,GNSS\nP-08,-3.7300,40.4080,-3.73014,40.40770,Cartografía`;
  const EARTH = 6371008.8;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseLine(line) { const out = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"' && line[i + 1] === '"' && quoted) { value += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ',' || char === '\t' || char === ';')) { out.push(value.trim()); value = ''; } else value += char; } out.push(value.trim()); return out; }
  function parseDelimited(text) { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error('La tabla necesita una cabecera y al menos una fila.'); const headers = parseLine(lines[0]).map((header, index) => header || `campo_${index + 1}`); return lines.slice(1).map((line) => { const values = parseLine(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])); }); }
  function norm(value) { return String(value ?? '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, ''); }
  function score(field, candidates) { const value = norm(field); return candidates.reduce((best, candidate, index) => Math.max(best, value === norm(candidate) ? 100 - index : value.includes(norm(candidate)) ? 45 - index : 0), 0); }
  function best(fields, candidates, excluded = []) { return fields.filter((field) => !excluded.includes(field)).map((field) => ({ field, score: score(field, candidates) })).sort((a, b) => b.score - a.score)[0]?.score > 0 ? fields.filter((field) => !excluded.includes(field)).map((field) => ({ field, score: score(field, candidates) })).sort((a, b) => b.score - a.score)[0].field : ''; }
  function optionList(empty, fields, selected) { return [`<option value="">${escapeHtml(empty)}</option>`, ...fields.map((field) => `<option value="${escapeHtml(field)}"${field === selected ? ' selected' : ''}>${escapeHtml(field)}</option>`)].join(''); }
  function chooseFields(rows) { state.rows = rows; const fields = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const refLon = best(fields, ['ref_lon', 'reference_lon', 'referencia_lon', 'lon_ref', 'x_ref', 'longitude_reference', 'longitud_referencia']); const refLat = best(fields, ['ref_lat', 'reference_lat', 'referencia_lat', 'lat_ref', 'y_ref', 'latitude_reference', 'latitud_referencia']); const obsLon = best(fields, ['obs_lon', 'observed_lon', 'observada_lon', 'lon_obs', 'x_obs', 'gps_lon', 'longitude_observed', 'longitud_observada']); const obsLat = best(fields, ['obs_lat', 'observed_lat', 'observada_lat', 'lat_obs', 'y_obs', 'gps_lat', 'latitude_observed', 'latitud_observada']); const used = [refLon, refLat, obsLon, obsLat].filter(Boolean); $('idField').innerHTML = optionList('Índice de fila', fields, best(fields, ['id', 'identifier', 'identificador', 'name', 'nombre'])); $('refLonField').innerHTML = optionList('Selecciona longitud', fields, refLon); $('refLatField').innerHTML = optionList('Selecciona latitud', fields, refLat); $('obsLonField').innerHTML = optionList('Selecciona longitud', fields, obsLon); $('obsLatField').innerHTML = optionList('Selecciona latitud', fields, obsLat); $('groupField').innerHTML = optionList('Sin grupo', fields.filter((field) => !used.includes(field)), best(fields, ['group', 'grupo', 'source', 'fuente', 'method', 'metodo'], used)); setStatus(`${rows.length.toLocaleString('es-ES')} filas detectadas. Revisa los campos y evalúa la precisión.`); }
  function number(value) { const raw = String(value ?? '').trim().replace(',', '.'); if (!raw) return null; const n = Number(raw); return Number.isFinite(n) ? n : null; }
  function valid(lon, lat) { return Number.isFinite(lon) && Number.isFinite(lat) && Math.abs(lon) <= 180 && Math.abs(lat) <= 90; }
  function distance(refLon, refLat, obsLon, obsLat) { const p1 = refLat * Math.PI / 180; const p2 = obsLat * Math.PI / 180; const dLat = (obsLat - refLat) * Math.PI / 180; const dLon = (obsLon - refLon) * Math.PI / 180; const a = Math.sin(dLat / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dLon / 2) ** 2; return 2 * EARTH * Math.atan2(Math.sqrt(a), Math.sqrt(Math.max(0, 1 - a))); }
  function metrics(refLon, refLat, obsLon, obsLat) { const meanLat = (refLat + obsLat) / 2 * Math.PI / 180; const dx = (obsLon - refLon) * Math.PI / 180 * EARTH * Math.cos(meanLat); const dy = (obsLat - refLat) * Math.PI / 180 * EARTH; const error = Math.hypot(dx, dy); const bearing = (Math.atan2(dx, dy) * 180 / Math.PI + 360) % 360; return { dx, dy, error, bearing }; }
  function quantile(values, q) { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return null; const pos = (sorted.length - 1) * q; const base = Math.floor(pos); const rest = pos - base; return sorted[base + 1] !== undefined ? sorted[base] + rest * (sorted[base + 1] - sorted[base]) : sorted[base]; }
  function analyze() { const fields = ['refLonField', 'refLatField', 'obsLonField', 'obsLatField'].map((id) => $(id).value); if (fields.some((field) => !field)) throw new Error('Selecciona las cuatro coordenadas: referencia y observada.'); const [refLonField, refLatField, obsLonField, obsLatField] = fields; const idField = $('idField').value; const groupField = $('groupField').value; const records = state.rows.map((row, index) => { const refLon = number(row[refLonField]); const refLat = number(row[refLatField]); const obsLon = number(row[obsLonField]); const obsLat = number(row[obsLatField]); if (!valid(refLon, refLat) || !valid(obsLon, obsLat)) return null; return { row, index, id: idField ? String(row[idField] ?? '').trim() || `Fila ${index + 1}` : `Fila ${index + 1}`, group: groupField ? String(row[groupField] ?? '').trim() || 'Sin grupo' : 'Sin grupo', refLon, refLat, obsLon, obsLat, ...metrics(refLon, refLat, obsLon, obsLat) }; }).filter(Boolean); if (!records.length) throw new Error('No hay pares con cuatro coordenadas WGS84 válidas.'); const errors = records.map((record) => record.error); const sumSq = records.reduce((sum, record) => sum + record.error ** 2, 0); const meanDx = records.reduce((sum, record) => sum + record.dx, 0) / records.length; const meanDy = records.reduce((sum, record) => sum + record.dy, 0) / records.length; state.result = { records, fields: { idField, groupField, refLonField, refLatField, obsLonField, obsLatField }, rmse: Math.sqrt(sumSq / records.length), meanError: errors.reduce((sum, value) => sum + value, 0) / records.length, cep50: quantile(errors, .5), p95: quantile(errors, .95), maxError: Math.max(...errors), meanDx, meanDy }; render(); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = false); setStatus(`${records.length.toLocaleString('es-ES')} pares válidos. Se han descartado ${state.rows.length - records.length} fila(s) sin coordenadas utilizables.`); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function render() { const r = state.result; $('summary').hidden = $('detailPanel').hidden = false; $('pairCount').textContent = r.records.length.toLocaleString('es-ES'); $('rmse').textContent = `${format(r.rmse)} m`; $('meanError').textContent = `${format(r.meanError)} m`; $('cep50').textContent = `${format(r.cep50)} m`; $('p95').textContent = `${format(r.p95)} m`; $('maxError').textContent = `${format(r.maxError)} m`; $('summaryBadge').textContent = `${r.records.length.toLocaleString('es-ES')} pares`; $('detailBadge').textContent = `${new Set(r.records.map((record) => record.group)).size} grupos`; $('interpretation').textContent = `Sesgo medio: ${format(r.meanDx)} m este y ${format(r.meanDy)} m norte. El rumbo indica hacia dónde se desplaza la observación respecto a la referencia. Estos indicadores resumen la muestra cargada y no estiman por sí solos precisión posicional normativa.`; $('detailBody').innerHTML = r.records.slice().sort((a, b) => b.error - a.error).map((record) => `<tr><th>${escapeHtml(record.id)}</th><td>${escapeHtml(record.group)}</td><td class="${record.error > r.p95 ? 'error-high' : 'error-low'}">${format(record.error)} m</td><td>${format(record.bearing, 1)}°</td><td>${format(record.dx)} m</td><td>${format(record.dy)} m</td><td>${format(record.refLon, 6)}, ${format(record.refLat, 6)}</td><td>${format(record.obsLon, 6)}, ${format(record.obsLat, 6)}</td></tr>`).join(''); $('chartBadge').textContent = `${r.records.length.toLocaleString('es-ES')} vectores`; renderChart(); renderMap(); }
  function renderChart() { const canvas = $('chart'); const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; canvas.width = Math.max(1, rect.width * dpr); canvas.height = Math.max(1, rect.height * dpr); const ctx = canvas.getContext('2d'); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); const width = rect.width; const height = rect.height; ctx.clearRect(0, 0, width, height); const values = state.result.records.map((record) => record.error); const max = Math.max(...values, 1); const bins = Math.min(12, Math.max(5, Math.ceil(Math.sqrt(values.length)))); const counts = Array.from({ length: bins }, () => 0); values.forEach((value) => counts[Math.min(bins - 1, Math.floor(value / max * bins))] += 1); const left = 48; const right = 20; const top = 20; const bottom = 42; const plotWidth = width - left - right; const plotHeight = height - top - bottom; const maxCount = Math.max(...counts, 1); ctx.font = '12px system-ui'; ctx.fillStyle = '#687a71'; ctx.strokeStyle = '#d7e6dd'; ctx.lineWidth = 1; for (let i = 0; i <= 4; i += 1) { const y = top + plotHeight * i / 4; ctx.beginPath(); ctx.moveTo(left, y); ctx.lineTo(width - right, y); ctx.stroke(); ctx.fillText(String(Math.round(maxCount - maxCount * i / 4)), 10, y + 4); } counts.forEach((count, index) => { const barWidth = plotWidth / bins - 6; const x = left + index * plotWidth / bins + 3; const barHeight = count / maxCount * plotHeight; ctx.fillStyle = '#4c9b7b'; ctx.fillRect(x, top + plotHeight - barHeight, barWidth, barHeight); }); ctx.fillStyle = '#687a71'; ctx.fillText('0 m', left, height - 14); const maxLabel = `${format(max)} m`; ctx.fillText(maxLabel, Math.max(left, width - right - ctx.measureText(maxLabel).width), height - 14); $('chartFallback').textContent = `${bins} intervalos. Cada barra muestra el número de pares dentro del rango de error.`; }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); const layers = []; state.result.records.forEach((record) => { const line = L.polyline([[record.refLat, record.refLon], [record.obsLat, record.obsLon]], { color: '#a33d50', weight: 2, opacity: .8, dashArray: '5 5' }).bindPopup(`<strong>${escapeHtml(record.id)}</strong><div>${escapeHtml(record.group)}<br>Error: ${format(record.error)} m<br>Rumbo: ${format(record.bearing, 1)}°<br>Δ este/norte: ${format(record.dx)} / ${format(record.dy)} m</div>`); const ref = L.circleMarker([record.refLat, record.refLon], { radius: 6, color: '#204e7c', fillColor: '#5f9bd1', fillOpacity: .95, weight: 1 }).bindTooltip(`${escapeHtml(record.id)} · referencia`); const obs = L.circleMarker([record.obsLat, record.obsLon], { radius: 5, color: '#833a45', fillColor: '#d46a75', fillOpacity: .95, weight: 1 }).bindTooltip(`${escapeHtml(record.id)} · observada`); layers.push(line, ref, obs); }); state.layer = L.layerGroup(layers).addTo(state.map); $('mapBadge').textContent = `${state.result.records.length.toLocaleString('es-ES')} vectores`; const bounds = L.latLngBounds(state.result.records.flatMap((record) => [[record.refLat, record.refLon], [record.obsLat, record.obsLon]])); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [35, 35], maxZoom: 17 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function report() { const r = state.result; if (!r) return; download('positional-accuracy-report.json', JSON.stringify({ assumptions: { crs: 'WGS84 geographic lon/lat', distance: 'Haversine plus local east/north components', units: 'metres' }, fields: r.fields, pairs: r.records.length, discarded_rows: state.rows.length - r.records.length, metrics: { rmse_2d_m: r.rmse, mean_error_m: r.meanError, cep50_m: r.cep50, p95_m: r.p95, max_error_m: r.maxError, mean_east_m: r.meanDx, mean_north_m: r.meanDy }, records: r.records.map((record) => ({ id: record.id, group: record.group, ref_lon: record.refLon, ref_lat: record.refLat, obs_lon: record.obsLon, obs_lat: record.obsLat, error_m: record.error, bearing_deg: record.bearing, east_m: record.dx, north_m: record.dy })) }, null, 2), 'application/json'); }
  function csv() { const r = state.result; if (!r) return; const rows = [['id', 'group', 'ref_lon', 'ref_lat', 'obs_lon', 'obs_lat', 'error_m', 'bearing_deg', 'east_m', 'north_m'], ...r.records.map((record) => [record.id, record.group, record.refLon, record.refLat, record.obsLon, record.obsLat, record.error, record.bearing, record.dx, record.dy])]; download('positional-accuracy-annotated.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function geojson() { const r = state.result; if (!r) return; const features = r.records.flatMap((record) => [{ type: 'Feature', properties: { id: record.id, group: record.group, role: 'reference', error_m: record.error, bearing_deg: record.bearing }, geometry: { type: 'Point', coordinates: [record.refLon, record.refLat] } }, { type: 'Feature', properties: { id: record.id, group: record.group, role: 'observed', error_m: record.error, bearing_deg: record.bearing }, geometry: { type: 'Point', coordinates: [record.obsLon, record.obsLat] } }, { type: 'Feature', properties: { id: record.id, group: record.group, role: 'displacement', error_m: record.error, bearing_deg: record.bearing, east_m: record.dx, north_m: record.dy }, geometry: { type: 'LineString', coordinates: [[record.refLon, record.refLat], [record.obsLon, record.obsLat]] } }]); download('positional-accuracy-vectors.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json'); }
  function loadText(text) { $('source').value = text; try { chooseFields(parseDelimited(text)); } catch (error) { setStatus(error.message || 'No se pudieron detectar los datos.', true); } }
  function clearAll() { state.rows = []; state.result = null; $('source').value = ''; $('fileInput').value = ''; ['idField', 'refLonField', 'refLatField', 'obsLonField', 'obsLatField', 'groupField'].forEach((id) => { $(id).innerHTML = '<option value="">Carga datos para detectar campos</option>'; }); $('summary').hidden = $('detailPanel').hidden = true; ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = true); state.layer?.remove(); state.layer = null; $('mapBadge').textContent = '—'; $('chartFallback').textContent = 'El histograma aparecerá tras evaluar los puntos.'; setStatus('Carga una tabla para detectar las coordenadas.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', () => loadText(example)); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { chooseFields(parseDelimited($('source').value)); analyze(); } catch (error) { setStatus(error.message || 'No se pudo evaluar la precisión.', true); } }); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { loadText(await file.text()); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id, index) => $(id).addEventListener('click', [report, csv, geojson][index])); window.addEventListener('resize', () => { if (state.result) renderChart(); }); $('source').value = example; initMap();
})();
