(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { zones: [], targets: [], output: null, matches: [], map: null, zoneLayer: null, targetLayer: null };
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const exampleZones = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'Sector oeste' }, geometry: { type: 'Polygon', coordinates: [[[-3.75, 40.40], [-3.70, 40.40], [-3.70, 40.45], [-3.75, 40.45], [-3.75, 40.40]]] } }, { type: 'Feature', properties: { name: 'Sector este' }, geometry: { type: 'Polygon', coordinates: [[[-3.70, 40.40], [-3.65, 40.40], [-3.65, 40.45], [-3.70, 40.45], [-3.70, 40.40]]] } }] };
  const exampleTargets = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { site: 'Observación A' }, geometry: { type: 'Point', coordinates: [-3.73, 40.425] } }, { type: 'Feature', properties: { site: 'Observación B' }, geometry: { type: 'Point', coordinates: [-3.675, 40.425] } }, { type: 'Feature', properties: { site: 'Observación C' }, geometry: { type: 'Point', coordinates: [-3.79, 40.43] } }] };

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function parseInput(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input.features; if (input.type === 'Feature') return [input]; if (typeof input.type === 'string' && depths[input.type] !== undefined) return [{ type: 'Feature', properties: {}, geometry: input }]; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON reconocible.'); }
  function positions(geometry, output = []) { if (!geometry || typeof geometry !== 'object') return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child) => positions(child, output)); return output; } const depth = depths[geometry.type]; if (depth === undefined) return output; const walk = (node, level) => { if (level === 0) { if (isPosition(node)) output.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return output; }
  function geometryBbox(geometry) { const points = positions(geometry); if (!points.length) return null; return points.reduce((bbox, point) => [Math.min(bbox[0], point[0]), Math.min(bbox[1], point[1]), Math.max(bbox[2], point[0]), Math.max(bbox[3], point[1])], [points[0][0], points[0][1], points[0][0], points[0][1]]); }
  function bboxContains(bbox, point) { return !bbox || (point[0] >= bbox[0] && point[0] <= bbox[2] && point[1] >= bbox[1] && point[1] <= bbox[3]); }
  function pointOnSegment(point, a, b) { const cross = (point[1] - a[1]) * (b[0] - a[0]) - (point[0] - a[0]) * (b[1] - a[1]); if (Math.abs(cross) > 1e-10) return false; return point[0] >= Math.min(a[0], b[0]) - 1e-10 && point[0] <= Math.max(a[0], b[0]) + 1e-10 && point[1] >= Math.min(a[1], b[1]) - 1e-10 && point[1] <= Math.max(a[1], b[1]) + 1e-10; }
  function ringContains(point, ring) { if (!Array.isArray(ring) || ring.length < 3) return false; let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const a = ring[previous], b = ring[index]; if (!isPosition(a) || !isPosition(b)) continue; if (pointOnSegment(point, a, b)) return true; const intersects = ((b[1] > point[1]) !== (a[1] > point[1])) && point[0] < (a[0] - b[0]) * (point[1] - b[1]) / (a[1] - b[1]) + b[0]; if (intersects) inside = !inside; } return inside; }
  function polygonContains(point, polygon) { if (!Array.isArray(polygon) || !ringContains(point, polygon[0])) return false; return !(polygon.slice(1).some((hole) => ringContains(point, hole))); }
  function geometryContains(point, geometry) { if (!geometry || typeof geometry !== 'object') return false; if (geometry.type === 'Polygon') return polygonContains(point, geometry.coordinates); if (geometry.type === 'MultiPolygon') return (geometry.coordinates || []).some((polygon) => polygonContains(point, polygon)); if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).some((child) => geometryContains(point, child)); return false; }
  function representative(feature) { const points = positions(feature?.geometry); if (!points.length) return null; if (feature.geometry.type === 'Point') return points[0]; return points.reduce((sum, point) => [sum[0] + point[0], sum[1] + point[1]], [0, 0]).map((value) => value / points.length); }
  function zoneName(feature, index) { const key = $('zoneKey').value.trim() || 'name'; const value = feature?.properties?.[key]; return value === undefined || value === null || value === '' ? `Zona ${index + 1}` : String(value); }
  function runJoin() { if (!state.zones.length || !state.targets.length) return; const zoneData = state.zones.map((feature, index) => ({ feature, index, bbox: geometryBbox(feature.geometry), name: zoneName(feature, index), count: 0 })); let matched = 0; state.matches = state.targets.map((feature, targetIndex) => { const point = representative(feature); const zone = point ? zoneData.find((candidate) => bboxContains(candidate.bbox, point) && geometryContains(point, candidate.feature.geometry)) : null; if (zone) { zone.count += 1; matched += 1; } return { targetIndex, point, zone }; }); state.output = { type: 'FeatureCollection', features: state.targets.map((feature, index) => { const item = state.matches[index]; const properties = isObject(feature.properties) ? clone(feature.properties) : {}; properties.spatial_join = item.zone ? { matched: true, zone_index: item.zone.index + 1, zone_name: item.zone.name, representative: item.point } : { matched: false, representative: item.point }; return { ...clone(feature), properties }; }) }; render(zoneData, matched); drawMap(); }
  function isObject(value) { return value !== null && typeof value === 'object' && !Array.isArray(value); }
  function render(zoneData, matched) { const unmatched = state.targets.length - matched; $('summary').hidden = false; $('zoneCount').textContent = state.zones.length.toLocaleString('es-ES'); $('targetCount').textContent = state.targets.length.toLocaleString('es-ES'); $('matchedCount').textContent = matched.toLocaleString('es-ES'); $('unmatchedCount').textContent = unmatched.toLocaleString('es-ES'); const tbody = $('summaryTable'); tbody.replaceChildren(); zoneData.forEach((zone) => { const row = tbody.insertRow(); row.insertCell().textContent = zone.name; row.insertCell().textContent = zone.count.toLocaleString('es-ES'); }); $('status').textContent = `${state.targets.length} observaciones procesadas: ${matched} asignadas y ${unmatched} sin zona.`; ['downloadBtn', 'csvBtn'].forEach((id) => { $(id).disabled = false; }); }
  function updateReady() { $('runBtn').disabled = !(state.zones.length && state.targets.length); if (state.zones.length || state.targets.length) $('status').textContent = `Zonas: ${state.zones.length} · observaciones: ${state.targets.length}.`; }
  async function readFile(file, kind) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { const features = parseInput(JSON.parse(await file.text())); state[kind] = features; updateReady(); if (state.zones.length && state.targets.length) runJoin(); } catch (error) { $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value).replace(/"/g, '""'); return /[",\n]/.test(text) ? `"${text}"` : text; }
  function download(text, name, mime) { const url = URL.createObjectURL(new Blob([text], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function mapPointFeature(feature, index) { const item = state.matches[index]; const point = item?.point || representative(feature); if (!point) return null; return { type: 'Feature', properties: feature.properties || {}, geometry: { type: 'Point', coordinates: point } }; }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function drawMap() { if (!state.map) return; state.zoneLayer?.remove(); state.targetLayer?.remove(); const zoneFeatures = state.zones.filter((feature) => feature?.type === 'Feature' && (feature.geometry?.type === 'Polygon' || feature.geometry?.type === 'MultiPolygon')); const targetFeatures = state.targets.map(mapPointFeature).filter(Boolean); try { if (zoneFeatures.length) state.zoneLayer = L.geoJSON({ type: 'FeatureCollection', features: zoneFeatures }, { color: '#76a9ff', weight: 2, fillColor: '#76a9ff', fillOpacity: .12, onEachFeature: (feature, layer) => layer.bindPopup(`<b>${zoneName(feature, state.zones.indexOf(feature))}</b>`) }).addTo(state.map); if (targetFeatures.length) state.targetLayer = L.geoJSON({ type: 'FeatureCollection', features: targetFeatures }, { pointToLayer: (feature, latlng) => { const matched = feature.properties?.spatial_join?.matched; return L.circleMarker(latlng, { radius: 7, color: matched ? '#5bd6a5' : '#ff7e87', fillColor: matched ? '#5bd6a5' : '#ff7e87', fillOpacity: .9, weight: 2 }); }, onEachFeature: (feature, layer) => layer.bindPopup(`<pre>${escapeHtml(JSON.stringify(feature.properties || {}, null, 2))}</pre>`) }).addTo(state.map); const bounds = (state.zoneLayer || state.targetLayer)?.getBounds(); if (bounds?.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); } catch { $('status').textContent += ' El mapa no pudo dibujar alguna geometría; la exportación sigue disponible.'; } }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  $('zoneInput').addEventListener('change', () => readFile($('zoneInput').files?.[0], 'zones')); $('targetInput').addEventListener('change', () => readFile($('targetInput').files?.[0], 'targets')); $('zoneKey').addEventListener('change', () => { if (state.zones.length && state.targets.length) runJoin(); }); $('runBtn').addEventListener('click', runJoin); $('exampleBtn').addEventListener('click', () => { state.zones = clone(exampleZones.features); state.targets = clone(exampleTargets.features); updateReady(); runJoin(); }); $('downloadBtn').addEventListener('click', () => { if (state.output) download(JSON.stringify(state.output, null, 2), 'spatial-join.geojson', 'application/geo+json'); }); $('csvBtn').addEventListener('click', () => { const zoneData = state.zones.map((feature, index) => ({ name: zoneName(feature, index), count: state.matches.filter((item) => item.zone?.index === index).length })); const rows = [['zona', 'elementos'], ...zoneData.map((zone) => [zone.name, zone.count])]; download(rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'spatial-join-resumen.csv', 'text/csv;charset=utf-8'); }); $('clearBtn').addEventListener('click', () => { state.zones = []; state.targets = []; state.output = null; state.matches = []; state.zoneLayer?.remove(); state.targetLayer?.remove(); $('summary').hidden = true; $('runBtn').disabled = true; ['downloadBtn', 'csvBtn'].forEach((id) => { $(id).disabled = true; }); $('status').textContent = 'Carga una capa de zonas y otra de observaciones.'; }); initMap();
})();
