(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { grids: {}, result: null, map: null, layer: null };
  const exampleA = { rows: 8, cols: 10, values: [120,124,128,132,135,138,140,141,142,143,118,122,126,130,133,136,138,139,140,141,115,119,123,127,130,133,135,137,138,139,112,116,120,124,127,130,132,134,135,136,109,113,117,121,124,127,129,131,132,133,106,110,114,118,121,124,126,128,129,130,103,107,111,115,118,121,123,125,126,127,100,104,108,112,115,118,120,122,123,124] };
  const exampleB = { rows: 8, cols: 10, values: [92,94,96,98,100,102,103,104,105,106,91,93,95,97,99,101,102,103,104,105,90,92,94,96,98,100,101,102,103,104,89,91,93,95,97,99,100,101,102,103,88,90,92,94,96,98,99,100,101,102,87,89,91,93,95,97,98,99,100,101,86,88,90,92,94,96,97,98,99,100,85,87,89,91,93,95,96,97,98,99] };
  const exampleC = { rows: 8, cols: 10, values: [40,41,42,43,44,45,46,47,48,49,41,42,43,44,45,46,47,48,49,50,42,43,44,45,46,47,48,49,50,51,43,44,45,46,47,48,49,50,51,52,44,45,46,47,48,49,50,51,52,53,45,46,47,48,49,50,51,52,53,54,46,47,48,49,50,51,52,53,54,55,47,48,49,50,51,52,53,54,55,56] };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function formatNumber(value, digits = 3) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseRows(rows) { if (!Array.isArray(rows) || rows.length < 2) throw new Error('La malla necesita al menos 2 filas.'); const cols = rows[0]?.length || 0; if (cols < 2 || cols > 200 || rows.length > 200) throw new Error('La malla debe tener entre 2 y 200 filas y columnas.'); if (rows.some((row) => !Array.isArray(row) || row.length !== cols)) throw new Error('Todas las filas deben tener el mismo número de columnas.'); return { rows: rows.length, cols, values: rows.flat() }; }
  function parseText(text) { const clean = text.trim(); if (!clean) throw new Error('Introduce una malla.'); if (clean.startsWith('{') || clean.startsWith('[')) { const parsed = JSON.parse(clean); if (Array.isArray(parsed)) return parseRows(parsed); const rows = Number(parsed.rows); const cols = Number(parsed.cols); const values = Array.isArray(parsed.values) ? parsed.values : Array.isArray(parsed.data) ? parsed.data : null; if (!Number.isInteger(rows) || !Number.isInteger(cols) || !values) throw new Error('El JSON debe contener rows, cols y values.'); return { rows, cols, values }; } return parseRows(clean.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => line.split(/[;,\t]+/).map((value) => Number(value.trim().replace(',', '.'))))); }
  function sanitize(grid) { if (!Number.isInteger(grid.rows) || !Number.isInteger(grid.cols) || grid.rows < 2 || grid.cols < 2 || grid.rows > 200 || grid.cols > 200) throw new Error('La malla debe tener entre 2 y 200 filas y columnas.'); if (grid.values.length !== grid.rows * grid.cols) throw new Error(`Se esperaban ${grid.rows * grid.cols} valores y se recibieron ${grid.values.length}.`); return { rows: grid.rows, cols: grid.cols, values: grid.values.map((value) => value === null || value === '' || !Number.isFinite(Number(value)) ? null : Number(value)) }; }
  function expression() { return $('expressionPreset').value === 'custom' ? $('customExpression').value.trim() : $('expressionPreset').value; }
  function compileExpression(raw) { const clean = raw.replace(/−/g, '-').trim(); if (!clean || !/^[ABCabc0-9+*/().\-\s]+$/.test(clean)) throw new Error('La expresión solo puede usar A, B, C, números, +, −, *, / y paréntesis.'); const normalized = clean.toUpperCase(); try { const fn = Function('A', 'B', 'C', `"use strict"; return (${normalized});`); return (a, b, c) => { const value = fn(a, b, c); return Number.isFinite(value) ? value : null; }; } catch { throw new Error('La expresión no es válida. Revisa los paréntesis y operadores.'); } }
  function requireGrids(expr) { const needed = [...new Set((expr.match(/[ABC]/g) || []))]; needed.forEach((key) => { if (!state.grids[key]) throw new Error(`La expresión usa ${key}, pero no hay una malla ${key} válida.`); }); const first = state.grids.A; Object.entries(state.grids).forEach(([key, grid]) => { if (grid && (grid.rows !== first.rows || grid.cols !== first.cols)) throw new Error(`La malla ${key} no coincide con las dimensiones de A.`); }); }
  function calc() {
    const expr = expression().toUpperCase().replace(/−/g, '-'); requireGrids(expr); const fn = compileExpression(expr); const first = state.grids.A; const values = first.values.map((_, i) => { const a = state.grids.A?.values[i]; const b = state.grids.B?.values[i]; const c = state.grids.C?.values[i]; if (![a, b, c].every((value, pos) => !expr.includes('ABC'[pos]) || Number.isFinite(value))) return null; return fn(a, b, c); }); const valid = values.map((value, i) => value === null ? -1 : i).filter((i) => i >= 0); const numeric = valid.map((i) => values[i]); if (!numeric.length) throw new Error('No hay celdas válidas para calcular la expresión.'); const min = Math.min(...numeric); const max = Math.max(...numeric); const mean = numeric.reduce((sum, value) => sum + value, 0) / numeric.length; state.result = { expr, values, valid, min, max, mean, rows: first.rows, cols: first.cols, cellSize: Math.max(1, Math.min(100000, Number($('cellSize').value) || 100)), west: Number($('west').value) || 0, south: Number($('south').value) || 0 }; $('cellSize').value = state.result.cellSize; $('summary').hidden = $('tablePanel').hidden = false; $('gridLabel').textContent = `${first.rows} × ${first.cols}`; $('formulaBadge').textContent = expr; $('validCount').textContent = first.values.filter((value) => Number.isFinite(value)).length.toLocaleString('es-ES'); $('resultCount').textContent = numeric.length.toLocaleString('es-ES'); $('missingCount').textContent = (values.length - numeric.length).toLocaleString('es-ES'); $('minValue').textContent = formatNumber(min); $('maxValue').textContent = formatNumber(max); $('meanValue').textContent = formatNumber(mean); $('interpretation').textContent = `Expresión ${expr}: rango ${formatNumber(min)}–${formatNumber(max)}, media ${formatNumber(mean)}. Las celdas con datos faltantes o divisiones no finitas quedan sin dato.`; renderHistogram(numeric); renderTable(); renderMap(); $('geojsonBtn').disabled = $('csvBtn').disabled = false; setStatus(`${numeric.length} celdas calculadas con ${expr}.`); }
  function box(index) { const row = Math.floor(index / state.result.cols); const col = index % state.result.cols; const latStep = state.result.cellSize / 110540; const midLat = state.result.south + state.result.rows * latStep / 2; const lonStep = state.result.cellSize / (111320 * Math.max(.15, Math.cos(midLat * Math.PI / 180))); const minLon = state.result.west + col * lonStep; const minLat = state.result.south + row * latStep; return { row, col, minLon, minLat, maxLon: minLon + lonStep, maxLat: minLat + latStep }; }
  function feature(index) { const b = box(index); const value = state.result.values[index]; return { type: 'Feature', properties: { row: b.row + 1, column: b.col + 1, expression: state.result.expr, value, a: state.grids.A.values[index], b: state.grids.B?.values[index] ?? null, c: state.grids.C?.values[index] ?? null }, geometry: { type: 'Polygon', coordinates: [[[b.minLon, b.minLat], [b.maxLon, b.minLat], [b.maxLon, b.maxLat], [b.minLon, b.maxLat], [b.minLon, b.minLat]]] } }; }
  function color(value) { const { min, max } = state.result; if (min === max) return '#67e6c1'; const ratio = (value - min) / (max - min); if (ratio < .25) return '#284cbd'; if (ratio < .5) return '#3c9ab0'; if (ratio < .75) return '#67e6c1'; return '#ed755e'; }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); const features = state.result.valid.map(feature); state.layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: (item) => ({ color: '#eaffff', weight: .45, opacity: .32, fillColor: color(item.properties.value), fillOpacity: .74 }), onEachFeature: (item, layer) => layer.bindPopup(`<strong>Fila ${item.properties.row}, columna ${item.properties.column}</strong><div class="popup-stat">Resultado: ${formatNumber(item.properties.value)}<br>A: ${formatNumber(item.properties.a)} · B: ${formatNumber(item.properties.b)}${item.properties.c === null ? '' : ` · C: ${formatNumber(item.properties.c)}`}</div>`) }).addTo(state.map); const latStep = state.result.cellSize / 110540; const midLat = state.result.south + state.result.rows * latStep / 2; const lonStep = state.result.cellSize / (111320 * Math.max(.15, Math.cos(midLat * Math.PI / 180))); state.map.fitBounds([[state.result.south, state.result.west], [state.result.south + state.result.rows * latStep, state.result.west + state.result.cols * lonStep]], { padding: [24, 24], maxZoom: 16 }); }
  function renderTable() { const sorted = [...state.result.valid].sort((a, b) => Math.abs(state.result.values[b]) - Math.abs(state.result.values[a])).slice(0, 40); $('resultsBody').innerHTML = sorted.map((i) => { const b = box(i); return `<tr><td>${b.row + 1}</td><td>${b.col + 1}</td><td>${formatNumber(state.grids.A.values[i])}</td><td>${formatNumber(state.grids.B?.values[i])}</td><td>${formatNumber(state.result.values[i])}</td><td>${b.minLon.toFixed(5)}</td><td>${b.minLat.toFixed(5)}</td></tr>`; }).join(''); }
  function renderHistogram(values) { const bins = Array.from({ length: 18 }, () => 0); const { min, max } = state.result; values.forEach((value) => { const index = min === max ? 8 : Math.min(17, Math.max(0, Math.floor(((value - min) / (max - min)) * 18))); bins[index] += 1; }); const peak = Math.max(...bins, 1); $('histogram').innerHTML = bins.map((count) => `<i title="${count} celdas" style="height:${Math.max(4, count / peak * 92)}px"></i>`).join(''); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function exportGeoJSON() { if (!state.result) return; download('raster-algebra-lab.geojson', JSON.stringify({ type: 'FeatureCollection', features: state.result.valid.map(feature) }, null, 2), 'application/geo+json'); }
  function exportCsv() { if (!state.result) return; const rows = [['row', 'column', 'a', 'b', 'c', 'result', 'expression', 'center_lon', 'center_lat'], ...state.result.valid.map((i) => { const b = box(i); return [b.row + 1, b.col + 1, state.grids.A.values[i], state.grids.B?.values[i] ?? '', state.grids.C?.values[i] ?? '', state.result.values[i], state.result.expr, (b.minLon + b.maxLon) / 2, (b.minLat + b.maxLat) / 2]; })]; download('raster-algebra-lab.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  async function readFile(input, target) { const file = input.files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { state.grids[target] = sanitize(parseText(await file.text())); $(`source${target}`).value = JSON.stringify(state.grids[target], null, 2); setStatus(`Malla ${target} cargada desde ${file.name}.`); } catch (error) { setStatus(error.message || `No se pudo leer la malla ${target}.`, true); } }
  function loadExample() { state.grids = { A: sanitize(exampleA), B: sanitize(exampleB), C: sanitize(exampleC) }; $('sourceA').value = JSON.stringify(exampleA, null, 2); $('sourceB').value = JSON.stringify(exampleB, null, 2); $('sourceC').value = JSON.stringify(exampleC, null, 2); $('expressionPreset').value = 'A-B'; calc(); }
  function clearAll() { state.grids = {}; state.result = null; ['sourceA', 'sourceB', 'sourceC'].forEach((id) => $(id).value = ''); ['fileA', 'fileB', 'fileC'].forEach((id) => $(id).value = ''); $('summary').hidden = $('tablePanel').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = true; state.layer?.remove(); state.layer = null; setStatus('Carga dos mallas o usa el ejemplo. Todo se procesa en este dispositivo.'); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }

  $('expressionPreset').addEventListener('change', () => { $('customExpressionWrap').hidden = $('expressionPreset').value !== 'custom'; if (state.grids.A) { try { calc(); } catch (error) { setStatus(error.message, true); } } });
  $('customExpression').addEventListener('change', () => { if (state.grids.A) { try { calc(); } catch (error) { setStatus(error.message, true); } } });
  $('exampleBtn').addEventListener('click', () => { try { loadExample(); } catch (error) { setStatus(error.message, true); } });
  $('clearBtn').addEventListener('click', clearAll);
  $('runBtn').addEventListener('click', () => { try { state.grids.A = sanitize(parseText($('sourceA').value)); state.grids.B = $('sourceB').value.trim() ? sanitize(parseText($('sourceB').value)) : null; state.grids.C = $('sourceC').value.trim() ? sanitize(parseText($('sourceC').value)) : null; calc(); } catch (error) { setStatus(error.message || 'No se pudo calcular la expresión.', true); } });
  [['fileA', 'A'], ['fileB', 'B'], ['fileC', 'C']].forEach(([input, target]) => $(input).addEventListener('change', () => readFile($(input), target)));
  $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', exportCsv);
  initMap();
})();
