(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const els = { file: $('fileInput'), fileName: $('fileName'), demo: $('demoBtn'), channel: $('channel'), status: $('status'), dimensions: $('dimensions'), pixels: $('pixelCount'), mean: $('channelMean'), range: $('channelRange'), transparent: $('transparent'), preview: $('preview'), empty: $('empty'), previewNote: $('previewNote'), histogram: $('histogram'), stats: $('channelStats'), pixelLabel: $('pixelLabel'), pixelValue: $('pixelValue'), reportTitle: $('reportTitle'), reportText: $('reportText'), report: $('reportBtn'), csv: $('csvBtn') };
  const state = { name: '', pixels: null, stats: null, histogram: null };
  const channelNames = { luma: 'luminancia', red: 'rojo', green: 'verde', blue: 'azul', alpha: 'alfa' };
  const clamp = value => Math.max(0, Math.min(255, value));
  const readChannel = (r, g, b, a, channel) => channel === 'red' ? r : channel === 'green' ? g : channel === 'blue' ? b : channel === 'alpha' ? a : .2126 * r + .7152 * g + .0722 * b;
  const format = (value, digits = 1) => Number.isFinite(value) ? value.toLocaleString('es-ES', { maximumFractionDigits: digits }) : '—';
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  function download(name, content, mime) { const url = URL.createObjectURL(new Blob([content], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function loadImage(file, label = file?.name || 'imagen local') {
    if (!file) return;
    const url = URL.createObjectURL(file); const image = new Image();
    image.onload = () => { URL.revokeObjectURL(url); state.name = label; const scale = Math.min(1, 1500 / image.naturalWidth, 1100 / image.naturalHeight); els.preview.width = Math.max(1, Math.round(image.naturalWidth * scale)); els.preview.height = Math.max(1, Math.round(image.naturalHeight * scale)); const context = els.preview.getContext('2d', { willReadFrequently: true }); context.drawImage(image, 0, 0, els.preview.width, els.preview.height); state.pixels = context.getImageData(0, 0, els.preview.width, els.preview.height); els.fileName.textContent = label; els.empty.hidden = true; els.previewNote.textContent = `${els.preview.width} × ${els.preview.height} px decodificados`; els.report.disabled = els.csv.disabled = false; analyse(); };
    image.onerror = () => { URL.revokeObjectURL(url); setStatus('No se pudo decodificar la imagen en este navegador.', true); }; image.src = url;
  }
  function makeDemo() { const canvas = document.createElement('canvas'); canvas.width = 900; canvas.height = 540; const context = canvas.getContext('2d'); const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height); gradient.addColorStop(0, '#142c59'); gradient.addColorStop(.35, '#1b9b8c'); gradient.addColorStop(.7, '#e2c45e'); gradient.addColorStop(1, '#b8444d'); context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height); for (let index = 0; index < 26; index += 1) { context.fillStyle = `rgba(255,255,255,${.03 + index / 700})`; context.beginPath(); context.arc(90 + index * 31, 80 + Math.sin(index / 2) * 110, 35 + index * 2, 0, Math.PI * 2); context.fill(); } canvas.toBlob(blob => loadImage(new File([blob], 'raster-inspector-demo.png', { type: 'image/png' }), 'raster-inspector-demo.png')); }
  function calculateStats(values) { const sorted = [...values].sort((a, b) => a - b); const sum = values.reduce((total, value) => total + value, 0); const mean = sum / values.length; const percentile = fraction => sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * fraction))]; return { min: sorted[0], max: sorted[sorted.length - 1], mean, median: percentile(.5), p02: percentile(.02), p98: percentile(.98), std: Math.sqrt(values.reduce((total, value) => total + (value - mean) ** 2, 0) / values.length) }; }
  function analyse() { if (!state.pixels) return; const channel = els.channel.value; const values = []; let transparent = 0; for (let index = 0; index < state.pixels.data.length; index += 4) { const alpha = state.pixels.data[index + 3]; if (alpha === 0) transparent += 1; values.push(readChannel(state.pixels.data[index], state.pixels.data[index + 1], state.pixels.data[index + 2], alpha, channel)); } state.stats = calculateStats(values); state.histogram = Array.from({ length: 32 }, () => 0); values.forEach(value => { state.histogram[Math.min(31, Math.floor(clamp(value) / 256 * 32))] += 1; }); renderStats(values.length, transparent); drawHistogram(); setStatus(`Análisis local completado · canal ${channelNames[channel]}.`); }
  function renderStats(count, transparent) { const channel = channelNames[els.channel.value]; els.dimensions.textContent = `${els.preview.width} × ${els.preview.height}`; els.pixels.textContent = `${count.toLocaleString('es-ES')} píxeles decodificados`; els.mean.textContent = `${format(state.stats.mean)} · ${format(state.stats.median)}`; els.range.textContent = `${format(state.stats.min)} – ${format(state.stats.max)}`; els.transparent.textContent = `${format(transparent / count * 100, 2)} %`; els.stats.innerHTML = [['Media', state.stats.mean], ['Mediana', state.stats.median], ['Desv. estándar', state.stats.std], ['Percentil 2', state.stats.p02], ['Percentil 98', state.stats.p98], ['Rango', `${format(state.stats.min)} – ${format(state.stats.max)}`]].map(([label, value]) => `<div><span>${escapeHtml(label)} · ${escapeHtml(channel)}</span><strong>${typeof value === 'number' ? format(value, 2) : escapeHtml(value)}</strong></div>`).join(''); els.reportTitle.textContent = `${state.name} · ${channel}`; els.reportText.textContent = `Se han revisado ${count.toLocaleString('es-ES')} píxeles sobre una imagen decodificada de ${els.preview.width} × ${els.preview.height} px. Media ${format(state.stats.mean, 2)}, mediana ${format(state.stats.median, 2)}, desviación estándar ${format(state.stats.std, 2)} y percentiles 2–98: ${format(state.stats.p02, 2)}–${format(state.stats.p98, 2)}.`; }
  function drawHistogram() { const canvas = els.histogram, context = canvas.getContext('2d'), width = canvas.width, height = canvas.height; context.clearRect(0, 0, width, height); context.fillStyle = '#0a1726'; context.fillRect(0, 0, width, height); if (!state.histogram) return; const peak = Math.max(...state.histogram, 1), barWidth = width / state.histogram.length; state.histogram.forEach((count, index) => { const barHeight = count / peak * (height - 34); const gradient = context.createLinearGradient(0, height - barHeight, 0, height); gradient.addColorStop(0, '#70e1bb'); gradient.addColorStop(1, '#266e80'); context.fillStyle = gradient; context.fillRect(index * barWidth + 1, height - barHeight - 18, Math.max(1, barWidth - 2), barHeight); }); context.strokeStyle = '#29455d'; context.beginPath(); context.moveTo(0, height - 17.5); context.lineTo(width, height - 17.5); context.stroke(); }
  function pixelAt(event) { if (!state.pixels) return; const rect = els.preview.getBoundingClientRect(); const x = Math.max(0, Math.min(els.preview.width - 1, Math.floor((event.clientX - rect.left) * els.preview.width / rect.width))); const y = Math.max(0, Math.min(els.preview.height - 1, Math.floor((event.clientY - rect.top) * els.preview.height / rect.height))); const index = (y * els.preview.width + x) * 4, data = state.pixels.data, luma = readChannel(data[index], data[index + 1], data[index + 2], data[index + 3], 'luma'); els.pixelLabel.textContent = `Píxel ${x}, ${y}`; els.pixelValue.textContent = `RGB ${data[index]}, ${data[index + 1]}, ${data[index + 2]} · alfa ${data[index + 3]} · luminancia ${format(luma, 1)}`; }
  function report() { if (!state.stats) return; const payload = { tool: 'Raster Inspector', file: state.name, decodedWidth: els.preview.width, decodedHeight: els.preview.height, channel: els.channel.value, channelLabel: channelNames[els.channel.value], statistics: state.stats, histogram: state.histogram, note: 'Estadísticas calculadas sobre los píxeles decodificados en el navegador. No implican CRS, resolución de terreno ni calibración radiométrica.' }; download('raster-inspector-report.json', JSON.stringify(payload, null, 2), 'application/json;charset=utf-8'); }
  function histogramCsv() { if (!state.histogram) return; const rows = [['channel', 'bin_min', 'bin_max', 'count'], ...state.histogram.map((count, index) => [els.channel.value, index * 8, (index + 1) * 8 - 1, count])]; download('raster-inspector-histogram.csv', '\ufeff' + rows.map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  els.file.addEventListener('change', event => loadImage(event.target.files[0])); els.demo.addEventListener('click', makeDemo); els.channel.addEventListener('change', analyse); els.preview.addEventListener('pointermove', pixelAt); els.preview.addEventListener('click', pixelAt); els.report.addEventListener('click', report); els.csv.addEventListener('click', histogramCsv); makeDemo();
})();
