(() => {
  'use strict';

  const state = { features: [], points: [], result: null, map: null, pointsLayer: null, ellipseLayer: null, centerLayer: null };
  const $ = (id) => document.getElementById(id);
  const els = { fileInput: $('fileInput'), fileName: $('fileName'), weightKey: $('weightKey'), sigmaScale: $('sigmaScale'), exampleBtn: $('exampleBtn'), clearBtn: $('clearBtn'), runBtn: $('runBtn'), status: $('status'), count: $('count'), weightTotal: $('weightTotal'), center: $('center'), majorAxis: $('majorAxis'), minorAxis: $('minorAxis'), orientation: $('orientation'), geojsonBtn: $('geojsonBtn'), csvBtn: $('csvBtn'), map: $('map'), mapFallback: $('mapFallback'), resultBody: $('resultBody'), tableHint: $('tableHint') };

  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function round(value, digits = 2) { const factor = 10 ** digits; return Math.round(value * factor) / factor; }
  function setStatus(message, error = false) { els.status.textContent = message; els.status.classList.toggle('error', error); }
  function featuresFrom(input) {
    if (!input || typeof input !== 'object') throw new Error('El contenido no es JSON válido.');
    if (input.type === 'FeatureCollection') return input.features.filter((feature) => feature && feature.type === 'Feature');
    if (input.type === 'Feature') return [input];
    if (input.type && input.coordinates) return [{ type: 'Feature', properties: {}, geometry: input }];
    throw new Error('Se esperaba una FeatureCollection, Feature o geometría GeoJSON.');
  }
  function positionsOf(value, output = []) {
    if (!Array.isArray(value)) return output;
    if (value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) { output.push([Number(value[0]), Number(value[1])]); return output; }
    value.forEach((child) => positionsOf(child, output)); return output;
  }
  function representative(feature) {
    if (!feature || !feature.geometry) return null;
    const positions = positionsOf(feature.geometry.coordinates).filter(([lon, lat]) => lon >= -180 && lon <= 180 && lat >= -90 && lat <= 90);
    if (!positions.length) return null;
    if (feature.geometry.type === 'Point') return positions[0];
    return [positions.reduce((sum, point) => sum + point[0], 0) / positions.length, positions.reduce((sum, point) => sum + point[1], 0) / positions.length];
  }
  function parseWeight(feature) { const key = els.weightKey.value.trim() || 'weight'; const raw = feature.properties && feature.properties[key]; const number = Number(raw); return Number.isFinite(number) && number > 0 ? number : 1; }
  function readFile(file) { const reader = new FileReader(); reader.onload = () => { try { state.features = featuresFrom(JSON.parse(reader.result)); els.fileName.textContent = `${file.name} · ${state.features.length} entidades`; els.runBtn.disabled = false; setStatus(`${state.features.length} entidades cargadas. Pulsa calcular para analizarlas.`); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus(`No se pudo leer ${file.name}.`, true); reader.readAsText(file); }
  function initMap() { if (!window.L) { els.map.hidden = true; els.mapFallback.hidden = false; return; } try { state.map = L.map(els.map, { zoomControl: true }).setView([40.4168, -3.7038], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' }).addTo(state.map); } catch (error) { els.map.hidden = true; els.mapFallback.hidden = false; setStatus('El análisis funciona, pero el mapa no pudo inicializarse.', true); } }
  function popup(title, properties) { return `<div class="popup-title">${escapeHtml(title)}</div><div class="popup-data">${escapeHtml(JSON.stringify(properties || {}, null, 2))}</div>`; }
  function clearLayers() { [state.pointsLayer, state.ellipseLayer, state.centerLayer].forEach((layer) => { if (layer && state.map) state.map.removeLayer(layer); }); state.pointsLayer = state.ellipseLayer = state.centerLayer = null; }
  function createEllipse(center, major, minor, angle, latitudeReference) { const coordinates = []; const longitudeScale = 111320 * Math.cos(latitudeReference * Math.PI / 180); for (let i = 0; i <= 72; i += 1) { const t = (i / 72) * Math.PI * 2; const x = major * Math.cos(t); const y = minor * Math.sin(t); const rotatedX = x * Math.cos(angle) - y * Math.sin(angle); const rotatedY = x * Math.sin(angle) + y * Math.cos(angle); coordinates.push([center[0] + rotatedX / longitudeScale, center[1] + rotatedY / 110540]); } return coordinates; }
  function renderMap() { if (!state.map || !state.result) return; clearLayers(); state.pointsLayer = L.layerGroup(); const bounds = []; state.points.forEach((point, index) => { const marker = L.circleMarker([point.coordinates[1], point.coordinates[0]], { radius: 6, color: '#fff', weight: 1, fillColor: '#76b5ff', fillOpacity: .9 }); marker.bindPopup(popup(`Observación ${index + 1}`, point.feature.properties)); marker.addTo(state.pointsLayer); bounds.push([point.coordinates[1], point.coordinates[0]]); }); state.ellipseLayer = L.geoJSON({ type: 'Feature', properties: { tipo: 'elipse_de_desviacion', sigma: state.result.sigma }, geometry: { type: 'Polygon', coordinates: [state.result.ellipse] } }, { style: { color: '#ffd071', weight: 3, fillColor: '#ffd071', fillOpacity: .12 } }).addTo(state.map); state.centerLayer = L.layerGroup(); const centerMarker = L.circleMarker([state.result.center[1], state.result.center[0]], { radius: 8, color: '#fff', weight: 2, fillColor: '#6ee0b1', fillOpacity: 1 }); centerMarker.bindPopup(`<div class="popup-title">Centro medio ponderado</div><div>${state.result.center[0].toFixed(6)}, ${state.result.center[1].toFixed(6)}</div>`); centerMarker.addTo(state.centerLayer); state.pointsLayer.addTo(state.map); state.centerLayer.addTo(state.map); bounds.push([state.result.center[1], state.result.center[0]]); if (bounds.length) state.map.fitBounds(bounds, { padding: [25, 25], maxZoom: 15 }); }
  function analyze() { const candidates = state.features.map((feature, index) => ({ feature, index, coordinates: representative(feature), weight: parseWeight(feature) })).filter((point) => point.coordinates); if (candidates.length < 2) { setStatus('Se necesitan al menos dos entidades con coordenadas válidas.', true); return; } const totalWeight = candidates.reduce((sum, point) => sum + point.weight, 0); const lon0 = candidates.reduce((sum, point) => sum + point.coordinates[0] * point.weight, 0) / totalWeight; const lat0 = candidates.reduce((sum, point) => sum + point.coordinates[1] * point.weight, 0) / totalWeight; const longitudeScale = 111320 * Math.cos(lat0 * Math.PI / 180); const local = candidates.map((point) => ({ ...point, x: (point.coordinates[0] - lon0) * longitudeScale, y: (point.coordinates[1] - lat0) * 110540 })); const meanX = local.reduce((sum, point) => sum + point.x * point.weight, 0) / totalWeight; const meanY = local.reduce((sum, point) => sum + point.y * point.weight, 0) / totalWeight; const center = [lon0 + meanX / longitudeScale, lat0 + meanY / 110540]; const sxx = local.reduce((sum, point) => sum + point.weight * (point.x - meanX) ** 2, 0) / totalWeight; const syy = local.reduce((sum, point) => sum + point.weight * (point.y - meanY) ** 2, 0) / totalWeight; const sxy = local.reduce((sum, point) => sum + point.weight * (point.x - meanX) * (point.y - meanY), 0) / totalWeight; const trace = sxx + syy; const root = Math.sqrt((sxx - syy) ** 2 + 4 * sxy ** 2); const majorVariance = Math.max(0, (trace + root) / 2); const minorVariance = Math.max(0, (trace - root) / 2); const angle = .5 * Math.atan2(2 * sxy, sxx - syy); const sigma = Math.min(4, Math.max(.25, Number(els.sigmaScale.value) || 1)); const major = sigma * Math.sqrt(majorVariance); const minor = sigma * Math.sqrt(minorVariance); const ellipse = createEllipse(center, major, minor, angle, lat0); state.points = local; state.result = { center, totalWeight, major, minor, angle, sigma, ellipse, latitudeReference: lat0 }; els.count.textContent = candidates.length; els.weightTotal.textContent = round(totalWeight, 2); els.center.textContent = `${center[0].toFixed(4)}, ${center[1].toFixed(4)}`; els.majorAxis.textContent = `${formatDistance(major)}`; els.minorAxis.textContent = `${formatDistance(minor)}`; els.orientation.textContent = `${round((angle * 180 / Math.PI + 360) % 180, 1)}°`; els.geojsonBtn.disabled = els.csvBtn.disabled = false; els.tableHint.textContent = `${candidates.length} observaciones válidas · escala ${sigma}σ`; els.resultBody.innerHTML = local.map((point, index) => { const distance = Math.sqrt((point.x - meanX) ** 2 + (point.y - meanY) ** 2); return `<tr><td>${index + 1}</td><td>${point.coordinates[0].toFixed(6)}</td><td>${point.coordinates[1].toFixed(6)}</td><td>${round(point.weight, 2)}</td><td>${formatDistance(distance)}</td></tr>`; }).join(''); renderMap(); setStatus(`Análisis completado: centro ${center[0].toFixed(4)}, ${center[1].toFixed(4)}.`); }
  function formatDistance(meters) { if (meters >= 1000) return `${round(meters / 1000, 2)} km`; return `${Math.round(meters)} m`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  function csvValue(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function downloadCsv() { const header = ['index', 'longitude', 'latitude', 'weight', 'distance_to_center_m']; const center = state.result.center; const lonScale = 111320 * Math.cos(state.result.latitudeReference * Math.PI / 180); const rows = [header]; state.points.forEach((point, index) => { const dx = (point.coordinates[0] - center[0]) * lonScale; const dy = (point.coordinates[1] - center[1]) * 110540; rows.push([index + 1, point.coordinates[0], point.coordinates[1], point.weight, Math.sqrt(dx * dx + dy * dy).toFixed(2)]); }); download('directional-observations.csv', rows.map((row) => row.map(csvValue).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function downloadGeoJSON() { const sourceFeatures = state.points.map((point, index) => ({ ...point.feature, properties: { ...(point.feature.properties || {}), directional_index: index + 1, directional_weight: point.weight } })); const features = [...sourceFeatures, { type: 'Feature', properties: { layer_role: 'mean_center', total_weight: state.result.totalWeight }, geometry: { type: 'Point', coordinates: state.result.center } }, { type: 'Feature', properties: { layer_role: 'standard_deviation_ellipse', sigma: state.result.sigma, major_axis_m: round(state.result.major, 2), minor_axis_m: round(state.result.minor, 2), orientation_degrees: round((state.result.angle * 180 / Math.PI + 360) % 180, 2) }, geometry: { type: 'Polygon', coordinates: [state.result.ellipse] } }]; download('directional-analysis.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json;charset=utf-8'); }
  function loadExample() { state.features = Array.from({ length: 12 }, (_, index) => { const x = -3.72 + index * .004 + Math.sin(index) * .002; const y = 40.40 + index * .003 + Math.cos(index * 1.7) * .002; return { type: 'Feature', properties: { id: `P-${String(index + 1).padStart(2, '0')}`, weight: index % 4 === 0 ? 2 : 1 }, geometry: { type: 'Point', coordinates: [x, y] } }; }); els.fileName.textContent = 'Ejemplo · 12 entidades'; els.weightKey.value = 'weight'; els.sigmaScale.value = '1'; els.runBtn.disabled = false; analyze(); }
  function clearAll() { state.features = []; state.points = []; state.result = null; els.fileInput.value = ''; els.fileName.textContent = 'Ningún archivo seleccionado'; els.runBtn.disabled = true; els.geojsonBtn.disabled = els.csvBtn.disabled = true; ['count', 'weightTotal', 'center', 'majorAxis', 'minorAxis', 'orientation'].forEach((id) => $(id).textContent = '—'); els.resultBody.innerHTML = '<tr><td colspan="5" class="empty">Todavía no hay resultados.</td></tr>'; els.tableHint.textContent = 'Ejecuta un análisis para ver las distancias al centro.'; clearLayers(); setStatus('Carga una capa o usa el ejemplo.'); }
  els.fileInput.addEventListener('change', (event) => { const file = event.target.files[0]; if (file) readFile(file); }); els.exampleBtn.addEventListener('click', loadExample); els.clearBtn.addEventListener('click', clearAll); els.runBtn.addEventListener('click', analyze); els.sigmaScale.addEventListener('change', () => { if (state.features.length) analyze(); }); els.weightKey.addEventListener('change', () => { if (state.features.length) analyze(); }); els.geojsonBtn.addEventListener('click', downloadGeoJSON); els.csvBtn.addEventListener('click', downloadCsv); initMap();
})();
