(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { input: null, output: null, features: [], fileName: 'capa.geojson', map: null, inputLayer: null, outputLayer: null };
  const A = 6378137;
  const ECC_SQUARED = 0.00669438;
  const K0 = 0.9996;
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const example = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'Punto de control' }, geometry: { type: 'Point', coordinates: [-3.7038, 40.4168] } }, { type: 'Feature', properties: { name: 'Línea de ejemplo' }, geometry: { type: 'LineString', coordinates: [[-3.72, 40.40], [-3.705, 40.412], [-3.69, 40.415], [-3.68, 40.42]] } }] };

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function isProjected(kind) { return kind !== 'wgs84'; }
  function parseInput(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input.features; if (input.type === 'Feature') return [input]; if (typeof input.type === 'string' && (depths[input.type] !== undefined || input.type === 'GeometryCollection')) return [{ type: 'Feature', properties: {}, geometry: input }]; throw new Error('Usa un FeatureCollection, Feature o una geometría GeoJSON reconocible.'); }
  function countCoordinates(node, depth) { if (depth === 0) return isPosition(node) ? 1 : 0; return Array.isArray(node) ? node.reduce((sum, child) => sum + countCoordinates(child, depth - 1), 0) : 0; }
  function countGeometry(geometry) { if (!geometry || typeof geometry !== 'object') return 0; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).reduce((sum, child) => sum + countGeometry(child), 0); const depth = depths[geometry.type]; return depth === undefined ? 0 : countCoordinates(geometry.coordinates, depth); }
  function geometryTransform(geometry, source, target) { if (!geometry || typeof geometry !== 'object') return geometry; if (geometry.type === 'GeometryCollection') return { ...clone(geometry), geometries: (geometry.geometries || []).map((child) => geometryTransform(child, source, target)) }; const depth = depths[geometry.type]; if (depth === undefined) return clone(geometry); const next = clone(geometry); const walk = (node, level) => level === 0 ? (isPosition(node) ? transformPosition(node, source, target) : clone(node)) : (Array.isArray(node) ? node.map((child) => walk(child, level - 1)) : clone(node)); next.coordinates = walk(geometry.coordinates, depth); return next; }
  function getConfig(prefix) { const zone = Math.max(1, Math.min(60, Math.round(Number($(prefix + 'Zone').value) || 30))); const hemisphere = $(prefix + 'Hemisphere').value === 'S' ? 'S' : 'N'; return { kind: $(prefix + 'Crs').value, zone, hemisphere }; }
  function isSouth(config) { return config.kind === 'utm-wgs84' && config.hemisphere === 'S'; }
  function epsg(config) { if (config.kind === 'wgs84') return 4326; if (config.kind === 'utm-etrs89') return 25800 + config.zone; return (isSouth(config) ? 32700 : 32600) + config.zone; }
  function displayCode(config) { return `EPSG:${epsg(config)}`; }
  function updateControls() { const source = getConfig('source'), target = getConfig('target'); ['source', 'target'].forEach((prefix) => { const kind = $(prefix + 'Crs').value; const projected = isProjected(kind); if (kind === 'utm-etrs89') $(`${prefix}Hemisphere`).value = 'N'; $(`${prefix}Zone`).disabled = !projected; $(`${prefix}Hemisphere`).disabled = !projected || kind === 'utm-etrs89'; }); $('sourceCode').textContent = displayCode(source); $('targetCode').textContent = displayCode(target); $('outputCode').textContent = displayCode(target); if (state.input) reproject(); }
  function forward(lon, lat, config) { const zone = config.zone; const lonOrigin = (zone - 1) * 6 - 180 + 3; const latRad = lat * Math.PI / 180; const lonRad = lon * Math.PI / 180; const lonOriginRad = lonOrigin * Math.PI / 180; const eccPrimeSquared = ECC_SQUARED / (1 - ECC_SQUARED); const n = A / Math.sqrt(1 - ECC_SQUARED * Math.sin(latRad) ** 2); const t = Math.tan(latRad) ** 2; const c = eccPrimeSquared * Math.cos(latRad) ** 2; const a = Math.cos(latRad) * (lonRad - lonOriginRad); const m = A * ((1 - ECC_SQUARED / 4 - 3 * ECC_SQUARED ** 2 / 64 - 5 * ECC_SQUARED ** 3 / 256) * latRad - (3 * ECC_SQUARED / 8 + 3 * ECC_SQUARED ** 2 / 32 + 45 * ECC_SQUARED ** 3 / 1024) * Math.sin(2 * latRad) + (15 * ECC_SQUARED ** 2 / 256 + 45 * ECC_SQUARED ** 3 / 1024) * Math.sin(4 * latRad) - (35 * ECC_SQUARED ** 3 / 3072) * Math.sin(6 * latRad)); const x = K0 * n * (a + (1 - t + c) * a ** 3 / 6 + (5 - 18 * t + t ** 2 + 72 * c - 58 * eccPrimeSquared) * a ** 5 / 120) + 500000; let y = K0 * (m + n * Math.tan(latRad) * (a ** 2 / 2 + (5 - t + 9 * c + 4 * c ** 2) * a ** 4 / 24 + (61 - 58 * t + t ** 2 + 600 * c - 330 * eccPrimeSquared) * a ** 6 / 720)); if (isSouth(config)) y += 10000000; return [x, y]; }
  function inverse(x, y, config) { const zone = config.zone; let northing = y; if (isSouth(config)) northing -= 10000000; const eccPrimeSquared = ECC_SQUARED / (1 - ECC_SQUARED); const e1 = (1 - Math.sqrt(1 - ECC_SQUARED)) / (1 + Math.sqrt(1 - ECC_SQUARED)); const m = northing / K0; const mu = m / (A * (1 - ECC_SQUARED / 4 - 3 * ECC_SQUARED ** 2 / 64 - 5 * ECC_SQUARED ** 3 / 256)); const phi1 = mu + (3 * e1 / 2 - 27 * e1 ** 3 / 32) * Math.sin(2 * mu) + (21 * e1 ** 2 / 16 - 55 * e1 ** 4 / 32) * Math.sin(4 * mu) + (151 * e1 ** 3 / 96) * Math.sin(6 * mu) + (1097 * e1 ** 4 / 512) * Math.sin(8 * mu); const n1 = A / Math.sqrt(1 - ECC_SQUARED * Math.sin(phi1) ** 2); const t1 = Math.tan(phi1) ** 2; const c1 = eccPrimeSquared * Math.cos(phi1) ** 2; const r1 = A * (1 - ECC_SQUARED) / (1 - ECC_SQUARED * Math.sin(phi1) ** 2) ** 1.5; const d = (x - 500000) / (n1 * K0); const lat = phi1 - (n1 * Math.tan(phi1) / r1) * (d ** 2 / 2 - (5 + 3 * t1 + 10 * c1 - 4 * c1 ** 2 - 9 * eccPrimeSquared) * d ** 4 / 24 + (61 + 90 * t1 + 298 * c1 + 45 * t1 ** 2 - 252 * eccPrimeSquared - 3 * c1 ** 2) * d ** 6 / 720); const lonOrigin = (zone - 1) * 6 - 180 + 3; const lon = (lonOrigin * Math.PI / 180) + (d - (1 + 2 * t1 + c1) * d ** 3 / 6 + (5 - 2 * c1 + 28 * t1 - 3 * c1 ** 2 + 8 * eccPrimeSquared + 24 * t1 ** 2) * d ** 5 / 120) / Math.cos(phi1); return [lon * 180 / Math.PI, lat * 180 / Math.PI]; }
  function transformPosition(position, source, target) { const original = Number(position[0]); const second = Number(position[1]); const geographic = source.kind === 'wgs84' ? [original, second] : inverse(original, second, source); const transformed = target.kind === 'wgs84' ? geographic : forward(geographic[0], geographic[1], target); return [...transformed, ...position.slice(2)]; }
  function reproject() { if (!state.input) return; const source = getConfig('source'), target = getConfig('target'); state.output = { type: 'FeatureCollection', features: state.features.map((feature) => ({ ...clone(feature), geometry: geometryTransform(feature.geometry, source, target) })) }; if (target.kind !== 'wgs84') state.output.crs = { type: 'name', properties: { name: displayCode(target) } }; const inputCount = state.features.reduce((sum, feature) => sum + countGeometry(feature.geometry), 0); $('vertexCount').textContent = inputCount.toLocaleString('es-ES'); $('featureCount').textContent = state.features.length.toLocaleString('es-ES'); $('geometryCount').textContent = state.features.reduce((sum, feature) => sum + (feature?.geometry ? 1 : 0), 0).toLocaleString('es-ES'); $('outputCode').textContent = displayCode(target); $('downloadBtn').disabled = false; $('status').textContent = `${state.fileName}: ${displayCode(source)} → ${displayCode(target)}.`; drawMap(); }
  function prepare(input, fileName) { state.features = parseInput(input); state.input = { type: 'FeatureCollection', features: clone(state.features) }; state.fileName = fileName || 'capa.geojson'; $('summary').hidden = false; reproject(); }
  function geographicFeatures(features, config) { const target = { kind: 'wgs84', zone: config.zone, hemisphere: config.hemisphere }; return features.map((feature) => ({ ...clone(feature), geometry: config.kind === 'wgs84' ? clone(feature.geometry) : geometryTransform(feature.geometry, config, target) })); }
  function geometryCanMap(geometry) { if (!geometry || typeof geometry !== 'object') return false; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).some(geometryCanMap); const depth = depths[geometry.type]; if (depth === undefined) return false; let valid = true; const walk = (node, level) => { if (level === 0) { valid = valid && isPosition(node) && Number(node[0]) >= -180 && Number(node[0]) <= 180 && Number(node[1]) >= -90 && Number(node[1]) <= 90; return; } if (!Array.isArray(node)) { valid = false; return; } node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return valid; }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.4, -3.7], 6); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function drawMap() { if (!state.map || !state.input || !state.output) return; state.inputLayer?.remove(); state.outputLayer?.remove(); const source = getConfig('source'), target = getConfig('target'); const inputFeatures = geographicFeatures(state.input.features, source).filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); const outputFeatures = geographicFeatures(state.output.features, target).filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); try { if (inputFeatures.length) state.inputLayer = L.geoJSON({ type: 'FeatureCollection', features: inputFeatures }, { color: '#9ea9bb', weight: 2, dashArray: '5 5', fillColor: '#9ea9bb', fillOpacity: .08, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 5, color: '#9ea9bb', fillOpacity: .7, weight: 1 }) }).addTo(state.map); if (outputFeatures.length) state.outputLayer = L.geoJSON({ type: 'FeatureCollection', features: outputFeatures }, { color: '#5bd6a5', weight: 3, fillColor: '#5bd6a5', fillOpacity: .22, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#5bd6a5', fillOpacity: .9, weight: 2 }) }).addTo(state.map); const layer = state.outputLayer || state.inputLayer; const bounds = layer?.getBounds(); if (bounds?.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 16 }); } catch { $('status').textContent += ' El mapa no pudo dibujar alguna geometría; la exportación sigue disponible.'; } }
  async function readFile(file) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { $('summary').hidden = true; $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  function inferZone() { if (!state.input) return; const source = getConfig('source'); const features = geographicFeatures(state.input.features, source); const values = []; const collect = (geometry) => { if (!geometry || typeof geometry !== 'object') return; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).forEach(collect); const depth = depths[geometry.type]; if (depth === undefined) return; const walk = (node, level) => { if (level === 0) { if (isPosition(node)) values.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); }; features.forEach((feature) => collect(feature.geometry)); if (!values.length) return; const lon = values.reduce((sum, point) => sum + point[0], 0) / values.length; const lat = values.reduce((sum, point) => sum + point[1], 0) / values.length; $('targetZone').value = Math.max(1, Math.min(60, Math.floor((lon + 180) / 6) + 1)); $('targetHemisphere').value = $('targetCrs').value === 'utm-etrs89' ? 'N' : (lat < 0 ? 'S' : 'N'); updateControls(); }
  $('fileInput').addEventListener('change', () => readFile($('fileInput').files?.[0])); $('exampleBtn').addEventListener('click', () => prepare(example, 'ejemplo-geojson-reproject.geojson')); $('processBtn').addEventListener('click', reproject); $('autoZoneBtn').addEventListener('click', inferZone); ['sourceCrs', 'sourceZone', 'sourceHemisphere', 'targetCrs', 'targetZone', 'targetHemisphere'].forEach((id) => $(id).addEventListener('change', updateControls)); $('downloadBtn').addEventListener('click', () => { if (!state.output) return; const code = displayCode(getConfig('target')).replace(':', '-'); download(JSON.stringify(state.output, null, 2), `${state.fileName.replace(/\.[^.]+$/, '')}-${code}.geojson`); }); $('clearBtn').addEventListener('click', () => { state.input = null; state.output = null; state.features = []; state.inputLayer?.remove(); state.outputLayer?.remove(); $('summary').hidden = true; $('downloadBtn').disabled = true; $('status').textContent = 'Sin capa cargada'; });
  initMap(); updateControls();
})();
