(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const R = 6371008.8;
  const state = { source: null, rows: [], map: null, layer: null };
  const rad = value => value * Math.PI / 180;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const number = value => Number.isFinite(Number(value)) ? Number(value) : null;
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function formatNumber(value, digits = 1) { return Number(value || 0).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function formatDistance(value) { if (!Number.isFinite(value)) return '—'; return value >= 1000 ? formatNumber(value / 1000, 3) + ' km' : formatNumber(value, 1) + ' m'; }
  function formatArea(value) { if (!Number.isFinite(value) || value <= 0) return '—'; return value >= 1000000 ? formatNumber(value / 1000000, 3) + ' km²' : formatNumber(value, 1) + ' m²'; }
  function flatCoords(coords, output = []) { if (!Array.isArray(coords)) return output; if (coords.length >= 2 && Number.isFinite(Number(coords[0])) && Number.isFinite(Number(coords[1]))) output.push([Number(coords[0]), Number(coords[1])]); else coords.forEach(child => flatCoords(child, output)); return output; }
  function validPoint(pair) { return Array.isArray(pair) && Number.isFinite(pair[0]) && Number.isFinite(pair[1]) && pair[0] >= -180 && pair[0] <= 180 && pair[1] >= -90 && pair[1] <= 90; }
  function haversine(a, b) { const lat1 = rad(a[1]), lat2 = rad(b[1]), dLat = lat2 - lat1, dLon = rad(b[0] - a[0]); const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.min(1, Math.sqrt(h))); }
  function lineLength(coords) { let total = 0; for (let i = 1; i < coords.length; i += 1) total += haversine(coords[i - 1], coords[i]); return total; }
  function ringArea(coords) { if (coords.length < 3) return 0; let sum = 0; for (let i = 0; i < coords.length - 1; i += 1) { const a = coords[i], b = coords[i + 1]; sum += rad(b[0] - a[0]) * (2 + Math.sin(rad(a[1])) + Math.sin(rad(b[1]))); } return Math.abs(sum * R * R / 2); }
  function geometryMetrics(geometry) {
    const empty = { length: 0, area: 0, vertices: 0, type: geometry?.type || 'Sin geometría', valid: true };
    if (!geometry || !geometry.type) return { ...empty, valid: false };
    const parts = geometry.type === 'Point' ? [[geometry.coordinates]] : geometry.type === 'MultiPoint' ? geometry.coordinates.map(point => [point]) : geometry.type === 'LineString' ? [geometry.coordinates] : geometry.type === 'MultiLineString' ? geometry.coordinates : geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.type === 'MultiPolygon' ? geometry.coordinates : [];
    if (!parts.length) return { ...empty, valid: false };
    let length = 0, area = 0, vertices = 0;
    if (geometry.type === 'Polygon' || geometry.type === 'MultiPolygon') {
      const polygons = geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;
      polygons.forEach(polygon => polygon.forEach((ring, index) => { const points = ring.filter(validPoint); vertices += points.length; length += lineLength(points); if (index === 0) area += ringArea(points); else area -= ringArea(points); }));
    } else {
      parts.forEach(part => { const points = part.filter(validPoint); vertices += points.length; length += lineLength(points); });
    }
    const flat = flatCoords(geometry.coordinates).filter(validPoint);
    if (!flat.length || vertices !== flatCoords(geometry.coordinates).length) return { length, area: Math.max(0, area), vertices, type: geometry.type, valid: false };
    return { length, area: Math.max(0, area), vertices, type: geometry.type, valid: true };
  }
  function normalizeInput(value) {
    const parsed = typeof value === 'string' ? JSON.parse(value) : value;
    if (parsed?.type === 'FeatureCollection') return { type: 'FeatureCollection', features: parsed.features || [] };
    if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] };
    if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] };
    throw new Error('El documento no es GeoJSON reconocible.');
  }
  function featureName(feature, index) { const props = feature.properties || {}; return props.name || props.nombre || props.id || 'Entidad ' + (index + 1); }
  function measure(source) {
    const rows = source.features.map((feature, index) => { const metrics = geometryMetrics(feature.geometry); return { feature, index, name: featureName(feature, index), properties: feature.properties || {}, ...metrics }; });
    state.source = source; state.rows = rows; $('countBadge').textContent = rows.length + (rows.length === 1 ? ' entidad' : ' entidades');
    const validRows = rows.filter(row => row.valid); $('featureCount').textContent = formatNumber(rows.length, 0); $('lengthTotal').textContent = formatDistance(validRows.reduce((sum, row) => sum + row.length, 0)); $('areaTotal').textContent = formatArea(validRows.reduce((sum, row) => sum + row.area, 0)); $('vertexTotal').textContent = formatNumber(validRows.reduce((sum, row) => sum + row.vertices, 0), 0); $('quality').textContent = validRows.length === rows.length ? 'Geometrías válidas' : `${rows.length - validRows.length} con revisión`; $('quality').className = 'quality ' + (validRows.length === rows.length ? '' : 'warn'); renderTable(); renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; $('jsonBtn').disabled = false; setStatus(`${rows.length} entidades medidas localmente${validRows.length < rows.length ? '; revisa las geometrías señaladas.' : '.'}`, validRows.length < rows.length); }
  function rowMatches(row) { const query = $('search').value.trim().toLowerCase(); const type = $('geometryFilter').value; const haystack = JSON.stringify(row.properties).toLowerCase() + ' ' + row.name.toLowerCase(); return (!query || haystack.includes(query)) && (type === 'all' || row.type === type); }
  function visibleRows() { const rows = state.rows.filter(rowMatches); const sort = $('sort').value; return rows.sort((a, b) => sort === 'length' ? b.length - a.length : sort === 'area' ? b.area - a.area : sort === 'vertices' ? b.vertices - a.vertices : a.index - b.index); }
  function renderTable() { if (!state.rows.length) { $('tableWrap').innerHTML = '<p class="empty">No hay entidades para mostrar.</p>'; return; } const rows = visibleRows(); if (!rows.length) { $('tableWrap').innerHTML = '<p class="empty">Ninguna entidad coincide con el filtro.</p>'; return; } $('tableWrap').innerHTML = '<table><thead><tr><th>#</th><th>Nombre</th><th>Tipo</th><th>Longitud / perímetro</th><th>Superficie</th><th>Vértices</th><th>Estado</th></tr></thead><tbody>' + rows.map(row => `<tr data-index="${row.index}"><td>${row.index + 1}</td><td><strong>${esc(row.name)}</strong></td><td><span class="type-badge">${esc(row.type)}</span></td><td>${formatDistance(row.length)}</td><td>${formatArea(row.area)}</td><td>${row.vertices}</td><td class="${row.valid ? 'ok' : 'bad'}">${row.valid ? 'válida' : 'revisar'}</td></tr>`).join('') + '</tbody></table>'; $('tableWrap').querySelectorAll('tr[data-index]').forEach(row => row.addEventListener('click', () => focusRow(Number(row.dataset.index)))); }
  function popup(row) { return `<strong>${esc(row.name)}</strong><br><span>${esc(row.type)}</span><br>Longitud: ${formatDistance(row.length)}<br>Superficie: ${formatArea(row.area)}<br>Vértices: ${row.vertices}${row.valid ? '' : '<br><b>Revisar coordenadas</b>'}`; }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer) return; state.layer.clearLayers(); const shown = visibleRows(); const geo = L.geoJSON({ type: 'FeatureCollection', features: shown.map(row => ({ ...row.feature, properties: { ...(row.feature.properties || {}), __measureIndex: row.index } })) }, { style: feature => ({ color: '#72e3be', weight: 3, fillColor: '#72e3be', fillOpacity: .18 }), pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#071b25', weight: 2, fillColor: '#72e3be', fillOpacity: .9 }), onEachFeature: (feature, layer) => { const row = state.rows[feature.properties.__measureIndex]; if (row) layer.bindPopup(popup(row)); } }).addTo(state.layer); if (geo.getLayers().length) state.map.fitBounds(geo.getBounds(), { padding: [22, 22], maxZoom: 16 }); }
  function focusRow(index) { const row = state.rows[index]; if (!row || !state.map) return; const layer = state.layer.getLayers().find(item => item.feature?.properties?.__measureIndex === index); if (layer) { state.map.fitBounds(layer.getBounds ? layer.getBounds() : L.latLngBounds(layer.getLatLng(), layer.getLatLng()), { padding: [30, 30], maxZoom: 17 }); layer.openPopup(); } }
  function safeProps(row) { const props = { ...(row.properties || {}), _measure_length_m: Number(row.length.toFixed(3)), _measure_area_m2: Number(row.area.toFixed(3)), _measure_vertices: row.vertices, _measure_geometry_type: row.type, _measure_valid: row.valid }; delete props.__measureIndex; return props; }
  function enriched() { return { type: 'FeatureCollection', features: state.rows.map(row => ({ ...row.feature, properties: safeProps(row) })) }; }
  function csvCell(value) { let text = String(value ?? ''); if (/^[=+\-@]/.test(text)) text = "'" + text; return '"' + text.replace(/"/g, '""') + '"'; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportGeoJSON() { download('geojson-medido.geojson', JSON.stringify(enriched(), null, 2), 'application/geo+json;charset=utf-8'); }
  function exportCSV() { const keys = [...new Set(state.rows.flatMap(row => Object.keys(row.properties)))]; const header = ['index', 'nombre', 'geometry_type', 'length_m', 'area_m2', 'vertices', 'valid', ...keys]; const lines = [header.map(csvCell).join(',')]; state.rows.forEach(row => lines.push([row.index + 1, row.name, row.type, row.length.toFixed(3), row.area.toFixed(3), row.vertices, row.valid, ...keys.map(key => row.properties[key])].map(csvCell).join(','))); download('geojson-metricas.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function exportJSON() { const valid = state.rows.filter(row => row.valid); const report = { generatedAt: new Date().toISOString(), processing: 'local-browser', count: state.rows.length, validCount: valid.length, totals: { length_m: valid.reduce((sum, row) => sum + row.length, 0), area_m2: valid.reduce((sum, row) => sum + row.area, 0), vertices: valid.reduce((sum, row) => sum + row.vertices, 0) }, features: state.rows.map(row => ({ index: row.index + 1, name: row.name, geometryType: row.type, length_m: row.length, area_m2: row.area, vertices: row.vertices, valid: row.valid })) }; download('geojson-informe-metricas.json', JSON.stringify(report, null, 2), 'application/json;charset=utf-8'); }
  function calculateFromText() { try { measure(normalizeInput($('source').value)); } catch (error) { setStatus(error.message || 'No se pudo interpretar el GeoJSON.', true); } }
  $('calculateBtn').addEventListener('click', calculateFromText); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; calculateFromText(); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); calculateFromText(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); ['search', 'geometryFilter', 'sort'].forEach(id => $(id).addEventListener(id === 'search' ? 'input' : 'change', () => { renderTable(); renderMap(); })); $('tableWrap').addEventListener('click', event => { const row = event.target.closest('tr[data-index]'); if (row) focusRow(Number(row.dataset.index)); }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', exportCSV); $('jsonBtn').addEventListener('click', exportJSON); initMap(); calculateFromText();
})();
