(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { rows: [], result: null, map: null, layer: null };
  const example = `id,pixel_x,pixel_y,target_x,target_y\nA,120,80,-3.705,40.421\nB,980,95,-3.682,40.420\nC,960,720,-3.683,40.405\nD,135,700,-3.706,40.406\nE,540,390,-3.694,40.413`;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseLine(line) { const out = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"' && line[i + 1] === '"' && quoted) { value += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ',' || char === '\t' || char === ';')) { out.push(value.trim()); value = ''; } else value += char; } out.push(value.trim()); return out; }
  function parseDelimited(text) { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 4) throw new Error('Necesitas al menos tres puntos y una cabecera.'); const headers = parseLine(lines[0]).map((header, index) => header || `campo_${index + 1}`); return lines.slice(1).map((line) => { const values = parseLine(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])); }); }
  function score(field, candidates) { const value = field.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); return candidates.reduce((best, candidate, index) => Math.max(best, value === candidate ? 100 - index : value.includes(candidate) ? 40 - index : 0), 0); }
  function chooseFields(rows) { state.rows = rows; const fields = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const best = (candidates) => fields.map((field) => ({ field, score: score(field, candidates) })).sort((a, b) => b.score - a.score)[0]?.score > 0 ? fields.map((field) => ({ field, score: score(field, candidates) })).sort((a, b) => b.score - a.score)[0].field : ''; const optionList = (empty, selected) => [empty, ...fields.map((field) => `<option value="${escapeHtml(field)}"${field === selected ? ' selected' : ''}>${escapeHtml(field)}</option>`)].join(''); $('pixelX').innerHTML = optionList('Selecciona píxel X', best(['pixel_x', 'pixelx', 'columna', 'column', 'x', 'px'])); $('pixelY').innerHTML = optionList('Selecciona píxel Y', best(['pixel_y', 'pixely', 'fila', 'row', 'y', 'py'])); $('targetX').innerHTML = optionList('Selecciona destino X', best(['target_x', 'targetx', 'longitude', 'longitud', 'lon', 'este', 'easting', 'x_destino'])); $('targetY').innerHTML = optionList('Selecciona destino Y', best(['target_y', 'targety', 'latitude', 'latitud', 'lat', 'norte', 'northing', 'y_destino'])); setStatus(`${rows.length.toLocaleString('es-ES')} puntos detectados. Revisa los campos y calcula el ajuste.`); }
  function num(value) { const raw = String(value ?? '').trim().replace(',', '.'); if (!raw) return null; const n = Number(raw); return Number.isFinite(n) ? n : null; }
  function solve3(matrix, vector) { const a = matrix.map((row, i) => [...row, vector[i]]); for (let col = 0; col < 3; col += 1) { let pivot = col; for (let row = col + 1; row < 3; row += 1) if (Math.abs(a[row][col]) > Math.abs(a[pivot][col])) pivot = row; if (Math.abs(a[pivot][col]) < 1e-12) throw new Error('Los puntos no permiten una transformación afín estable: pueden estar alineados o duplicados.'); [a[col], a[pivot]] = [a[pivot], a[col]]; const divisor = a[col][col]; for (let j = col; j < 4; j += 1) a[col][j] /= divisor; for (let row = 0; row < 3; row += 1) { if (row === col) continue; const factor = a[row][col]; for (let j = col; j < 4; j += 1) a[row][j] -= factor * a[col][j]; } } return [a[0][3], a[1][3], a[2][3]]; }
  function fit(points, target) { const normal = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]; const vector = [0, 0, 0]; points.forEach((point, i) => { const row = [point.x, point.y, 1]; row.forEach((value, j) => { row.forEach((other, k) => { normal[j][k] += value * other; }); vector[j] += value * target[i]; }); }); return solve3(normal, vector); }
  function format(value) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: 10 }); }
  function calculate() { const fields = ['pixelX', 'pixelY', 'targetX', 'targetY'].map((id) => $(id).value); if (fields.some((field) => !field)) throw new Error('Selecciona los cuatro campos de coordenadas.'); const points = state.rows.map((row, index) => ({ id: row.id || row.ID || `P${index + 1}`, row, x: num(row[fields[0]]), y: num(row[fields[1]]), tx: num(row[fields[2]]), ty: num(row[fields[3]]) })).filter((point) => [point.x, point.y, point.tx, point.ty].every(Number.isFinite)); if (points.length < 3) throw new Error('Se necesitan al menos tres filas con cuatro coordenadas numéricas.'); const ax = fit(points, points.map((point) => point.tx)); const ay = fit(points, points.map((point) => point.ty)); const fitted = points.map((point) => { const fx = ax[0] * point.x + ax[1] * point.y + ax[2]; const fy = ay[0] * point.x + ay[1] * point.y + ay[2]; const dx = fx - point.tx; const dy = fy - point.ty; return { ...point, fx, fy, dx, dy, residual: Math.hypot(dx, dy) }; }); const rmseX = Math.sqrt(fitted.reduce((sum, point) => sum + point.dx ** 2, 0) / fitted.length); const rmseY = Math.sqrt(fitted.reduce((sum, point) => sum + point.dy ** 2, 0) / fitted.length); const rmse = Math.hypot(rmseX, rmseY); const maxResidual = Math.max(...fitted.map((point) => point.residual)); const geographic = fitted.every((point) => Math.abs(point.tx) <= 180 && Math.abs(point.ty) <= 90); state.result = { fields: { pixelX: fields[0], pixelY: fields[1], targetX: fields[2], targetY: fields[3] }, points: fitted, coefficients: { x: ax, y: ay }, rmseX, rmseY, rmse, maxResidual, geographic, imageWidth: num($('imageWidth').value), imageHeight: num($('imageHeight').value) }; render(); $('transformBtn').disabled = $('worldBtn').disabled = $('pointsBtn').disabled = false; setStatus(`${points.length.toLocaleString('es-ES')} puntos ajustados. RMSE combinado: ${format(rmse)} unidades destino.`); }
  function render() { const r = state.result; $('summary').hidden = $('residualPanel').hidden = false; $('pointCount').textContent = r.points.length.toLocaleString('es-ES'); $('rmseX').textContent = format(r.rmseX); $('rmseY').textContent = format(r.rmseY); $('rmseTotal').textContent = format(r.rmse); $('maxResidual').textContent = format(r.maxResidual); $('mapState').textContent = r.geographic ? 'WGS84?' : 'no geográfico'; $('qualityBadge').textContent = r.rmse < Math.max(Math.abs(r.rmseX), Math.abs(r.rmseY), 1) * .1 ? 'ajuste sólido' : 'revisar residuos'; $('qualityBadge').style.background = r.rmse < 1 ? '' : '#fff2d9'; $('qualityBadge').style.color = r.rmse < 1 ? '' : 'var(--warning)'; const [a,b,c] = r.coefficients.x; const [d,e,f] = r.coefficients.y; $('formula').textContent = `X = ${format(a)}·pixel_x + ${format(b)}·pixel_y + ${format(c)}\nY = ${format(d)}·pixel_x + ${format(e)}·pixel_y + ${format(f)}`; $('residualBadge').textContent = `${r.points.length.toLocaleString('es-ES')} puntos`; $('residualBody').innerHTML = r.points.map((point) => `<tr><th>${escapeHtml(point.id)}</th><td>${format(point.x)}, ${format(point.y)}</td><td>${format(point.tx)}, ${format(point.ty)}</td><td>${format(point.fx)}, ${format(point.fy)}</td><td class="${point.residual <= r.rmse * 2 || point.residual < 1e-10 ? 'residual-good' : 'residual-bad'}">${format(point.residual)}</td></tr>`).join(''); renderMap(); }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); if (!state.result.geographic) { $('mapBadge').textContent = 'no disponible'; $('mapFallback').textContent = 'El destino no parece lon/lat WGS84; se conserva el ajuste numérico sin inventar una posición sobre Leaflet.'; return; } const points = state.result.points.map((point) => L.circleMarker([point.ty, point.tx], { radius: 7, color: point.residual <= state.result.rmse * 2 ? '#176b50' : '#a33d50', weight: 1, fillColor: point.residual <= state.result.rmse * 2 ? '#55c68c' : '#ef737d', fillOpacity: .9 }).bindPopup(`<strong>${escapeHtml(point.id)}</strong><div>Destino: ${format(point.tx)}, ${format(point.ty)}<br>Residual: ${format(point.residual)}</div>`)); state.layer = L.layerGroup(points).addTo(state.map); $('mapBadge').textContent = `${points.length.toLocaleString('es-ES')} puntos`; $('mapFallback').textContent = 'El mapa muestra el destino de los puntos de control; el color señala residuos bajos y altos.'; if (points.length) state.map.fitBounds(L.featureGroup(points).getBounds(), { padding: [30, 30], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function transformJson() { const r = state.result; download('georeference-transform.json', JSON.stringify(r, null, 2), 'application/json'); }
  function worldFile() { const r = state.result; const [a,b,c] = r.coefficients.x; const [d,e,f] = r.coefficients.y; const C = c + (a + b) / 2; const F = f + (d + e) / 2; download('georeference.wld', [a,d,b,e,C,F].map((value) => Number(value).toPrecision(15)).join('\n'), 'text/plain'); }
  function adjustedCsv() { const r = state.result; const rows = r.points.map((point) => ({ ...point.row, fitted_x: point.fx, fitted_y: point.fy, residual: point.residual })); const headers = [...new Set(rows.flatMap((row) => Object.keys(row)))]; download('georeference-points-adjusted.csv', [headers, ...rows.map((row) => headers.map((header) => row[header] ?? ''))].map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function loadText(text) { $('source').value = text; try { chooseFields(parseDelimited(text)); } catch (error) { setStatus(error.message || 'No se pudieron detectar los puntos.', true); } }
  function clearAll() { state.rows = []; state.result = null; $('source').value = ''; $('fileInput').value = ''; ['pixelX','pixelY','targetX','targetY'].forEach((id) => { $(id).innerHTML = '<option value="">Carga datos para detectar campos</option>'; }); $('summary').hidden = $('residualPanel').hidden = true; $('transformBtn').disabled = $('worldBtn').disabled = $('pointsBtn').disabled = true; state.layer?.remove(); state.layer = null; $('mapBadge').textContent = '—'; setStatus('Carga al menos tres puntos y calcula el ajuste.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', () => loadText(example)); $('clearBtn').addEventListener('click', clearAll); $('solveBtn').addEventListener('click', () => { try { chooseFields(parseDelimited($('source').value)); calculate(); } catch (error) { setStatus(error.message || 'No se pudo calcular la transformación.', true); } }); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { loadText(await file.text()); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }); $('transformBtn').addEventListener('click', transformJson); $('worldBtn').addEventListener('click', worldFile); $('pointsBtn').addEventListener('click', adjustedCsv); $('source').value = example; initMap();
})();
