(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, features: [], issues: [], badFeatures: new Set(), map: null, layer: null, fileName: 'capa.geojson', segmentCount: 0 };
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const example = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'Polígono con cruce' }, geometry: { type: 'Polygon', coordinates: [[[-3.73, 40.40], [-3.68, 40.44], [-3.68, 40.40], [-3.73, 40.44], [-3.73, 40.40]]] } }, { type: 'Feature', properties: { name: 'Anillo abierto' }, geometry: { type: 'Polygon', coordinates: [[[-3.75, 40.41], [-3.70, 40.41], [-3.70, 40.45], [-3.75, 40.45]]] } }, { type: 'Feature', properties: { name: 'Geometría válida' }, geometry: { type: 'Polygon', coordinates: [[[-3.67, 40.41], [-3.64, 40.41], [-3.64, 40.44], [-3.67, 40.44], [-3.67, 40.41]]] } }] };

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function isObject(value) { return value !== null && typeof value === 'object'; }
  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function parseInput(input) { if (!isObject(input)) throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input.features; if (input.type === 'Feature') return [input]; if (typeof input.type === 'string' && (depths[input.type] !== undefined || input.type === 'GeometryCollection')) return [{ type: 'Feature', properties: {}, geometry: input }]; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON reconocible.'); }
  function addIssue(severity, code, feature, path, message) { if (state.issues.length >= 500) return; state.issues.push({ severity, code, feature: feature || '—', path: path || '—', message }); if (feature && feature !== '—') state.badFeatures.add(Number(feature) - 1); }
  function samePosition(a, b) { return isPosition(a) && isPosition(b) && Number(a[0]) === Number(b[0]) && Number(a[1]) === Number(b[1]); }
  function orient(a, b, c) { return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]); }
  function onSegment(a, b, c) { return c[0] >= Math.min(a[0], b[0]) - 1e-10 && c[0] <= Math.max(a[0], b[0]) + 1e-10 && c[1] >= Math.min(a[1], b[1]) - 1e-10 && c[1] <= Math.max(a[1], b[1]) + 1e-10; }
  function segmentsIntersect(a, b, c, d) { const abC = orient(a, b, c), abD = orient(a, b, d), cdA = orient(c, d, a), cdB = orient(c, d, b); const proper = ((abC > 1e-10 && abD < -1e-10) || (abC < -1e-10 && abD > 1e-10)) && ((cdA > 1e-10 && cdB < -1e-10) || (cdA < -1e-10 && cdB > 1e-10)); if (proper) return true; return (Math.abs(abC) <= 1e-10 && onSegment(a, b, c)) || (Math.abs(abD) <= 1e-10 && onSegment(a, b, d)) || (Math.abs(cdA) <= 1e-10 && onSegment(c, d, a)) || (Math.abs(cdB) <= 1e-10 && onSegment(c, d, b)); }
  function signedArea(points) { let area = 0; for (let index = 1; index < points.length; index += 1) area += Number(points[index - 1][0]) * Number(points[index][1]) - Number(points[index][0]) * Number(points[index - 1][1]); return area / 2; }
  function inspectLine(points, closed, feature, path) { const valid = Array.isArray(points) ? points.filter(isPosition) : []; const minimum = closed ? 4 : 2; if (valid.length < minimum) addIssue('error', closed ? 'short-ring' : 'short-line', feature, path, `${closed ? 'Un anillo' : 'Una línea'} necesita al menos ${minimum} posiciones.`); if (closed && valid.length >= 3 && !samePosition(valid[0], valid[valid.length - 1])) addIssue('warning', 'open-ring', feature, path, 'El primer y último vértice del anillo no coinciden.'); if (closed && valid.length >= 4 && Math.abs(signedArea(valid)) < 1e-12) addIssue('warning', 'zero-area', feature, path, 'El anillo tiene un área prácticamente nula.'); const segmentLimit = Math.max(0, valid.length - 1); state.segmentCount += segmentLimit; for (let first = 0; first < segmentLimit; first += 1) { for (let second = first + 1; second < segmentLimit; second += 1) { if (second - first <= 1 || (closed && first === 0 && second === segmentLimit - 1)) continue; if (segmentsIntersect(valid[first], valid[first + 1], valid[second], valid[second + 1])) { addIssue('error', 'self-intersection', feature, `${path}[${first}]↔[${second}]`, 'Dos segmentos no adyacentes se cruzan; revisa el orden de vértices.'); break; } } } }
  function inspectGeometry(geometry, feature, path = 'geometry') { if (geometry === null) { addIssue('warning', 'empty-geometry', feature, path, 'La entidad no tiene geometría.'); return; } if (!isObject(geometry) || typeof geometry.type !== 'string') { addIssue('error', 'invalid-geometry', feature, path, 'La geometría no es un objeto GeoJSON válido.'); return; } if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child, index) => inspectGeometry(child, feature, `${path}.geometries[${index}]`)); return; } if (geometry.type === 'LineString') inspectLine(geometry.coordinates, false, feature, `${path}.coordinates`); else if (geometry.type === 'MultiLineString') (geometry.coordinates || []).forEach((line, index) => inspectLine(line, false, feature, `${path}.coordinates[${index}]`)); else if (geometry.type === 'Polygon') (geometry.coordinates || []).forEach((ring, index) => inspectLine(ring, true, feature, `${path}.coordinates[${index}]`)); else if (geometry.type === 'MultiPolygon') (geometry.coordinates || []).forEach((polygon, polygonIndex) => (polygon || []).forEach((ring, ringIndex) => inspectLine(ring, true, feature, `${path}.coordinates[${polygonIndex}][${ringIndex}]`))); else if (depths[geometry.type] === undefined) addIssue('error', 'unsupported-type', feature, `${path}.type`, `Tipo de geometría no soportado: ${geometry.type}.`); }
  function analyse(input, fileName) { const features = parseInput(input); state.source = input; state.features = features; state.issues = []; state.badFeatures = new Set(); state.segmentCount = 0; state.fileName = fileName || 'capa.geojson'; features.forEach((feature, index) => { const number = index + 1; if (!isObject(feature) || feature.type !== 'Feature') { addIssue('error', 'invalid-feature', number, `features[${index}]`, 'La entidad no tiene type: Feature.'); return; } inspectGeometry(feature.geometry, number); }); render(); drawMap(); }
  function render() { const errors = state.issues.filter((issue) => issue.severity === 'error').length; const warnings = state.issues.filter((issue) => issue.severity === 'warning').length; $('summary').hidden = false; $('featureCount').textContent = state.features.length.toLocaleString('es-ES'); $('segmentCount').textContent = state.segmentCount.toLocaleString('es-ES'); $('errorCount').textContent = errors; $('warningCount').textContent = warnings; $('issueCount').textContent = `${state.issues.length} hallazgo${state.issues.length === 1 ? '' : 's'}`; const tbody = $('issueTable'); tbody.replaceChildren(); if (!state.issues.length) { const row = tbody.insertRow(); const cell = row.insertCell(); cell.colSpan = 4; cell.textContent = 'No se han encontrado problemas con estas reglas.'; } else state.issues.slice(0, 300).forEach((issue) => { const row = tbody.insertRow(); const level = row.insertCell(); level.className = `severity ${issue.severity}`; level.textContent = issue.severity === 'error' ? 'Error' : issue.severity === 'warning' ? 'Aviso' : 'Info'; row.insertCell().textContent = issue.feature; row.insertCell().textContent = issue.code; const detail = row.insertCell(); detail.className = 'detail'; detail.textContent = `${issue.message} · ${issue.path}`; }); $('status').textContent = `${state.fileName}: ${state.features.length} features revisadas, ${errors} errores y ${warnings} avisos.`; }
  function geometryCanMap(geometry) { if (!geometry || typeof geometry !== 'object') return false; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).some(geometryCanMap); const depth = depths[geometry.type]; if (depth === undefined) return false; let valid = true; const walk = (node, level) => { if (level === 0) { valid = valid && isPosition(node) && Number(node[0]) >= -180 && Number(node[0]) <= 180 && Number(node[1]) >= -90 && Number(node[1]) <= 90; return; } if (!Array.isArray(node)) { valid = false; return; } node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return valid; }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function drawMap() { if (!state.map) return; state.layer?.remove(); const features = state.features.filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); if (!features.length) return; try { state.layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: (feature) => state.badFeatures.has(state.features.indexOf(feature)) ? { color: '#ff7e87', weight: 3, fillColor: '#ff7e87', fillOpacity: .25 } : { color: '#5bd6a5', weight: 2, fillColor: '#5bd6a5', fillOpacity: .14 }, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#5bd6a5', fillOpacity: .9, weight: 2 }), onEachFeature: (feature, layer) => layer.bindPopup(`<pre>${escapeHtml(JSON.stringify(feature.properties || {}, null, 2))}</pre>`) }).addTo(state.map); const bounds = state.layer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); } catch { $('status').textContent += ' El mapa no pudo dibujar alguna geometría; el informe sigue disponible.'; } }
  function download(text, name, mime) { const url = URL.createObjectURL(new Blob([text], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function readFile(file) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { analyse(JSON.parse(await file.text()), file.name); } catch (error) { $('summary').hidden = true; $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  $('fileInput').addEventListener('change', () => readFile($('fileInput').files?.[0])); $('exampleBtn').addEventListener('click', () => analyse(example, 'ejemplo-topology-lab.geojson')); $('clearBtn').addEventListener('click', () => { state.source = null; state.features = []; state.issues = []; state.badFeatures = new Set(); state.layer?.remove(); $('summary').hidden = true; $('issueTable').replaceChildren(); $('issueCount').textContent = '—'; $('status').textContent = 'Sin capa cargada'; }); $('reportBtn').addEventListener('click', () => download(JSON.stringify({ tool: 'Topology Lab', file: state.fileName, checkedAt: new Date().toISOString(), summary: { features: state.features.length, segments: state.segmentCount, errors: state.issues.filter((issue) => issue.severity === 'error').length, warnings: state.issues.filter((issue) => issue.severity === 'warning').length }, issues: state.issues }, null, 2), `${state.fileName.replace(/\.[^.]+$/, '')}-topology.json`, 'application/json')); $('csvBtn').addEventListener('click', () => { const rows = [['nivel', 'regla', 'feature', 'ruta', 'detalle'], ...state.issues.map((issue) => [issue.severity, issue.code, issue.feature, issue.path, issue.message])]; download(rows.map((row) => row.map((value) => { const text = String(value ?? '').replace(/"/g, '""'); return /[",\n]/.test(text) ? `"${text}"` : text; }).join(',')).join('\n'), `${state.fileName.replace(/\.[^.]+$/, '')}-topology.csv`, 'text/csv;charset=utf-8'); }); initMap();
})();
