(() => {
  'use strict';

  const map = L.map('map').setView([40.32, -3.7], 6);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
  const state = { service: '', layers: [], selected: null, result: null, resultLayer: null, checkedAt: null };
  const els = { service: document.getElementById('serviceInput'), inspect: document.getElementById('inspectBtn'), clear: document.getElementById('clearBtn'), demo: document.getElementById('demoBtn'), status: document.getElementById('status'), select: document.getElementById('layerSelect'), meta: document.getElementById('layerMeta'), limit: document.getElementById('limitInput'), bbox: document.getElementById('bboxInput'), query: document.getElementById('queryBtn'), download: document.getElementById('downloadBtn'), csv: document.getElementById('csvBtn'), mapTitle: document.getElementById('mapTitle'), mapStatus: document.getElementById('mapStatus') };
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  const textOf = (node, localName) => [...node.children].find(child => child.localName === localName)?.textContent?.trim() || '';
  const normaliseService = () => { const url = new URL(els.service.value.trim()); if (!['http:', 'https:'].includes(url.protocol)) throw new Error('La URL debe comenzar por http o https.'); url.hash = ''; return url; };
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const layerByName = name => state.layers.find(layer => layer.name === name);

  function renderMeta() { const layer = layerByName(state.selected); els.meta.replaceChildren(); if (!layer) { const empty = document.createElement('span'); empty.className = 'meta-empty'; empty.textContent = 'La descripción y el CRS de la capa aparecerán aquí.'; els.meta.appendChild(empty); els.query.disabled = true; return; } const title = document.createElement('b'); title.textContent = layer.title || layer.name; const name = document.createElement('p'); name.textContent = `Nombre WFS: ${layer.name}`; const crs = document.createElement('p'); crs.textContent = `CRS declarado: ${layer.crs || 'no indicado'}`; const abstract = document.createElement('p'); abstract.textContent = layer.abstract || 'El servicio no ofrece un resumen para esta capa.'; els.meta.append(title, name, crs, abstract); els.query.disabled = false; }
  function renderLayers() { els.select.replaceChildren(); if (!state.layers.length) { const option = document.createElement('option'); option.textContent = 'No hay capas descubiertas'; els.select.appendChild(option); } state.layers.forEach(layer => { const option = document.createElement('option'); option.value = layer.name; option.textContent = layer.title && layer.title !== layer.name ? `${layer.title} · ${layer.name}` : layer.name; els.select.appendChild(option); }); els.select.disabled = !state.layers.length; els.query.disabled = !state.layers.length; state.selected = state.layers[0]?.name || null; if (state.selected) els.select.value = state.selected; renderMeta(); }
  function parseCapabilities(xml) { return [...xml.querySelectorAll('*')].filter(node => node.localName === 'FeatureType').map(node => ({ name: textOf(node, 'Name'), title: textOf(node, 'Title'), abstract: textOf(node, 'Abstract'), crs: textOf(node, 'DefaultCRS') || textOf(node, 'DefaultSRS') || textOf(node, 'SRS') })).filter((layer, index, all) => layer.name && all.findIndex(item => item.name === layer.name) === index); }
  async function inspect() { try { const serviceUrl = normaliseService(), requestUrl = new URL(serviceUrl); requestUrl.searchParams.set('service', 'WFS'); requestUrl.searchParams.set('request', 'GetCapabilities'); requestUrl.searchParams.set('version', '2.0.0'); els.inspect.disabled = true; setStatus('Consultando GetCapabilities del WFS…'); const response = await fetch(requestUrl, { headers: { Accept: 'application/xml,text/xml' } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const xml = new DOMParser().parseFromString(await response.text(), 'text/xml'); if (xml.querySelector('parsererror')) throw new Error('XML no válido'); const layers = parseCapabilities(xml); if (!layers.length) throw new Error('No se encontraron FeatureType con nombre.'); state.service = serviceUrl.toString(); state.layers = layers; state.result = null; renderLayers(); resetResult(); setStatus(`${layers.length} tipo${layers.length === 1 ? '' : 's'} de entidad descubierto${layers.length === 1 ? '' : 's'}.`); } catch (error) { state.layers = []; renderLayers(); setStatus(error.message === 'Failed to fetch' ? 'El navegador ha bloqueado la consulta CORS o el servicio no responde.' : `No se pudo leer el servicio: ${error.message}`, true); } finally { els.inspect.disabled = false; } }
  function parseBbox() { const value = els.bbox.value.trim(); if (!value) return null; const numbers = value.split(/[,;\s]+/).map(Number); if (numbers.length !== 4 || numbers.some(number => !Number.isFinite(number))) throw new Error('La BBOX debe tener cuatro números: minLon,minLat,maxLon,maxLat.'); if (numbers[0] >= numbers[2] || numbers[1] >= numbers[3]) throw new Error('La BBOX debe estar ordenada de menor a mayor.'); return numbers.join(','); }
  async function queryFeatures() { const layer = layerByName(state.selected); if (!layer) return; try { const serviceUrl = normaliseService(), requestUrl = new URL(serviceUrl); requestUrl.searchParams.set('service', 'WFS'); requestUrl.searchParams.set('request', 'GetFeature'); requestUrl.searchParams.set('version', '2.0.0'); requestUrl.searchParams.set('typeNames', layer.name); requestUrl.searchParams.set('outputFormat', 'application/json; subtype=geojson'); requestUrl.searchParams.set('count', String(Math.max(1, Math.min(5000, Number(els.limit.value) || 250)))); const bbox = parseBbox(); if (bbox) requestUrl.searchParams.set('bbox', bbox + ',urn:ogc:def:crs:OGC:1.3:CRS84'); els.query.disabled = true; setStatus('Consultando entidades GeoJSON…'); const response = await fetch(requestUrl, { headers: { Accept: 'application/geo+json,application/json' } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const json = await response.json(); if (!json || json.type !== 'FeatureCollection') throw new Error('El servicio no devolvió un FeatureCollection GeoJSON.'); state.result = json; state.checkedAt = new Date().toISOString(); state.service = serviceUrl.toString(); renderResult(layer); setStatus(`${json.features.length} entidad${json.features.length === 1 ? '' : 'es'} recibida${json.features.length === 1 ? '' : 's'} desde ${layer.name}.`); } catch (error) { setStatus(error.message === 'Failed to fetch' ? 'El navegador ha bloqueado la consulta CORS o el servicio no responde.' : `No se pudo consultar la capa: ${error.message}`, true); } finally { els.query.disabled = false; } }
  function resetResult() { state.resultLayer?.remove(); state.resultLayer = null; els.download.disabled = true; els.csv.disabled = true; els.mapTitle.textContent = 'Mapa base'; els.mapStatus.textContent = 'Mapa base listo.'; document.getElementById('resultBadge').textContent = '0 entidades'; document.getElementById('featureCount').textContent = '—'; document.getElementById('geometryType').textContent = '—'; document.getElementById('fieldCount').textContent = '—'; document.getElementById('checkedAt').textContent = '—'; document.getElementById('tableWrap').innerHTML = '<p class="empty">Consulta una capa para revisar sus atributos.</p>'; }
  function featurePoint(feature) { const coordinates = feature.geometry?.coordinates; if (!coordinates) return ['', '']; const first = feature.geometry.type === 'Point' ? coordinates : Array.isArray(coordinates[0]) ? coordinates[0] : coordinates; return [Array.isArray(first[0]) ? first[0][0] : first[0], Array.isArray(first[0]) ? first[0][1] : first[1]]; }
  function renderResult(layer) { state.resultLayer?.remove(); state.resultLayer = L.geoJSON(state.result, { style: { color: '#75d6c4', weight: 2, fillColor: '#75d6c4', fillOpacity: .22 }, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#75d6c4', fillColor: '#75d6c4', fillOpacity: .8 }), onEachFeature: (feature, featureLayer) => { const rows = Object.entries(feature.properties || {}).slice(0, 18).map(([key, value]) => `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(value)}</td></tr>`).join(''); featureLayer.bindPopup(`<table class="popup-table">${rows || '<tr><td>Sin atributos</td></tr>'}</table>`); } }).addTo(map); const bounds = state.resultLayer.getBounds(); if (bounds.isValid()) map.fitBounds(bounds.pad(.12)); els.mapTitle.textContent = layer.title || layer.name; els.mapStatus.textContent = `${state.result.features.length} entidades visibles.`; els.download.disabled = false; els.csv.disabled = false; const features = state.result.features, fields = [...new Set(features.flatMap(feature => Object.keys(feature.properties || {})))], geometryTypes = [...new Set(features.map(feature => feature.geometry?.type).filter(Boolean))]; document.getElementById('resultBadge').textContent = `${features.length} entidades`; document.getElementById('featureCount').textContent = format(features.length, 0); document.getElementById('geometryType').textContent = geometryTypes.length ? geometryTypes.join(', ') : 'sin geometría'; document.getElementById('fieldCount').textContent = format(fields.length, 0); document.getElementById('checkedAt').textContent = new Date(state.checkedAt).toLocaleTimeString('es-ES'); const sample = features.slice(0, 12); document.getElementById('tableWrap').innerHTML = fields.length ? `<table><thead><tr><th>ENTIDAD</th>${fields.slice(0, 8).map(field => `<th>${escapeHtml(field)}</th>`).join('')}</tr></thead><tbody>${sample.map((feature, index) => `<tr><td>${index + 1}</td>${fields.slice(0, 8).map(field => `<td>${escapeHtml(feature.properties?.[field] ?? '')}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="table-caption">Se muestran hasta 12 entidades y 8 campos para mantener la consulta legible. El GeoJSON descargado conserva la respuesta completa.</p>` : '<p class="empty">Las entidades no contienen atributos tabulares.</p>'; }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function csvCell(value) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportGeoJson() { download('wfs-consulta.geojson', JSON.stringify(state.result, null, 2), 'application/geo+json;charset=utf-8'); }
  function exportCsv() { const fields = [...new Set(state.result.features.flatMap(feature => Object.keys(feature.properties || {})))], rows = [['feature_index','geometry_type','lon','lat', ...fields], ...state.result.features.map((feature, index) => { const point = featurePoint(feature); return [index + 1, feature.geometry?.type || '', point[0], point[1], ...fields.map(field => feature.properties?.[field] ?? '')]; })]; download('wfs-atributos.csv', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  els.inspect.addEventListener('click', inspect); els.demo.addEventListener('click', () => { els.service.value = 'https://demo.mapserver.org/cgi-bin/wfs'; inspect(); }); els.select.addEventListener('change', () => { state.selected = els.select.value; renderMeta(); }); els.query.addEventListener('click', queryFeatures); els.clear.addEventListener('click', () => { state.layers = []; state.selected = null; state.result = null; renderLayers(); resetResult(); setStatus('Inventario y consulta limpiados.'); }); els.download.addEventListener('click', exportGeoJson); els.csv.addEventListener('click', exportCsv);
  CartografiaPlaceSearch(map, { input: document.getElementById('placeQuery'), button: document.getElementById('placeSearchButton'), results: document.getElementById('placeResults'), status: document.getElementById('placeStatus'), zoom: 13 });
})();
