(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { layers: [], merged: null, map: null, mapLayers: [] };
  const colors = ['#72e3be','#8bc4ff','#ffd47b','#ff9b9b','#c6a3ff','#f28ebd','#a6e3a1','#f6c177'];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection') return { type: 'FeatureCollection', features: parsed.features || [] }; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El documento no contiene GeoJSON reconocible.'); }
  function sourceName(name, fallback) { const clean = String(name || fallback).trim().replace(/[\\/:*?"<>|]/g, '-'); return clean || fallback; }
  function addLayer(name, collection) { const features = collection.features.filter(feature => feature && feature.geometry); if (!features.length) throw new Error('La capa no contiene entidades con geometría.'); state.layers.push({ name: sourceName(name, 'capa-' + (state.layers.length + 1) + '.geojson'), features }); renderSources(); renderMap(); $('mergeBtn').disabled = false; setStatus(`${state.layers.length} capas preparadas localmente.`); }
  function renderSources() { const total = state.layers.reduce((sum, layer) => sum + layer.features.length, 0); $('layerCount').textContent = state.layers.length; $('inputCount').textContent = total; $('countBadge').textContent = total + (total === 1 ? ' entidad' : ' entidades'); $('sourceList').innerHTML = state.layers.length ? state.layers.map((layer, index) => `<div class="source-row"><span class="source-dot" style="background:${colors[index % colors.length]}"></span><span><strong>${esc(layer.name)}</strong><small>${layer.features.length} entidades · ${[...new Set(layer.features.map(feature => feature.geometry?.type || 'Sin geometría'))].join(', ')}</small></span><button type="button" class="remove-source" data-index="${index}" aria-label="Quitar ${esc(layer.name)}">Quitar</button></div>`).join('') : '<p class="empty">Todavía no hay capas añadidas.</p>'; }
  function featureLabel(feature, index) { const props = feature.properties || {}; return props.name || props.nombre || props.id || 'Entidad ' + (index + 1); }
  function geometryKey(geometry) { return JSON.stringify(geometry, (key, value) => Array.isArray(value) ? value.map(item => Number.isFinite(Number(item)) ? Number(Number(item).toFixed(8)) : item) : value); }
  function mergeLayers() { if (!state.layers.length) return; const seen = new Set(), features = [], keptBySource = new Map(); state.layers.forEach(layer => { layer.features.forEach((feature, index) => { const key = geometryKey(feature.geometry); if ($('duplicates').value === 'drop' && seen.has(key)) return; seen.add(key); const sourceIndex = keptBySource.get(layer.name) || 0; keptBySource.set(layer.name, sourceIndex + 1); features.push({ ...feature, properties: { ...(feature.properties || {}), _merge_source: layer.name, _merge_order: sourceIndex + 1 } }); }); }); state.merged = { type: 'FeatureCollection', features }; $('outputCount').textContent = features.length; $('countBadge').textContent = features.length + (features.length === 1 ? ' entidad' : ' entidades'); $('sourceCount').textContent = new Set(features.map(feature => feature.properties._merge_source)).size; $('quality').textContent = $('duplicates').value === 'drop' && features.length < state.layers.reduce((sum, layer) => sum + layer.features.length, 0) ? 'Duplicados eliminados' : 'Combinación completa'; $('quality').className = 'quality'; renderSummary(); renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${features.length} entidades combinadas localmente.`); }
  function renderSummary() { const grouped = new Map(); (state.merged?.features || []).forEach(feature => { const source = feature.properties?._merge_source || 'sin fuente'; if (!grouped.has(source)) grouped.set(source, { count: 0, types: new Set() }); const item = grouped.get(source); item.count += 1; item.types.add(feature.geometry?.type || 'Sin geometría'); }); $('summary').innerHTML = '<table><thead><tr><th>Fuente</th><th>Entidades</th><th>Geometrías</th></tr></thead><tbody>' + [...grouped.entries()].map(([source, item]) => `<tr><td><span class="source-dot" style="background:${colors[[...grouped.keys()].indexOf(source) % colors.length]}"></span><strong>${esc(source)}</strong></td><td>${item.count}</td><td>${esc([...item.types].join(', '))}</td></tr>`).join('') + '</tbody></table>'; }
  function popup(feature) { const props = feature.properties || {}; const entries = Object.entries(props).filter(([key]) => !key.startsWith('_merge_')).slice(0, 8); return `<strong>${esc(featureLabel(feature, 0))}</strong><br><span>Fuente: ${esc(props._merge_source || '—')}</span><br>${esc(entries.map(([key, value]) => key + ': ' + value).join(' · '))}`; }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); }
  function renderMap() { if (!state.map) return; state.mapLayers.forEach(layer => state.map.removeLayer(layer)); state.mapLayers = []; const bounds = []; const sourceOrder = state.merged ? [...new Set(state.merged.features.map(feature => feature.properties?._merge_source))] : state.layers.map(layer => layer.name); sourceOrder.forEach((source, sourceIndex) => { const features = state.merged ? state.merged.features.filter(feature => feature.properties?._merge_source === source) : state.layers.find(layer => layer.name === source)?.features || []; if (!features.length) return; const layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: { color: colors[sourceIndex % colors.length], weight: 3, fillColor: colors[sourceIndex % colors.length], fillOpacity: .18 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#071b25', weight: 2, fillColor: colors[sourceIndex % colors.length], fillOpacity: .9 }), onEachFeature: (feature, item) => item.bindPopup(popup(feature)) }).addTo(state.map); state.mapLayers.push(layer); if (layer.getBounds().isValid()) bounds.push(layer.getBounds()); }); if (bounds.length) { const full = bounds.reduce((acc, item) => acc.extend(item), L.latLngBounds([])); state.map.fitBounds(full, { padding: [22, 22], maxZoom: 16 }); } }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const features = state.merged?.features || []; const keys = [...new Set(features.flatMap(feature => Object.keys(feature.properties || {})))]; const header = ['index','geometry_type',...keys]; const quote = value => '"' + String(value ?? '').replace(/"/g, '""') + '"'; const lines = [header.map(quote).join(',')]; features.forEach((feature, index) => lines.push([index + 1, feature.geometry?.type || '', ...keys.map(key => feature.properties?.[key])].map(quote).join(','))); download('capas-combinadas.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  $('addBtn').addEventListener('click', () => { try { addLayer($('sourceName').value, normalize($('source').value)); } catch (error) { setStatus(error.message || 'No se pudo añadir la capa.', true); } }); $('sampleBtn').addEventListener('click', () => { $('sourceName').value = 'capa-pegada.geojson'; $('source').value = sample; setStatus('Ejemplo restaurado; pulsa «Añadir capa pegada».'); }); $('file').addEventListener('change', event => { const files = [...(event.target.files || [])]; files.forEach(file => { const reader = new FileReader(); reader.onload = () => { try { addLayer(file.name, normalize(String(reader.result || ''))); } catch (error) { setStatus(`${file.name}: ${error.message || 'no se pudo leer.'}`, true); } }; reader.onerror = () => setStatus(`${file.name}: no se pudo leer el archivo local.`, true); reader.readAsText(file); }); event.target.value = ''; }); $('sourceList').addEventListener('click', event => { const button = event.target.closest('.remove-source'); if (!button) return; state.layers.splice(Number(button.dataset.index), 1); state.merged = null; renderSources(); renderMap(); $('mergeBtn').disabled = !state.layers.length; $('geojsonBtn').disabled = true; $('csvBtn').disabled = true; $('outputCount').textContent = '—'; $('quality').textContent = 'Sin combinar'; $('quality').className = 'quality muted'; setStatus('Capa retirada; los datos siguen locales.'); }); $('mergeBtn').addEventListener('click', mergeLayers); $('duplicates').addEventListener('change', () => { if (state.merged) mergeLayers(); }); $('geojsonBtn').addEventListener('click', () => { const name = sourceName($('outputName').value, 'capas-combinadas.geojson'); download(name.endsWith('.geojson') ? name : name + '.geojson', JSON.stringify(state.merged, null, 2), 'application/geo+json;charset=utf-8'); }); $('csvBtn').addEventListener('click', exportCsv); initMap(); try { addLayer('capa-pegada.geojson', normalize(sample)); } catch (error) { setStatus(error.message || 'No se pudo cargar el ejemplo.', true); }
})();
