(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { collection: null, points: [], hull: [], bbox: null, map: null, layer: null };
  const R = 6371008.8, rad = value => value * Math.PI / 180;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function formatDistance(value) { return value >= 1000 ? (value / 1000).toLocaleString('es-ES', { maximumFractionDigits: 3 }) + ' km' : value.toLocaleString('es-ES', { maximumFractionDigits: 1 }) + ' m'; }
  function formatArea(value) { return value >= 1000000 ? (value / 1000000).toLocaleString('es-ES', { maximumFractionDigits: 3 }) + ' km²' : value.toLocaleString('es-ES', { maximumFractionDigits: 1 }) + ' m²'; }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection') return parsed; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El documento no contiene GeoJSON reconocible.'); }
  function flatten(coords, output = []) { if (!Array.isArray(coords)) return output; if (coords.length >= 2 && Number.isFinite(Number(coords[0])) && Number.isFinite(Number(coords[1])) && Number(coords[0]) >= -180 && Number(coords[0]) <= 180 && Number(coords[1]) >= -90 && Number(coords[1]) <= 90) output.push([Number(coords[0]), Number(coords[1])]); else coords.forEach(value => flatten(value, output)); return output; }
  function featurePoint(feature) { const points = flatten(feature.geometry?.coordinates); if (!points.length) return null; return [points.reduce((sum, point) => sum + point[0], 0) / points.length, points.reduce((sum, point) => sum + point[1], 0) / points.length]; }
  function uniquePoints(points) { const seen = new Set(); return points.filter(point => { const key = point[0].toFixed(8) + ',' + point[1].toFixed(8); if (seen.has(key)) return false; seen.add(key); return true; }); }
  function cross(origin, a, b) { return (a[0] - origin[0]) * (b[1] - origin[1]) - (a[1] - origin[1]) * (b[0] - origin[0]); }
  function convexHull(points) { const sorted = [...uniquePoints(points)].sort((a, b) => a[0] - b[0] || a[1] - b[1]); if (sorted.length <= 2) return sorted; const lower = []; sorted.forEach(point => { while (lower.length >= 2 && cross(lower[lower.length - 2], lower[lower.length - 1], point) <= 0) lower.pop(); lower.push(point); }); const upper = []; [...sorted].reverse().forEach(point => { while (upper.length >= 2 && cross(upper[upper.length - 2], upper[upper.length - 1], point) <= 0) upper.pop(); upper.push(point); }); return lower.slice(0, -1).concat(upper.slice(0, -1)); }
  function bbox(points) { const lons = points.map(point => point[0]), lats = points.map(point => point[1]); const west = Math.min(...lons), east = Math.max(...lons), south = Math.min(...lats), north = Math.max(...lats); return { west, east, south, north, coordinates: [[west, south], [east, south], [east, north], [west, north], [west, south]] }; }
  function project(point, origin) { return { x: R * rad(point[0] - origin[0]) * Math.cos(rad(origin[1])), y: R * rad(point[1] - origin[1]) }; }
  function areaMeters(points) { if (points.length < 3) return 0; const origin = points[0], projected = points.map(point => project(point, origin)); let sum = 0; for (let i = 0; i < projected.length; i += 1) { const next = projected[(i + 1) % projected.length]; sum += projected[i].x * next.y - next.x * projected[i].y; } return Math.abs(sum / 2); }
  function distance(a, b) { const p1 = rad(a[1]), p2 = rad(b[1]), dLat = p2 - p1, dLon = rad(b[0] - a[0]), h = Math.sin(dLat / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.min(1, Math.sqrt(h))); }
  function perimeter(points) { return points.reduce((sum, point, index) => sum + distance(point, points[(index + 1) % points.length]), 0); }
  function calculate(collection) { const features = collection.features || [], points = []; features.forEach(feature => { const values = $('pointMode').value === 'centroids' ? [featurePoint(feature)].filter(Boolean) : flatten(feature.geometry?.coordinates); points.push(...values); }); const clean = uniquePoints(points); if (clean.length < 3) throw new Error('Se necesitan al menos tres posiciones válidas para calcular una huella.'); state.collection = collection; state.points = clean; state.hull = convexHull(clean); state.bbox = bbox(clean); const width = distance([state.bbox.west, (state.bbox.south + state.bbox.north) / 2], [state.bbox.east, (state.bbox.south + state.bbox.north) / 2]), height = distance([(state.bbox.west + state.bbox.east) / 2, state.bbox.south], [(state.bbox.west + state.bbox.east) / 2, state.bbox.north]); $('featureCount').textContent = features.length.toLocaleString('es-ES'); $('usedCount').textContent = clean.length.toLocaleString('es-ES'); $('hullCount').textContent = state.hull.length.toLocaleString('es-ES'); $('pointBadge').textContent = clean.length + ' puntos'; $('area').textContent = formatArea(areaMeters(state.hull)); $('width').textContent = formatDistance(width); $('height').textContent = formatDistance(height); $('perimeter').textContent = formatDistance(perimeter(state.hull)); $('quality').textContent = $('pointMode').value === 'centroids' ? 'Centros aproximados' : 'Vértices válidos'; $('quality').className = 'quality'; renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${clean.length} posiciones usadas localmente para ${features.length} entidades.`); }
  function outputCollection() { const features = [{ type: 'Feature', properties: { name: 'Huella convexa', point_count: state.points.length, hull_vertices: state.hull.length, area_m2: Number(areaMeters(state.hull).toFixed(3)) }, geometry: { type: 'Polygon', coordinates: [state.hull.concat([state.hull[0]])] } }, { type: 'Feature', properties: { name: 'Caja de extensión', west: state.bbox.west, east: state.bbox.east, south: state.bbox.south, north: state.bbox.north }, geometry: { type: 'Polygon', coordinates: [state.bbox.coordinates] } }]; if ($('showPoints').checked) state.points.forEach((point, index) => features.push({ type: 'Feature', properties: { name: 'Punto usado ' + (index + 1), order: index + 1 }, geometry: { type: 'Point', coordinates: point } })); return { type: 'FeatureCollection', features }; }
  function renderMap() { if (!state.map) return; state.layer?.clearLayers(); state.layer = L.layerGroup().addTo(state.map); const collection = outputCollection(); const geo = L.geoJSON(collection, { style: feature => feature.properties?.name === 'Caja de extensión' ? { color: '#ffd47b', weight: 2, fillOpacity: .06, dashArray: '7 5' } : { color: '#72e3be', weight: 4, fillColor: '#72e3be', fillOpacity: .16 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 5, color: '#071b25', weight: 2, fillColor: '#8bc4ff', fillOpacity: .95 }), onEachFeature: (feature, layer) => layer.bindPopup(`<strong>${esc(feature.properties?.name)}</strong><br>${feature.geometry.type}`) }).addTo(state.layer); if (geo.getBounds().isValid()) state.map.fitBounds(geo.getBounds(), { padding: [22, 22], maxZoom: 16 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const lines = ['orden,longitud,latitud']; state.points.forEach((point, index) => lines.push(`${index + 1},${point[0]},${point[1]}`)); download('huella-puntos.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); }
  function run() { try { calculate(normalize($('source').value)); } catch (error) { setStatus(error.message || 'No se pudo calcular la huella.', true); } }
  $('calculateBtn').addEventListener('click', run); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; $('pointMode').value = 'vertices'; run(); }); $('pointMode').addEventListener('change', run); $('showPoints').addEventListener('change', () => { if (state.points.length) renderMap(); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); run(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', () => download('huella-espacial.geojson', JSON.stringify(outputCollection(), null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', exportCsv); initMap(); run();
})();
