(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const state = { width: 720, height: 460, bands: [], composite: null, report: null, pixel: null };

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function bandName(index) { return `Banda ${index + 1}`; }
  function createBand(generator) { const data = new ImageData(state.width, state.height); for (let y = 0; y < state.height; y += 1) for (let x = 0; x < state.width; x += 1) { const index = (y * state.width + x) * 4, value = clamp(Math.round(generator(x, y)), 0, 255); data.data[index] = value; data.data[index + 1] = value; data.data[index + 2] = value; data.data[index + 3] = 255; } return data; }
  function makeExamples() {
    state.bands = [
      createBand((x, y) => 52 + x / state.width * 155 + Math.sin(y / 34) * 18),
      createBand((x, y) => 38 + y / state.height * 185 + Math.cos(x / 40) * 24),
      createBand((x, y) => 118 + Math.sin(x / 44) * 44 + Math.cos(y / 29) * 35)
    ];
    [[145,150,95],[490,190,125],[340,355,155]].forEach(([cx, cy, radius], shapeIndex) => { state.bands.forEach((band, bandIndex) => { const color = [230 - bandIndex * 34 - shapeIndex * 12, 72 + bandIndex * 38 + shapeIndex * 15, 100 + shapeIndex * 28]; for (let y = Math.max(0, cy - radius); y < Math.min(state.height, cy + radius); y += 1) for (let x = Math.max(0, cx - radius); x < Math.min(state.width, cx + radius); x += 1) { if ((x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2) { const index = (y * state.width + x) * 4; band.data[index] = color[bandIndex]; band.data[index + 1] = color[bandIndex]; band.data[index + 2] = color[bandIndex]; } } }); });
  }
  function readImage(file, bandIndex) { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = state.width; canvas.height = state.height; const context = canvas.getContext('2d'); context.fillStyle = '#000'; context.fillRect(0, 0, state.width, state.height); context.drawImage(image, 0, 0, state.width, state.height); const rgba = context.getImageData(0, 0, state.width, state.height), luminance = new ImageData(state.width, state.height); for (let index = 0; index < rgba.data.length; index += 4) { const value = Math.round(rgba.data[index] * .299 + rgba.data[index + 1] * .587 + rgba.data[index + 2] * .114); luminance.data[index] = value; luminance.data[index + 1] = value; luminance.data[index + 2] = value; luminance.data[index + 3] = rgba.data[index + 3]; } state.bands[bandIndex] = luminance; calculate(); setStatus(`${bandName(bandIndex)} cargada localmente como luminancia. La imagen no salió del navegador.`); }; image.onerror = () => setStatus(`No se pudo decodificar ${bandName(bandIndex)}.`, true); image.src = String(reader.result || ''); }; reader.onerror = () => setStatus(`No se pudo leer ${bandName(bandIndex)}.`, true); reader.readAsDataURL(file); }
  function histogramStats(data) { const histogram = new Uint32Array(256); let valid = 0, min = 255, max = 0; for (let index = 0; index < data.data.length; index += 4) { if (data.data[index + 3] < 10) continue; const value = data.data[index]; histogram[value] += 1; valid += 1; min = Math.min(min, value); max = Math.max(max, value); } return { histogram, valid, min: valid ? min : null, max: valid ? max : null }; }
  function percentile(histogram, total, fraction) { if (!total) return 0; const target = Math.max(1, Math.ceil(total * fraction)); let accumulated = 0; for (let value = 0; value < histogram.length; value += 1) { accumulated += histogram[value]; if (accumulated >= target) return value; } return 255; }
  function rangeFor(data, bandIndex) { const stats = histogramStats(data), mode = $('stretch').value; if (mode === 'minmax') return { min: stats.min ?? 0, max: stats.max ?? 255, stats }; if (mode === 'manual') { return { min: clamp(Number($(`min${bandIndex}`).value) || 0, 0, 255), max: clamp(Number($(`max${bandIndex}`).value) || 255, 0, 255), stats }; } return { min: percentile(stats.histogram, stats.valid, .02), max: percentile(stats.histogram, stats.valid, .98), stats }; }
  function stretch(value, range) { if (range.max <= range.min) return value >= range.max ? 255 : 0; return clamp(Math.round((value - range.min) / (range.max - range.min) * 255), 0, 255); }
  function applyPreset() { const preset = $('preset').value; $('profileBadge').textContent = preset === 'falsecolor' ? 'NIR–R–G' : preset === 'natural' ? 'RGB' : 'PERSONALIZADO'; if (preset === 'natural') { $('redBand').value = '0'; $('greenBand').value = '1'; $('blueBand').value = '2'; } if (preset === 'falsecolor') { $('redBand').value = '0'; $('greenBand').value = '1'; $('blueBand').value = '2'; } }
  function calculate() {
    try {
      if (state.bands.length !== 3) makeExamples();
      applyPreset();
      const ranges = state.bands.map((band, index) => rangeFor(band, index)), red = Number($('redBand').value), green = Number($('greenBand').value), blue = Number($('blueBand').value), output = new ImageData(state.width, state.height), validByBand = state.bands.map(() => 0);
      let valid = 0;
      for (let index = 0; index < output.data.length; index += 4) { const source = state.bands.map(band => band.data[index]), alpha = Math.min(...state.bands.map(band => band.data[index + 3])); if ($('transparent').value === 'yes' && alpha < 10) { output.data[index + 3] = 0; continue; } const values = ranges.map((range, bandIndex) => { const value = stretch(source[bandIndex], range); validByBand[bandIndex] += 1; return value; }); output.data[index] = values[red]; output.data[index + 1] = values[green]; output.data[index + 2] = values[blue]; output.data[index + 3] = 255; valid += 1; }
      state.composite = output; state.report = { width: state.width, height: state.height, profile: $('preset').value, profileLabel: $('profileBadge').textContent, stretch: $('stretch').value, mapping: { red, green, blue }, transparent: $('transparent').value === 'yes', validPixels: valid, bands: ranges.map((range, index) => ({ name: bandName(index), sourcePixels: validByBand[index], minimum: range.min, maximum: range.max, sourceMinimum: range.stats.min, sourceMaximum: range.stats.max })) };
      $('compositeCanvas').getContext('2d').putImageData(output, 0, 0); renderReport(); updatePixel(); $('pngBtn').disabled = false; $('jsonBtn').disabled = false; $('csvBtn').disabled = false; $('quality').textContent = 'Listo'; $('quality').className = 'quality ready'; setStatus(`${format(valid, 0)} píxeles válidos. Composición generada localmente con estiramiento ${$('stretch').value}.`);
    } catch (error) { setStatus(error.message || 'No se pudo crear la composición.', true); }
  }
  function renderReport() { const report = state.report; $('imageSize').textContent = `${report.width} × ${report.height}`; $('validPixels').textContent = format(report.validPixels, 0); $('redSource').textContent = bandName(report.mapping.red); $('greenSource').textContent = bandName(report.mapping.green); $('blueSource').textContent = bandName(report.mapping.blue); $('tableWrap').innerHTML = `<table><thead><tr><th>BANDA</th><th>RANGO USADO</th><th>RANGO DE ORIGEN</th><th>PÍXELES</th></tr></thead><tbody>${report.bands.map(item => `<tr><td>${item.name}</td><td>${format(item.minimum)} – ${format(item.maximum)}</td><td>${item.sourceMinimum === null ? '—' : format(item.sourceMinimum) + ' – ' + format(item.sourceMaximum)}</td><td>${format(item.sourcePixels, 0)}</td></tr>`).join('')}</tbody></table>`; }
  function pixelAt(event) { const rect = $('compositeCanvas').getBoundingClientRect(), x = clamp(Math.floor((event.clientX - rect.left) / rect.width * state.width), 0, state.width - 1), y = clamp(Math.floor((event.clientY - rect.top) / rect.height * state.height), 0, state.height - 1), index = (y * state.width + x) * 4, mapping = state.report.mapping, values = state.bands.map(band => band.data[index]), output = state.composite.data; state.pixel = { x, y, values, rgb: [output[index], output[index + 1], output[index + 2]] }; updatePixel(); }
  function updatePixel() { if (!state.pixel) { $('pixelText').textContent = 'Píxel: haz clic en la composición.'; return; } $('pixelSwatch').style.background = `rgb(${state.pixel.rgb.join(',')})`; $('pixelText').textContent = `Píxel ${state.pixel.x}, ${state.pixel.y} · bandas ${state.pixel.values.join(', ')} · RGB ${state.pixel.rgb.join(', ')}`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportPng() { const link = document.createElement('a'); link.href = $('compositeCanvas').toDataURL('image/png'); link.download = 'composicion-raster.png'; link.click(); }
  function exportJson() { download('informe-composicion-raster.json', JSON.stringify(state.report, null, 2), 'application/json;charset=utf-8'); }
  function csvCell(value) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }
  function exportCsv() { const rows = [['banda','minimo_usado','maximo_usado','minimo_origen','maximo_origen','pixeles'], ...state.report.bands.map(item => [item.name, item.minimum, item.maximum, item.sourceMinimum, item.sourceMaximum, item.sourcePixels])]; download('estadisticas-composicion-raster.csv', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8'); }

  $('calculateBtn').addEventListener('click', calculate); $('sampleBtn').addEventListener('click', () => { makeExamples(); calculate(); }); $('preset').addEventListener('change', calculate); $('stretch').addEventListener('change', () => { $('manualGrid').hidden = $('stretch').value !== 'manual'; calculate(); }); ['redBand', 'greenBand', 'blueBand', 'transparent', 'min0', 'max0', 'min1', 'max1', 'min2', 'max2'].forEach(id => $(id).addEventListener('change', calculate)); [0,1,2].forEach(index => $(`file${index}`).addEventListener('change', event => { const file = event.target.files?.[0]; if (file) readImage(file, index); })); $('compositeCanvas').addEventListener('click', pixelAt); $('pngBtn').addEventListener('click', exportPng); $('jsonBtn').addEventListener('click', exportJson); $('csvBtn').addEventListener('click', exportCsv);
  makeExamples(); calculate();
})();
