(() => {
  'use strict';
  const map = L.map('map').setView([40.32, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
  const state = { geojson: null, rows: [], output: null, layer: null, joinedAt: null };
  const els = { geoFile: document.getElementById('geoFile'), tableFile: document.getElementById('tableFile'), geoKey: document.getElementById('geoKey'), tableKey: document.getElementById('tableKey'), joinType: document.getElementById('joinType'), prefix: document.getElementById('prefix'), join: document.getElementById('joinBtn'), clear: document.getElementById('clearBtn'), sample: document.getElementById('sampleBtn'), status: document.getElementById('status'), mapTitle: document.getElementById('mapTitle'), mapStatus: document.getElementById('mapStatus') };
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const keyOf = value => String(value ?? '').trim();
  const csvCell = value => `"${String(value ?? '').replace(/"/g, '""')}"`;
  function parseDelimited(text) { const delimiter = (text.split(/\r?\n/, 1)[0].match(/\t/g) || []).length > (text.split(/\r?\n/, 1)[0].match(/;/g) || []).length ? '\t' : ((text.split(/\r?\n/, 1)[0].match(/;/g) || []).length > (text.split(/\r?\n/, 1)[0].match(/,/g) || []).length ? ';' : ','); const rows = [], row = []; let cell = '', quoted = false; for (let index = 0; index < text.length; index += 1) { const character = text[index], next = text[index + 1]; if (character === '"' && quoted && next === '"') { cell += '"'; index += 1; } else if (character === '"') quoted = !quoted; else if (character === delimiter && !quoted) { row.push(cell); cell = ''; } else if ((character === '\n' || character === '\r') && !quoted) { if (character === '\r' && next === '\n') index += 1; row.push(cell); rows.push(row.splice(0)); cell = ''; } else cell += character; } row.push(cell); if (row.length > 1 || row[0]) rows.push(row); const headers = (rows.shift() || []).map((header, index) => header.trim() || `campo_${index + 1}`); return { headers, rows: rows.filter(values => values.some(value => value.trim() !== '')).map(values => Object.fromEntries(headers.map((header, index) => [header, (values[index] ?? '').trim()]))), delimiter }; }
  function geoFields() { const fields = new Set(); state.geojson?.features?.forEach(feature => Object.keys(feature.properties || {}).forEach(field => fields.add(field))); return [...fields]; }
  function tableFields() { return state.rows.length ? Object.keys(state.rows[0]) : []; }
  function fillSelect(select, fields, empty) { select.replaceChildren(); if (!fields.length) { const option = document.createElement('option'); option.textContent = empty; select.appendChild(option); select.disabled = true; return; } fields.forEach(field => { const option = document.createElement('option'); option.value = field; option.textContent = field; select.appendChild(option); }); select.disabled = false; }
  function refreshSelectors() { const geo = geoFields(), table = tableFields(); fillSelect(els.geoKey, geo, 'Carga un GeoJSON'); fillSelect(els.tableKey, table, 'Carga una tabla'); if (geo.length) els.geoKey.value = geo.find(field => /^(id|codigo|code|key|clave)$/i.test(field)) || geo[0]; if (table.length) els.tableKey.value = table.find(field => field === els.geoKey.value) || table.find(field => /^(id|codigo|code|key|clave)$/i.test(field)) || table[0]; els.join.disabled = !(geo.length && table.length); }
  function readGeo(file) { const reader = new FileReader(); reader.onload = () => { try { const json = JSON.parse(String(reader.result || '')); if (!json || json.type !== 'FeatureCollection' || !Array.isArray(json.features)) throw new Error('Se esperaba un FeatureCollection GeoJSON.'); state.geojson = json; refreshSelectors(); setStatus(`${json.features.length} entidades GeoJSON cargadas localmente.`); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus('No se pudo leer el GeoJSON.', true); reader.readAsText(file); }
  function readTable(file) { const reader = new FileReader(); reader.onload = () => { try { const parsed = parseDelimited(String(reader.result || '')); if (!parsed.headers.length || !parsed.rows.length) throw new Error('La tabla no contiene cabeceras y filas reconocibles.'); state.rows = parsed.rows; refreshSelectors(); setStatus(`${parsed.rows.length} filas cargadas localmente; separador detectado: ${parsed.delimiter === '\t' ? 'tabulador' : parsed.delimiter}.`); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus('No se pudo leer la tabla.', true); reader.readAsText(file); }
  function popup(feature) { const rows = Object.entries(feature.properties || {}).slice(0, 20).map(([key, value]) => `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(value)}</td></tr>`).join(''); return `<table class="popup-table">${rows || '<tr><td>Sin atributos</td></tr>'}</table>`; }
  function renderMap() { state.layer?.remove(); if (!state.output) return; state.layer = L.geoJSON(state.output, { style: feature => ({ color: feature.properties?.join_status === 'matched' ? '#75d6c4' : '#ff9d9d', weight: 2, fillColor: feature.properties?.join_status === 'matched' ? '#75d6c4' : '#ff9d9d', fillOpacity: .24 }), pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: feature.properties?.join_status === 'matched' ? '#75d6c4' : '#ff9d9d', fillColor: feature.properties?.join_status === 'matched' ? '#75d6c4' : '#ff9d9d', fillOpacity: .85 }), onEachFeature: (feature, layer) => layer.bindPopup(popup(feature)) }).addTo(map); const bounds = state.layer.getBounds(); if (bounds.isValid()) map.fitBounds(bounds.pad(.12)); els.mapTitle.textContent = 'Capa unida'; els.mapStatus.textContent = `${state.output.features.length} entidades · verde coincide · rojo sin coincidencia.`; }
  function calculate() { if (!state.geojson || !state.rows.length) return; const geoKey = els.geoKey.value, tableKey = els.tableKey.value, prefix = els.prefix.value || 'join_', tableMap = new Map(), duplicateKeys = new Set(); state.rows.forEach(row => { const key = keyOf(row[tableKey]); if (!key) return; if (tableMap.has(key)) duplicateKeys.add(key); else tableMap.set(key, row); }); const joined = [], matchedKeys = new Set(); state.geojson.features.forEach(feature => { const properties = feature.properties || {}, key = keyOf(properties[geoKey]), row = tableMap.get(key), matched = Boolean(row); if (matched) matchedKeys.add(key); if (!matched && els.joinType.value === 'inner') return; const extra = {}; if (row) Object.entries(row).forEach(([field, value]) => { if (field !== tableKey) extra[`${prefix}${field}`] = value; }); joined.push({ ...feature, properties: { ...properties, ...extra, join_status: matched ? 'matched' : 'unmatched', join_key: key } }); }); state.output = { type: 'FeatureCollection', features: joined }; state.joinedAt = new Date().toISOString(); renderMap(); renderReport({ geoKey, tableKey, duplicateKeys, matchedKeys, tableMap }); setStatus(`${matchedKeys.size} claves de tabla encontradas; ${joined.length} entidades en la salida.`); }
  function renderReport(context) { const features = state.geojson?.features || [], output = state.output?.features || [], matched = output.filter(feature => feature.properties?.join_status === 'matched').length, unmatched = output.length - matched; document.getElementById('geoCount').textContent = format(features.length); document.getElementById('outputCount').textContent = format(output.length); document.getElementById('matchedCount').textContent = format(matched); document.getElementById('unmatchedCount').textContent = format(unmatched); document.getElementById('duplicateCount').textContent = format(context.duplicateKeys.size); document.getElementById('quality').textContent = unmatched ? 'Revisar' : 'Completo'; document.getElementById('quality').className = unmatched ? 'quality warn' : 'quality ready'; ['geoBtn','csvBtn','reportBtn'].forEach(id => { document.getElementById(id).disabled = !state.output; }); const fields = [...new Set(output.flatMap(feature => Object.keys(feature.properties || {})))], visible = fields.slice(0, 8), sample = output.slice(0, 16); document.getElementById('tableWrap').innerHTML = output.length ? `<table><thead><tr><th>ENTIDAD</th>${visible.map(field => `<th>${escapeHtml(field)}</th>`).join('')}</tr></thead><tbody>${sample.map((feature, index) => `<tr><td>${index + 1}</td>${visible.map(field => `<td>${escapeHtml(feature.properties?.[field] ?? '')}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="table-caption">Se muestran hasta 16 entidades y 8 campos. El GeoJSON descargado conserva todas las propiedades.</p>` : '<p class="empty">La unión interior no ha encontrado coincidencias.</p>'; }
  function format(value) { return Number(value).toLocaleString('es-ES'); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportGeo() { download('capa-unida.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8'); }
  function exportCsv() { const fields = [...new Set(state.output.features.flatMap(feature => Object.keys(feature.properties || {})))], rows = [['feature_index', ...fields], ...state.output.features.map((feature, index) => [index + 1, ...fields.map(field => feature.properties?.[field] ?? '')])]; download('capa-unida-propiedades.csv', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function exportReport() { download('informe-union.json', JSON.stringify({ joinedAt: state.joinedAt, geoKey: els.geoKey.value, tableKey: els.tableKey.value, joinType: els.joinType.value, prefix: els.prefix.value, geojsonFeatures: state.geojson.features.length, outputFeatures: state.output.features.length, output: state.output.features.map(feature => feature.properties?.join_status) }, null, 2), 'application/json;charset=utf-8'); }
  function loadSample() { state.geojson = { type: 'FeatureCollection', features: [[-3.71,40.42,'MAD'],[-3.70,40.41,'MAD-2'],[-0.38,39.47,'VAL'],[-5.99,37.39,'SEV'],[-1.13,37.99,'MUR']].map(([lon, lat, code], index) => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [lon, lat] }, properties: { site_id: code, nombre: ['Centro','Ribera','Puerto','Alameda','Huerta'][index] } })) }; state.rows = [{ site_id: 'MAD', poblacion: '3223334', grupo: 'capital' }, { site_id: 'VAL', poblacion: '789744', grupo: 'costa' }, { site_id: 'SEV', poblacion: '684025', grupo: 'capital' }, { site_id: 'ZZZ', poblacion: '10', grupo: 'fuera' }, { site_id: 'ZZZ', poblacion: '11', grupo: 'duplicada' }]; refreshSelectors(); calculate(); setStatus('Ejemplo cargado: hay una entidad sin coincidencia y una clave de tabla duplicada para revisar.'); }
  els.geoFile.addEventListener('change', event => { const file = event.target.files?.[0]; if (file) readGeo(file); }); els.tableFile.addEventListener('change', event => { const file = event.target.files?.[0]; if (file) readTable(file); }); els.sample.addEventListener('click', loadSample); els.join.addEventListener('click', calculate); els.geoKey.addEventListener('change', calculate); els.tableKey.addEventListener('change', calculate); els.joinType.addEventListener('change', calculate); els.clear.addEventListener('click', () => { state.geojson = null; state.rows = []; state.output = null; state.layer?.remove(); state.layer = null; refreshSelectors(); document.getElementById('tableWrap').innerHTML = '<p class="empty">Ejecuta una unión para revisar la salida.</p>'; ['geoBtn','csvBtn','reportBtn'].forEach(id => { document.getElementById(id).disabled = true; }); setStatus('Fuentes y resultados limpiados.'); }); document.getElementById('geoBtn').addEventListener('click', exportGeo); document.getElementById('csvBtn').addEventListener('click', exportCsv); document.getElementById('reportBtn').addEventListener('click', exportReport);
  CartografiaPlaceSearch(map, { input: document.getElementById('placeQuery'), button: document.getElementById('placeSearchButton'), results: document.getElementById('placeResults'), status: document.getElementById('placeStatus'), zoom: 13 });
  function init() { refreshSelectors(); document.getElementById('tableWrap').innerHTML = '<p class="empty">Ejecuta una unión para revisar la salida.</p>'; }
  init();
})();
