const $ = id => document.getElementById(id);
const state = { base: null, current: null, results: [], visible: [], selected: null, hitAreas: [], keys: new Set() };
const demoBase = { type: 'FeatureCollection', features: [
  { type: 'Feature', properties: { id: 'A-01', nombre: 'Villa del Arroyo', estado: 'documentado' }, geometry: { type: 'Polygon', coordinates: [[[-4.75, 40.42], [-4.71, 40.45], [-4.66, 40.42], [-4.7, 40.38], [-4.75, 40.42]]] } },
  { type: 'Feature', properties: { id: 'A-02', nombre: 'Camino de la Sierra', estado: 'parcial' }, geometry: { type: 'LineString', coordinates: [[-4.83, 40.34], [-4.76, 40.37], [-4.69, 40.4], [-4.61, 40.46]] } },
  { type: 'Feature', properties: { id: 'A-03', nombre: 'Atalaya norte', estado: 'documentado' }, geometry: { type: 'Point', coordinates: [-4.8, 40.49] } }
] };
const demoCurrent = { type: 'FeatureCollection', features: [
  { type: 'Feature', properties: { id: 'A-01', nombre: 'Villa del Arroyo', estado: 'consolidado' }, geometry: { type: 'Polygon', coordinates: [[[-4.75, 40.42], [-4.71, 40.46], [-4.65, 40.42], [-4.7, 40.38], [-4.75, 40.42]]] } },
  { type: 'Feature', properties: { id: 'A-02', nombre: 'Camino de la Sierra', estado: 'parcial' }, geometry: { type: 'LineString', coordinates: [[-4.83, 40.34], [-4.76, 40.37], [-4.69, 40.4], [-4.61, 40.46]] } },
  { type: 'Feature', properties: { id: 'A-04', nombre: 'Cantera de granito', estado: 'nuevo' }, geometry: { type: 'Point', coordinates: [-4.59, 40.36] } }
] };
function escapeHtml(value) { return String(value == null ? '—' : value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character])); }
function normalize(input) { if (input && input.type === 'FeatureCollection') return input.features.filter(feature => feature && feature.geometry); if (input && input.type === 'Feature' && input.geometry) return [input]; if (Array.isArray(input)) return input.filter(feature => feature && feature.geometry); throw new Error('GeoJSON no válido: se esperaba una FeatureCollection.'); }
function coords(geometry) { const points = []; const walk = value => { if (Array.isArray(value) && typeof value[0] === 'number') points.push([value[0], value[1]]); else if (Array.isArray(value)) value.forEach(walk); }; walk(geometry && geometry.coordinates); return points.filter(point => Number.isFinite(point[0]) && Number.isFinite(point[1])); }
function typeOf(feature) { return feature.geometry && feature.geometry.type || 'Sin geometría'; }
function labelOf(feature, index) { const props = feature.properties || {}; const key = Object.keys(props).find(name => /^(name|nombre|title|label)$/i.test(name)) || Object.keys(props).find(name => /^(id|codigo|code)$/i.test(name)); return key ? String(props[key]) : 'Entidad ' + (index + 1); }
function keysOf(features) { return [...new Set(features.flatMap(feature => Object.keys(feature.properties || {})))].sort((a, b) => a.localeCompare(b)); }
function refreshKeyOptions() { const keys = keysOf([...(state.base || []), ...(state.current || [])]); $('key').innerHTML = '<option value="auto">Auto: id, código o nombre</option>' + keys.map(key => '<option value="' + escapeHtml(key) + '">' + escapeHtml(key) + '</option>').join(''); }
function keyOf(feature, index) { const props = feature.properties || {}; const chosen = $('key').value; if (chosen !== 'auto' && props[chosen] != null) return String(props[chosen]); const candidate = Object.keys(props).find(name => /^(id|codigo|code|name|nombre|title|label)$/i.test(name)); return candidate && props[candidate] != null ? String(props[candidate]) : labelOf(feature, index); }
function same(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
function compare() {
  if (!state.base || !state.current) { state.results = []; render(); return; }
  const baseMap = new Map(state.base.map((feature, index) => [keyOf(feature, index), { feature, index }])); const used = new Set(); const results = [];
  state.current.forEach((feature, index) => { const key = keyOf(feature, index); const previous = baseMap.get(key); let status = 'added'; if (previous) { used.add(key); status = same(previous.feature.geometry, feature.geometry) && same(previous.feature.properties || {}, feature.properties || {}) ? 'unchanged' : 'changed'; } results.push({ status, key, feature, previous: previous && previous.feature, source: 'actual', label: labelOf(feature, index) }); });
  state.base.forEach((feature, index) => { const key = keyOf(feature, index); if (!used.has(key) && !state.current.some((item, currentIndex) => keyOf(item, currentIndex) === key)) results.push({ status: 'removed', key, feature, previous: feature, source: 'anterior', label: labelOf(feature, index) }); });
  state.results = results; state.selected = null; $('status').textContent = state.base.length + ' entidades anteriores · ' + state.current.length + ' actuales · comparación completada.'; render();
}
function extent() { const points = state.results.flatMap(result => coords(result.feature.geometry)); if (!points.length) return [-1, -1, 1, 1]; const xs = points.map(point => point[0]); const ys = points.map(point => point[1]); const dx = Math.max((Math.max(...xs) - Math.min(...xs)) * .08, .001); const dy = Math.max((Math.max(...ys) - Math.min(...ys)) * .08, .001); return [Math.min(...xs) - dx, Math.min(...ys) - dy, Math.max(...xs) + dx, Math.max(...ys) + dy]; }
function drawGeometry(context, geometry, project) { const line = values => values.forEach((value, index) => { const pair = project(value); index ? context.lineTo(pair[0], pair[1]) : context.moveTo(pair[0], pair[1]); }); if (geometry.type === 'Point') { const pair = project(geometry.coordinates); context.beginPath(); context.arc(pair[0], pair[1], 6, 0, Math.PI * 2); context.fill(); context.stroke(); return; } if (geometry.type === 'MultiPoint') { geometry.coordinates.forEach(value => drawGeometry(context, { type: 'Point', coordinates: value }, project)); return; } const polygon = values => values.forEach(ring => { context.beginPath(); line(ring); context.closePath(); context.fill(); context.stroke(); }); context.beginPath(); if (geometry.type === 'LineString') line(geometry.coordinates); if (geometry.type === 'MultiLineString') geometry.coordinates.forEach(line); if (geometry.type === 'Polygon') polygon(geometry.coordinates); if (geometry.type === 'MultiPolygon') geometry.coordinates.forEach(polygon); if (geometry.type.indexOf('Polygon') !== -1) { context.fill(); context.stroke(); } else context.stroke(); }
function draw() { const canvas = $('map'); const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; const width = Math.max(320, rect.width); const height = Math.max(240, width * .62); canvas.width = width * dpr; canvas.height = height * dpr; canvas.style.height = String(height) + 'px'; const context = canvas.getContext('2d'); context.setTransform(dpr, 0, 0, dpr, 0, 0); context.fillStyle = '#0a202a'; context.fillRect(0, 0, width, height); const box = extent(); const pad = 30; const project = coordinate => [pad + (coordinate[0] - box[0]) / (box[2] - box[0]) * (width - pad * 2), height - pad - (coordinate[1] - box[1]) / (box[3] - box[1]) * (height - pad * 2)]; context.strokeStyle = '#1d4351'; context.lineWidth = 1; for (let i = 0; i < 5; i += 1) { const x = pad + i * (width - pad * 2) / 4; const y = pad + i * (height - pad * 2) / 4; context.beginPath(); context.moveTo(x, pad); context.lineTo(x, height - pad); context.moveTo(pad, y); context.lineTo(width - pad, y); context.stroke(); } state.hitAreas = []; state.visible.forEach((result, index) => { const points = coords(result.feature.geometry); if (!points.length) return; const screen = points.map(project); const xs = screen.map(point => point[0]); const ys = screen.map(point => point[1]); const selected = state.selected === result; const color = result.status === 'added' ? '#7ae6a1' : result.status === 'removed' ? '#ff8090' : result.status === 'changed' ? '#ffc76b' : '#8ec9ff'; context.save(); context.globalAlpha = selected ? 1 : result.status === 'unchanged' ? .45 : .9; context.strokeStyle = color; context.fillStyle = color + '24'; context.lineWidth = selected ? 4 : result.status === 'removed' ? 2 : 1.8; drawGeometry(context, result.feature.geometry, project); context.restore(); state.hitAreas.push({ result, minX: Math.min(...xs) - 12, maxX: Math.max(...xs) + 12, minY: Math.min(...ys) - 12, maxY: Math.max(...ys) + 12 }); }); }
function renderDetails() { const result = state.selected; $('selection').textContent = result ? result.status + ' · ' + result.label : 'Sin selección'; if (!result) { $('details').innerHTML = '<p class="empty">Selecciona un resultado en la tabla o el mapa.</p>'; return; } const props = Object.entries(result.feature.properties || {}); $('details').innerHTML = '<p class="change-note"><b>' + escapeHtml(result.status) + '</b> · clave ' + escapeHtml(result.key) + ' · origen ' + escapeHtml(result.source) + '</p><dl>' + (props.length ? props.map(item => '<div class="property"><dt>' + escapeHtml(item[0]) + '</dt><dd>' + escapeHtml(typeof item[1] === 'object' ? JSON.stringify(item[1]) : item[1]) + '</dd></div>').join('') : '<p class="empty">Sin propiedades.</p>') + '</dl><p class="hint">Geometría: ' + escapeHtml(typeOf(result.feature)) + ' · ' + coords(result.feature.geometry).length + ' vértices</p>'; }
function render() { const query = $('search').value.trim().toLocaleLowerCase(); const filter = $('statusFilter').value; state.visible = state.results.filter(result => (filter === 'all' || result.status === filter) && (!query || result.label.toLocaleLowerCase().includes(query) || result.key.toLocaleLowerCase().includes(query))); const counts = state.results.reduce((out, result) => { out[result.status] = (out[result.status] || 0) + 1; return out; }, {}); const values = [['Anterior', state.base ? state.base.length : 0], ['Actual', state.current ? state.current.length : 0], ['Añadidos', counts.added || 0], ['Eliminados', counts.removed || 0], ['Modificados', counts.changed || 0], ['Sin cambios', counts.unchanged || 0]]; $('metrics').innerHTML = values.map(item => '<div class="metric"><b>' + item[1].toLocaleString('es-ES') + '</b><span>' + item[0] + '</span></div>').join(''); $('table').innerHTML = state.visible.length ? state.visible.map((result, index) => '<tr><td>' + (index + 1) + '</td><td><span class="change-badge change-' + result.status + '">' + result.status + '</span></td><td>' + escapeHtml(result.key) + '</td><td>' + escapeHtml(result.label) + '</td><td>' + escapeHtml(result.source) + '</td><td><button type="button" class="row-button" data-index="' + index + '">Ver</button></td></tr>').join('') : '<tr><td colspan="6">No hay resultados con estos filtros.</td></tr>'; document.querySelectorAll('.row-button').forEach(button => button.addEventListener('click', () => { state.selected = state.visible[Number(button.dataset.index)]; renderDetails(); draw(); render(); })); $('tableHint').textContent = state.visible.length + ' de ' + state.results.length + ' resultados visibles.'; $('export').disabled = !state.results.length; $('exportCsv').disabled = !state.results.length; draw(); renderDetails(); }
function download(name, type, value) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([value], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function report() { return { type: 'FeatureCollection', features: state.results.map(result => ({ ...result.feature, properties: { ...(result.feature.properties || {}), _change: result.status, _match_key: result.key, _source: result.source } })) }; }
function csv() { return ['change,match_key,label,source', ...state.results.map(result => [result.status, result.key, result.label, result.source].map(value => JSON.stringify(value)).join(','))].join('\n'); }
function loadFile(input, label) { const file = input.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { if (label === 'base') state.base = normalize(JSON.parse(reader.result)); else state.current = normalize(JSON.parse(reader.result)); refreshKeyOptions(); compare(); } catch (error) { $('status').textContent = 'No se pudo leer ' + label + ': ' + error.message; } }; reader.readAsText(file); }
$('demo').addEventListener('click', () => { state.base = normalize(demoBase); state.current = normalize(demoCurrent); refreshKeyOptions(); compare(); });
$('baseFile').addEventListener('change', event => loadFile(event.target, 'base')); $('currentFile').addEventListener('change', event => loadFile(event.target, 'current')); $('key').addEventListener('change', compare); $('statusFilter').addEventListener('change', render); $('search').addEventListener('input', render);
$('export').addEventListener('click', () => download('layer-diff-informe.geojson', 'application/geo+json', JSON.stringify(report(), null, 2))); $('exportCsv').addEventListener('click', () => download('layer-diff-informe.csv', 'text/csv', csv()));
$('map').addEventListener('pointerdown', event => { const rect = $('map').getBoundingClientRect(); const x = event.clientX - rect.left; const y = event.clientY - rect.top; const hit = [...state.hitAreas].reverse().find(area => x >= area.minX && x <= area.maxX && y >= area.minY && y <= area.maxY); if (hit) { state.selected = hit.result; renderDetails(); draw(); } });
window.addEventListener('resize', draw); $('demo').click();
