(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, features: [], field: '', stats: null, map: null, layer: null };
  const palette = ['#3b82c4', '#32a7c1', '#4cc38d', '#b9d35e', '#f2a34a', '#f27c56', '#e45d72'];
  const example = { type: 'FeatureCollection', features: [[-3.716, 40.419, 12, 'Norte', '2021'], [-3.712, 40.421, 19, 'Norte', '2021'], [-3.708, 40.417, 24, 'Norte', '2022'], [-3.704, 40.423, 28, 'Norte', '2022'], [-3.695, 40.414, 36, 'Centro', '2021'], [-3.691, 40.418, 42, 'Centro', '2022'], [-3.687, 40.412, 48, 'Centro', '2022'], [-3.678, 40.428, 57, 'Este', '2023'], [-3.674, 40.432, 63, 'Este', '2023'], [-3.668, 40.429, 71, 'Este', '2024'], [-3.658, 40.438, 84, 'Este', '2024'], [-3.651, 40.442, null, 'Este', '2024']].map(([lon, lat, value, zone, year], index) => ({ type: 'Feature', properties: { id: `obs-${index + 1}`, indice: value, zona: zone, periodo: year }, geometry: { type: 'Point', coordinates: [lon, lat] } })) };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function toNumber(value) { if (value === null || value === undefined || value === '' || (typeof value === 'string' && !value.trim())) return null; const number = Number(String(value).replace(',', '.')); return Number.isFinite(number) ? number : null; }
  function normalize(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input; if (input.type === 'Feature') return { type: 'FeatureCollection', features: [input] }; if (typeof input.type === 'string') return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: input }] }; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON.'); }
  function collectCoordinates(geometry, output = []) { if (!geometry || typeof geometry !== 'object') return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child) => collectCoordinates(child, output)); return output; } const walk = (node) => { if (!Array.isArray(node)) return; if (node.length >= 2 && Number.isFinite(Number(node[0])) && Number.isFinite(Number(node[1]))) { output.push([Number(node[0]), Number(node[1])]); return; } node.forEach(walk); }; walk(geometry.coordinates); return output; }
  function representative(geometry) { const points = collectCoordinates(geometry); if (!points.length) return null; return points.reduce((sum, point) => [sum[0] + point[0], sum[1] + point[1]], [0, 0]).map((value) => value / points.length); }
  function propertyKeys() { const keys = new Set(); state.features.forEach((feature) => Object.keys(feature.properties || {}).forEach((key) => keys.add(key))); return [...keys]; }
  function isNumericField(key) { const values = state.features.map((feature) => toNumber(feature.properties?.[key])).filter((value) => value !== null); return values.length > 0; }
  function fillFieldSelects() { const keys = propertyKeys(); const numeric = keys.filter(isNumericField); const category = keys.filter((key) => !numeric.includes(key) || state.features.some((feature) => typeof feature.properties?.[key] === 'string')); $('field').innerHTML = numeric.length ? numeric.map((key) => `<option value="${escapeHtml(key)}">${escapeHtml(key)}</option>`).join('') : '<option value="">No hay atributos numéricos</option>'; $('field').disabled = !numeric.length; $('categoryField').innerHTML = '<option value="">— ningún campo categórico —</option>' + category.map((key) => `<option value="${escapeHtml(key)}">${escapeHtml(key)}</option>`).join(''); $('categoryField').disabled = !category.length; state.field = numeric[0] || ''; }
  function quantile(sorted, probability) { if (!sorted.length) return null; const position = (sorted.length - 1) * probability; const base = Math.floor(position); const rest = position - base; return sorted[base + 1] === undefined ? sorted[base] : sorted[base] + rest * (sorted[base + 1] - sorted[base]); }
  function classThresholds(sorted, count) { return Array.from({ length: count - 1 }, (_, index) => quantile(sorted, (index + 1) / count)); }
  function classFor(value, thresholds) { let result = 1; thresholds.forEach((threshold) => { if (value > threshold) result += 1; }); return result; }
  function formatNumber(value) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: 3 }); }
  function formatRange(value) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: 2 }); }
  function clearMap() { if (state.layer) { state.layer.remove(); state.layer = null; } }
  function popup(feature, value, classId) { const properties = feature.properties || {}; const rows = Object.entries(properties).slice(0, 12).map(([key, item]) => `<div><span>${escapeHtml(key)}</span><b>${escapeHtml(item)}</b></div>`).join(''); return `<strong>${escapeHtml(state.field || 'Entidad')}</strong><div class="popup-class" style="border-color:${palette[(classId || 1) - 1] || '#8998a7'}">Clase ${classId || 'sin valor'} · ${value === null ? 'sin valor numérico' : escapeHtml(formatNumber(value))}</div><section class="popup-properties">${rows || '<em>Sin atributos</em>'}</section>`; }
  function renderMap() { clearMap(); if (!state.map || !state.stats) return; const valueByFeature = state.stats.values; state.layer = L.geoJSON(state.source, { style: (_feature) => ({ color: '#d7e7f7', weight: 1.5, fillColor: '#8998a7', fillOpacity: .25 }), pointToLayer: (feature, latlng) => { const index = state.features.indexOf(feature); const value = valueByFeature[index]; const classId = value === null ? 0 : state.stats.classes[index]; const color = classId ? palette[classId - 1] : '#8998a7'; return L.circleMarker(latlng, { radius: 8, color: '#fff', weight: 1, fillColor: color, fillOpacity: .9 }); }, onEachFeature: (feature, layer) => { const index = state.features.indexOf(feature); const value = valueByFeature[index]; const classId = value === null ? 0 : state.stats.classes[index]; layer.setStyle?.({ color: classId ? palette[classId - 1] : '#8998a7', fillColor: classId ? palette[classId - 1] : '#8998a7', fillOpacity: .58 }); layer.bindPopup(popup(feature, value, classId)); } }).addTo(state.map); const bounds = state.layer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function renderHistogram(values) { const min = Math.min(...values); const max = Math.max(...values); const bins = 8; const step = min === max ? 1 : (max - min) / bins; const counts = Array(bins).fill(0); values.forEach((value) => { const index = min === max ? 0 : Math.min(bins - 1, Math.floor((value - min) / step)); counts[index] += 1; }); const top = Math.max(...counts); $('histogram').innerHTML = counts.map((count, index) => { const from = min + index * step; const to = index === bins - 1 ? max : min + (index + 1) * step; return `<div class="bar" style="height:${Math.max(3, (count / top) * 100)}%" title="${escapeHtml(formatRange(from))}–${escapeHtml(formatRange(to))}: ${count}"><b>${count}</b><span>${escapeHtml(formatRange(from))}</span></div>`; }).join(''); $('histogram').setAttribute('aria-label', `Histograma de ${values.length} valores en ${bins} intervalos`); $('histogramHint').textContent = min === max ? `valor único ${formatRange(min)}` : `${bins} intervalos · ${formatRange(min)}–${formatRange(max)}`; }
  function renderCategories() { const field = $('categoryField').value; if (!field) { $('categoryBody').innerHTML = '<tr><td colspan="3" class="empty">Selecciona un campo categórico.</td></tr>'; return; } const counts = new Map(); state.features.forEach((feature) => { const value = feature.properties?.[field]; const label = value === null || value === undefined || value === '' ? '(sin valor)' : String(value); counts.set(label, (counts.get(label) || 0) + 1); }); const rows = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, 15); const total = state.features.length || 1; $('categoryBody').innerHTML = rows.map(([label, count]) => `<tr><td title="${escapeHtml(label)}">${escapeHtml(label)}</td><td>${count}</td><td>${formatNumber(count * 100 / total)}%</td></tr>`).join('') || '<tr><td colspan="3" class="empty">No hay categorías.</td></tr>'; }
  function renderStats() { const field = $('field').value; if (!field) throw new Error('La capa no contiene atributos numéricos analizables.'); state.field = field; const values = state.features.map((feature) => toNumber(feature.properties?.[field])); const valid = values.filter((value) => value !== null).sort((a, b) => a - b); if (!valid.length) throw new Error('El atributo elegido no tiene valores numéricos válidos.'); const sum = valid.reduce((total, value) => total + value, 0); const mean = sum / valid.length; const variance = valid.reduce((total, value) => total + (value - mean) ** 2, 0) / valid.length; const classCount = Number($('classCount').value); const thresholds = classThresholds(valid, classCount); const classes = values.map((value) => value === null ? 0 : classFor(value, thresholds)); state.stats = { field, values, classes, thresholds, count: state.features.length, valid: valid.length, missing: state.features.length - valid.length, sum, mean, median: quantile(valid, .5), q1: quantile(valid, .25), q3: quantile(valid, .75), stddev: Math.sqrt(variance), min: valid[0], max: valid[valid.length - 1] }; $('summary').hidden = false; $('fieldLabel').textContent = field; $('featureCount').textContent = state.stats.count.toLocaleString('es-ES'); $('validCount').textContent = state.stats.valid.toLocaleString('es-ES'); $('missingCount').textContent = state.stats.missing.toLocaleString('es-ES'); $('mean').textContent = formatNumber(mean); $('median').textContent = formatNumber(state.stats.median); $('stddev').textContent = formatNumber(state.stats.stddev); $('minimum').textContent = formatNumber(state.stats.min); $('maximum').textContent = formatNumber(state.stats.max); renderHistogram(valid); renderCategories(); renderMap(); $('geojsonBtn').disabled = $('csvBtn').disabled = $('jsonBtn').disabled = false; setStatus(`${state.stats.valid} valores válidos analizados en ${state.stats.count} entidades.`); }
  function prepare(input, filename = 'Ejemplo · 12 observaciones') { const normalized = normalize(input); if (!Array.isArray(normalized.features) || !normalized.features.length) throw new Error('La capa no contiene entidades.'); if (normalized.features.length > 50000) throw new Error('Para mantener el navegador ágil, carga como máximo 50.000 entidades.'); state.source = normalized; state.features = normalized.features.filter((feature) => feature && (feature.geometry || Object.keys(feature.properties || {}).length)); state.source.features = state.features; $('fileName').textContent = filename; fillFieldSelects(); if (!state.field) throw new Error('No se encontró ningún campo numérico.'); $('field').value = state.field; $('runBtn').disabled = false; renderStats(); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function enrichedGeoJSON() { const output = clone(state.source); output.features = output.features.map((feature, index) => ({ ...feature, properties: { ...(feature.properties || {}), stats_field: state.field, stats_value: state.stats.values[index], stats_class: state.stats.classes[index], stats_class_count: Number($('classCount').value) } })); return output; }
  function downloadCSV() { const rows = [['feature_index', 'field', 'value', 'stats_class', 'longitude', 'latitude']]; state.features.forEach((feature, index) => { const point = representative(feature.geometry); rows.push([index + 1, state.field, state.stats.values[index] ?? '', state.stats.classes[index] || '', point?.[0] ?? '', point?.[1] ?? '']); }); download('attribute-stats-results.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function reset() { state.source = null; state.features = []; state.stats = null; $('fileInput').value = ''; $('fileName').textContent = 'Ningún archivo seleccionado'; $('field').innerHTML = '<option>Primero carga una capa</option>'; $('field').disabled = true; $('categoryField').innerHTML = '<option>—</option>'; $('categoryField').disabled = true; $('runBtn').disabled = true; $('summary').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = $('jsonBtn').disabled = true; clearMap(); setStatus('Carga una capa o usa el ejemplo.'); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON.', true); } });
  $('field').addEventListener('change', () => { if (state.source) renderStats(); }); $('classCount').addEventListener('change', () => { if (state.source) renderStats(); }); $('categoryField').addEventListener('change', renderCategories); $('exampleBtn').addEventListener('click', () => { try { prepare(example); } catch (error) { setStatus(error.message, true); } }); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', () => { try { renderStats(); } catch (error) { setStatus(error.message, true); } }); $('geojsonBtn').addEventListener('click', () => { if (state.stats) download('attribute-stats-classified.geojson', JSON.stringify(enrichedGeoJSON(), null, 2), 'application/geo+json'); }); $('csvBtn').addEventListener('click', downloadCSV); $('jsonBtn').addEventListener('click', () => { if (state.stats) download('attribute-stats-summary.json', JSON.stringify({ ...state.stats, source_features: state.features.length }, null, 2), 'application/json'); });
  initMap();
})();
