(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { raster: null, polygons: [], result: null, map: null, layer: null, rasterOverlay: null };
  const examplePolygons = { type: 'FeatureCollection', features: [
    { type: 'Feature', properties: { name: 'Zona oeste' }, geometry: { type: 'Polygon', coordinates: [[[-3.765,40.45],[-3.69,40.45],[-3.69,40.395],[-3.765,40.395],[-3.765,40.45]]] } },
    { type: 'Feature', properties: { name: 'Zona este' }, geometry: { type: 'Polygon', coordinates: [[[-3.69,40.45],[-3.615,40.45],[-3.615,40.395],[-3.69,40.395],[-3.69,40.45]]] } }
  ] };
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function format(value, digits = 3) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function quantile(values, q) { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return null; const p = (sorted.length - 1) * q; const base = Math.floor(p); const rest = p - base; return sorted[base + 1] === undefined ? sorted[base] : sorted[base] + rest * (sorted[base + 1] - sorted[base]); }
  function stats(values, nodata) { const valid = Array.from(values).filter((value) => Number.isFinite(value) && (nodata === null || value !== nodata)); return valid.length ? { values: valid, count: valid.length, min: Math.min(...valid), max: Math.max(...valid), mean: valid.reduce((sum, value) => sum + value, 0) / valid.length } : { values: [], count: 0, min: null, max: null, mean: null }; }
  function pointInRing(point, ring) { let inside = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i, i += 1) { const xi = ring[i][0]; const yi = ring[i][1]; const xj = ring[j][0]; const yj = ring[j][1]; const crosses = ((yi > point[1]) !== (yj > point[1])) && point[0] < (xj - xi) * (point[1] - yi) / ((yj - yi) || Number.EPSILON) + xi; if (crosses) inside = !inside; } return inside; }
  function pointInGeometry(point, geometry) { if (geometry.type === 'Polygon') return pointInRing(point, geometry.coordinates[0]) && geometry.coordinates.slice(1).every((hole) => !pointInRing(point, hole)); if (geometry.type === 'MultiPolygon') return geometry.coordinates.some((polygon) => pointInRing(point, polygon[0]) && polygon.slice(1).every((hole) => !pointInRing(point, hole))); return false; }
  function bboxGeometry(geometry) { const coords = []; const collect = (value) => Array.isArray(value) && typeof value[0] === 'number' ? coords.push(value) : Array.isArray(value) ? value.forEach(collect) : null; collect(geometry.coordinates); const xs = coords.map((point) => point[0]); const ys = coords.map((point) => point[1]); return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)]; }
  function syntheticRaster() { const width = 180; const height = 120; const values = new Float32Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) values[y * width + x] = 120 + 30 * Math.sin(x / 18) + 24 * Math.cos(y / 14) + 80 * Math.exp(-((x - 92) ** 2 + (y - 62) ** 2) / 1700); return { width, height, values, origin: [-3.78, 40.48], resolution: [0.001, -0.001], nodata: null, source: 'Ejemplo sintético', samples: 1 }; }
  function geographic(raster) { if (!raster?.origin || !raster?.resolution) return false; const west = raster.origin[0]; const north = raster.origin[1]; const east = west + raster.width * raster.resolution[0]; const south = north + raster.height * raster.resolution[1]; return [west, east, south, north].every(Number.isFinite) && west >= -180 && east <= 180 && south >= -90 && north <= 90 && Math.abs(raster.resolution[0]) < 2 && Math.abs(raster.resolution[1]) < 2; }
  function parsePolygons(data) { const features = data?.type === 'FeatureCollection' ? data.features : data?.type === 'Feature' ? [data] : []; const polygons = features.filter((feature) => ['Polygon', 'MultiPolygon'].includes(feature?.geometry?.type)); if (!polygons.length) throw new Error('El GeoJSON debe contener al menos un Polygon o MultiPolygon.'); return polygons; }
  function fillIdFields() { const fields = [...new Set(state.polygons.flatMap((feature) => Object.keys(feature.properties || {})))]; $('idField').innerHTML = [`<option value="">Índice de entidad</option>`, ...fields.map((field) => `<option value="${escapeHtml(field)}">${escapeHtml(field)}</option>`)].join(''); const preferred = fields.find((field) => /(^id$|name|nombre|name|code|codigo)/i.test(field)); if (preferred) $('idField').value = preferred; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function loadPolygons(data) { state.polygons = parsePolygons(data); fillIdFields(); setStatus(`${state.polygons.length.toLocaleString('es-ES')} zonas poligonales detectadas.`); renderMap(); }
  async function readRaster(file) { if (!window.GeoTIFF) throw new Error('GeoTIFF.js no está disponible; revisa la conexión y vuelve a intentarlo.'); const tiff = await window.GeoTIFF.fromArrayBuffer(await file.arrayBuffer()); const image = await tiff.getImage(); const rasters = await image.readRasters({ interleave: false }); const rawNoData = image.getGDALNoData?.(); const nodata = rawNoData === null || rawNoData === undefined || rawNoData === '' ? null : Number(rawNoData); return { width: image.getWidth(), height: image.getHeight(), values: rasters[0], origin: image.getOrigin?.() || null, resolution: image.getResolution?.() || null, nodata: Number.isFinite(nodata) ? nodata : null, source: file.name, samples: image.getSamplesPerPixel() }; }
  function parseGeoJSON(text) { try { loadPolygons(JSON.parse(text)); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON poligonal.', true); } }
  function analyze() { if (!state.raster || !state.polygons.length) throw new Error('Carga un ráster y una capa poligonal antes de calcular.'); if (!geographic(state.raster)) throw new Error('El ráster no tiene una extensión lon/lat compatible con WGS84. Reprojéctalo antes de cruzarlo.'); const raster = state.raster; const cap = Math.max(1000, Number($('pixelCap').value) || 120000); const global = stats(raster.values, raster.nodata); const results = state.polygons.map((feature, featureIndex) => { const bbox = bboxGeometry(feature.geometry); let minColumn = Math.max(0, Math.floor((bbox[0] - raster.origin[0]) / raster.resolution[0])); let maxColumn = Math.min(raster.width - 1, Math.ceil((bbox[2] - raster.origin[0]) / raster.resolution[0])); if (minColumn > maxColumn) [minColumn, maxColumn] = [maxColumn, minColumn]; let rowA = (bbox[1] - raster.origin[1]) / raster.resolution[1]; let rowB = (bbox[3] - raster.origin[1]) / raster.resolution[1]; let minRow = Math.max(0, Math.floor(Math.min(rowA, rowB))); let maxRow = Math.min(raster.height - 1, Math.ceil(Math.max(rowA, rowB))); const candidates = Math.max(1, (maxColumn - minColumn + 1) * (maxRow - minRow + 1)); const stride = Math.max(1, Math.ceil(Math.sqrt(candidates / cap))); const values = []; for (let row = minRow; row <= maxRow; row += stride) for (let column = minColumn; column <= maxColumn; column += stride) { const x = raster.origin[0] + (column + .5) * raster.resolution[0]; const y = raster.origin[1] + (row + .5) * raster.resolution[1]; const value = raster.values[row * raster.width + column]; if (pointInGeometry([x, y], feature.geometry) && Number.isFinite(value) && (raster.nodata === null || value !== raster.nodata)) values.push(value); } const zonal = stats(values, null); return { feature, featureIndex, values, stride, ...zonal, p95: quantile(values, .95), id: $('idField').value ? feature.properties?.[$('idField').value] ?? `Zona ${featureIndex + 1}` : `Zona ${featureIndex + 1}` }; }); state.result = { results, global, sampled: results.reduce((sum, result) => sum + result.values.length, 0), source: raster.source, raster: { width: raster.width, height: raster.height, origin: raster.origin, resolution: raster.resolution, nodata: raster.nodata }, idField: $('idField').value, pixelCap: cap }; renderResult(); ['csvBtn', 'geoBtn', 'reportBtn'].forEach((id) => $(id).disabled = false); setStatus(`${results.length.toLocaleString('es-ES')} zonas calculadas; ${state.result.sampled.toLocaleString('es-ES')} píxeles válidos incluidos.`); }
  function renderResult() { const r = state.result; const valid = r.results.filter((result) => result.count); $('summary').hidden = $('detailPanel').hidden = false; $('zoneCount').textContent = r.results.length.toLocaleString('es-ES'); $('pixelCount').textContent = r.sampled.toLocaleString('es-ES'); $('globalMean').textContent = r.global.mean === null ? '—' : format(r.global.mean); $('minMean').textContent = valid.length ? format(Math.min(...valid.map((result) => result.mean))) : '—'; $('maxMean').textContent = valid.length ? format(Math.max(...valid.map((result) => result.mean))) : '—'; $('emptyZones').textContent = String(r.results.length - valid.length); $('summaryBadge').textContent = `${valid.length} con datos`; $('detailBadge').textContent = `${r.results.length} zonas`; $('interpretation').textContent = `La primera banda global tiene ${r.global.count.toLocaleString('es-ES')} píxeles válidos. Las zonas sin valores pueden estar fuera de la huella ráster, usar otra proyección o contener solo NoData.`; $('detailBody').innerHTML = r.results.map((result) => `<tr><th>${escapeHtml(result.id)}</th><td>${result.count.toLocaleString('es-ES')}</td><td class="${result.count ? '' : 'empty'}">${result.count ? format(result.mean) : 'Sin datos'}</td><td>${result.count ? format(result.min) : '—'}</td><td>${result.count ? format(result.max) : '—'}</td><td>${result.count ? format(result.p95) : '—'}</td><td>${escapeHtml(Object.entries(result.feature.properties || {}).map(([key, value]) => `${key}=${value}`).join(' · ') || '—')}</td></tr>`).join(''); $('mapBadge').textContent = `${r.results.length} zonas`; renderMap(); }
  function colorFor(value, min, max) { const t = max === min ? .5 : Math.max(0, Math.min(1, (value - min) / (max - min))); const hue = 155 - t * 130; return `hsl(${hue} 58% ${48 - t * 5}%)`; }
  function renderMap() { if (!state.map) return; state.layer?.remove(); state.rasterOverlay?.remove(); const layers = []; if (state.raster && geographic(state.raster) && state.raster.rendered) { const west = state.raster.origin[0]; const north = state.raster.origin[1]; const east = west + state.raster.width * state.raster.resolution[0]; const south = north + state.raster.height * state.raster.resolution[1]; state.rasterOverlay = L.imageOverlay(state.raster.rendered, [[Math.min(south, north), Math.min(west, east)], [Math.max(south, north), Math.max(west, east)]], { opacity: .35 }).addTo(state.map); } const valid = state.result?.results.filter((result) => result.count) || []; const min = valid.length ? Math.min(...valid.map((result) => result.mean)) : 0; const max = valid.length ? Math.max(...valid.map((result) => result.mean)) : 1; state.polygons.forEach((feature, index) => { const result = state.result?.results[index]; const color = result?.count ? colorFor(result.mean, min, max) : '#9aa9a2'; const layer = L.geoJSON(feature, { style: { color, weight: 2, fillColor: color, fillOpacity: result?.count ? .52 : .18 } }).bindPopup(`<strong>${escapeHtml(result?.id || `Zona ${index + 1}`)}</strong><div>${result?.count ? `Media: ${format(result.mean)}<br>Píxeles: ${result.count}<br>Rango: ${format(result.min)}–${format(result.max)}` : 'Sin valores válidos'}</div>`); layers.push(layer); }); state.layer = L.layerGroup(layers).addTo(state.map); const bounds = L.latLngBounds([]); state.polygons.forEach((feature) => { const bbox = bboxGeometry(feature.geometry); bounds.extend([[bbox[1], bbox[0]], [bbox[3], bbox[2]]]); }); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [35, 35], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function csv() { const r = state.result; if (!r) return; const rows = [['zone', 'pixel_count', 'mean', 'min', 'max', 'p95', ...new Set(state.polygons.flatMap((feature) => Object.keys(feature.properties || {})))]]; r.results.forEach((result) => rows.push([result.id, result.count, result.mean ?? '', result.min ?? '', result.max ?? '', result.p95 ?? '', ...rows[0].slice(6).map((key) => result.feature.properties?.[key] ?? '')])); download('raster-zonal-stats.csv', rows.map((row) => row.map((value) => /[",\n]/.test(String(value)) ? `"${String(value).replace(/"/g, '""')}"` : value).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function geojson() { const r = state.result; if (!r) return; const features = r.results.map((result) => ({ ...result.feature, properties: { ...result.feature.properties, raster_count: result.count, raster_mean: result.mean, raster_min: result.min, raster_max: result.max, raster_p95: result.p95, raster_sample_stride: result.stride } })); download('raster-zonal-enriched.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json'); }
  function report() { const r = state.result; if (!r) return; download('raster-zonal-report.json', JSON.stringify({ assumptions: { coordinate_system: 'WGS84 geographic lon/lat', pixel_statistic: 'pixel-center in polygon', no_data: r.raster.nodata, sampling_cap_per_zone: r.pixelCap }, fields: { zone_id: r.idField }, raster: r.raster, source: r.source, zones: r.results.map((result) => ({ id: result.id, count: result.count, mean: result.mean, min: result.min, max: result.max, p95: result.p95, stride: result.stride })) }, null, 2), 'application/json'); }
  function loadExample() { state.raster = syntheticRaster(); loadPolygons(examplePolygons); $('polygonSource').value = JSON.stringify(examplePolygons, null, 2); setStatus('Ejemplo sintético cargado. Pulsa «Calcular estadísticas».'); renderMap(); }
  function clearAll() { state.raster = null; state.polygons = []; state.result = null; state.layer?.remove(); state.rasterOverlay?.remove(); state.layer = state.rasterOverlay = null; $('rasterFile').value = ''; $('polygonFile').value = ''; $('polygonSource').value = ''; $('idField').innerHTML = '<option value="">Índice de entidad</option>'; $('summary').hidden = $('detailPanel').hidden = true; ['csvBtn', 'geoBtn', 'reportBtn'].forEach((id) => $(id).disabled = true); $('mapBadge').textContent = '—'; setStatus('Carga un GeoTIFF y una capa poligonal para empezar.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', loadExample); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { analyze(); } catch (error) { setStatus(error.message || 'No se pudieron calcular las zonas.', true); } }); $('polygonSource').addEventListener('change', () => parseGeoJSON($('polygonSource').value)); $('rasterFile').addEventListener('change', async () => { const file = $('rasterFile').files?.[0]; if (!file) return; setStatus('Leyendo GeoTIFF…'); try { state.raster = await readRaster(file); setStatus(`${state.raster.width} × ${state.raster.height} píxeles leídos. Carga o pega los polígonos y calcula.`); renderMap(); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoTIFF.', true); } }); $('polygonFile').addEventListener('change', async () => { const file = $('polygonFile').files?.[0]; if (!file) return; try { const text = await file.text(); $('polygonSource').value = text; parseGeoJSON(text); } catch (error) { setStatus(error.message || 'No se pudo leer la capa poligonal.', true); } }); ['csvBtn', 'geoBtn', 'reportBtn'].forEach((id, index) => $(id).addEventListener('click', [csv, geojson, report][index])); initMap();
})();
