(() => {
  'use strict';

  const state = { features: [], buffers: [], map: null, sourceLayer: null, bufferLayer: null, output: null };
  const $ = (id) => document.getElementById(id);
  const els = { fileInput: $('fileInput'), fileName: $('fileName'), radius: $('radius'), radiusKey: $('radiusKey'), segments: $('segments'), segmentsOutput: $('segmentsOutput'), exampleBtn: $('exampleBtn'), clearBtn: $('clearBtn'), runBtn: $('runBtn'), status: $('status'), validCount: $('validCount'), bufferCount: $('bufferCount'), minRadius: $('minRadius'), maxRadius: $('maxRadius'), geojsonBtn: $('geojsonBtn'), csvBtn: $('csvBtn'), map: $('map'), mapFallback: $('mapFallback'), resultBody: $('resultBody'), tableHint: $('tableHint') };

  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function round(value, digits = 2) { const factor = 10 ** digits; return Math.round(value * factor) / factor; }
  function setStatus(message, error = false) { els.status.textContent = message; els.status.classList.toggle('error', error); }
  function featureCollection(input) {
    if (!input || typeof input !== 'object') throw new Error('El contenido no es JSON válido.');
    if (input.type === 'FeatureCollection') return input.features.filter((feature) => feature && feature.type === 'Feature');
    if (input.type === 'Feature') return [input];
    if (input.type && input.coordinates) return [{ type: 'Feature', properties: {}, geometry: input }];
    throw new Error('Se esperaba una FeatureCollection, Feature o geometría GeoJSON.');
  }
  function positionsOf(value, output = []) { if (!Array.isArray(value)) return output; if (value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) { output.push([Number(value[0]), Number(value[1])]); return output; } value.forEach((child) => positionsOf(child, output)); return output; }
  function representative(feature) { if (!feature || !feature.geometry) return null; const positions = positionsOf(feature.geometry.coordinates).filter(([lon, lat]) => lon >= -180 && lon <= 180 && lat >= -90 && lat <= 90); if (!positions.length) return null; if (feature.geometry.type === 'Point') return positions[0]; return [positions.reduce((sum, point) => sum + point[0], 0) / positions.length, positions.reduce((sum, point) => sum + point[1], 0) / positions.length]; }
  function readFile(file) { const reader = new FileReader(); reader.onload = () => { try { state.features = featureCollection(JSON.parse(reader.result)); els.fileName.textContent = `${file.name} · ${state.features.length} entidades`; els.runBtn.disabled = false; setStatus(`${state.features.length} entidades cargadas. Pulsa generar para crear los buffers.`); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus(`No se pudo leer ${file.name}.`, true); reader.readAsText(file); }
  function radiusFor(feature) { const key = els.radiusKey.value.trim(); const fromField = key && feature.properties ? Number(feature.properties[key]) : NaN; if (Number.isFinite(fromField) && fromField > 0) return { value: Math.min(fromField, 1000000), source: key }; const global = Number(els.radius.value); if (!Number.isFinite(global) || global <= 0) throw new Error('Introduce un radio global mayor que cero.'); return { value: Math.min(global, 1000000), source: 'global' }; }
  function destinationPoint(center, distance, bearingDegrees) { const radiusEarth = 6371008.8; const angular = distance / radiusEarth; const bearing = bearingDegrees * Math.PI / 180; const lat1 = center[1] * Math.PI / 180; const lon1 = center[0] * Math.PI / 180; const lat2 = Math.asin(Math.sin(lat1) * Math.cos(angular) + Math.cos(lat1) * Math.sin(angular) * Math.cos(bearing)); const lon2 = lon1 + Math.atan2(Math.sin(bearing) * Math.sin(angular) * Math.cos(lat1), Math.cos(angular) - Math.sin(lat1) * Math.sin(lat2)); let lon = lon2 * 180 / Math.PI; lon = ((lon + 540) % 360) - 180; return [lon, lat2 * 180 / Math.PI]; }
  function makeBuffer(center, distance, segments) { const coordinates = []; for (let index = 0; index <= segments; index += 1) coordinates.push(destinationPoint(center, distance, index * 360 / segments)); return coordinates; }
  function initMap() { if (!window.L) { els.map.hidden = true; els.mapFallback.hidden = false; return; } try { state.map = L.map(els.map, { zoomControl: true }).setView([40.4168, -3.7038], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' }).addTo(state.map); } catch (error) { els.map.hidden = true; els.mapFallback.hidden = false; setStatus('El análisis funciona, pero el mapa no pudo inicializarse.', true); } }
  function popup(title, properties) { return `<div class="popup-title">${escapeHtml(title)}</div><div class="popup-data">${escapeHtml(JSON.stringify(properties || {}, null, 2))}</div>`; }
  function clearLayers() { [state.sourceLayer, state.bufferLayer].forEach((layer) => { if (layer && state.map) state.map.removeLayer(layer); }); state.sourceLayer = state.bufferLayer = null; }
  function renderMap() { if (!state.map || !state.output) return; clearLayers(); state.bufferLayer = L.geoJSON({ type: 'FeatureCollection', features: state.buffers.map((item) => item.bufferFeature) }, { style: { color: '#ffd071', weight: 2, fillColor: '#ffd071', fillOpacity: .18 }, onEachFeature: (feature, layer) => layer.bindPopup(popup(`Buffer ${feature.properties.buffer_source_index}`, feature.properties)) }).addTo(state.map); state.sourceLayer = L.layerGroup(); const bounds = []; state.buffers.forEach((item) => { const marker = L.circleMarker([item.center[1], item.center[0]], { radius: 6, color: '#fff', weight: 1, fillColor: '#76b5ff', fillOpacity: .95 }); marker.bindPopup(popup(`Entidad ${item.index + 1}`, item.source.properties)); marker.addTo(state.sourceLayer); bounds.push([item.center[1], item.center[0]]); }); state.sourceLayer.addTo(state.map); const bufferBounds = state.bufferLayer.getBounds(); if (bufferBounds.isValid()) state.map.fitBounds(bufferBounds, { padding: [20, 20], maxZoom: 15 }); else if (bounds.length) state.map.fitBounds(bounds, { padding: [20, 20], maxZoom: 15 }); }
  function formatDistance(meters) { if (meters >= 1000) return `${round(meters / 1000, 2)} km`; return `${Math.round(meters)} m`; }
  function generate() { const segments = Number(els.segments.value); const candidates = state.features.map((source, index) => ({ source, index, center: representative(source) })).filter((item) => item.center); if (!candidates.length) { setStatus('No hay entidades con coordenadas válidas.', true); return; } try { state.buffers = candidates.map((item) => { const radius = radiusFor(item.source); const bufferFeature = { type: 'Feature', properties: { ...(item.source.properties || {}), buffer_source_index: item.index + 1, buffer_radius_m: round(radius.value, 2), buffer_radius_source: radius.source, buffer_representation: item.source.geometry.type === 'Point' ? 'point' : 'average_vertices' }, geometry: { type: 'Polygon', coordinates: [makeBuffer(item.center, radius.value, segments)] } }; return { ...item, radius: radius.value, radiusSource: radius.source, bufferFeature }; }); state.output = { type: 'FeatureCollection', features: state.buffers.map((item) => item.bufferFeature) }; const values = state.buffers.map((item) => item.radius); els.validCount.textContent = candidates.length; els.bufferCount.textContent = state.buffers.length; els.minRadius.textContent = formatDistance(Math.min(...values)); els.maxRadius.textContent = formatDistance(Math.max(...values)); els.geojsonBtn.disabled = els.csvBtn.disabled = false; els.tableHint.textContent = `${state.buffers.length} buffers · ${segments} segmentos por círculo`; els.resultBody.innerHTML = state.buffers.map((item) => `<tr><td>${item.index + 1}</td><td>${item.center[0].toFixed(6)}</td><td>${item.center[1].toFixed(6)}</td><td>${formatDistance(item.radius)}</td><td>${escapeHtml(item.radiusSource === 'global' ? 'global' : `propiedad «${item.radiusSource}»`)}</td></tr>`).join(''); renderMap(); setStatus(`Generación completada: ${state.buffers.length} áreas de influencia.`); } catch (error) { setStatus(error.message, true); } }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  function csvValue(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function downloadCsv() { const rows = [['source_index', 'longitude', 'latitude', 'radius_m', 'radius_source']]; state.buffers.forEach((item) => rows.push([item.index + 1, item.center[0], item.center[1], item.radius, item.radiusSource])); download('buffer-summary.csv', rows.map((row) => row.map(csvValue).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function loadExample() { state.features = [{ type: 'Feature', properties: { name: 'Yacimiento A', buffer_m: 350 }, geometry: { type: 'Point', coordinates: [-3.706, 40.418] } }, { type: 'Feature', properties: { name: 'Yacimiento B', buffer_m: 180 }, geometry: { type: 'Point', coordinates: [-3.693, 40.409] } }, { type: 'Feature', properties: { name: 'Muestra C', buffer_m: 500 }, geometry: { type: 'Point', coordinates: [-3.675, 40.43] } }, { type: 'Feature', properties: { name: 'Control D' }, geometry: { type: 'Point', coordinates: [-3.75, 40.4] } }]; els.fileName.textContent = 'Ejemplo · 4 entidades'; els.radius.value = '250'; els.radiusKey.value = 'buffer_m'; els.segments.value = '48'; els.segmentsOutput.textContent = '48'; els.runBtn.disabled = false; generate(); }
  function clearAll() { state.features = []; state.buffers = []; state.output = null; els.fileInput.value = ''; els.fileName.textContent = 'Ningún archivo seleccionado'; els.runBtn.disabled = true; els.geojsonBtn.disabled = els.csvBtn.disabled = true; ['validCount', 'bufferCount', 'minRadius', 'maxRadius'].forEach((id) => $(id).textContent = '—'); els.resultBody.innerHTML = '<tr><td colspan="5" class="empty">Todavía no hay resultados.</td></tr>'; els.tableHint.textContent = 'Ejecuta el proceso para ver el detalle.'; clearLayers(); setStatus('Carga una capa o usa el ejemplo.'); }
  els.fileInput.addEventListener('change', (event) => { const file = event.target.files[0]; if (file) readFile(file); }); els.exampleBtn.addEventListener('click', loadExample); els.clearBtn.addEventListener('click', clearAll); els.runBtn.addEventListener('click', generate); els.segments.addEventListener('input', () => { els.segmentsOutput.textContent = els.segments.value; }); els.geojsonBtn.addEventListener('click', () => download('buffers.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8')); els.csvBtn.addEventListener('click', downloadCsv); initMap();
})();
