(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { rows: [], sourceType: 'table', result: null, map: null, layer: null };
  const example = `id,name,lon,lat\n1,Puerta del Sol,-3.7038,40.4168\n2,Retiro,-3.6844,40.4153\n3,Alcalá,-3.6883,40.4194\n4,Registro sin latitud,-3.70,\n5,Fuera de rango,181.20,40.40\n6,Posible eje invertido,40.42,-3.70\n7,Duplicado,-3.7038,40.4168`;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseLine(line) { const out = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"' && line[i + 1] === '"' && quoted) { value += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ',' || char === '\t' || char === ';')) { out.push(value.trim()); value = ''; } else value += char; } out.push(value.trim()); return out; }
  function parseDelimited(text) { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error('La tabla necesita una cabecera y al menos una fila.'); const headers = parseLine(lines[0]).map((header, index) => header || `campo_${index + 1}`); return lines.slice(1).map((line) => { const values = parseLine(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])); }); }
  function representativePoint(geometry) { if (!geometry?.coordinates) return null; const points = []; const flatten = (value) => { if (Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) points.push([Number(value[0]), Number(value[1])]); else if (Array.isArray(value)) value.forEach(flatten); }; flatten(geometry.coordinates); if (!points.length) return null; return [points.reduce((sum, point) => sum + point[0], 0) / points.length, points.reduce((sum, point) => sum + point[1], 0) / points.length]; }
  function parseInput(text) { const clean = text.trim(); if (!clean) throw new Error('Introduce una tabla o un GeoJSON.'); if (clean.startsWith('{') || clean.startsWith('[')) { const parsed = JSON.parse(clean); const features = parsed.type === 'FeatureCollection' ? parsed.features : parsed.type === 'Feature' ? [parsed] : null; if (!features) throw new Error('El JSON debe ser una FeatureCollection o Feature GeoJSON.'); state.sourceType = 'geojson'; return features.map((feature) => { const point = representativePoint(feature.geometry); return { ...(feature.properties || {}), __lon: point?.[0] ?? '', __lat: point?.[1] ?? '' }; }); } state.sourceType = 'table'; return parseDelimited(clean); }
  function fieldScore(field, candidates) { const value = field.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); return candidates.reduce((best, candidate, index) => Math.max(best, value === candidate ? 100 - index : value.includes(candidate) ? 40 - index : 0), 0); }
  function chooseFields(rows) { if (!rows.length) throw new Error('No se encontraron filas.'); state.rows = rows; const fields = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const best = (candidates) => fields.map((field) => ({ field, score: fieldScore(field, candidates) })).sort((a, b) => b.score - a.score)[0]?.score > 0 ? fields.map((field) => ({ field, score: fieldScore(field, candidates) })).sort((a, b) => b.score - a.score)[0].field : ''; const lon = best(['__lon', 'longitude', 'longitud', 'lon', 'lng', 'este', 'easting', 'x']); const lat = best(['__lat', 'latitude', 'latitud', 'lat', 'norte', 'northing', 'y']); const optionList = (empty, selected) => [empty, ...fields.map((field) => `<option value="${escapeHtml(field)}"${field === selected ? ' selected' : ''}>${escapeHtml(field)}</option>`)].join(''); $('lonField').innerHTML = optionList('Selecciona longitud / X', lon); $('latField').innerHTML = optionList('Selecciona latitud / Y', lat); setStatus(`${rows.length.toLocaleString('es-ES')} registros detectados. Revisa los campos y audita las coordenadas.`); }
  function number(value) { const raw = String(value ?? '').trim().replace(',', '.'); if (!raw) return null; const parsed = Number(raw); return Number.isFinite(parsed) ? parsed : null; }
  function audit() { const lonField = $('lonField').value; const latField = $('latField').value; if (!lonField || !latField) throw new Error('Selecciona los campos de longitud y latitud.'); const precision = Number($('precision').value); const swapped = $('axisMode').value === 'swapped'; const items = state.rows.map((row, index) => { const first = number(row[lonField]); const second = number(row[latField]); const lon = swapped ? second : first; const lat = swapped ? first : second; const hasFirst = first !== null; const hasSecond = second !== null; let status = 'ok'; let reason = 'Coordenada válida'; if (!hasFirst || !hasSecond) { status = 'missing'; reason = !hasFirst && !hasSecond ? 'Faltan ambas coordenadas' : !hasFirst ? 'Falta longitud/X' : 'Falta latitud/Y'; } else if (Math.abs(lon) > 180 || Math.abs(lat) > 90) { status = 'invalid'; reason = 'Fuera de rango WGS84'; } else if (!swapped && ((Math.abs(first) <= 90 && Math.abs(second) > 90 && Math.abs(second) <= 180) || (Math.abs(first) <= 90 && Math.abs(second) <= 90 && Math.abs(first) > Math.abs(second) && first * second < 0))) { status = 'warn'; reason = 'Posibles ejes invertidos'; } return { row, index, first, second, lon, lat, status, reason, key: status === 'ok' || status === 'warn' ? `${lon.toFixed(precision)}|${lat.toFixed(precision)}` : '' }; }); const keyCounts = {}; items.forEach((item) => { if (item.key) keyCounts[item.key] = (keyCounts[item.key] || 0) + 1; }); items.forEach((item) => { item.duplicate = Boolean(item.key && keyCounts[item.key] > 1); }); const counts = { ok: items.filter((item) => item.status === 'ok').length, missing: items.filter((item) => item.status === 'missing').length, invalid: items.filter((item) => item.status === 'invalid').length, warn: items.filter((item) => item.status === 'warn').length }; const valid = items.filter((item) => (item.status === 'ok' || item.status === 'warn') && Math.abs(item.lon) <= 180 && Math.abs(item.lat) <= 90); const lons = valid.map((item) => item.lon); const lats = valid.map((item) => item.lat); const extent = lons.length ? { minLon: Math.min(...lons), minLat: Math.min(...lats), maxLon: Math.max(...lons), maxLat: Math.max(...lats), centroidLon: lons.reduce((sum, value) => sum + value, 0) / lons.length, centroidLat: lats.reduce((sum, value) => sum + value, 0) / lats.length } : null; const duplicateRows = items.filter((item) => item.duplicate).length; state.result = { items, counts, valid, extent, duplicateRows, precision, lonField, latField, sourceType: state.sourceType, total: items.length }; renderSummary(); renderIssues(); renderMap(); $('reportBtn').disabled = $('cleanBtn').disabled = $('geojsonBtn').disabled = false; const problemCount = counts.missing + counts.invalid + counts.warn + duplicateRows; setStatus(`${items.length.toLocaleString('es-ES')} registros auditados: ${problemCount.toLocaleString('es-ES')} requieren revisión.`); }
  function renderSummary() { const { counts, total, duplicateRows, extent } = state.result; const problems = counts.missing + counts.invalid + counts.warn + duplicateRows; $('summary').hidden = false; $('rowCount').textContent = total.toLocaleString('es-ES'); $('validCount').textContent = (counts.ok + counts.warn).toLocaleString('es-ES'); $('missingCount').textContent = counts.missing.toLocaleString('es-ES'); $('invalidCount').textContent = counts.invalid.toLocaleString('es-ES'); $('duplicateCount').textContent = duplicateRows.toLocaleString('es-ES'); $('swappedCount').textContent = counts.warn.toLocaleString('es-ES'); $('qualityBadge').textContent = problems ? `${problems.toLocaleString('es-ES')} revisar` : 'sin incidencias'; $('qualityBadge').style.background = problems ? '#fff2d9' : ''; $('qualityBadge').style.color = problems ? 'var(--warning)' : ''; $('interpretation').textContent = problems ? `Se han encontrado ${problems.toLocaleString('es-ES')} registros o incidencias que conviene revisar antes de exportar. Los posibles ejes invertidos se marcan como advertencia, no como error automático.` : 'Todas las filas tienen coordenadas dentro de los rangos WGS84 y no se han detectado duplicados con la precisión elegida.'; $('extent').textContent = extent ? `Extensión: lon ${extent.minLon.toFixed(6)}…${extent.maxLon.toFixed(6)} · lat ${extent.minLat.toFixed(6)}…${extent.maxLat.toFixed(6)} · centro ${extent.centroidLon.toFixed(6)}, ${extent.centroidLat.toFixed(6)}` : 'Sin coordenadas válidas para calcular extensión.'; }
  function renderIssues() { const issues = state.result.items.filter((item) => item.status !== 'ok' || item.duplicate); $('issuesPanel').hidden = !issues.length; $('issueBadge').textContent = `${issues.length.toLocaleString('es-ES')} filas`; $('issuesBody').innerHTML = issues.map((item) => `<tr><th>${item.index + 2}</th><td class="status-cell ${item.status === 'missing' || item.status === 'invalid' ? 'bad' : 'warn'}">${item.status === 'missing' ? 'Falta' : item.status === 'invalid' ? 'Fuera de rango' : 'Revisar'}</td><td>${escapeHtml(item.first ?? '—')}</td><td>${escapeHtml(item.second ?? '—')}</td><td>${escapeHtml(item.reason)}${item.duplicate ? ' · coordenada duplicada' : ''}</td></tr>`).join(''); }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); const points = state.result.items.filter((item) => (item.status === 'ok' || item.status === 'warn') && Math.abs(item.lon) <= 180 && Math.abs(item.lat) <= 90).map((item) => L.circleMarker([item.lat, item.lon], { radius: 7, color: item.status === 'warn' ? '#84540c' : '#0d7350', weight: 1, fillColor: item.status === 'warn' ? '#e5a93b' : '#35b77a', fillOpacity: .88 }).bindPopup(`<strong>Fila ${item.index + 2}</strong><div>lon: ${item.lon}<br>lat: ${item.lat}<br>${escapeHtml(item.reason)}${item.duplicate ? '<br>coordenada duplicada' : ''}</div>`)); state.layer = L.layerGroup(points).addTo(state.map); $('mapBadge').textContent = `${points.length.toLocaleString('es-ES')} representables`; if (points.length) state.map.fitBounds(L.featureGroup(points).getBounds(), { padding: [32, 32], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function report() { if (!state.result) return; const { items, ...summary } = state.result; download('coordinate-qa-report.json', JSON.stringify({ ...summary, issues: items.filter((item) => item.status !== 'ok' || item.duplicate).map((item) => ({ row: item.index + 2, status: item.status, reason: item.reason, duplicate: item.duplicate })) }, null, 2), 'application/json'); }
  function cleanCsv() { if (!state.result) return; const rows = state.result.items.map((item) => ({ ...item.row, qa_status: item.status, qa_reason: item.reason, qa_lon: item.lon ?? '', qa_lat: item.lat ?? '', qa_duplicate: item.duplicate ? 'true' : 'false' })); const headers = [...new Set(rows.flatMap((row) => Object.keys(row)))]; download('coordinate-qa-audited.csv', [headers, ...rows.map((row) => headers.map((header) => row[header] ?? ''))].map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function geojson() { if (!state.result) return; const features = state.result.valid.map((item) => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [item.lon, item.lat] }, properties: { ...item.row, qa_status: item.status, qa_reason: item.reason, qa_duplicate: item.duplicate } })); download('coordinate-qa-points.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json'); }
  function loadText(text) { $('source').value = text; try { chooseFields(parseInput(text)); } catch (error) { setStatus(error.message || 'No se pudieron detectar los datos.', true); } }
  function clearAll() { state.rows = []; state.result = null; $('source').value = ''; $('fileInput').value = ''; ['lonField', 'latField'].forEach((id) => { $(id).innerHTML = '<option value="">Carga datos para detectar campos</option>'; }); $('summary').hidden = $('issuesPanel').hidden = true; $('reportBtn').disabled = $('cleanBtn').disabled = $('geojsonBtn').disabled = true; state.layer?.remove(); state.layer = null; $('mapBadge').textContent = '—'; setStatus('Carga una tabla o un GeoJSON para detectar los campos.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', () => loadText(example)); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { chooseFields(parseInput($('source').value)); audit(); } catch (error) { setStatus(error.message || 'No se pudo auditar la fuente.', true); } }); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { loadText(await file.text()); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }); $('reportBtn').addEventListener('click', report); $('cleanBtn').addEventListener('click', cleanCsv); $('geojsonBtn').addEventListener('click', geojson); $('source').value = example; initMap();
})();
