(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { rows: [], result: null, map: null, layer: null };
  const example = `id,lon,lat,u,v,grupo\nP-01,-3.7038,40.4168,3.2,1.4,Estación A\nP-02,-3.6980,40.4182,2.6,2.1,Estación A\nP-03,-3.7120,40.4145,1.1,-2.4,Estación A\nP-04,-3.6901,40.4200,-1.8,1.3,Estación B\nP-05,-3.7210,40.4114,-2.4,-1.2,Estación B\nP-06,-3.6824,40.4230,0.4,3.8,Estación B\nP-07,-3.6750,40.4190,4.0,-0.4,Estación C\nP-08,-3.7300,40.4080,-1.0,-3.1,Estación C\nP-09,-3.7140,40.4260,2.2,2.8,Estación C\nP-10,-3.6860,40.4070,-3.0,0.6,Estación A`;
  const EARTH = 6371008.8;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseLine(line) { const out = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"' && line[i + 1] === '"' && quoted) { value += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ',' || char === '\t' || char === ';')) { out.push(value.trim()); value = ''; } else value += char; } out.push(value.trim()); return out; }
  function parseDelimited(text) { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error('La tabla necesita una cabecera y al menos una fila.'); const headers = parseLine(lines[0]).map((header, index) => header || `campo_${index + 1}`); return lines.slice(1).map((line) => { const values = parseLine(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])); }); }
  function norm(value) { return String(value ?? '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, ''); }
  function score(field, candidates) { const value = norm(field); return candidates.reduce((best, candidate, index) => Math.max(best, value === norm(candidate) ? 100 - index : value.includes(norm(candidate)) ? 45 - index : 0), 0); }
  function best(fields, candidates, excluded = []) { const candidatesFields = fields.filter((field) => !excluded.includes(field)).map((field) => ({ field, score: score(field, candidates) })).sort((a, b) => b.score - a.score); return candidatesFields[0]?.score > 0 ? candidatesFields[0].field : ''; }
  function optionList(empty, fields, selected) { return [`<option value="">${escapeHtml(empty)}</option>`, ...fields.map((field) => `<option value="${escapeHtml(field)}"${field === selected ? ' selected' : ''}>${escapeHtml(field)}</option>`)].join(''); }
  function chooseFields(rows) { state.rows = rows; const fields = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const lon = best(fields, ['longitude', 'longitud', 'lon', 'lng', 'x']); const lat = best(fields, ['latitude', 'latitud', 'lat', 'y']); const u = best(fields, ['u', 'east', 'eastward', 'este', 'dx', 'vx', 'wind_u']); const v = best(fields, ['v', 'north', 'northward', 'norte', 'dy', 'vy', 'wind_v']); const speed = best(fields, ['speed', 'velocity', 'velocidad', 'magnitude', 'modulo', 'modulus']); const direction = best(fields, ['direction', 'direccion', 'bearing', 'azimuth', 'rumbo', 'heading']); const used = [lon, lat, u, v].filter(Boolean); $('idField').innerHTML = optionList('Índice de fila', fields, best(fields, ['id', 'identifier', 'identificador', 'name', 'nombre'])); $('lonField').innerHTML = optionList('Selecciona longitud', fields, lon); $('latField').innerHTML = optionList('Selecciona latitud', fields, lat); $('uField').innerHTML = optionList('Sin seleccionar', fields, u); $('vField').innerHTML = optionList('Sin seleccionar', fields, v); $('speedField').innerHTML = optionList('Sin seleccionar', fields, speed); $('directionField').innerHTML = optionList('Sin seleccionar', fields, direction); $('groupField').innerHTML = optionList('Sin grupo', fields.filter((field) => !used.includes(field)), best(fields, ['group', 'grupo', 'source', 'fuente', 'station', 'estacion'], used)); setStatus(`${rows.length.toLocaleString('es-ES')} observaciones detectadas. Usa u/v o velocidad/dirección y analiza el campo.`); }
  function number(value) { const raw = String(value ?? '').trim().replace(',', '.'); if (!raw) return null; const n = Number(raw); return Number.isFinite(n) ? n : null; }
  function valid(lon, lat) { return Number.isFinite(lon) && Number.isFinite(lat) && Math.abs(lon) <= 180 && Math.abs(lat) <= 90; }
  function toVector(row, uField, vField, speedField, directionField) { let u = uField ? number(row[uField]) : null; let v = vField ? number(row[vField]) : null; if ((!Number.isFinite(u) || !Number.isFinite(v)) && speedField && directionField) { const speed = number(row[speedField]); const direction = number(row[directionField]); if (Number.isFinite(speed) && Number.isFinite(direction)) { const radians = (direction % 360) * Math.PI / 180; u = speed * Math.sin(radians); v = speed * Math.cos(radians); } } return Number.isFinite(u) && Number.isFinite(v) ? { u, v, speed: Math.hypot(u, v), direction: (Math.atan2(u, v) * 180 / Math.PI + 360) % 360 } : null; }
  function analyze() { const lonField = $('lonField').value; const latField = $('latField').value; if (!lonField || !latField) throw new Error('Selecciona longitud y latitud.'); const uField = $('uField').value; const vField = $('vField').value; const speedField = $('speedField').value; const directionField = $('directionField').value; if ((!uField || !vField) && (!speedField || !directionField)) throw new Error('Selecciona u/v o velocidad y dirección.'); const idField = $('idField').value; const groupField = $('groupField').value; const records = state.rows.map((row, index) => { const lon = number(row[lonField]); const lat = number(row[latField]); const vector = toVector(row, uField, vField, speedField, directionField); if (!valid(lon, lat) || !vector) return null; return { row, index, id: idField ? String(row[idField] ?? '').trim() || `Fila ${index + 1}` : `Fila ${index + 1}`, group: groupField ? String(row[groupField] ?? '').trim() || 'Sin grupo' : 'Sin grupo', lon, lat, ...vector }; }).filter(Boolean); if (!records.length) throw new Error('No hay observaciones con coordenadas y vector válidos.'); const speeds = records.map((record) => record.speed); state.result = { records, fields: { idField, groupField, lonField, latField, uField, vField, speedField, directionField }, count: records.length, meanSpeed: speeds.reduce((sum, value) => sum + value, 0) / speeds.length, maxSpeed: Math.max(...speeds), p95Speed: quantile(speeds, .95), meanU: records.reduce((sum, record) => sum + record.u, 0) / records.length, meanV: records.reduce((sum, record) => sum + record.v, 0) / records.length }; render(); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = false); setStatus(`${records.length.toLocaleString('es-ES')} observaciones válidas. Se han descartado ${state.rows.length - records.length} fila(s).`); }
  function quantile(values, q) { const sorted = [...values].sort((a, b) => a - b); const position = (sorted.length - 1) * q; const base = Math.floor(position); const rest = position - base; return sorted[base + 1] === undefined ? sorted[base] : sorted[base] + rest * (sorted[base + 1] - sorted[base]); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function render() { const r = state.result; $('summary').hidden = $('detailPanel').hidden = false; $('count').textContent = r.count.toLocaleString('es-ES'); $('meanSpeed').textContent = format(r.meanSpeed); $('maxSpeed').textContent = format(r.maxSpeed); $('p95Speed').textContent = format(r.p95Speed); $('meanU').textContent = format(r.meanU); $('meanV').textContent = format(r.meanV); $('summaryBadge').textContent = `${r.count.toLocaleString('es-ES')} vectores`; $('detailBadge').textContent = `${new Set(r.records.map((record) => record.group)).size} grupos`; const meanDirection = (Math.atan2(r.meanU, r.meanV) * 180 / Math.PI + 360) % 360; $('interpretation').textContent = `El vector medio apunta a ${format(meanDirection, 1)}° y tiene módulo ${format(Math.hypot(r.meanU, r.meanV))}. Las unidades de los componentes se conservan tal como aparecen en la fuente.`; $('detailBody').innerHTML = r.records.slice().sort((a, b) => b.speed - a.speed).map((record) => `<tr><th>${escapeHtml(record.id)}</th><td>${escapeHtml(record.group)}</td><td>${format(record.u)}</td><td>${format(record.v)}</td><td>${format(record.speed)}</td><td>${format(record.direction, 1)}°</td><td>${format(record.lon, 6)}, ${format(record.lat, 6)}</td></tr>`).join(''); $('mapBadge').textContent = `${r.count.toLocaleString('es-ES')} flechas`; $('roseBadge').textContent = `${r.count.toLocaleString('es-ES')} direcciones`; renderMap(); renderRose(); }
  function colorFor(value, max) { const ratio = Math.max(0, Math.min(1, value / Math.max(max, 1e-12))); const hue = 205 - ratio * 175; return `hsl(${hue} 62% ${48 - ratio * 5}%)`; }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); const max = state.result.maxSpeed; const scale = .012 / Math.max(max, 1e-12); const layers = []; state.result.records.forEach((record) => { const dLat = record.v * scale; const dLon = record.u * scale / Math.max(.2, Math.cos(record.lat * Math.PI / 180)); const end = [record.lat + dLat, record.lon + dLon]; const color = colorFor(record.speed, max); const line = L.polyline([[record.lat, record.lon], end], { color, weight: 3, opacity: .9 }).bindPopup(`<strong>${escapeHtml(record.id)}</strong><div>${escapeHtml(record.group)}<br>Módulo: ${format(record.speed)}<br>Dirección hacia: ${format(record.direction, 1)}°<br>Este/norte: ${format(record.u)} / ${format(record.v)}</div>`); const head = L.circleMarker(end, { radius: 4, color, fillColor: color, fillOpacity: 1, weight: 1 }); const point = L.circleMarker([record.lat, record.lon], { radius: 4, color: '#173d2e', fillColor: '#fff', fillOpacity: .95, weight: 1 }).bindTooltip(`${escapeHtml(record.id)} · ${format(record.speed)}`); layers.push(line, head, point); }); state.layer = L.layerGroup(layers).addTo(state.map); const bounds = L.latLngBounds(state.result.records.flatMap((record) => { const scale = .012 / Math.max(max, 1e-12); return [[record.lat, record.lon], [record.lat + record.v * scale, record.lon + record.u * scale / Math.max(.2, Math.cos(record.lat * Math.PI / 180))]]; })); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [35, 35], maxZoom: 15 }); }
  function renderRose() { const canvas = $('rose'); const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; canvas.width = Math.max(1, rect.width * dpr); canvas.height = Math.max(1, rect.height * dpr); const ctx = canvas.getContext('2d'); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); const width = rect.width; const height = rect.height; ctx.clearRect(0, 0, width, height); const cx = width / 2; const cy = height / 2 - 2; const radius = Math.min(width, height) * .32; const bins = Array.from({ length: 12 }, () => 0); state.result.records.forEach((record) => bins[Math.floor(((record.direction + 15) % 360) / 30)] += 1); const max = Math.max(...bins, 1); ctx.strokeStyle = '#c9ded2'; ctx.fillStyle = '#687a71'; ctx.font = '12px system-ui'; [0.33, .66, 1].forEach((ratio) => { ctx.beginPath(); ctx.arc(cx, cy, radius * ratio, 0, Math.PI * 2); ctx.stroke(); }); ['N', 'E', 'S', 'O'].forEach((label, index) => { const angle = index * Math.PI / 2; ctx.fillText(label, cx + Math.sin(angle) * (radius + 22) - 4, cy - Math.cos(angle) * (radius + 22) + 4); }); bins.forEach((count, index) => { const start = (index * 30 - 15 - 90) * Math.PI / 180; const end = (index * 30 + 15 - 90) * Math.PI / 180; const outer = radius * count / max; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.arc(cx, cy, outer, start, end); ctx.closePath(); ctx.fillStyle = '#4c9b7b'; ctx.globalAlpha = .82; ctx.fill(); ctx.globalAlpha = 1; }); $('roseFallback').textContent = 'Sectores de 30°; la flecha representa el sentido hacia el que apunta cada vector. El módulo no pondera el conteo de sectores.'; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function report() { const r = state.result; if (!r) return; download('vector-field-report.json', JSON.stringify({ assumptions: { coordinates: 'WGS84 geographic lon/lat', direction: 'degrees clockwise from north, towards vector', map_arrow_scale: '0.012 degrees at maximum module' }, fields: r.fields, count: r.count, discarded_rows: state.rows.length - r.count, metrics: { mean_speed: r.meanSpeed, max_speed: r.maxSpeed, p95_speed: r.p95Speed, mean_u: r.meanU, mean_v: r.meanV }, records: r.records.map((record) => ({ id: record.id, group: record.group, lon: record.lon, lat: record.lat, u: record.u, v: record.v, speed: record.speed, direction_deg: record.direction })) }, null, 2), 'application/json'); }
  function csv() { const r = state.result; if (!r) return; const rows = [['id', 'group', 'lon', 'lat', 'u', 'v', 'speed', 'direction_deg'], ...r.records.map((record) => [record.id, record.group, record.lon, record.lat, record.u, record.v, record.speed, record.direction])]; download('vector-field-annotated.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function geojson() { const r = state.result; if (!r) return; const scale = .012 / Math.max(r.maxSpeed, 1e-12); const features = r.records.flatMap((record) => { const end = [record.lon + record.u * scale / Math.max(.2, Math.cos(record.lat * Math.PI / 180)), record.lat + record.v * scale]; const props = { id: record.id, group: record.group, u: record.u, v: record.v, speed: record.speed, direction_deg: record.direction }; return [{ type: 'Feature', properties: { ...props, role: 'origin' }, geometry: { type: 'Point', coordinates: [record.lon, record.lat] } }, { type: 'Feature', properties: { ...props, role: 'vector' }, geometry: { type: 'LineString', coordinates: [[record.lon, record.lat], end] } }]; }); download('vector-field.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json'); }
  function loadText(text) { $('source').value = text; try { chooseFields(parseDelimited(text)); } catch (error) { setStatus(error.message || 'No se pudieron detectar los datos.', true); } }
  function clearAll() { state.rows = []; state.result = null; $('source').value = ''; $('fileInput').value = ''; ['idField', 'lonField', 'latField', 'groupField', 'uField', 'vField', 'speedField', 'directionField'].forEach((id) => { $(id).innerHTML = '<option value="">Carga datos para detectar campos</option>'; }); $('summary').hidden = $('detailPanel').hidden = true; ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = true); state.layer?.remove(); state.layer = null; $('mapBadge').textContent = $('roseBadge').textContent = '—'; $('roseFallback').textContent = 'La rosa aparecerá tras analizar los datos.'; setStatus('Carga una tabla para detectar coordenadas y componentes.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', () => loadText(example)); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { chooseFields(parseDelimited($('source').value)); analyze(); } catch (error) { setStatus(error.message || 'No se pudo analizar el campo.', true); } }); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { loadText(await file.text()); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id, index) => $(id).addEventListener('click', [report, csv, geojson][index])); window.addEventListener('resize', () => { if (state.result) renderRose(); }); $('source').value = example; initMap();
})();
