(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { features: [], points: [], output: null, allCells: [], map: null, cellLayer: null, pointLayer: null };
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const example = { type: 'FeatureCollection', features: [[-3.720, 40.415], [-3.718, 40.417], [-3.715, 40.418], [-3.710, 40.416], [-3.708, 40.419], [-3.705, 40.420], [-3.700, 40.421], [-3.698, 40.423], [-3.695, 40.425], [-3.690, 40.424], [-3.688, 40.426], [-3.686, 40.428], [-3.680, 40.430], [-3.675, 40.432], [-3.670, 40.434]].map((coordinates, index) => ({ type: 'Feature', properties: { id: `muestra-${index + 1}` }, geometry: { type: 'Point', coordinates } })) };
  const maxCells = 20000;

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function parseInput(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input.features; if (input.type === 'Feature') return [input]; if (typeof input.type === 'string' && depths[input.type] !== undefined) return [{ type: 'Feature', properties: {}, geometry: input }]; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON reconocible.'); }
  function positions(geometry, output = []) { if (!geometry || typeof geometry !== 'object') return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child) => positions(child, output)); return output; } const depth = depths[geometry.type]; if (depth === undefined) return output; const walk = (node, level) => { if (level === 0) { if (isPosition(node)) output.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return output; }
  function bbox(points) { if (!points.length) return null; return points.reduce((box, point) => [Math.min(box[0], point[0]), Math.min(box[1], point[1]), Math.max(box[2], point[0]), Math.max(box[3], point[1])], [points[0][0], points[0][1], points[0][0], points[0][1]]); }
  function local(point, metersLon, metersLat) { return [point[0] * metersLon, point[1] * metersLat]; }
  function ringContains(point, ring) { let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const a = ring[previous], b = ring[index]; const intersects = ((b[1] > point[1]) !== (a[1] > point[1])) && point[0] < (a[0] - b[0]) * (point[1] - b[1]) / (a[1] - b[1]) + b[0]; if (intersects) inside = !inside; } return inside; }
  function hexRing(centerX, centerY, radius, metersLon, metersLat) { const ring = []; for (let index = 0; index < 6; index += 1) { const angle = (30 + index * 60) * Math.PI / 180; ring.push([(centerX + radius * Math.cos(angle)) / metersLon, (centerY + radius * Math.sin(angle)) / metersLat]); } ring.push([...ring[0]]); return ring; }
  function makeGrid(box, radiusKm, metersLon, metersLat) { const radius = radiusKm * 1000; const horizontal = Math.sqrt(3) * radius; const vertical = 1.5 * radius; const localMin = local([box[0], box[1]], metersLon, metersLat); const localMax = local([box[2], box[3]], metersLon, metersLat); const startX = localMin[0] - horizontal; const endX = localMax[0] + horizontal; const startY = localMin[1] - 1.5 * radius; const endY = localMax[1] + 1.5 * radius; const cells = []; const byKey = new Map(); let row = 0; for (let y = startY; y <= endY; y += vertical, row += 1) { const offset = row % 2 ? horizontal / 2 : 0; let col = 0; for (let x = startX + offset; x <= endX; x += horizontal, col += 1) { const cell = { row, col, count: 0, center: [x / metersLon, y / metersLat], geometry: { type: 'Polygon', coordinates: [hexRing(x, y, radius, metersLon, metersLat)] } }; cells.push(cell); byKey.set(`${row}:${col}`, cell); if (cells.length > maxCells) throw new Error('La extensión y el tamaño elegidos generan más de 20.000 celdas. Aumenta el tamaño de celda o recorta la capa.'); } } return { cells, byKey, radius, startX, startY, horizontal, vertical }; }
  function assignPoints(points, grid) { points.forEach((point) => { const rowGuess = Math.round((point.local[1] - grid.startY) / grid.vertical); for (let row = rowGuess - 1; row <= rowGuess + 1; row += 1) { const offset = row % 2 ? grid.horizontal / 2 : 0; const colGuess = Math.round((point.local[0] - grid.startX - offset) / grid.horizontal); for (let col = colGuess - 1; col <= colGuess + 1; col += 1) { const cell = grid.byKey.get(`${row}:${col}`); if (cell && ringContains(point.coordinate, cell.geometry.coordinates[0])) { cell.count += 1; return; } } } }); }
  function run() { if (!state.points.length) return; const radiusKm = Math.max(.05, Math.min(100, Number($('cellSize').value) || 1)); const meanLat = state.points.reduce((sum, point) => sum + point.coordinate[1], 0) / state.points.length; const metersLat = 110540; const metersLon = 111320 * Math.max(.15, Math.cos(meanLat * Math.PI / 180)); const box = bbox(state.points.map((point) => point.coordinate)); try { const grid = makeGrid(box, radiusKm, metersLon, metersLat); state.points.forEach((point) => { point.local = local(point.coordinate, metersLon, metersLat); }); assignPoints(state.points, grid); state.allCells = grid.cells; const maxCount = Math.max(0, ...grid.cells.map((cell) => cell.count)); const active = grid.cells.filter((cell) => cell.count > 0); const source = $('onlyNonEmpty').checked ? active : grid.cells; state.output = { type: 'FeatureCollection', features: source.map((cell, index) => ({ type: 'Feature', properties: { grid_id: `${cell.row}-${cell.col}`, count: cell.count, density_rank: maxCount ? Number((cell.count / maxCount).toFixed(4)) : 0, center_lon: Number(cell.center[0].toFixed(7)), center_lat: Number(cell.center[1].toFixed(7)) }, geometry: cell.geometry })) }; $('summary').hidden = false; $('pointCount').textContent = state.points.length.toLocaleString('es-ES'); $('cellCount').textContent = grid.cells.length.toLocaleString('es-ES'); $('activeCount').textContent = active.length.toLocaleString('es-ES'); $('maxCount').textContent = maxCount.toLocaleString('es-ES'); $('downloadBtn').disabled = false; $('csvBtn').disabled = false; $('status').textContent = `${state.points.length} puntos agregados en ${grid.cells.length} celdas; ${active.length} con observaciones.`; drawMap(maxCount); } catch (error) { $('status').textContent = error.message || 'No se pudo calcular la densidad.'; } }
  function prepare(input) { const features = parseInput(input); state.features = features; state.points = features.map((feature, index) => { const values = positions(feature.geometry); if (!values.length) return null; const coordinate = feature.geometry?.type === 'Point' ? values[0] : values.reduce((sum, point) => [sum[0] + point[0], sum[1] + point[1]], [0, 0]).map((value) => value / values.length); return coordinate[0] >= -180 && coordinate[0] <= 180 && coordinate[1] >= -90 && coordinate[1] <= 90 ? { coordinate, feature, index } : null; }).filter(Boolean); $('summary').hidden = false; $('pointCount').textContent = state.points.length.toLocaleString('es-ES'); $('status').textContent = `${state.points.length} puntos válidos listos para calcular.`; run(); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function colorFor(value, max) { const ratio = max ? value / max : 0; const hue = 220 - ratio * 195; return `hsl(${hue}, 88%, ${52 - ratio * 8}%)`; }
  function drawMap(maxCount) { if (!state.map || !state.output) return; state.cellLayer?.remove(); state.pointLayer?.remove(); const style = (feature) => ({ color: colorFor(feature.properties?.count || 0, maxCount), weight: 1, fillColor: colorFor(feature.properties?.count || 0, maxCount), fillOpacity: feature.properties?.count ? .72 : .08 }); state.cellLayer = L.geoJSON(state.output, { style, onEachFeature: (feature, layer) => layer.bindPopup(`<b>Celda ${escapeHtml(feature.properties?.grid_id)}</b><br>Observaciones: ${feature.properties?.count || 0}`) }).addTo(state.map); const pointFeatures = state.points.map((point) => ({ type: 'Feature', properties: point.feature.properties || {}, geometry: { type: 'Point', coordinates: point.coordinate } })); if (pointFeatures.length) state.pointLayer = L.geoJSON({ type: 'FeatureCollection', features: pointFeatures }, { pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 4, color: '#eef5ff', fillColor: '#eef5ff', fillOpacity: .8, weight: 1 }) }).addTo(state.map); const bounds = state.cellLayer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value).replace(/"/g, '""'); return /[",\n]/.test(text) ? `"${text}"` : text; }
  function download(text, name, mime) { const url = URL.createObjectURL(new Blob([text], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function readFile(file) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { prepare(JSON.parse(await file.text())); } catch (error) { $('summary').hidden = true; $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  $('fileInput').addEventListener('change', () => readFile($('fileInput').files?.[0])); $('exampleBtn').addEventListener('click', () => prepare(example)); $('runBtn').addEventListener('click', run); $('cellSize').addEventListener('change', run); $('onlyNonEmpty').addEventListener('change', run); $('downloadBtn').addEventListener('click', () => { if (state.output) download(JSON.stringify(state.output, null, 2), 'density-lab-hexagonos.geojson', 'application/geo+json'); }); $('csvBtn').addEventListener('click', () => { const rows = [['grid_id', 'count', 'density_rank', 'center_lon', 'center_lat'], ...(state.output?.features || []).map((feature) => [feature.properties.grid_id, feature.properties.count, feature.properties.density_rank, feature.properties.center_lon, feature.properties.center_lat])]; download(rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'density-lab-resumen.csv', 'text/csv;charset=utf-8'); }); $('clearBtn').addEventListener('click', () => { state.features = []; state.points = []; state.output = null; state.allCells = []; state.cellLayer?.remove(); state.pointLayer?.remove(); $('summary').hidden = true; $('downloadBtn').disabled = true; $('csvBtn').disabled = true; $('status').textContent = 'Carga una capa de puntos o el ejemplo.'; }); initMap();
})();
