(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { collection: null, fields: [], output: null, records: [], map: null, layer: null };
  const sample = $('source').value;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection' && Array.isArray(parsed.features)) return parsed; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El documento no contiene GeoJSON reconocible.'); }
  function positions(geometry, output = []) { if (!geometry) return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach(item => positions(item, output)); return output; } const walk = (node, depth) => { if (depth === 0) { if (Array.isArray(node) && Number.isFinite(Number(node[0])) && Number.isFinite(Number(node[1]))) output.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach(child => walk(child, depth - 1)); }; const depth = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 }[geometry.type]; if (depth !== undefined) walk(geometry.coordinates, depth); return output; }
  function center(feature) { const points = positions(feature.geometry); if (!points.length) return null; const sum = points.reduce((total, point) => [total[0] + point[0], total[1] + point[1]], [0, 0]); return [sum[0] / points.length, sum[1] / points.length]; }
  function numericFields(collection) { const fields = new Map(); collection.features.forEach(feature => Object.entries(feature.properties || {}).forEach(([key, value]) => { const number = Number(value); if (value !== null && value !== '' && Number.isFinite(number)) fields.set(key, (fields.get(key) || 0) + 1); })); return [...fields.entries()].filter(([, count]) => count >= 2).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([key]) => key); }
  function refreshFields(preferred = []) { state.fields = numericFields(state.collection); for (let index = 0; index < 3; index += 1) { const select = $('field-' + index); const current = preferred[index] || select.value || state.fields[index] || ''; select.innerHTML = '<option value="">(sin criterio)</option>' + state.fields.map(field => `<option value="${esc(field)}">${esc(field)}</option>`).join(''); select.value = state.fields.includes(current) ? current : ''; } }
  function criteria() { return [0, 1, 2].map(index => ({ field: $('field-' + index).value, direction: $('direction-' + index).value, weight: Number($('weight-' + index).value) || 0 })).filter(item => item.field && item.weight > 0); }
  function classFor(score) { return score >= 80 ? 'Muy alta' : score >= 60 ? 'Alta' : score >= 40 ? 'Media' : 'Baja'; }
  function colorFor(score) { if (score >= 80) return '#d95f59'; if (score >= 60) return '#f1a340'; if (score >= 40) return '#a6d96a'; return '#4c9bc8'; }
  function calculate() {
    if (!state.collection) throw new Error('Carga una capa GeoJSON antes de calcular.');
    const selected = criteria(); if (!selected.length) throw new Error('Selecciona al menos un campo numérico y asígnale un peso.');
    const totalWeight = selected.reduce((sum, item) => sum + item.weight, 0); if (!totalWeight) throw new Error('La suma de pesos debe ser mayor que cero.');
    const ranges = Object.fromEntries(selected.map(item => { const values = state.collection.features.map(feature => Number(feature.properties?.[item.field])).filter(Number.isFinite); let min = values[0] ?? 0, max = values[0] ?? 0; for (let index = 1; index < values.length; index += 1) { if (values[index] < min) min = values[index]; if (values[index] > max) max = values[index]; } return [item.field, { min, max }]; }));
    const records = state.collection.features.map((feature, index) => { let score = 0, missing = 0; selected.forEach(item => { const value = Number(feature.properties?.[item.field]), range = ranges[item.field]; if (!Number.isFinite(value)) { missing += 1; return; } const span = range.max - range.min; let normalized = span ? (value - range.min) / span : 1; if (item.direction === 'low') normalized = 1 - normalized; score += normalized * item.weight; }); score = Math.max(0, Math.min(100, score / totalWeight * 100)); return { index, feature, score, missing, center: center(feature) }; });
    const ordered = [...records].sort((a, b) => b.score - a.score || a.index - b.index); const rank = new Map(ordered.map((record, index) => [record.index, index + 1]));
    records.forEach(record => { record.rank = rank.get(record.index); record.className = classFor(record.score); });
    const features = records.map(record => ({ ...record.feature, properties: { ...(record.feature.properties || {}), suitability_score: Number(record.score.toFixed(3)), suitability_rank: record.rank, suitability_class: record.className, suitability_missing: record.missing, suitability_criteria: selected.map(item => `${item.field}:${item.direction}:${item.weight}`).join('|') } }));
    state.records = records; state.output = { type: 'FeatureCollection', name: 'suitability-lab', features }; const scores = records.map(record => record.score); const missing = records.filter(record => record.missing > 0).length;
    $('featureCount').textContent = records.length.toLocaleString('es-ES'); $('meanScore').textContent = (scores.reduce((sum, value) => sum + value, 0) / scores.length).toFixed(1); $('maxScore').textContent = scores.reduce((max, value) => Math.max(max, value), 0).toFixed(1); $('missingCount').textContent = missing.toLocaleString('es-ES'); $('featureBadge').textContent = records.length + (records.length === 1 ? ' entidad' : ' entidades'); $('quality').textContent = `${selected.length} criterios · ${totalWeight}% ponderado`; $('quality').className = 'quality';
    renderTable(); renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${records.length} entidades puntuadas localmente con ${selected.length} criterios.`);
  }
  function refreshSource(value, preferred = []) { try { state.collection = normalize(value); refreshFields(preferred); calculate(); } catch (error) { setStatus(error.message || 'No se pudo leer la capa.', true); } }
  function renderTable() { const rows = [...state.records].sort((a, b) => a.rank - b.rank).slice(0, 300).map(record => `<tr><td>${record.rank}</td><td>${esc(record.feature.properties?.sitio || record.feature.properties?.name || `Entidad ${record.index + 1}`)}</td><td><strong>${record.score.toFixed(1)}</strong></td><td>${esc(record.className)}</td><td>${record.missing}</td></tr>`).join(''); $('tableWrap').innerHTML = `<table><thead><tr><th>Rango</th><th>Entidad</th><th>Puntuación</th><th>Clase</th><th>Faltantes</th></tr></thead><tbody>${rows}</tbody></table>${state.records.length > 300 ? `<p class="table-note">Se muestran 300 de ${state.records.length.toLocaleString('es-ES')} entidades; la exportación incluye todas.</p>` : ''}`; }
  function popup(record) { return `<strong>${esc(record.feature.properties?.sitio || record.feature.properties?.name || `Entidad ${record.index + 1}`)}</strong><br>Puntuación: ${record.score.toFixed(1)} · rango ${record.rank}<br>Clase: ${esc(record.className)}<br>Campos faltantes: ${record.missing}`; }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.4168, -3.7038], 13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer || !state.output) return; state.layer.clearLayers(); const geo = L.geoJSON(state.output, { style: feature => ({ color: colorFor(Number(feature.properties?.suitability_score) || 0), fillColor: colorFor(Number(feature.properties?.suitability_score) || 0), fillOpacity: .68, weight: 2 }), pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 8, color: '#071b25', weight: 2, fillColor: colorFor(Number(feature.properties?.suitability_score) || 0), fillOpacity: .9 }), onEachFeature: (feature, layer) => { const record = state.records.find(item => item.feature === state.collection.features.find(source => source === feature)); const fallback = { feature, index: 0, score: Number(feature.properties?.suitability_score) || 0, rank: feature.properties?.suitability_rank || '—', className: feature.properties?.suitability_class || '—', missing: feature.properties?.suitability_missing || 0 }; layer.bindPopup(popup(record || fallback)); } }).addTo(state.layer); const bounds = geo.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [25, 25], maxZoom: 16 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const lines = ['rank,score,class,missing,entity']; [...state.records].sort((a, b) => a.rank - b.rank).forEach(record => lines.push([record.rank, record.score.toFixed(3), record.className, record.missing, record.feature.properties?.sitio || record.feature.properties?.name || `Entidad ${record.index + 1}`].map(value => '"' + String(value).replace(/"/g, '""') + '"').join(','))); download('ranking-aptitud.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  $('calculateBtn').addEventListener('click', () => { try { calculate(); } catch (error) { setStatus(error.message || 'No se pudo calcular la aptitud.', true); } }); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; refreshSource(sample, ['accesibilidad', 'visibilidad', 'distancia_agua']); }); $('clearBtn').addEventListener('click', () => { state.collection = null; state.fields = []; state.output = null; state.records = []; state.layer?.clearLayers(); [0, 1, 2].forEach(index => { $('field-' + index).innerHTML = '<option value="">(sin criterio)</option>'; }); $('tableWrap').innerHTML = '<p class="empty">Calcula una puntuación para ver el ranking.</p>'; $('featureCount').textContent = '—'; $('meanScore').textContent = '—'; $('maxScore').textContent = '—'; $('missingCount').textContent = '—'; $('featureBadge').textContent = '0 entidades'; $('quality').textContent = 'Sin calcular'; $('quality').className = 'quality muted'; $('geojsonBtn').disabled = true; $('csvBtn').disabled = true; setStatus('Carga una capa para empezar.'); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); refreshSource($('source').value); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', () => download('aptitud-multicriterio.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', exportCsv); initMap(); refreshSource(sample, ['accesibilidad', 'visibilidad', 'distancia_agua']);
})();
