(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { graph: null, result: null, map: null, layer: null };
  const example = { type: 'FeatureCollection', features: [
    { type: 'Feature', properties: { name: 'Camino norte' }, geometry: { type: 'LineString', coordinates: [[-3.714,40.421],[-3.704,40.426],[-3.693,40.423],[-3.684,40.428]] } },
    { type: 'Feature', properties: { name: 'Camino central' }, geometry: { type: 'LineString', coordinates: [[-3.704,40.426],[-3.700,40.416],[-3.704,40.407],[-3.696,40.399]] } },
    { type: 'Feature', properties: { name: 'Camino sur' }, geometry: { type: 'LineString', coordinates: [[-3.704,40.407],[-3.715,40.402],[-3.727,40.407],[-3.734,40.399]] } },
    { type: 'Feature', properties: { name: 'Acceso este' }, geometry: { type: 'LineString', coordinates: [[-3.700,40.416],[-3.688,40.412],[-3.677,40.416],[-3.667,40.410]] } }
  ] };
  const EARTH = 6371008.8;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function haversine(a, b) { const p1 = a[1] * Math.PI / 180; const p2 = b[1] * Math.PI / 180; const dLat = (b[1] - a[1]) * Math.PI / 180; const dLon = (b[0] - a[0]) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dLon / 2) ** 2; return 2 * EARTH * Math.atan2(Math.sqrt(x), Math.sqrt(Math.max(0, 1 - x))); }
  function key(point) { return `${point[0].toFixed(7)},${point[1].toFixed(7)}`; }
  function readLines(data) { const root = data?.type === 'FeatureCollection' ? data.features : data?.type === 'Feature' ? [data] : []; const lines = []; root.forEach((feature, featureIndex) => { const geometry = feature?.geometry; if (!geometry) return; if (geometry.type === 'LineString' && geometry.coordinates.length > 1) lines.push({ coordinates: geometry.coordinates, featureIndex, properties: feature.properties || {} }); if (geometry.type === 'MultiLineString') geometry.coordinates.filter((line) => line.length > 1).forEach((coordinates) => lines.push({ coordinates, featureIndex, properties: feature.properties || {} })); }); if (!lines.length) throw new Error('El GeoJSON debe contener al menos una LineString o MultiLineString con dos vértices.'); return lines; }
  function buildGraph(data) { const lines = readLines(data); const nodes = []; const nodeByKey = new Map(); const edges = []; const getNode = (point) => { const clean = [Number(point[0]), Number(point[1])]; const id = key(clean); if (!nodeByKey.has(id)) { nodeByKey.set(id, nodes.length); nodes.push({ id: nodes.length + 1, key: id, lon: clean[0], lat: clean[1], degree: 0 }); } return nodeByKey.get(id); }; const adjacency = []; lines.forEach((line) => { const ids = line.coordinates.map(getNode); for (let i = 0; i < ids.length - 1; i += 1) { const a = ids[i]; const b = ids[i + 1]; const coordinates = [[nodes[a].lon, nodes[a].lat], [nodes[b].lon, nodes[b].lat]]; const weight = haversine(coordinates[0], coordinates[1]); if (!Number.isFinite(weight) || weight <= 0) continue; const edge = { id: edges.length + 1, a, b, weight, coordinates, featureIndex: line.featureIndex }; edges.push(edge); nodes[a].degree += 1; nodes[b].degree += 1; (adjacency[a] ||= []).push({ node: b, weight, edge }); (adjacency[b] ||= []).push({ node: a, weight, edge }); } }); if (!edges.length) throw new Error('No se pudieron construir aristas con longitud positiva.'); return { lines, nodes, edges, adjacency, totalLength: edges.reduce((sum, edge) => sum + edge.weight, 0) }; }
  function nodeLabel(node) { return `Nodo ${node.id} · ${node.lon.toFixed(5)}, ${node.lat.toFixed(5)}`; }
  function loadData(data) { state.graph = buildGraph(data); $('startNode').innerHTML = state.graph.nodes.map((node) => `<option value="${node.id - 1}">${escapeHtml(nodeLabel(node))}</option>`).join(''); const middle = state.graph.nodes.slice().sort((a, b) => b.degree - a.degree)[0]; if (middle) $('startNode').value = String(middle.id - 1); setStatus(`${state.graph.nodes.length.toLocaleString('es-ES')} nodos y ${state.graph.edges.length.toLocaleString('es-ES')} aristas construidos. Elige un origen y calcula.`); renderNetwork(); }
  function dijkstra(start) { const graph = state.graph; const distances = Array.from({ length: graph.nodes.length }, () => Infinity); distances[start] = 0; const visited = new Set(); for (let iteration = 0; iteration < graph.nodes.length; iteration += 1) { let current = -1; let best = Infinity; distances.forEach((distance, index) => { if (!visited.has(index) && distance < best) { best = distance; current = index; } }); if (current < 0) break; visited.add(current); (graph.adjacency[current] || []).forEach((connection) => { const candidate = distances[current] + connection.weight; if (candidate < distances[connection.node]) distances[connection.node] = candidate; }); } return distances; }
  function analyze() { if (!state.graph) throw new Error('Carga una red antes de calcular.'); const limitKm = Number($('limitInput').value); const speed = Number($('speedInput').value); if (!Number.isFinite(limitKm) || limitKm <= 0 || !Number.isFinite(speed) || speed <= 0) throw new Error('La distancia y la velocidad deben ser mayores que cero.'); const start = Number($('startNode').value); if (!Number.isInteger(start) || !state.graph.nodes[start]) throw new Error('Selecciona un nodo de origen.'); const distances = dijkstra(start); const limit = limitKm * 1000; const nodeResults = state.graph.nodes.map((node, index) => ({ ...node, distance: distances[index], accessible: distances[index] <= limit })).filter((node) => node.accessible); const edges = state.graph.edges.map((edge) => { const fromA = Number.isFinite(distances[edge.a]) ? Math.max(0, limit - distances[edge.a]) : 0; const fromB = Number.isFinite(distances[edge.b]) ? Math.max(0, limit - distances[edge.b]) : 0; const accessibleLength = Math.min(edge.weight, Math.max(fromA, fromB)); return { ...edge, accessible: accessibleLength > 0, accessibleLength }; }); const accessibleEdges = edges.filter((edge) => edge.accessible); const accessibleLength = accessibleEdges.reduce((sum, edge) => sum + edge.accessibleLength, 0); state.result = { start, limitKm, speed, distances, nodes: nodeResults, edges, accessibleEdges, accessibleLength, totalLength: state.graph.totalLength, maxDistance: Math.max(...nodeResults.map((node) => node.distance), 0) }; renderResult(); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = false); setStatus(`${nodeResults.length.toLocaleString('es-ES')} nodos alcanzables dentro de ${limitKm.toLocaleString('es-ES')} km. Se conserva la red completa para comparación.`); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function renderResult() { const r = state.result; $('summary').hidden = $('detailPanel').hidden = false; $('totalLength').textContent = `${format(r.totalLength / 1000)} km`; $('graphSize').textContent = `${state.graph.nodes.length} / ${state.graph.edges.length}`; $('reachableNodes').textContent = `${r.nodes.length} / ${state.graph.nodes.length}`; $('reachableEdges').textContent = `${r.accessibleEdges.length} / ${state.graph.edges.length}`; $('accessibleLength').textContent = `${format(r.accessibleLength / 1000)} km`; $('maxTime').textContent = format(r.maxDistance / 1000 / r.speed * 60) + ' min'; $('summaryBadge').textContent = `${format(r.limitKm, 1)} km`; $('detailBadge').textContent = `${r.nodes.length} nodos`; const coverage = r.totalLength ? r.accessibleLength / r.totalLength * 100 : 0; $('interpretation').textContent = `Cobertura aproximada de la longitud: ${format(coverage, 1)} %. El tiempo máximo usa ${format(r.speed, 1)} km/h y solo representa el recorrido por la red desde el nodo seleccionado.`; $('detailBody').innerHTML = r.nodes.slice().sort((a, b) => a.distance - b.distance).map((node) => `<tr><th>${node.id}</th><td>${format(node.lon, 6)}</td><td>${format(node.lat, 6)}</td><td>${format(node.distance / 1000)} km</td><td>${format(node.distance / 1000 / r.speed * 60)} min</td><td>${node.degree}</td></tr>`).join(''); $('mapBadge').textContent = `${r.nodes.length} nodos accesibles`; renderNetwork(); }
  function renderNetwork() { if (!state.map || !state.graph) return; state.layer?.remove(); const layers = []; state.graph.edges.forEach((edge) => { const accessible = state.result?.edges.find((item) => item.id === edge.id)?.accessible; layers.push(L.polyline(edge.coordinates.map((point) => [point[1], point[0]]), { color: accessible ? '#4c9b7b' : '#a3b0aa', weight: accessible ? 4 : 2, opacity: accessible ? .9 : .55 }).bindTooltip(`Tramo ${edge.id} · ${format(edge.weight / 1000)} km`)); }); const accessibleNodeIds = new Set(state.result?.nodes.map((node) => node.id - 1) || []); state.graph.nodes.forEach((node, index) => { const isStart = state.result?.start === index; const accessible = accessibleNodeIds.has(index); const marker = L.circleMarker([node.lat, node.lon], { radius: isStart ? 9 : accessible ? 5 : 3, color: isStart ? '#a33d50' : accessible ? '#176b50' : '#899990', fillColor: isStart ? '#e46e72' : accessible ? '#80d0a5' : '#d4ded8', fillOpacity: .95, weight: isStart ? 2 : 1 }).bindPopup(`<strong>${escapeHtml(nodeLabel(node))}</strong><div>Grado: ${node.degree}${Number.isFinite(state.result?.distances[index]) ? `<br>Distancia: ${format(state.result.distances[index] / 1000)} km` : ''}</div>`); marker.on('click', () => { $('startNode').value = String(index); }); layers.push(marker); }); state.layer = L.layerGroup(layers).addTo(state.map); const bounds = L.latLngBounds(state.graph.nodes.map((node) => [node.lat, node.lon])); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [35, 35], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function report() { const r = state.result; if (!r) return; download('network-access-report.json', JSON.stringify({ assumptions: { crs: 'WGS84 geographic lon/lat', routing: 'Dijkstra over vertices and consecutive segments', edge_access: 'partial segment estimated from reachable endpoint' }, origin_node: state.graph.nodes[r.start], max_distance_km: r.limitKm, speed_kmh: r.speed, graph: { nodes: state.graph.nodes.length, edges: state.graph.edges.length, total_length_km: r.totalLength / 1000 }, result: { reachable_nodes: r.nodes.length, reachable_edges: r.accessibleEdges.length, accessible_length_km: r.accessibleLength / 1000, max_reachable_distance_km: r.maxDistance / 1000 }, nodes: r.nodes.map((node) => ({ id: node.id, lon: node.lon, lat: node.lat, distance_m: node.distance, minutes: node.distance / 1000 / r.speed * 60, degree: node.degree })) }, null, 2), 'application/json'); }
  function csv() { const r = state.result; if (!r) return; const rows = [['node_id', 'lon', 'lat', 'distance_m', 'minutes', 'degree', 'accessible'], ...state.graph.nodes.map((node, index) => [node.id, node.lon, node.lat, r.distances[index], Number.isFinite(r.distances[index]) ? r.distances[index] / 1000 / r.speed * 60 : '', node.degree, r.distances[index] <= r.limitKm * 1000])]; download('network-access-nodes.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function geojson() { const r = state.result; if (!r) return; const features = state.graph.edges.map((edge) => { const analysis = r.edges.find((item) => item.id === edge.id); return { type: 'Feature', properties: { edge_id: edge.id, length_m: edge.weight, accessible: analysis.accessible, accessible_length_m: analysis.accessibleLength, distance_a_m: r.distances[edge.a], distance_b_m: r.distances[edge.b] }, geometry: { type: 'LineString', coordinates: edge.coordinates } }; }); state.graph.nodes.forEach((node, index) => features.push({ type: 'Feature', properties: { node_id: node.id, distance_m: r.distances[index], accessible: r.distances[index] <= r.limitKm * 1000, degree: node.degree }, geometry: { type: 'Point', coordinates: [node.lon, node.lat] } })); download('network-access-result.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json'); }
  function loadText(text) { $('source').value = text; try { loadData(JSON.parse(text)); } catch (error) { setStatus(error.message || 'No se pudo leer la red GeoJSON.', true); } }
  function clearAll() { state.graph = null; state.result = null; $('source').value = ''; $('fileInput').value = ''; $('startNode').innerHTML = '<option value="">Carga una red para detectar nodos</option>'; $('summary').hidden = $('detailPanel').hidden = true; ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id) => $(id).disabled = true); state.layer?.remove(); state.layer = null; $('mapBadge').textContent = '—'; setStatus('Carga una red para construir el grafo.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', () => loadText(JSON.stringify(example, null, 2))); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { analyze(); } catch (error) { setStatus(error.message || 'No se pudo calcular la accesibilidad.', true); } }); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 50 * 1024 * 1024) { setStatus('El archivo supera 50 MB; no se abre en esta herramienta local.', true); return; } try { loadText(await file.text()); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }); ['reportBtn', 'csvBtn', 'geoBtn'].forEach((id, index) => $(id).addEventListener('click', [report, csv, geojson][index])); $('source').value = JSON.stringify(example, null, 2); initMap();
})();
