(() => {
  const $ = id => document.getElementById(id), canvas=$('canvas'), ctx=canvas.getContext('2d',{willReadFrequently:true});
  const controls=['channel','ramp','min','max','gamma','invert'].map(id=>$(id)); let source=null, sourceData=null;
  const ramps={
    terrain:[[0,'#153b59'],[.24,'#2d8b87'],[.48,'#b4c96b'],[.68,'#e9cf76'],[.84,'#a85a42'],[1,'#f2eee4']],
    viridis:[[0,'#440154'],[.25,'#3b528b'],[.5,'#21918c'],[.75,'#5ec962'],[1,'#fde725']],
    inferno:[[0,'#000004'],[.25,'#420a68'],[.5,'#932667'],[.75,'#dd513a'],[1,'#fba238']],
    blueRed:[[0,'#2166ac'],[.5,'#f7f7f7'],[1,'#b2182b']],gray:[[0,'#050505'],[1,'#fafafa']]
  };
  function hexRgb(hex){return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]}
  function colorAt(rampName,t){const stops=ramps[rampName], r=stops[0], q=stops[stops.length-1]; for(let i=1;i<stops.length;i++){if(t<=stops[i][0]){const a=stops[i-1],b=stops[i],f=(t-a[0])/(b[0]-a[0]),ca=hexRgb(a[1]),cb=hexRgb(b[1]);return ca.map((v,j)=>Math.round(v+(cb[j]-v)*f))}}return hexRgb(q[1])}
  function readValue(r,g,b,a,channel){if(channel==='red')return r;if(channel==='green')return g;if(channel==='blue')return b;return .2126*r+.7152*g+.0722*b}
  function apply(){if(!sourceData)return;const min=Number($('min').value), max=Number($('max').value), gamma=Number($('gamma').value), invert=$('invert').checked, channel=$('channel').value, ramp=$('ramp').value;if(max<=min){$('status').textContent='El máximo debe ser mayor que el mínimo.';return}const out=ctx.createImageData(sourceData.width,sourceData.height), span=max-min;for(let i=0;i<sourceData.data.length;i+=4){const v=readValue(sourceData.data[i],sourceData.data[i+1],sourceData.data[i+2],sourceData.data[i+3],channel), raw=Math.min(1,Math.max(0,(v-min)/span)), t=invert?1-Math.pow(raw,gamma):Math.pow(raw,gamma), c=colorAt(ramp,t);out.data[i]=c[0];out.data[i+1]=c[1];out.data[i+2]=c[2];out.data[i+3]=sourceData.data[i+3]}ctx.putImageData(out,0,0);$('status').textContent=`Estilo aplicado · canal ${channel} · rampa ${ramp}.`;$('downloadBtn').disabled=false;$('legendBar').style.background=`linear-gradient(90deg,${ramps[ramp].map(s=>s[1]).join(',')})`}
  function load(file){if(!file)return;const img=new Image();img.onload=()=>{const maxWidth=1400, scale=Math.min(1,maxWidth/img.naturalWidth);canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));ctx.drawImage(img,0,0,canvas.width,canvas.height);sourceData=ctx.getImageData(0,0,canvas.width,canvas.height);$('dimensions').textContent=`${canvas.width} × ${canvas.height} px`;$('empty').hidden=true;$('applyBtn').disabled=false;$('status').textContent='Imagen cargada. Ajusta la rampa y aplica el estilo.';apply()};img.onerror=()=>{$('status').textContent='No se pudo leer la imagen.'};img.src=URL.createObjectURL(file)}
  $('imageInput').addEventListener('change',e=>load(e.target.files[0]));$('applyBtn').addEventListener('click',apply);controls.forEach(c=>c.addEventListener('input',()=>{if(c.id==='min')$('minOut').textContent=c.value;if(c.id==='max')$('maxOut').textContent=c.value;if(c.id==='gamma')$('gammaOut').textContent=Number(c.value).toFixed(2);if(sourceData)apply()}));$('resetBtn').addEventListener('click',()=>{$('min').value=0;$('max').value=255;$('gamma').value=1;$('invert').checked=false;$('minOut').textContent='0';$('maxOut').textContent='255';$('gammaOut').textContent='1.00';if(sourceData)apply()});$('downloadBtn').addEventListener('click',()=>{const a=document.createElement('a');a.download='raster-colorizado.png';a.href=canvas.toDataURL('image/png');a.click()});canvas.addEventListener('click',e=>{if(!sourceData)return;const rect=canvas.getBoundingClientRect(),x=Math.min(canvas.width-1,Math.max(0,Math.floor((e.clientX-rect.left)*canvas.width/rect.width))),y=Math.min(canvas.height-1,Math.max(0,Math.floor((e.clientY-rect.top)*canvas.height/rect.height))),p=ctx.getImageData(x,y,1,1).data;$('pixelLabel').textContent=`Píxel ${x}, ${y}`;$('pixelValue').textContent=`RGB ${p[0]}, ${p[1]}, ${p[2]}`});
})();
