(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, zones: [], samples: [], result: null, map: null, zoneLayer: null, sampleLayer: null };
  const example = { type: 'FeatureCollection', features: [
    { type: 'Feature', properties: { name: 'Zona norte', tipo: 'bosque' }, geometry: { type: 'Polygon', coordinates: [[[-3.725, 40.425], [-3.705, 40.425], [-3.700, 40.440], [-3.720, 40.445], [-3.735, 40.435], [-3.725, 40.425]]] } },
    { type: 'Feature', properties: { name: 'Zona central', tipo: 'cultivo' }, geometry: { type: 'Polygon', coordinates: [[[-3.690, 40.400], [-3.665, 40.400], [-3.660, 40.415], [-3.680, 40.420], [-3.695, 40.412], [-3.690, 40.400]]] } },
    { type: 'Feature', properties: { name: 'Zona sur', tipo: 'ribera' }, geometry: { type: 'Polygon', coordinates: [[[-3.745, 40.385], [-3.720, 40.380], [-3.710, 40.395], [-3.735, 40.402], [-3.745, 40.385]]] } }
  ] };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function normalize(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input; if (input.type === 'Feature') return { type: 'FeatureCollection', features: [input] }; if (typeof input.type === 'string') return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: input }] }; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON.'); }
  function parts(geometry) { if (!geometry) return []; if (geometry.type === 'Polygon') return [geometry.coordinates || []]; if (geometry.type === 'MultiPolygon') return geometry.coordinates || []; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).flatMap(parts); return []; }
  function flattenCoordinates(geometry, output = []) { parts(geometry).flat(2).forEach((point) => { if (Array.isArray(point) && point.length >= 2 && Number.isFinite(Number(point[0])) && Number.isFinite(Number(point[1]))) output.push([Number(point[0]), Number(point[1])]); }); return output; }
  function bbox(geometry) { const points = flattenCoordinates(geometry); if (!points.length) return null; return points.reduce((box, point) => [Math.min(box[0], point[0]), Math.min(box[1], point[1]), Math.max(box[2], point[0]), Math.max(box[3], point[1])], [points[0][0], points[0][1], points[0][0], points[0][1]]); }
  function inRing(point, ring) { let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const a = ring[previous], b = ring[index]; const crosses = ((b[1] > point[1]) !== (a[1] > point[1])) && point[0] < (a[0] - b[0]) * (point[1] - b[1]) / (a[1] - b[1]) + b[0]; if (crosses) inside = !inside; } return inside; }
  function contains(point, geometry) { return parts(geometry).some((rings) => rings.length && inRing(point, rings[0]) && !rings.slice(1).some((ring) => inRing(point, ring))); }
  function seedRandom(seed) { let hash = 2166136261; String(seed || 'muestreo').split('').forEach((character) => { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 16777619); }); return () => { hash += 0x6D2B79F5; let value = Math.imul(hash ^ hash >>> 15, 1 | hash); value ^= value + Math.imul(value ^ value >>> 7, 61 | value); return ((value ^ value >>> 14) >>> 0) / 4294967296; }; }
  function project(point, reference) { return [point[0] * 111320 * Math.max(.15, Math.cos(reference[1] * Math.PI / 180)), point[1] * 110540]; }
  function distanceSquared(a, b) { return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2; }
  function zoneName(feature, index) { const properties = feature.properties || {}; return String(properties.name ?? properties.nombre ?? properties.id ?? `Zona ${index + 1}`); }
  function prepare(input, filename = 'Ejemplo · 3 zonas') { const normalized = normalize(input); const zones = normalized.features.map((feature, index) => ({ feature, index, bbox: bbox(feature.geometry), name: zoneName(feature, index) })).filter((zone) => zone.bbox && parts(zone.feature.geometry).length); if (!zones.length) throw new Error('No se encontraron polígonos o multipolígonos válidos.'); if (zones.length > 500) throw new Error('Para mantener el navegador ágil, carga como máximo 500 zonas.'); state.source = normalized; state.zones = zones; $('fileName').textContent = filename; $('runBtn').disabled = false; generate(); }
  function generate() { if (!state.zones.length) return; const target = Math.max(1, Math.min(500, Math.floor(Number($('sampleCount').value) || 8))); const minDistance = Math.max(0, Math.min(100000, Number($('minDistance').value) || 0)); const seed = $('seed').value.trim() || 'muestreo'; const reference = [state.zones.reduce((sum, zone) => sum + (zone.bbox[0] + zone.bbox[2]) / 2, 0) / state.zones.length, state.zones.reduce((sum, zone) => sum + (zone.bbox[1] + zone.bbox[3]) / 2, 0) / state.zones.length]; const random = seedRandom(seed); const samples = []; const rows = []; state.zones.forEach((zone) => { const local = []; const localBox = zone.bbox; const minimumSquared = minDistance ** 2; const maxAttempts = Math.max(5000, target * 1500); let attempts = 0; while (local.length < target && attempts < maxAttempts) { attempts += 1; const candidate = [localBox[0] + random() * (localBox[2] - localBox[0]), localBox[1] + random() * (localBox[3] - localBox[1])]; if (!contains(candidate, zone.feature.geometry)) continue; const xy = project(candidate, reference); if (minDistance && samples.some((sample) => distanceSquared(xy, sample.xy) < minimumSquared)) continue; const sample = { id: `M-${samples.length + 1}`, sourceIndex: zone.index, sourceName: zone.name, coordinate: candidate, xy, attempt: attempts }; local.push(sample); samples.push(sample); } rows.push({ zone, target, generated: local.length, attempts, status: local.length === target ? 'completo' : 'parcial' }); }); state.samples = samples; state.result = { seed, target, minDistance, rows, reference }; $('summary').hidden = false; $('seedLabel').textContent = `${seed} · ≥ ${minDistance} m`; $('zoneCount').textContent = state.zones.length.toLocaleString('es-ES'); $('targetCount').textContent = (target * state.zones.length).toLocaleString('es-ES'); $('generatedCount').textContent = samples.length.toLocaleString('es-ES'); $('shortfallCount').textContent = rows.reduce((sum, row) => sum + row.target - row.generated, 0).toLocaleString('es-ES'); $('zoneBody').innerHTML = rows.map((row) => `<tr><td>${escapeHtml(row.zone.name)}</td><td>${row.target}</td><td>${row.generated}</td><td><span class="state-${row.status}">${row.status}</span></td></tr>`).join(''); $('geojsonBtn').disabled = $('csvBtn').disabled = false; renderMap(); const missing = rows.reduce((sum, row) => sum + row.target - row.generated, 0); setStatus(`${samples.length} puntos generados en ${state.zones.length} zonas${missing ? `; faltan ${missing} por la restricción espacial` : ''}.`); }
  function renderMap() { if (!state.map || !state.source) return; state.zoneLayer?.remove(); state.sampleLayer?.remove(); state.zoneLayer = L.geoJSON(state.source, { style: { color: '#63a7d8', weight: 2, fillColor: '#2e6687', fillOpacity: .22 }, onEachFeature: (feature, layer) => layer.bindPopup(`<strong>${escapeHtml(zoneName(feature, state.source.features.indexOf(feature)))}</strong><br>Zona de muestreo`) }).addTo(state.map); state.sampleLayer = L.layerGroup(); state.samples.forEach((sample) => { const marker = L.circleMarker([sample.coordinate[1], sample.coordinate[0]], { radius: 7, color: '#fff', weight: 1, fillColor: '#ffbe62', fillOpacity: .95 }); marker.bindPopup(`<strong>${escapeHtml(sample.id)}</strong><br>${escapeHtml(sample.sourceName)}<br>${sample.coordinate[0].toFixed(6)}, ${sample.coordinate[1].toFixed(6)}`); marker.addTo(state.sampleLayer); }); state.sampleLayer.addTo(state.map); const bounds = state.zoneLayer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function sampleGeoJSON() { return { type: 'FeatureCollection', features: state.samples.map((sample) => ({ type: 'Feature', properties: { sample_id: sample.id, source_feature: sample.sourceIndex, source_name: sample.sourceName, seed: state.result.seed, min_distance_m: state.result.minDistance }, geometry: { type: 'Point', coordinates: sample.coordinate } })) }; }
  function downloadCsv() { const rows = [['sample_id', 'source_feature', 'source_name', 'longitude', 'latitude', 'seed', 'min_distance_m'], ...state.samples.map((sample) => [sample.id, sample.sourceIndex + 1, sample.sourceName, sample.coordinate[0], sample.coordinate[1], state.result.seed, state.result.minDistance])]; download('sampling-lab-campaign.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function reset() { state.source = null; state.zones = []; state.samples = []; state.result = null; $('fileInput').value = ''; $('fileName').textContent = 'Ningún archivo seleccionado'; $('runBtn').disabled = true; $('summary').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = true; state.zoneLayer?.remove(); state.sampleLayer?.remove(); setStatus('Carga una capa de polígonos o usa el ejemplo.'); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON.', true); } }); $('sampleCount').addEventListener('change', () => { if (state.source) generate(); }); $('minDistance').addEventListener('change', () => { if (state.source) generate(); }); $('seed').addEventListener('change', () => { if (state.source) generate(); }); $('exampleBtn').addEventListener('click', () => { try { prepare(example); } catch (error) { setStatus(error.message, true); } }); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', () => { try { generate(); } catch (error) { setStatus(error.message, true); } }); $('geojsonBtn').addEventListener('click', () => { if (state.result) download('sampling-lab-points.geojson', JSON.stringify(sampleGeoJSON(), null, 2), 'application/geo+json'); }); $('csvBtn').addEventListener('click', downloadCsv);
  initMap();
})();
