(() => {
  const map = L.map('map', { zoomControl: true, preferCanvas: false, worldCopyJump: true }).setView([40.32, -3.7], 6);
  const homeView = { center: [40.32, -3.7], zoom: 6 };
  const baseLayers = {};
  const osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
  const baseLabels = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, opacity: 0, attribution: '&copy; OpenStreetMap contributors' });
  baseLayers.osm = osm;
  baseLayers.labels = baseLabels;
  const scale = L.control.scale({ imperial: false, position: 'bottomleft' }).addTo(map);

  const catalog = [
    { id: 'ign-pnoa-current', group: 'IGN · relieve y teledetección', label: 'PNOA máxima actualidad', short: 'Ortoimagen nacional · WMS', type: 'wms', service: 'https://www.ign.es/wms-inspire/pnoa-ma', layerName: 'OI.OrthoimageCoverage', format: 'image/jpeg', transparent: false, attribution: 'PNOA / IGN', opacity: .9 },
    { id: 'ign-pnoa-mosaic', group: 'IGN · relieve y teledetección', label: 'PNOA mosaico histórico disponible', short: 'Mosaico ortofotográfico · WMS', type: 'wms', service: 'https://www.ign.es/wms-inspire/pnoa-ma', layerName: 'OI.MosaicElement', format: 'image/jpeg', transparent: false, attribution: 'PNOA / IGN', opacity: .82 },
    { id: 'ign-base', group: 'IGN · relieve y teledetección', label: 'Base cartográfica del IGN', short: 'Topografía y referencias · WMS', type: 'wms', service: 'https://www.ign.es/wms-inspire/ign-base', layerName: 'IGNBaseTodo', format: 'image/png', transparent: true, attribution: 'IGN', opacity: .82 },
    { id: 'ign-pnoa-2024', group: 'IGN · ortofotos históricas', label: 'PNOA anual 2024', short: 'Ortofoto histórica · WMS', type: 'wms', service: 'https://www.ign.es/wms/pnoa-historico', layerName: 'PNOA2024', format: 'image/jpeg', transparent: false, attribution: 'PNOA / IGN', opacity: .82 },
    { id: 'ign-pnoa-2023', group: 'IGN · ortofotos históricas', label: 'PNOA anual 2023', short: 'Ortofoto histórica · WMS', type: 'wms', service: 'https://www.ign.es/wms/pnoa-historico', layerName: 'PNOA2023', format: 'image/jpeg', transparent: false, attribution: 'PNOA / IGN', opacity: .82 },
    { id: 'ign-pnoa-2010', group: 'IGN · ortofotos históricas', label: 'PNOA anual 2010', short: 'Ortofoto histórica · WMS', type: 'wms', service: 'https://www.ign.es/wms/pnoa-historico', layerName: 'PNOA2010', format: 'image/jpeg', transparent: false, attribution: 'PNOA / IGN', opacity: .82 },
    { id: 'scuam-lopez-1773', group: 'Cartografía histórica', label: 'SCUAM · Tomás López 1773', short: 'Mapa histórico de Madrid · WMS', type: 'wms', service: 'https://guiadigital.uam.es/geoserver/atlas_lopez_UAM_WMS/wms?', layerName: 'ATLopez_Madrid_1773_lam1_UAM', format: 'image/png', transparent: true, attribution: 'SCUAM / UAM', opacity: .82 },
    { id: 'igme-magna-50', group: 'IGME · geología', label: 'IGME · MAGNA 1:50.000', short: 'Mapa geológico nacional · WMS', type: 'wms', service: 'https://mapas.igme.es/gis/services/Cartografia_Geologica/IGME_MAGNA_50/MapServer/WMSServer', layerName: '0', format: 'image/png', transparent: true, attribution: 'IGME', opacity: .82 },
    { id: 'igme-geode-50', group: 'IGME · geología', label: 'IGME · GEODE continuo 1:50.000', short: 'Mapa geológico continuo · WMS', type: 'wms', service: 'https://mapas.igme.es/gis/services/Cartografia_Geologica/IGME_Geode_50/MapServer/WMSServer', layerName: '0', format: 'image/png', transparent: true, attribution: 'IGME', opacity: .82 },
    { id: 'esri-imagery', group: 'Bases globales', label: 'Esri World Imagery', short: 'Imagen satélite global · XYZ', type: 'xyz', url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', attribution: 'Esri, Maxar, Earthstar Geographics', opacity: .9 },
    { id: 'opentopo', group: 'Bases globales', label: 'OpenTopoMap', short: 'Topografía mundial · XYZ', type: 'xyz', url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', attribution: 'OpenTopoMap · OpenStreetMap contributors', opacity: .86 }
  ];
  const state = { layers: [], catalogFilter: '', swipeEnabled: false, swipeLayerId: '', swipePosition: 50, clicked: null, northLock: false };
  const els = {
    catalog: document.getElementById('catalog'), activeLayers: document.getElementById('activeLayers'), layerCount: document.getElementById('layerCount'), layerStatus: document.getElementById('layerStatus'), mapStatus: document.getElementById('mapStatus'), sourceStatus: document.getElementById('sourceStatus'), mapTitle: document.getElementById('mapTitle'),
    customForm: document.getElementById('customLayerForm'), customType: document.getElementById('customType'), customUrl: document.getElementById('customUrl'), customName: document.getElementById('customName'), customLabel: document.getElementById('customLabel'), customNameField: document.getElementById('customNameField'), catalogFilter: document.getElementById('catalogFilter'),
    swipeToggle: document.getElementById('swipeToggle'), swipeLayer: document.getElementById('swipeLayer'), swipeRange: document.getElementById('swipeRange'), swipeOutput: document.getElementById('swipeOutput'), swipeLine: document.getElementById('swipeLine'), clickedCoords: document.getElementById('clickedCoords'), copyCoordsBtn: document.getElementById('copyCoordsBtn'), analysisStatus: document.getElementById('analysisStatus'), downloadConfigBtn: document.getElementById('downloadConfigBtn'), cursorCoords: document.getElementById('cursorCoords'), placeQuery: document.getElementById('placeQuery')
  };

  function setLayerStatus(message, error = false) { els.layerStatus.textContent = message; els.layerStatus.classList.toggle('error', error); }
  function findLayer(id) { return state.layers.find(item => item.id === id); }
  function normaliseUrl(value) { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } }
  function makeLayer(config) {
    if (config.type === 'xyz') return L.tileLayer(config.url, { maxZoom: config.maxZoom || 19, opacity: config.opacity ?? .85, attribution: config.attribution || 'Teselas públicas' });
    return L.tileLayer.wms(config.service, { layers: config.layerName, format: config.format || 'image/png', transparent: config.transparent !== false, version: '1.3.0', opacity: config.opacity ?? .8, attribution: config.attribution || 'Servicio WMS público', zIndex: 420 });
  }
  function addLayer(config) {
    const existing = findLayer(config.id);
    if (existing) { existing.visible = true; existing.leafletLayer.addTo(map); render(); setLayerStatus(`«${existing.label}» ya estaba preparada y vuelve a estar visible.`); return existing; }
    const layer = makeLayer(config);
    const item = { ...config, leafletLayer: layer, visible: true, opacity: config.opacity ?? .8, loaded: false, errorTimer: null };
    layer.on('loading', () => { els.mapStatus.textContent = `Cargando ${item.label}…`; });
    layer.on('tileload load', () => { item.loaded = true; if (item.errorTimer) clearTimeout(item.errorTimer); els.mapStatus.textContent = `${state.layers.length} capa${state.layers.length === 1 ? '' : 's'} adicional${state.layers.length === 1 ? '' : 'es'} activa${state.layers.length === 1 ? '' : 's'}.`; });
    layer.on('tileerror', () => { if (item.loaded || item.errorTimer) return; item.errorTimer = setTimeout(() => { if (!item.loaded) setLayerStatus(`«${item.label}» no ha entregado teselas en esta vista. Puede requerir otra escala o haber cambiado su servicio.`, true); }, 2800); });
    layer.addTo(map); state.layers.push(item); updateZIndexes(); render(); setLayerStatus(`Añadida «${item.label}».`); return item;
  }
  function removeLayer(id) { const index = state.layers.findIndex(item => item.id === id); if (index < 0) return; const [item] = state.layers.splice(index, 1); item.leafletLayer.remove(); if (state.swipeLayerId === id) state.swipeLayerId = state.layers[0]?.id || ''; updateZIndexes(); render(); setLayerStatus(`Retirada «${item.label}».`); }
  function toggleLayer(id, visible) { const item = findLayer(id); if (!item) return; item.visible = visible; if (visible) item.leafletLayer.addTo(map); else item.leafletLayer.remove(); applySwipe(); render(); }
  function updateOpacity(id, value) { const item = findLayer(id); if (!item) return; item.opacity = Number(value); item.leafletLayer.setOpacity(item.opacity); const output = document.querySelector(`[data-opacity-output="${CSS.escape(id)}"]`); if (output) output.textContent = `${Math.round(item.opacity * 100)}%`; }
  function moveLayer(id, direction) { const index = state.layers.findIndex(item => item.id === id), next = index + direction; if (index < 0 || next < 0 || next >= state.layers.length) return; [state.layers[index], state.layers[next]] = [state.layers[next], state.layers[index]]; updateZIndexes(); render(); }
  function updateZIndexes() { state.layers.forEach((item, index) => item.leafletLayer.setZIndex(420 + index)); }
  function applySwipe() { const selected = findLayer(state.swipeLayerId); state.layers.forEach(item => { const container = item.leafletLayer.getContainer?.(); if (!container) return; container.style.clipPath = state.swipeEnabled && selected && item.id === selected.id && item.visible ? `inset(0 0 0 ${state.swipePosition}%)` : ''; }); const visible = Boolean(state.swipeEnabled && selected?.visible); els.swipeLine.hidden = !visible; els.swipeLine.style.left = `${state.swipePosition}%`; }
  function updateSwipeOptions() { const current = state.swipeLayerId; els.swipeLayer.replaceChildren(); if (!state.layers.length) { const option = document.createElement('option'); option.value = ''; option.textContent = 'Añade una capa primero'; els.swipeLayer.appendChild(option); state.swipeLayerId = ''; } else { state.layers.forEach(item => { const option = document.createElement('option'); option.value = item.id; option.textContent = item.label; els.swipeLayer.appendChild(option); }); state.swipeLayerId = state.layers.some(item => item.id === current) ? current : state.layers[state.layers.length - 1].id; els.swipeLayer.value = state.swipeLayerId; } applySwipe(); }
  function renderCatalog() { els.catalog.replaceChildren(); const filter = state.catalogFilter.toLocaleLowerCase(); let group = ''; catalog.filter(config => !filter || `${config.label} ${config.short} ${config.group}`.toLocaleLowerCase().includes(filter)).forEach(config => { if (group !== config.group) { group = config.group; const heading = document.createElement('div'); heading.className = 'catalog-group'; heading.textContent = group; els.catalog.appendChild(heading); } const wrapper = document.createElement('div'); wrapper.className = `catalog-item${findLayer(config.id) ? ' is-added' : ''}`; const text = document.createElement('div'); const title = document.createElement('b'); title.textContent = config.label; const detail = document.createElement('small'); detail.textContent = config.short; text.append(title, detail); const button = document.createElement('button'); button.type = 'button'; button.textContent = findLayer(config.id) ? 'Mostrar' : 'Añadir'; button.addEventListener('click', () => addLayer(config)); wrapper.append(text, button); els.catalog.appendChild(wrapper); }); if (!els.catalog.children.length) { const empty = document.createElement('div'); empty.className = 'empty-card'; empty.textContent = 'No hay coincidencias en el catálogo.'; els.catalog.appendChild(empty); } }
  function renderActiveLayers() { els.activeLayers.replaceChildren(); if (!state.layers.length) { const empty = document.createElement('div'); empty.className = 'empty-card'; empty.textContent = 'No hay capas adicionales activas.'; els.activeLayers.appendChild(empty); } state.layers.forEach((item, index) => { const row = document.createElement('div'); row.className = 'layer-row'; const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.checked = item.visible; checkbox.setAttribute('aria-label', `Visibilidad de ${item.label}`); checkbox.addEventListener('change', () => toggleLayer(item.id, checkbox.checked)); const name = document.createElement('div'); name.className = 'layer-name'; const title = document.createElement('b'); title.textContent = item.label; const detail = document.createElement('small'); detail.textContent = item.type === 'xyz' ? item.url : `${item.service} · ${item.layerName}`; name.append(title, detail); const opacity = document.createElement('label'); opacity.className = 'opacity'; opacity.innerHTML = '<span>Opacidad</span>'; const range = document.createElement('input'); range.type = 'range'; range.min = 0; range.max = 1; range.step = .01; range.value = item.opacity; range.setAttribute('aria-label', `Opacidad de ${item.label}`); const output = document.createElement('output'); output.dataset.opacityOutput = item.id; output.textContent = `${Math.round(item.opacity * 100)}%`; opacity.append(range, output); range.addEventListener('input', () => updateOpacity(item.id, range.value)); const actions = document.createElement('div'); actions.className = 'row-actions'; [['↑', -1], ['↓', 1], ['×', null]].forEach(([label, direction]) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'tiny'; button.textContent = label; button.addEventListener('click', () => direction === null ? removeLayer(item.id) : moveLayer(item.id, direction)); actions.appendChild(button); }); actions.children[0].disabled = index === 0; actions.children[1].disabled = index === state.layers.length - 1; row.append(checkbox, name, opacity, actions); els.activeLayers.appendChild(row); }); }
  function render() { els.layerCount.textContent = `${state.layers.length} activa${state.layers.length === 1 ? '' : 's'}`; els.downloadConfigBtn.disabled = !state.layers.length; renderCatalog(); renderActiveLayers(); updateSwipeOptions(); const labels = state.layers.filter(item => item.visible).map(item => item.label); els.sourceStatus.textContent = labels.length ? `${labels.length} capa${labels.length === 1 ? '' : 's'} · ${labels.slice(0, 2).join(' · ')}` : 'OSM · IGN · SCUAM'; }
  function selectTab(tabId) { ['layersTab', 'optionsTab', 'analysisTab'].forEach(id => { const button = document.getElementById(id); const panel = document.getElementById(button.getAttribute('aria-controls')); const active = id === tabId; button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); panel.hidden = !active; }); }
  function updateImageFilter() { const b = document.getElementById('brightnessRange').value, c = document.getElementById('contrastRange').value, s = document.getElementById('saturationRange').value; document.getElementById('map').style.filter = `brightness(${b}%) contrast(${c}%) saturate(${s}%)`; document.getElementById('brightnessOutput').textContent = `${b}%`; document.getElementById('contrastOutput').textContent = `${c}%`; document.getElementById('saturationOutput').textContent = `${s}%`; }
  function resetImage() { ['brightnessRange', 'contrastRange', 'saturationRange'].forEach(id => { document.getElementById(id).value = 100; }); updateImageFilter(); }
  function downloadConfig() { const payload = { tool: 'Cartotecnia Next', generatedAt: new Date().toISOString(), center: map.getCenter(), zoom: map.getZoom(), layers: state.layers.map(({ id, label, group, type, service, layerName, url, opacity, visible, attribution }) => ({ id, label, group, type, service, layer: layerName, url, opacity, visible, attribution })) }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'cartotecnia-next-configuracion.json'; link.click(); URL.revokeObjectURL(link.href); els.analysisStatus.textContent = 'Configuración descargada.'; }

  els.catalogFilter.addEventListener('input', () => { state.catalogFilter = els.catalogFilter.value; renderCatalog(); });
  els.customType.addEventListener('change', () => { els.customNameField.hidden = els.customType.value !== 'wms'; els.customName.required = els.customType.value === 'wms'; els.customUrl.placeholder = els.customType.value === 'wms' ? 'https://servidor.example/wms' : 'https://servidor.example/{z}/{x}/{y}.png'; });
  els.customForm.addEventListener('submit', event => { event.preventDefault(); const url = normaliseUrl(els.customUrl.value.trim()); if (!url) { setLayerStatus('Escribe una URL http:// o https:// válida.', true); return; } if (els.customType.value === 'wms' && !els.customName.value.trim()) { setLayerStatus('Para un WMS indica también el nombre de la capa.', true); return; } const label = els.customLabel.value.trim() || els.customName.value.trim() || 'Teselas personalizadas'; addLayer(els.customType.value === 'wms' ? { id: `custom-${Date.now()}`, label, short: 'WMS indicado por el usuario', type: 'wms', service: url, layerName: els.customName.value.trim(), format: 'image/png', transparent: true, attribution: 'WMS indicado por el usuario' } : { id: `custom-${Date.now()}`, label, short: 'XYZ indicado por el usuario', type: 'xyz', url, attribution: 'XYZ indicado por el usuario' }); els.customForm.reset(); els.customNameField.hidden = false; els.customName.required = true; });
  els.swipeToggle.addEventListener('change', () => { state.swipeEnabled = els.swipeToggle.checked; applySwipe(); }); els.swipeLayer.addEventListener('change', () => { state.swipeLayerId = els.swipeLayer.value; applySwipe(); }); els.swipeRange.addEventListener('input', () => { state.swipePosition = Number(els.swipeRange.value); els.swipeOutput.textContent = `${state.swipePosition}%`; applySwipe(); });
  document.querySelectorAll('.tab').forEach(button => button.addEventListener('click', () => selectTab(button.id)));
  document.getElementById('scaleToggle').addEventListener('change', event => { if (event.target.checked) scale.addTo(map); else scale.remove(); }); document.getElementById('coordsToggle').addEventListener('change', event => { els.cursorCoords.hidden = !event.target.checked; }); document.getElementById('northToggle').addEventListener('change', event => { state.northLock = event.target.checked; if (state.northLock) map.setView(map.getCenter(), map.getZoom()); }); document.getElementById('navigationToggle').addEventListener('change', event => { if (event.target.checked) { map.dragging.enable(); map.scrollWheelZoom.enable(); } else { map.dragging.disable(); map.scrollWheelZoom.disable(); } }); document.getElementById('labelsToggle').addEventListener('change', event => { if (event.target.checked) baseLabels.addTo(map); else baseLabels.remove(); });
  ['brightnessRange', 'contrastRange', 'saturationRange'].forEach(id => document.getElementById(id).addEventListener('input', updateImageFilter)); document.getElementById('resetImageBtn').addEventListener('click', resetImage);
  function setView(center, zoom, title) { map.setView(center, zoom); if (title) els.mapTitle.textContent = title; }
  document.getElementById('spainBtn').addEventListener('click', () => map.fitBounds([[35.95, -9.4], [43.9, 4.5]], { padding: [20, 20] })); document.getElementById('madridBtn').addEventListener('click', () => setView([40.4168, -3.7038], 11, 'Madrid · vista de detalle')); document.getElementById('homeBtn').addEventListener('click', () => setView(homeView.center, homeView.zoom, 'Vista general de España')); document.getElementById('northBtn').addEventListener('click', () => map.setView(map.getCenter(), map.getZoom())); document.getElementById('locateBtn').addEventListener('click', () => map.locate({ setView: true, maxZoom: 14 })); map.on('locationfound', event => { L.circleMarker(event.latlng, { radius: 7, color: '#62ddb0', fillColor: '#62ddb0', fillOpacity: .85 }).addTo(map).bindPopup('Tu ubicación aproximada').openPopup(); }); map.on('locationerror', () => { els.analysisStatus.textContent = 'El navegador no ha permitido obtener la ubicación.'; selectTab('analysisTab'); });
  document.getElementById('fullscreenBtn').addEventListener('click', () => { const element = document.getElementById('map'); if (document.fullscreenElement) document.exitFullscreen?.(); else element.requestFullscreen?.(); });
  document.getElementById('clearLayersBtn').addEventListener('click', () => { state.layers.forEach(item => item.leafletLayer.remove()); state.layers = []; state.swipeLayerId = ''; render(); setLayerStatus('Se han retirado las capas adicionales.'); }); els.downloadConfigBtn.addEventListener('click', downloadConfig);
  map.on('mousemove', event => { const text = `${event.latlng.lat.toFixed(5)}, ${event.latlng.lng.toFixed(5)}`; els.cursorCoords.textContent = text; }); map.on('click', event => { state.clicked = event.latlng; const text = `${event.latlng.lat.toFixed(6)}, ${event.latlng.lng.toFixed(6)}`; els.clickedCoords.textContent = text; els.copyCoordsBtn.disabled = false; els.analysisStatus.textContent = 'Posición consultada en el mapa.'; L.popup().setLatLng(event.latlng).setContent(`<b>Coordenadas</b><br>${text}`).openOn(map); }); els.copyCoordsBtn.addEventListener('click', async () => { if (!state.clicked) return; const text = `${state.clicked.lat.toFixed(6)}, ${state.clicked.lng.toFixed(6)}`; try { await navigator.clipboard.writeText(text); els.analysisStatus.textContent = 'Coordenadas copiadas.'; } catch { els.analysisStatus.textContent = text; } });
  const sourcesDialog = document.getElementById('sourcesDialog'); document.getElementById('sourcesBtn').addEventListener('click', () => sourcesDialog.showModal()); document.getElementById('closeSourcesBtn').addEventListener('click', () => sourcesDialog.close()); document.getElementById('tourBtn').addEventListener('click', () => { addLayer(catalog[0]); selectTab('layersTab'); document.getElementById('map').scrollIntoView({ behavior: 'smooth', block: 'center' }); });
  CartografiaPlaceSearch(map, { input: document.getElementById('placeQuery'), button: document.getElementById('placeSearchButton'), results: document.getElementById('placeResults'), status: document.getElementById('placeStatus'), zoom: 13 });
  render(); resetImage();
})();
