(() => {
  'use strict';
  const map = L.map('map').setView([40.32, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
  const state = { input: null, output: null, layer: null, report: null };
  const els = { file: document.getElementById('file'), mode: document.getElementById('mode'), prefix: document.getElementById('prefix'), run: document.getElementById('runBtn'), clear: document.getElementById('clearBtn'), sample: document.getElementById('sampleBtn'), status: document.getElementById('status'), mapTitle: document.getElementById('mapTitle'), mapStatus: document.getElementById('mapStatus') };
  const colors = ['#75d6c4', '#8ab4f8', '#f7c86b', '#f78fb3', '#c7f464', '#d3a7ff'];
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const csvCell = value => `"${String(value ?? '').replace(/"/g, '""')}"`;
  function parts(geometry) { if (!geometry) return []; if (geometry.type === 'MultiPoint') return geometry.coordinates.map(coordinates => ({ type: 'Point', coordinates })); if (geometry.type === 'MultiLineString') return geometry.coordinates.map(coordinates => ({ type: 'LineString', coordinates })); if (geometry.type === 'MultiPolygon') return geometry.coordinates.map(coordinates => ({ type: 'Polygon', coordinates })); if (geometry.type === 'GeometryCollection') return geometry.geometries.flatMap(parts); return [geometry]; }
  function loadJson(file) { const reader = new FileReader(); reader.onload = () => { try { const json = JSON.parse(String(reader.result || '')); if (!json || json.type !== 'FeatureCollection' || !Array.isArray(json.features)) throw new Error('Se esperaba un FeatureCollection GeoJSON.'); state.input = json; els.run.disabled = false; setStatus(`${json.features.length} entidades cargadas. Pulsa «Explotar geometrías».`); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus('No se pudo leer el GeoJSON.', true); reader.readAsText(file); }
  function explode() { if (!state.input) return; const prefix = els.prefix.value || '_part_', output = [], stats = { sourceCount: state.input.features.length, splitCount: 0, partCount: 0 }; state.input.features.forEach((feature, parentIndex) => { const geometries = parts(feature.geometry); const isMultipart = geometries.length > 1 || feature.geometry?.type === 'GeometryCollection' || /^Multi/.test(feature.geometry?.type || ''); if (!isMultipart && els.mode.value === 'multi') return; if (isMultipart) stats.splitCount += 1; geometries.forEach((geometry, partIndex) => { stats.partCount += 1; output.push({ type: 'Feature', id: `${feature.id ?? parentIndex}-${partIndex + 1}`, geometry, properties: { ...(feature.properties || {}), [`${prefix}parent`]: parentIndex + 1, [`${prefix}index`]: partIndex + 1, [`${prefix}geometry`]: feature.geometry?.type || '' } }); }); }); state.output = { type: 'FeatureCollection', features: output }; stats.outputCount = output.length; stats.geometryTypes = [...new Set(output.map(feature => feature.geometry?.type).filter(Boolean))]; state.report = stats; renderMap(); renderReport(); setStatus(`${output.length} entidades generadas a partir de ${stats.splitCount} entidades multipartes.`); }
  function popup(feature) { const rows = Object.entries(feature.properties || {}).slice(0, 16).map(([key, value]) => `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(value)}</td></tr>`).join(''); return `<table class="popup-table">${rows || '<tr><td>Sin atributos</td></tr>'}</table>`; }
  function renderMap() { state.layer?.remove(); if (!state.output) return; state.layer = L.geoJSON(state.output, { style: feature => ({ color: colors[(Number(feature.properties?.[`${els.prefix.value || '_part_'}index`]) - 1) % colors.length] || colors[0], weight: 2, fillColor: colors[(Number(feature.properties?.[`${els.prefix.value || '_part_'}index`]) - 1) % colors.length] || colors[0], fillOpacity: .24 }), pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: colors[0], fillColor: colors[0], fillOpacity: .82 }), onEachFeature: (feature, layer) => layer.bindPopup(popup(feature)) }).addTo(map); const bounds = state.layer.getBounds(); if (bounds.isValid()) map.fitBounds(bounds.pad(.12)); els.mapTitle.textContent = 'Geometrías explotadas'; els.mapStatus.textContent = `${state.output.features.length} entidades visibles.`; }
  function renderReport() { const report = state.report; document.getElementById('sourceCount').textContent = format(report.sourceCount); document.getElementById('outputCount').textContent = format(report.outputCount); document.getElementById('splitCount').textContent = format(report.splitCount); document.getElementById('partCount').textContent = format(report.partCount); document.getElementById('geometryTypes').textContent = report.geometryTypes.join(', ') || '—'; document.getElementById('quality').textContent = report.outputCount ? 'Listo' : 'Sin salida'; document.getElementById('quality').className = report.outputCount ? 'quality ready' : 'quality warn'; ['geoBtn','csvBtn','reportBtn'].forEach(id => { document.getElementById(id).disabled = !report.outputCount; }); const fields = [...new Set(state.output.features.flatMap(feature => Object.keys(feature.properties || {})))], visible = fields.slice(0, 8); document.getElementById('tableWrap').innerHTML = report.outputCount ? `<table><thead><tr><th>ENTIDAD</th><th>GEOMETRÍA</th>${visible.map(field => `<th>${escapeHtml(field)}</th>`).join('')}</tr></thead><tbody>${state.output.features.slice(0, 18).map((feature, index) => `<tr><td>${index + 1}</td><td>${feature.geometry?.type || '—'}</td>${visible.map(field => `<td>${escapeHtml(feature.properties?.[field] ?? '')}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="table-caption">Se muestran hasta 18 entidades y 8 campos. El GeoJSON descargado conserva toda la salida.</p>` : '<p class="empty">No hay geometrías que exportar.</p>'; }
  function format(value) { return Number(value).toLocaleString('es-ES'); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportGeo() { download('geometrias-explotadas.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8'); }
  function exportCsv() { const fields = [...new Set(state.output.features.flatMap(feature => Object.keys(feature.properties || {})))], rows = [['feature_index','geometry_type', ...fields], ...state.output.features.map((feature, index) => [index + 1, feature.geometry?.type || '', ...fields.map(field => feature.properties?.[field] ?? '')])]; download('geometrias-explotadas.csv', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function exportReport() { download('informe-explode.json', JSON.stringify({ ...state.report, mode: els.mode.value, prefix: els.prefix.value, generatedAt: new Date().toISOString() }, null, 2), 'application/json;charset=utf-8'); }
  function sample() { state.input = { type: 'FeatureCollection', features: [{ type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [[-3.71,40.42],[-3.70,40.41],[-3.69,40.43]] }, properties: { grupo: 'muestras', nombre: 'Tres puntos' } }, { type: 'Feature', geometry: { type: 'MultiLineString', coordinates: [[[-3.75,40.40],[-3.68,40.44]],[[-3.74,40.43],[-3.67,40.40]]] }, properties: { grupo: 'transectos', nombre: 'Dos líneas' } }, { type: 'Feature', geometry: { type: 'GeometryCollection', geometries: [{ type: 'Point', coordinates: [-3.72,40.39] }, { type: 'LineString', coordinates: [[-3.72,40.39],[-3.70,40.37]] }] }, properties: { grupo: 'mixto', nombre: 'Colección' } }] }; els.run.disabled = false; explode(); setStatus('Ejemplo cargado y explotado: revisa los índices de origen.'); }
  els.file.addEventListener('change', event => { const file = event.target.files?.[0]; if (file) loadJson(file); }); els.sample.addEventListener('click', sample); els.run.addEventListener('click', explode); els.mode.addEventListener('change', () => { if (state.input) explode(); }); els.prefix.addEventListener('change', () => { if (state.input) explode(); }); els.clear.addEventListener('click', () => { state.input = null; state.output = null; state.report = null; state.layer?.remove(); state.layer = null; els.run.disabled = true; ['geoBtn','csvBtn','reportBtn'].forEach(id => { document.getElementById(id).disabled = true; }); document.getElementById('tableWrap').innerHTML = '<p class="empty">Ejecuta la transformación para revisar la salida.</p>'; els.mapTitle.textContent = 'Mapa base'; els.mapStatus.textContent = 'Mapa base listo.'; setStatus('Capa y salida limpiadas.'); }); document.getElementById('geoBtn').addEventListener('click', exportGeo); document.getElementById('csvBtn').addEventListener('click', exportCsv); document.getElementById('reportBtn').addEventListener('click', exportReport);
  CartografiaPlaceSearch(map, { input: document.getElementById('placeQuery'), button: document.getElementById('placeSearchButton'), results: document.getElementById('placeResults'), status: document.getElementById('placeStatus'), zoom: 13 });
})();
