(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { grid: null, result: null, map: null, layer: null };
  const exampleGrid = { rows: 10, cols: 12, values: [
    132,128,125,121,118,116,114,111,108,106,104,101,
    126,123,120,117,114,110,106,103,100,98,96,94,
    122,119,116,112,108,104,99,96,93,91,89,88,
    119,116,112,108,103,98,93,89,86,84,83,82,
    115,111,107,102,97,92,87,82,79,77,76,75,
    110,106,101,96,91,86,81,76,72,70,69,68,
    105,101,96,91,86,81,76,71,66,64,63,62,
    100,96,91,86,81,76,71,66,61,58,57,56,
    95,91,86,81,76,71,66,61,56,53,51,50,
    90,86,81,76,71,66,61,56,51,47,45,44
  ] };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function formatNumber(value, maximumFractionDigits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits }); }
  function exampleText() { return JSON.stringify(exampleGrid, null, 2); }
  function parseJsonGrid(input) { const rows = Number(input.rows); const cols = Number(input.cols); const values = Array.isArray(input.values) ? input.values : Array.isArray(input.data) ? input.data : null; if (!Number.isInteger(rows) || !Number.isInteger(cols) || !values) throw new Error('El JSON debe contener rows, cols y values.'); return { rows, cols, values }; }
  function parseText(text) {
    const clean = text.trim(); if (!clean) throw new Error('Introduce datos de elevación.');
    if (clean.startsWith('{') || clean.startsWith('[')) { const parsed = JSON.parse(clean); if (Array.isArray(parsed)) return parseRows(parsed); return parseJsonGrid(parsed); }
    const rows = clean.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => line.split(/[;,\t]+/).map((value) => Number(value.trim().replace(',', '.')))); return parseRows(rows);
  }
  function parseRows(rows) { if (!Array.isArray(rows) || rows.length < 3) throw new Error('La malla necesita al menos 3 filas.'); const cols = rows[0]?.length || 0; if (cols < 3 || cols > 200 || rows.length > 200) throw new Error('La malla debe tener entre 3 y 200 filas y columnas.'); const values = rows.flat(); if (rows.some((row) => !Array.isArray(row) || row.length !== cols)) throw new Error('Todas las filas deben tener el mismo número de columnas.'); return { rows: rows.length, cols, values }; }
  function sanitizeGrid(grid) { if (!Number.isInteger(grid.rows) || !Number.isInteger(grid.cols) || grid.rows < 3 || grid.cols < 3 || grid.rows > 200 || grid.cols > 200) throw new Error('La malla debe tener entre 3 y 200 filas y columnas.'); const values = grid.values.map((value) => value === null || value === '' || !Number.isFinite(Number(value)) ? null : Number(value)); if (values.length !== grid.rows * grid.cols) throw new Error(`Se esperaban ${grid.rows * grid.cols} valores y se recibieron ${values.length}.`); if (values.filter((value) => value !== null).length < 3) throw new Error('La malla debe contener al menos tres elevaciones válidas.'); return { rows: grid.rows, cols: grid.cols, values }; }
  function idx(row, col) { return row * state.grid.cols + col; }
  function neighbours(row, col) { const result = []; for (let dr = -1; dr <= 1; dr += 1) for (let dc = -1; dc <= 1; dc += 1) { if (!dr && !dc) continue; const r = row + dr; const c = col + dc; if (r >= 0 && r < state.grid.rows && c >= 0 && c < state.grid.cols) result.push({ row: r, col: c, distance: Math.hypot(dr, dc) }); } return result; }
  function directionName(row, col, downstream) { if (downstream < 0) return 'salida'; const targetRow = Math.floor(downstream / state.grid.cols); const targetCol = downstream % state.grid.cols; const angle = Math.atan2(targetCol - col, -(targetRow - row)) * 180 / Math.PI; const normalized = (angle + 360) % 360; const names = ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO']; return names[Math.round(normalized / 45) % 8]; }
  function calculate() {
    const grid = sanitizeGrid(parseText($('source').value)); state.grid = grid; const cellSize = Math.max(1, Math.min(10000, Number($('cellSize').value) || 100)); $('cellSize').value = cellSize; const threshold = Math.max(1, Math.min(1000000, Math.floor(Number($('threshold').value) || 8))); $('threshold').value = threshold;
    const valid = grid.values.map((value, index) => value === null ? -1 : index).filter((index) => index >= 0); const downstream = Array(grid.values.length).fill(-1); valid.forEach((index) => { const row = Math.floor(index / grid.cols); const col = index % grid.cols; const elevation = grid.values[index]; let bestDrop = 0; let best = -1; neighbours(row, col).forEach((candidate) => { const target = idx(candidate.row, candidate.col); const targetValue = grid.values[target]; if (targetValue === null) return; const drop = (elevation - targetValue) / candidate.distance; if (drop > bestDrop) { bestDrop = drop; best = target; } }); downstream[index] = best; });
    const accumulation = Array(grid.values.length).fill(0); valid.forEach((index) => { accumulation[index] = 1; }); valid.slice().sort((a, b) => grid.values[b] - grid.values[a]).forEach((index) => { if (downstream[index] >= 0) accumulation[downstream[index]] += accumulation[index]; });
    const minElevation = valid.reduce((minimum, index) => Math.min(minimum, grid.values[index]), Infinity); const maxElevation = valid.reduce((maximum, index) => Math.max(maximum, grid.values[index]), -Infinity); const cellAreaHa = (cellSize * cellSize) / 10000; const streams = valid.filter((index) => accumulation[index] >= threshold); const outlets = valid.filter((index) => downstream[index] < 0); const maxAccumulation = valid.reduce((maximum, index) => Math.max(maximum, accumulation[index]), 0); state.result = { cellSize, threshold, downstream, accumulation, valid, streams, outlets, minElevation, maxElevation, cellAreaHa, maxAccumulation, west: Number($('west').value) || 0, south: Number($('south').value) || 0 }; $('summary').hidden = false; $('tablePanel').hidden = false; $('gridLabel').textContent = `${grid.rows} × ${grid.cols}`; $('validCount').textContent = valid.length.toLocaleString('es-ES'); $('cellArea').textContent = `${formatNumber(cellAreaHa, 3)} ha`; $('maxAccum').textContent = `${maxAccumulation.toLocaleString('es-ES')} celdas`; $('streamCount').textContent = streams.length.toLocaleString('es-ES'); $('outletCount').textContent = outlets.length.toLocaleString('es-ES'); $('elevationRange').textContent = `${formatNumber(minElevation, 1)}–${formatNumber(maxElevation, 1)}`; $('interpretation').textContent = `El flujo D8 identifica ${streams.length.toLocaleString('es-ES')} celdas por encima del umbral de ${threshold.toLocaleString('es-ES')} contribuciones y ${outlets.length.toLocaleString('es-ES')} salidas locales. La acumulación máxima es ${maxAccumulation.toLocaleString('es-ES')} celdas.`; $('geojsonBtn').disabled = $('csvBtn').disabled = false; renderTable(); renderMap(); setStatus(`${grid.rows} × ${grid.cols} celdas procesadas; ${streams.length} superan el umbral de cauce.`); }
  function cellFeature(index) { const row = Math.floor(index / state.grid.cols); const col = index % state.grid.cols; const cell = state.result; const midLat = cell.south + state.grid.rows * cell.cellSize / 110540 / 2; const lonStep = cell.cellSize / (111320 * Math.max(.15, Math.cos(midLat * Math.PI / 180))); const latStep = cell.cellSize / 110540; const minLon = cell.west + col * lonStep; const minLat = cell.south + row * latStep; const maxLon = minLon + lonStep; const maxLat = minLat + latStep; const isStream = cell.accumulation[index] >= cell.threshold; const direction = directionName(row, col, cell.downstream[index]); return { type: 'Feature', properties: { row: row + 1, column: col + 1, elevation: state.grid.values[index], flow_accum_cells: cell.accumulation[index], flow_area_ha: Number((cell.accumulation[index] * cell.cellAreaHa).toFixed(6)), downstream_index: cell.downstream[index] < 0 ? null : cell.downstream[index], direction, stream: isStream, threshold_cells: cell.threshold }, geometry: { type: 'Polygon', coordinates: [[[minLon, minLat], [maxLon, minLat], [maxLon, maxLat], [minLon, maxLat], [minLon, minLat]]] } }; }
  function renderTable() { const rows = state.result.valid.slice().sort((a, b) => state.result.accumulation[b] - state.result.accumulation[a]).slice(0, 40).map((index) => { const row = Math.floor(index / state.grid.cols); const col = index % state.grid.cols; const direction = directionName(row, col, state.result.downstream[index]); const stream = state.result.accumulation[index] >= state.result.threshold ? 'Sí' : 'No'; return `<tr><td>${row + 1}</td><td>${col + 1}</td><td>${formatNumber(state.grid.values[index], 2)}</td><td>${state.result.accumulation[index]}</td><td>${formatNumber(state.result.accumulation[index] * state.result.cellAreaHa, 3)}</td><td>${direction}</td><td>${stream}</td></tr>`; }).join(''); $('resultsBody').innerHTML = rows; }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); const features = state.result.valid.filter((index) => !$('streamOnly').checked || state.result.accumulation[index] >= state.result.threshold).map(cellFeature); const maxLog = Math.log1p(state.result.maxAccumulation); state.layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: (feature) => { const ratio = maxLog ? Math.log1p(feature.properties.flow_accum_cells) / maxLog : 0; const isStream = feature.properties.stream; return { color: isStream ? '#ef7c61' : '#bde9ff', weight: isStream ? 1.3 : .45, opacity: isStream ? .95 : .35, fillColor: isStream ? '#ef7c61' : ratio < .35 ? '#c9ecff' : ratio < .72 ? '#50a9d8' : '#164d9b', fillOpacity: isStream ? .78 : .5 }; }, onEachFeature: (feature, layer) => layer.bindPopup(`<strong>Fila ${feature.properties.row}, columna ${feature.properties.column}</strong><div class="popup-stat">Elevación: ${feature.properties.elevation} · acumulación: ${feature.properties.flow_accum_cells} celdas · dirección: ${feature.properties.direction}</div>`) }).addTo(state.map); const rows = state.grid.rows; const cols = state.grid.cols; const cell = state.result; const latStep = cell.cellSize / 110540; const lonStep = cell.cellSize / (111320 * Math.max(.15, Math.cos((cell.south + rows * latStep / 2) * Math.PI / 180))); state.map.fitBounds([[cell.south, cell.west], [cell.south + rows * latStep, cell.west + cols * lonStep]], { padding: [24, 24], maxZoom: 16 }); }
  function loadGrid(grid, filename) { state.grid = sanitizeGrid(grid); $('source').value = JSON.stringify({ rows: state.grid.rows, cols: state.grid.cols, values: state.grid.values }, null, 2); $('fileName').textContent = filename; calculate(); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function exportGeoJSON() { if (!state.result) return; download('flow-accumulation-lab.geojson', JSON.stringify({ type: 'FeatureCollection', features: state.result.valid.map(cellFeature) }, null, 2), 'application/geo+json'); }
  function downloadCsv() { if (!state.result) return; const rows = [['row', 'column', 'elevation', 'flow_accum_cells', 'flow_area_ha', 'downstream_index', 'direction', 'stream'], ...state.result.valid.map((index) => { const row = Math.floor(index / state.grid.cols); const col = index % state.grid.cols; return [row + 1, col + 1, state.grid.values[index], state.result.accumulation[index], state.result.accumulation[index] * state.result.cellAreaHa, state.result.downstream[index] < 0 ? '' : state.result.downstream[index], directionName(row, col, state.result.downstream[index]), state.result.accumulation[index] >= state.result.threshold]; })]; download('flow-accumulation-lab.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function reset() { state.grid = null; state.result = null; $('source').value = ''; $('fileInput').value = ''; $('fileName').textContent = 'Ningún archivo seleccionado'; $('summary').hidden = true; $('tablePanel').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = true; state.layer?.remove(); state.layer = null; setStatus('Introduce una malla regular o usa el ejemplo.'); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('source').value = exampleText(); $('exampleBtn').addEventListener('click', () => { try { loadGrid(exampleGrid, 'Ejemplo · 10 × 12'); } catch (error) { setStatus(error.message, true); } }); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', () => { try { calculate(); } catch (error) { setStatus(error.message || 'No se pudo calcular la acumulación.', true); } }); $('streamOnly').addEventListener('change', renderMap); ['cellSize', 'threshold', 'west', 'south'].forEach((id) => $(id).addEventListener('change', () => { if (state.grid) { try { calculate(); } catch (error) { setStatus(error.message, true); } } })); $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 30 * 1024 * 1024) { setStatus('El archivo supera 30 MB; no se abre en esta herramienta local.', true); return; } try { const text = await file.text(); loadGrid(parseText(text), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer la malla.', true); } }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', downloadCsv);
  initMap();
})();
