(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { source: null, output: null, reports: [], map: null, layer: null };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function number(value) { const parsed = Number(String(value ?? '').replace(',', '.')); return Number.isFinite(parsed) ? parsed : null; }
  function parseSource(value) { const parsed = JSON.parse(value.trim()), features = parsed.type === 'FeatureCollection' ? parsed.features : parsed.type === 'Feature' ? [parsed] : [{ type: 'Feature', properties: {}, geometry: parsed }]; const valid = features.filter(feature => feature?.geometry?.type); if (!valid.length) throw new Error('No se encontraron entidades GeoJSON con geometría.'); return { parsed, features: valid }; }
  function allCoordinates(geometry, visit) { if (!geometry) return; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).forEach(item => allCoordinates(item, visit)); const walk = value => { if (Array.isArray(value) && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) visit([Number(value[0]), Number(value[1])]); else if (Array.isArray(value)) value.forEach(walk); }; walk(geometry.coordinates); }
  function extent(features) { const coords = []; features.forEach(feature => allCoordinates(feature.geometry, coordinate => coords.push(coordinate))); if (!coords.length) throw new Error('La capa no contiene coordenadas válidas.'); const xs = coords.map(pair => pair[0]), ys = coords.map(pair => pair[1]); return { minLon: Math.min(...xs), minLat: Math.min(...ys), maxLon: Math.max(...xs), maxLat: Math.max(...ys) }; }
  function inside(point, box) { return point[0] >= box.minLon && point[0] <= box.maxLon && point[1] >= box.minLat && point[1] <= box.maxLat; }
  function intersect(a, b, edge, value) { const ratio = edge === 'x' ? (value - a[0]) / (b[0] - a[0]) : (value - a[1]) / (b[1] - a[1]); return edge === 'x' ? [value, a[1] + (b[1] - a[1]) * ratio] : [a[0] + (b[0] - a[0]) * ratio, value]; }
  function clipLineSegment(a, b, box) { const dx = b[0] - a[0], dy = b[1] - a[1]; let t0 = 0, t1 = 1; const checks = [[-dx, a[0] - box.minLon], [dx, box.maxLon - a[0]], [-dy, a[1] - box.minLat], [dy, box.maxLat - a[1]]]; for (const [p, q] of checks) { if (p === 0 && q < 0) return null; if (p !== 0) { const t = q / p; if (p < 0) { if (t > t1) return null; if (t > t0) t0 = t; } else { if (t < t0) return null; if (t < t1) t1 = t; } } } return [[a[0] + dx * t0, a[1] + dy * t0], [a[0] + dx * t1, a[1] + dy * t1]]; }
  function clipLine(coords, box) { const parts = [], current = []; for (let index = 1; index < coords.length; index++) { const segment = clipLineSegment(coords[index - 1], coords[index], box); if (!segment) { if (current.length > 1) parts.push(current.splice(0)); continue; } const [start, end] = segment; if (!current.length) current.push(start, end); else if (Math.abs(current[current.length - 1][0] - start[0]) < 1e-10 && Math.abs(current[current.length - 1][1] - start[1]) < 1e-10) current.push(end); else { if (current.length > 1) parts.push(current.splice(0)); current.push(start, end); } } if (current.length > 1) parts.push(current); return parts; }
  function clipRing(ring, box) { let points = ring.slice(0, -1); const edges = [['x', box.minLon, point => point[0] >= box.minLon], ['x', box.maxLon, point => point[0] <= box.maxLon], ['y', box.minLat, point => point[1] >= box.minLat], ['y', box.maxLat, point => point[1] <= box.maxLat]]; for (const [edge, value, isInside] of edges) { const result = []; for (let index = 0; index < points.length; index++) { const current = points[index], previous = points[(index + points.length - 1) % points.length], currentInside = isInside(current), previousInside = isInside(previous); if (currentInside !== previousInside) result.push(intersect(previous, current, edge, value)); if (currentInside) result.push(current); } points = result; if (!points.length) break; } return points.length >= 3 ? points.concat([points[0]]) : null; }
  function clipGeometry(geometry, box) { if (!geometry) return null; if (geometry.type === 'Point') return inside(geometry.coordinates, box) ? geometry : null; if (geometry.type === 'MultiPoint') { const coordinates = geometry.coordinates.filter(point => inside(point, box)); return coordinates.length ? { type: 'MultiPoint', coordinates } : null; } if (geometry.type === 'LineString') { const parts = clipLine(geometry.coordinates, box); return parts.length === 1 ? { type: 'LineString', coordinates: parts[0] } : parts.length ? { type: 'MultiLineString', coordinates: parts } : null; } if (geometry.type === 'MultiLineString') { const parts = geometry.coordinates.flatMap(line => clipLine(line, box)); return parts.length ? { type: 'MultiLineString', coordinates: parts } : null; } if (geometry.type === 'Polygon') { const rings = geometry.coordinates.map(ring => clipRing(ring, box)).filter(Boolean); return rings.length ? { type: 'Polygon', coordinates: rings } : null; } if (geometry.type === 'MultiPolygon') { const polygons = geometry.coordinates.map(polygon => polygon.map(ring => clipRing(ring, box)).filter(Boolean)).filter(polygon => polygon.length); return polygons.length ? { type: 'MultiPolygon', coordinates: polygons } : null; } return null; }
  function vertexCount(geometry) { let count = 0; allCoordinates(geometry, () => count += 1); return count; }
  function getBox() { const values = ['minLon', 'minLat', 'maxLon', 'maxLat'].map(id => number($(id).value)); if (values.some(value => value === null)) throw new Error('Completa las cuatro coordenadas de la caja.'); const [minLon, minLat, maxLon, maxLat] = values; if (minLon >= maxLon || minLat >= maxLat) throw new Error('La caja debe tener mínimo menor que máximo.'); return { minLon, minLat, maxLon, maxLat }; }

  function calculate() { try { const parsed = parseSource($('source').value), box = getBox(), reports = [], output = []; parsed.features.forEach((feature, index) => { const clipped = clipGeometry(feature.geometry, box), originalVertices = vertexCount(feature.geometry), clippedVertices = clipped ? vertexCount(clipped) : 0, status = !clipped ? 'descartada' : JSON.stringify(clipped) === JSON.stringify(feature.geometry) ? 'sin cambios' : 'recortada'; reports.push({ index, feature, status, originalVertices, clippedVertices }); if (clipped) output.push({ ...feature, geometry: clipped, properties: { ...(feature.properties || {}), _clip_status: status, _clip_original_index: index + 1 } }); }); state.source = parsed; state.output = { type: 'FeatureCollection', features: output }; state.reports = reports; renderMap(box); renderTable(); updateStats(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; const changed = reports.filter(report => report.status === 'recortada').length; setStatus(`${output.length} de ${parsed.features.length} entidades conservadas; ${changed} geometrías han cambiado.`); $('quality').textContent = changed ? 'Recortada' : 'Sin cambios'; $('quality').style.background = changed ? '#143747' : '#342c18'; $('quality').style.borderColor = changed ? '#346275' : '#725c2a'; $('quality').style.color = changed ? 'var(--accent)' : '#f4c56b'; } catch (error) { setStatus(error.message || 'No se pudo recortar la capa.', true); } }
  function renderMap(box) { if (!state.layer) return; state.layer.clearLayers(); const sourceLayer = L.geoJSON(state.source, { style: { color: '#8ab4f8', weight: 2, fillColor: '#8ab4f8', fillOpacity: .14 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#8ab4f8', fillColor: '#8ab4f8', fillOpacity: .7 }) }).addTo(state.layer); L.rectangle([[box.minLat, box.minLon], [box.maxLat, box.maxLon]], { color: '#f7c86b', weight: 2, dashArray: '6 5', fill: false }).addTo(state.layer); L.geoJSON(state.output, { style: { color: '#ff9d6c', weight: 3, fillColor: '#ff9d6c', fillOpacity: .32 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#ff9d6c', fillColor: '#ff9d6c', fillOpacity: .9 }) }).addTo(state.layer); const bounds = L.latLngBounds([[box.minLat, box.minLon], [box.maxLat, box.maxLon]]); state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function renderTable() { $('tableWrap').innerHTML = `<table><thead><tr><th>#</th><th>ENTIDAD</th><th>ESTADO</th><th>VÉRTICES</th><th>SALIDA</th></tr></thead><tbody>${state.reports.map(report => `<tr><td>${report.index + 1}</td><td>${esc(report.feature.properties?.nombre || report.feature.properties?.name || `Entidad ${report.index + 1}`)}</td><td><span class="row-status ${report.status === 'descartada' ? 'is-dropped' : report.status === 'recortada' ? 'is-clipped' : 'is-unchanged'}">${report.status}</span></td><td>${report.originalVertices}</td><td>${report.clippedVertices}</td></tr>`).join('')}</tbody></table>`; }
  function updateStats() { $('sourceCount').textContent = state.reports.length; $('outputCount').textContent = state.output.features.length; $('droppedCount').textContent = state.reports.filter(report => report.status === 'descartada').length; $('changedCount').textContent = state.reports.filter(report => report.status === 'recortada').length; $('vertexCount').textContent = state.reports.reduce((sum, report) => sum + report.clippedVertices, 0); $('resultBadge').textContent = `${state.output.features.length}/${state.reports.length}`; }
  function initMap() { if (!window.L) return; state.map = L.map('map').setView([40.42, -3.70], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function csvCell(value) { const text = String(value ?? ''); return `"${text.replace(/"/g, '""')}"`; }
  function exportCsv() { const lines = ['indice,entidad,estado,vertices_entrada,vertices_salida']; state.reports.forEach(report => lines.push([report.index + 1, report.feature.properties?.nombre || report.feature.properties?.name || `Entidad ${report.index + 1}`, report.status, report.originalVertices, report.clippedVertices].map(csvCell).join(','))); download('informe-recorte.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function exportGeoJSON() { download('capa-recortada.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8'); }
  $('calculateBtn').addEventListener('click', calculate); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; calculate(); }); $('extentBtn').addEventListener('click', () => { try { const parsed = parseSource($('source').value), box = extent(parsed.features); $('minLon').value = box.minLon.toFixed(6); $('minLat').value = box.minLat.toFixed(6); $('maxLon').value = box.maxLon.toFixed(6); $('maxLat').value = box.maxLat.toFixed(6); setStatus('Extensión de la capa aplicada; pulsa «Recortar capa».'); } catch (error) { setStatus(error.message || 'No se pudo calcular la extensión.', true); } });
  $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); try { const box = extent(parseSource($('source').value).features); $('minLon').value = box.minLon.toFixed(6); $('minLat').value = box.minLat.toFixed(6); $('maxLon').value = box.maxLon.toFixed(6); $('maxLat').value = box.maxLat.toFixed(6); } catch {} calculate(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', exportCsv); initMap(); calculate();
})();
