(() => {
  const $=id=>document.getElementById(id), map=L.map('map').setView([40.5,-3.7],8), gridGroup=L.layerGroup().addTo(map); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map); CartografiaPlaceSearch(map,{input:$('placeQuery'),button:$('placeSearchButton'),results:$('placeResults'),status:$('placeStatus')}); let collection=null;
  const inputs=['minLon','minLat','maxLon','maxLat','cols','rows','order'].map(id=>$(id));
  function number(id){return Number($(id).value)}
  function buildGrid(minLon,minLat,maxLon,maxLat,cols,rows,order){const width=(maxLon-minLon)/cols,height=(maxLat-minLat)/rows,features=[];for(let r=0;r<rows;r++){const logicalRow=order==='south'?r:rows-1-r, south=minLat+logicalRow*height,north=south+height;for(let c=0;c<cols;c++){const west=minLon+c*width,east=west+width,id=`R${String(r+1).padStart(2,'0')}C${String(c+1).padStart(2,'0')}`;features.push({type:'Feature',properties:{id,row:r+1,column:c+1,min_lon:west,min_lat:south,max_lon:east,max_lat:north,centroid_lon:(west+east)/2,centroid_lat:(south+north)/2},geometry:{type:'Polygon',coordinates:[[[west,south],[east,south],[east,north],[west,north],[west,south]]]}})}}return{type:'FeatureCollection',features}}
  function validate(){const minLon=number('minLon'),minLat=number('minLat'),maxLon=number('maxLon'),maxLat=number('maxLat'),cols=number('cols'),rows=number('rows');if([minLon,minLat,maxLon,maxLat,cols,rows].some(v=>!Number.isFinite(v))||minLon<-180||maxLon>180||minLat<-90||maxLat>90||minLon>=maxLon||minLat>=maxLat||!Number.isInteger(cols)||!Number.isInteger(rows)||cols<1||rows<1||cols>100||rows>100||cols*rows>2500)throw new Error('Revisa la extensión, usa coordenadas WGS84 válidas y una cuadrícula de 1 a 2500 celdas.');return{minLon,minLat,maxLon,maxLat,cols,rows,order:$('order').value}}
  function generate(){try{const p=validate();collection=buildGrid(p.minLon,p.minLat,p.maxLon,p.maxLat,p.cols,p.rows,p.order);gridGroup.clearLayers();const layer=L.geoJSON(collection,{style:{color:'#5bd6a5',weight:1,fillColor:'#5bd6a5',fillOpacity:.1},onEachFeature:(feature,l)=>{const q=feature.properties;l.bindTooltip(q.id,{permanent:true,direction:'center',className:'cell-label'});l.bindPopup(`<b>${q.id}</b><br>Fila ${q.row} · columna ${q.column}<br>Centroide: ${q.centroid_lon.toFixed(5)}, ${q.centroid_lat.toFixed(5)}`)}}).addTo(gridGroup);map.fitBounds(layer.getBounds(),{padding:[12,12]});$('cellCount').textContent=collection.features.length;$('cellWidth').textContent=`${((p.maxLon-p.minLon)/p.cols).toFixed(5)}°`;$('cellHeight').textContent=`${((p.maxLat-p.minLat)/p.rows).toFixed(5)}°`;$('center').textContent=`${((p.minLon+p.maxLon)/2).toFixed(4)}, ${((p.minLat+p.maxLat)/2).toFixed(4)}`;$('status').textContent=`Cuadrícula generada: ${collection.features.length} celdas. Haz clic en una para consultar sus datos.`;$('geoBtn').disabled=false;$('csvBtn').disabled=false}catch(error){collection=null;$('status').textContent=error.message;$('geoBtn').disabled=true;$('csvBtn').disabled=true}}
  function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
  $('generateBtn').addEventListener('click',generate);$('clearBtn').addEventListener('click',()=>{collection=null;gridGroup.clearLayers();$('cellCount').textContent='—';$('cellWidth').textContent='—';$('cellHeight').textContent='—';$('center').textContent='—';$('status').textContent='Cuadrícula limpiada.';$('geoBtn').disabled=true;$('csvBtn').disabled=true});$('geoBtn').addEventListener('click',()=>collection&&download('cuadricula-aoi.geojson',JSON.stringify(collection,null,2),'application/geo+json'));$('csvBtn').addEventListener('click',()=>{if(!collection)return;const h='id,row,column,min_lon,min_lat,max_lon,max_lat,centroid_lon,centroid_lat';const rows=collection.features.map(f=>{const p=f.properties;return[p.id,p.row,p.column,p.min_lon,p.min_lat,p.max_lon,p.max_lat,p.centroid_lon,p.centroid_lat].join(',')});download('cuadricula-aoi.csv',[h,...rows].join('\n'),'text/csv;charset=utf-8')});inputs.forEach(i=>i.addEventListener('change',generate));generate();
})();
