(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, features: [], field: '', result: null, map: null, layer: null };
  const colors = { hotspot: '#ee625f', coldspot: '#4e91e8', neutral: '#8291a4' };
  const example = { type: 'FeatureCollection', features: [
    [-3.735, 40.435, 91], [-3.729, 40.431, 86], [-3.723, 40.437, 94], [-3.718, 40.432, 88], [-3.727, 40.424, 89],
    [-3.681, 40.405, 14], [-3.675, 40.399, 21], [-3.668, 40.404, 12], [-3.660, 40.398, 18], [-3.674, 40.412, 16],
    [-3.706, 40.420, 49], [-3.697, 40.414, 54], [-3.688, 40.425, 44], [-3.698, 40.432, 57], [-3.711, 40.404, 31],
    [-3.748, 40.411, 68], [-3.646, 40.445, 7], [-3.631, 40.453, 73]
  ].map(([lon, lat, value], index) => ({ type: 'Feature', properties: { id: `obs-${index + 1}`, valor: value, campaña: index < 5 ? 'norte' : index < 10 ? 'sur' : 'control' }, geometry: { type: 'Point', coordinates: [lon, lat] } })) };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function toNumber(value) { if (value === null || value === undefined || value === '' || (typeof value === 'string' && !value.trim())) return null; const number = Number(String(value).replace(',', '.')); return Number.isFinite(number) ? number : null; }
  function normalize(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input; if (input.type === 'Feature') return { type: 'FeatureCollection', features: [input] }; if (typeof input.type === 'string') return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: input }] }; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON.'); }
  function coordinates(geometry, output = []) { if (!geometry || typeof geometry !== 'object') return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child) => coordinates(child, output)); return output; } const walk = (node) => { if (!Array.isArray(node)) return; if (node.length >= 2 && Number.isFinite(Number(node[0])) && Number.isFinite(Number(node[1]))) { output.push([Number(node[0]), Number(node[1])]); return; } node.forEach(walk); }; walk(geometry.coordinates); return output; }
  function representative(geometry) { const points = coordinates(geometry); if (!points.length) return null; return points.reduce((sum, point) => [sum[0] + point[0], sum[1] + point[1]], [0, 0]).map((value) => value / points.length); }
  function keys() { const result = new Set(); state.features.forEach((feature) => Object.keys(feature.properties || {}).forEach((key) => result.add(key))); return [...result]; }
  function numericKeys() { return keys().filter((key) => state.features.some((feature) => toNumber(feature.properties?.[key]) !== null)); }
  function fillFields() { const fields = numericKeys(); $('field').innerHTML = fields.length ? fields.map((key) => `<option value="${escapeHtml(key)}">${escapeHtml(key)}</option>`).join('') : '<option value="">No hay campos numéricos</option>'; $('field').disabled = !fields.length; state.field = fields[0] || ''; }
  function project(point, reference) { return [point[0] * 111320 * Math.max(.15, Math.cos(reference[1] * Math.PI / 180)), point[1] * 110540]; }
  function distanceSquared(a, b) { return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2; }
  function buildWeights(points) {
    const method = $('method').value; const n = points.length; const rows = Array.from({ length: n }, () => []);
    const parameter = method === 'knn' ? Math.max(1, Math.min(30, Math.floor(Number($('neighbours').value) || 5))) : Math.max(1, Math.min(500000, Number($('radius').value) || 2200));
    points.forEach((point, index) => {
      const candidates = points.map((candidate, candidateIndex) => ({ index: candidateIndex, distance: candidateIndex === index ? Infinity : Math.sqrt(distanceSquared(point.xy, candidate.xy)) })).filter((candidate) => method === 'knn' || candidate.distance <= parameter).sort((a, b) => a.distance - b.distance);
      const selected = method === 'knn' ? candidates.slice(0, Math.min(parameter, n - 1)) : candidates;
      rows[index] = [index, ...selected.map((candidate) => candidate.index)];
    });
    return rows;
  }
  function erfc(value) { const x = Math.abs(value); const t = 1 / (1 + .5 * x); const answer = t * Math.exp(-x * x - 1.26551223 + t * (1.00002368 + t * (.37409196 + t * (.09678418 + t * (-.18628806 + t * (.27886807 + t * (-1.13520398 + t * (1.48851587 + t * (-.82215223 + t * .17087277))))))))); return value >= 0 ? answer : 2 - answer; }
  function normalP(z) { return erfc(Math.abs(z) / Math.SQRT2); }
  function classFor(z, threshold, neighbours) { if (!neighbours) return 'neutral'; if (z >= threshold) return 'hotspot'; if (z <= -threshold) return 'coldspot'; return 'neutral'; }
  function calculate() {
    const field = $('field').value; if (!field) throw new Error('Selecciona un atributo numérico.');
    const validPoints = state.features.map((feature, index) => ({ feature, index, value: toNumber(feature.properties?.[field]), coordinate: representative(feature.geometry) })).filter((item) => item.value !== null && item.coordinate && item.coordinate[0] >= -180 && item.coordinate[0] <= 180 && item.coordinate[1] >= -90 && item.coordinate[1] <= 90);
    if (validPoints.length < 3) throw new Error('Se necesitan al menos tres entidades con valor y coordenadas válidas.');
    if (validPoints.length > 2500) throw new Error('Para mantener el navegador ágil, carga como máximo 2.500 observaciones válidas.');
    const reference = [validPoints.reduce((sum, item) => sum + item.coordinate[0], 0) / validPoints.length, validPoints.reduce((sum, item) => sum + item.coordinate[1], 0) / validPoints.length];
    validPoints.forEach((item) => { item.xy = project(item.coordinate, reference); });
    const weights = buildWeights(validPoints); const values = validPoints.map((item) => item.value); const n = values.length; const mean = values.reduce((sum, value) => sum + value, 0) / n; const variance = values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / n; const standardDeviation = Math.sqrt(variance);
    if (!standardDeviation) throw new Error('El atributo es constante; no se puede detectar concentración.');
    const threshold = Number($('threshold').value) || 1.96;
    const local = validPoints.map((item, index) => { const row = weights[index]; const sumWeights = row.length; const sumSquaredWeights = row.length; const weightedSum = row.reduce((sum, neighbour) => sum + values[neighbour], 0); const denominator = standardDeviation * Math.sqrt(Math.max(0, (n * sumSquaredWeights - sumWeights ** 2) / Math.max(1, n - 1))); const z = denominator ? (weightedSum - mean * sumWeights) / denominator : 0; const classification = classFor(z, threshold, row.length - 1); return { ...item, neighbours: Math.max(0, row.length - 1), giZ: z, pApprox: normalP(z), classification }; });
    const classes = local.reduce((counts, item) => { counts[item.classification] = (counts[item.classification] || 0) + 1; return counts; }, {});
    const relationCount = weights.reduce((sum, row) => sum + Math.max(0, row.length - 1), 0);
    state.field = field; state.result = { field, validPoints, local, classes, mean, threshold, relationCount };
    $('summary').hidden = false; $('tablePanel').hidden = false; $('fieldLabel').textContent = field; $('pointCount').textContent = n.toLocaleString('es-ES'); $('hotCount').textContent = classes.hotspot || 0; $('coldCount').textContent = classes.coldspot || 0; $('neutralCount').textContent = classes.neutral || 0; $('mean').textContent = mean.toLocaleString('es-ES', { maximumFractionDigits: 3 }); $('relationCount').textContent = relationCount.toLocaleString('es-ES');
    $('interpretation').textContent = `Con umbral |z| ≥ ${threshold.toLocaleString('es-ES', { maximumFractionDigits: 3 })}, se identifican ${classes.hotspot || 0} hotspots y ${classes.coldspot || 0} coldspots. La p aproximada supone una referencia normal y no sustituye una prueba de permutación.`;
    $('geojsonBtn').disabled = $('csvBtn').disabled = false; renderTable(); renderMap(); setStatus(`${n} observaciones analizadas con ${relationCount} relaciones de vecindad.`);
  }
  function popup(item) { const properties = Object.entries(item.feature.properties || {}).slice(0, 12).map(([key, value]) => `<div><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></div>`).join(''); return `<strong>${escapeHtml(item.classification)}</strong><div class="popup-stat">Gi* z: ${item.giZ.toFixed(3)} · p aprox.: ${item.pApprox.toFixed(4)} · vecinos: ${item.neighbours}</div><section class="popup-properties">${properties || '<em>Sin atributos</em>'}</section>`; }
  function renderTable() { const rows = state.result.local.slice(0, 40).map((item, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(item.value)}</td><td>${item.giZ.toFixed(3)}</td><td>${item.pApprox.toFixed(4)}</td><td><span class="tag ${item.classification === 'hotspot' ? 'hot' : item.classification === 'coldspot' ? 'cold' : 'neutral'}">${escapeHtml(item.classification)}</span></td><td>${item.neighbours}</td></tr>`).join(''); $('resultsBody').innerHTML = rows; }
  function renderMap() { if (!state.map || !state.result) return; state.layer?.remove(); state.layer = L.layerGroup(); state.result.local.forEach((item) => { const marker = L.circleMarker([item.coordinate[1], item.coordinate[0]], { radius: 8, color: '#fff', weight: 1, fillColor: colors[item.classification], fillOpacity: .9 }); marker.bindPopup(popup(item)); marker.addTo(state.layer); }); state.layer.addTo(state.map); const bounds = L.latLngBounds(state.result.local.map((item) => [item.coordinate[1], item.coordinate[0]])); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function prepare(input, filename = 'Ejemplo · 18 observaciones') { const normalized = normalize(input); if (!normalized.features.length) throw new Error('La capa no contiene entidades.'); state.source = normalized; state.features = normalized.features.filter(Boolean); $('fileName').textContent = filename; fillFields(); if (!state.field) throw new Error('No se encontró ningún campo numérico.'); $('field').value = state.field; $('runBtn').disabled = false; calculate(); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function enriched() { const output = JSON.parse(JSON.stringify(state.source)); const byIndex = new Map(state.result.local.map((item) => [item.index, item])); output.features = output.features.map((feature, index) => { const item = byIndex.get(index); return { ...feature, properties: { ...(feature.properties || {}), hotspot_field: state.field, hotspot_value: item?.value ?? null, hotspot_gi_z: item?.giZ ?? null, hotspot_p_approx: item?.pApprox ?? null, hotspot_class: item?.classification || 'sin_dato', hotspot_neighbours: item?.neighbours || 0 } }; }); return output; }
  function downloadCsv() { const rows = [['feature_index', 'field', 'value', 'gi_star_z', 'p_approx', 'class', 'neighbours', 'longitude', 'latitude'], ...state.result.local.map((item) => [item.index + 1, state.field, item.value, item.giZ, item.pApprox, item.classification, item.neighbours, item.coordinate[0], item.coordinate[1]])]; download('hotspot-lab-results.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function reset() { state.source = null; state.features = []; state.result = null; $('fileInput').value = ''; $('fileName').textContent = 'Ningún archivo seleccionado'; $('field').innerHTML = '<option>Primero carga una capa</option>'; $('field').disabled = true; $('runBtn').disabled = true; $('summary').hidden = true; $('tablePanel').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = true; state.layer?.remove(); state.layer = null; setStatus('Carga una capa de puntos o usa el ejemplo.'); }
  function updateMethod() { const isDistance = $('method').value === 'distance'; $('neighboursWrap').hidden = isDistance; $('radiusWrap').hidden = !isDistance; }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON.', true); } }); $('method').addEventListener('change', () => { updateMethod(); if (state.source) calculate(); }); ['field', 'neighbours', 'radius', 'threshold'].forEach((id) => $(id).addEventListener('change', () => { if (state.source) calculate(); })); $('exampleBtn').addEventListener('click', () => { try { prepare(example); } catch (error) { setStatus(error.message, true); } }); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', () => { try { calculate(); } catch (error) { setStatus(error.message, true); } }); $('geojsonBtn').addEventListener('click', () => { if (state.result) download('hotspot-lab-enriched.geojson', JSON.stringify(enriched(), null, 2), 'application/geo+json'); }); $('csvBtn').addEventListener('click', downloadCsv);
  updateMethod(); initMap();
})();
