(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { features: [], points: [], output: null, cells: [], map: null, layer: null, pointLayer: null };
  const example = JSON.parse($('source').value);
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection' && Array.isArray(parsed.features)) return parsed.features; if (parsed?.type === 'Feature') return [parsed]; if (parsed?.type && parsed.coordinates) return [{ type: 'Feature', properties: {}, geometry: parsed }]; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON reconocible.'); }
  function positions(geometry, output = []) { if (!geometry) return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach(child => positions(child, output)); return output; } const depth = depths[geometry.type]; if (depth === undefined) return output; const walk = (node, level) => { if (level === 0) { if (isPosition(node)) output.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach(child => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return output; }
  function representative(feature) { const values = positions(feature.geometry); if (!values.length) return null; const sum = values.reduce((total, point) => [total[0] + point[0], total[1] + point[1]], [0, 0]); return [sum[0] / values.length, sum[1] / values.length]; }
  function numericFields(features) { const fields = new Map(); features.forEach(feature => Object.entries(feature.properties || {}).forEach(([key, value]) => { const number = Number(value); if (value !== null && value !== '' && Number.isFinite(number)) fields.set(key, (fields.get(key) || 0) + 1); })); return [...fields.entries()].filter(([, count]) => count >= 1).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([key]) => key); }
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function refreshFields(preferred = '') { const fields = numericFields(state.features); const current = preferred || $('valueField').value; $('valueField').innerHTML = '<option value="">(sin campo numérico)</option>' + fields.map(field => `<option value="${esc(field)}">${esc(field)}</option>`).join(''); $('valueField').value = fields.includes(current) ? current : fields[0] || ''; }
  function local(point, metersLon, metersLat) { return [point[0] * metersLon, point[1] * metersLat]; }
  function bbox(points) { return points.reduce((box, point) => [Math.min(box[0], point[0]), Math.min(box[1], point[1]), Math.max(box[2], point[0]), Math.max(box[3], point[1])], [points[0][0], points[0][1], points[0][0], points[0][1]]); }
  function ring(centerX, centerY, radius, metersLon, metersLat) { const output = []; for (let index = 0; index < 6; index += 1) { const angle = (30 + index * 60) * Math.PI / 180; output.push([(centerX + radius * Math.cos(angle)) / metersLon, (centerY + radius * Math.sin(angle)) / metersLat]); } output.push([...output[0]]); return output; }
  function makeGrid(box, radiusKm, metersLon, metersLat) { const radius = radiusKm * 1000, horizontal = Math.sqrt(3) * radius, vertical = 1.5 * radius, min = local([box[0], box[1]], metersLon, metersLat), max = local([box[2], box[3]], metersLon, metersLat), cells = [], byKey = new Map(); let row = 0; for (let y = min[1] - 1.5 * radius; y <= max[1] + 1.5 * radius; y += vertical, row += 1) { const offset = row % 2 ? horizontal / 2 : 0; let col = 0; for (let x = min[0] - horizontal + offset; x <= max[0] + horizontal; x += horizontal, col += 1) { const cell = { row, col, count: 0, values: [], center: [x / metersLon, y / metersLat], geometry: { type: 'Polygon', coordinates: [ring(x, y, radius, metersLon, metersLat)] } }; cells.push(cell); byKey.set(`${row}:${col}`, cell); if (cells.length > 20000) throw new Error('La extensión y el tamaño elegidos generan más de 20.000 celdas. Aumenta el tamaño o recorta la capa.'); } } return { cells, byKey, radius, horizontal, vertical, startX: min[0] - horizontal, startY: min[1] - 1.5 * radius }; }
  function contains(point, ringCoordinates) { let inside = false; for (let index = 0, previous = ringCoordinates.length - 1; index < ringCoordinates.length; previous = index, index += 1) { const a = ringCoordinates[previous], b = ringCoordinates[index]; const cross = ((b[1] > point[1]) !== (a[1] > point[1])) && point[0] < (a[0] - b[0]) * (point[1] - b[1]) / (a[1] - b[1]) + b[0]; if (cross) inside = !inside; } return inside; }
  function assign(points, grid, metersLon, metersLat) { points.forEach(point => { const localPoint = local(point.coordinate, metersLon, metersLat); const rowGuess = Math.round((localPoint[1] - grid.startY) / grid.vertical); for (let row = rowGuess - 1; row <= rowGuess + 1; row += 1) { const offset = row % 2 ? grid.horizontal / 2 : 0; const colGuess = Math.round((localPoint[0] - grid.startX - offset) / grid.horizontal); for (let col = colGuess - 1; col <= colGuess + 1; col += 1) { const cell = grid.byKey.get(`${row}:${col}`); if (cell && contains(point.coordinate, cell.geometry.coordinates[0])) { cell.count += 1; const value = Number(point.feature.properties?.[$('valueField').value]); if (Number.isFinite(value)) cell.values.push(value); return; } } } }); }
  function metricValue(cell) { const metric = $('metric').value; if (metric === 'count') return cell.count; if (!cell.values.length) return null; const sum = cell.values.reduce((total, value) => total + value, 0); return metric === 'sum' ? sum : sum / cell.values.length; }
  function run() { if (!state.points.length) return setStatus('No hay puntos válidos para agregar.', true); const radiusKm = Math.max(.05, Math.min(100, Number($('cellSize').value) || 1)); const meanLat = state.points.reduce((sum, point) => sum + point.coordinate[1], 0) / state.points.length, metersLat = 110540, metersLon = 111320 * Math.max(.15, Math.cos(meanLat * Math.PI / 180)); try { const grid = makeGrid(bbox(state.points.map(point => point.coordinate)), radiusKm, metersLon, metersLat); assign(state.points, grid, metersLon, metersLat); state.cells = grid.cells; const active = grid.cells.filter(cell => cell.count > 0), source = $('onlyNonEmpty').checked ? active : grid.cells, features = source.map((cell, index) => { const sum = cell.values.reduce((total, value) => total + value, 0), mean = cell.values.length ? sum / cell.values.length : null, value = metricValue(cell); return { type: 'Feature', properties: { grid_id: `${cell.row}-${cell.col}`, cell_index: index + 1, cell_size_km: radiusKm, count: cell.count, value_count: cell.values.length, sum: Number(sum.toFixed(6)), mean: mean === null ? null : Number(mean.toFixed(6)), metric: $('metric').value, metric_value: value === null ? null : Number(value.toFixed(6)), center_lon: Number(cell.center[0].toFixed(7)), center_lat: Number(cell.center[1].toFixed(7)) }, geometry: cell.geometry }; }); state.output = { type: 'FeatureCollection', name: 'hexbin-stats-lab', features }; let max = 0; source.forEach(cell => { const value = metricValue(cell); if (Number.isFinite(value) && value > max) max = value; }); $('summary').hidden = false; $('pointCount').textContent = state.points.length.toLocaleString('es-ES'); $('cellCount').textContent = grid.cells.length.toLocaleString('es-ES'); $('activeCount').textContent = active.length.toLocaleString('es-ES'); $('maxValue').textContent = max.toLocaleString('es-ES', { maximumFractionDigits: 2 }); $('downloadBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${state.points.length} puntos agregados en ${grid.cells.length} celdas; ${active.length} activas.`); drawMap(max); } catch (error) { setStatus(error.message || 'No se pudo calcular la agregación.', true); } }
  function prepare(input) { try { state.features = normalize(input); state.points = state.features.map((feature, index) => { const coordinate = representative(feature); return coordinate && coordinate[0] >= -180 && coordinate[0] <= 180 && coordinate[1] >= -90 && coordinate[1] <= 90 ? { feature, index, coordinate } : null; }).filter(Boolean); refreshFields(); run(); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON.', true); } }
  function colorFor(value, max) { const ratio = max ? Math.max(0, Math.min(1, Number(value || 0) / max)) : 0; return `hsl(${220 - ratio * 195} 88% ${56 - ratio * 9}%)`; }
  function drawMap(max) { if (!state.map || !state.output) return; state.layer?.clearLayers(); state.pointLayer?.clearLayers(); state.layer = L.geoJSON(state.output, { style: feature => { const value = feature.properties?.metric_value; const color = colorFor(value, max); return { color, fillColor: color, fillOpacity: feature.properties?.count ? .72 : .08, weight: 1 }; }, onEachFeature: (feature, layer) => layer.bindPopup(`<b>Celda ${esc(feature.properties?.grid_id)}</b><br>Puntos: ${feature.properties?.count || 0}<br>Valor: ${feature.properties?.metric_value ?? '—'}<br>Suma: ${feature.properties?.sum ?? 0} · Media: ${feature.properties?.mean ?? '—'}`) }).addTo(state.map); const points = state.points.map(point => ({ type: 'Feature', properties: point.feature.properties || {}, geometry: { type: 'Point', coordinates: point.coordinate } })); state.pointLayer = L.geoJSON({ type: 'FeatureCollection', features: points }, { pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 4, color: '#eef5ff', fillColor: '#eef5ff', fillOpacity: .8, weight: 1 }) }).addTo(state.map); const bounds = state.layer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); state.pointLayer = L.layerGroup().addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) return setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); prepare($('source').value); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('exampleBtn').addEventListener('click', () => { $('source').value = JSON.stringify(example); $('cellSize').value = 1; $('metric').value = 'mean'; prepare(example); }); $('runBtn').addEventListener('click', () => prepare($('source').value)); $('cellSize').addEventListener('change', run); $('metric').addEventListener('change', run); $('valueField').addEventListener('change', run); $('onlyNonEmpty').addEventListener('change', run); $('clearBtn').addEventListener('click', () => { state.features = []; state.points = []; state.output = null; state.cells = []; state.layer?.clearLayers(); state.pointLayer?.clearLayers(); $('summary').hidden = true; $('downloadBtn').disabled = true; $('csvBtn').disabled = true; $('valueField').innerHTML = '<option value="">(sin campo numérico)</option>'; setStatus('Carga una capa o usa el ejemplo.'); }); $('downloadBtn').addEventListener('click', () => { if (state.output) download('hexbin-estadisticas.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json'); }); $('csvBtn').addEventListener('click', () => { const rows = [['grid_id', 'cell_size_km', 'count', 'value_count', 'sum', 'mean', 'metric', 'metric_value', 'center_lon', 'center_lat'], ...(state.output?.features || []).map(feature => { const p = feature.properties; return [p.grid_id, p.cell_size_km, p.count, p.value_count, p.sum, p.mean, p.metric, p.metric_value, p.center_lon, p.center_lat]; })]; download('hexbin-estadisticas.csv', rows.map(row => row.map(value => '"' + String(value ?? '').replace(/"/g, '""') + '"').join(',')).join('\n'), 'text/csv;charset=utf-8'); }); initMap(); prepare(example);
})();
