(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, features: [], entries: [], times: [], currentIndex: 0, output: null, map: null, layer: null, fileName: 'capa.geojson', timer: null };
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };
  const example = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'Castro documentado', year: 1750 }, geometry: { type: 'Point', coordinates: [-3.72, 40.415] } }, { type: 'Feature', properties: { name: 'Camino histórico', year: 1850 }, geometry: { type: 'LineString', coordinates: [[-3.73, 40.41], [-3.70, 40.42], [-3.68, 40.43]] } }, { type: 'Feature', properties: { name: 'Yacimiento catalogado', year: 1950 }, geometry: { type: 'Point', coordinates: [-3.69, 40.425] } }, { type: 'Feature', properties: { name: 'Área protegida', year: 2000 }, geometry: { type: 'Polygon', coordinates: [[[-3.67, 40.41], [-3.64, 40.41], [-3.64, 40.44], [-3.67, 40.44], [-3.67, 40.41]]] } }, { type: 'Feature', properties: { name: 'Sin fecha', note: 'Revisión pendiente' }, geometry: { type: 'Point', coordinates: [-3.66, 40.425] } }] };

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function isObject(value) { return value !== null && typeof value === 'object'; }
  function parseInput(input) { if (!isObject(input)) throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input.features; if (input.type === 'Feature') return [input]; if (typeof input.type === 'string' && (depths[input.type] !== undefined || input.type === 'GeometryCollection')) return [{ type: 'Feature', properties: {}, geometry: input }]; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON reconocible.'); }
  function parseTime(value) { if (value === null || value === undefined || value === '') return null; if (typeof value === 'number' && Number.isFinite(value)) return { key: String(value), sort: value, label: String(value) }; const text = String(value).trim(); if (/^\d{4}$/.test(text)) return { key: text, sort: Number(text), label: text }; const numeric = Number(text); if (Number.isFinite(numeric) && /^-?\d+(\.\d+)?$/.test(text)) return { key: text, sort: numeric, label: text }; const parsed = Date.parse(text); return Number.isFinite(parsed) ? { key: text, sort: parsed, label: text } : null; }
  function temporalEntries(features) { const entries = []; features.forEach((feature, index) => { const value = feature?.properties?.[$('timeField').value.trim() || 'year']; const time = parseTime(value); entries.push({ feature, index, time }); }); return entries; }
  function geometryCanMap(geometry) { if (!geometry || typeof geometry !== 'object') return false; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).some(geometryCanMap); const depth = depths[geometry.type]; if (depth === undefined) return false; let valid = true; const walk = (node, level) => { if (level === 0) { valid = valid && Array.isArray(node) && Number.isFinite(Number(node[0])) && Number.isFinite(Number(node[1])) && Number(node[0]) >= -180 && Number(node[0]) <= 180 && Number(node[1]) >= -90 && Number(node[1]) <= 90; return; } if (!Array.isArray(node)) { valid = false; return; } node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return valid; }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function currentTime() { return state.times[state.currentIndex] || null; }
  function visibleEntries() { const current = currentTime(); if (!current) return []; return state.entries.filter((entry) => entry.time && ($(('mode')).value === 'cumulative' ? entry.time.sort <= current.sort : entry.time.key === current.key)); }
  function prepare(input, fileName) { state.source = input; state.features = parseInput(input); state.entries = temporalEntries(state.features); state.fileName = fileName || 'capa.geojson'; const map = new Map(); state.entries.forEach((entry) => { if (entry.time && !map.has(entry.time.key)) map.set(entry.time.key, entry.time); }); state.times = [...map.values()].sort((a, b) => a.sort - b.sort); state.currentIndex = 0; $('timelinePanel').hidden = !state.times.length; if (!state.times.length) { $('status').textContent = 'No se encontraron valores temporales reconocibles en el campo indicado.'; state.output = null; state.layer?.remove(); return; } $('timeSlider').max = String(state.times.length - 1); $('timeSlider').value = '0'; updateView(); }
  function updateView() { const time = currentTime(); if (!time) return; const visible = visibleEntries(); const missing = state.entries.filter((entry) => !entry.time).length; state.output = { type: 'FeatureCollection', features: visible.map((entry) => clone(entry.feature)) }; $('timeLabel').textContent = time.label; $('timePosition').textContent = `${state.currentIndex + 1} / ${state.times.length}`; $('temporalCount').textContent = state.entries.filter((entry) => entry.time).length.toLocaleString('es-ES'); $('missingCount').textContent = missing.toLocaleString('es-ES'); $('visibleCount').textContent = visible.length.toLocaleString('es-ES'); $('periodCount').textContent = state.times.length.toLocaleString('es-ES'); $('downloadBtn').disabled = false; $('status').textContent = `${state.fileName}: ${visible.length} features visibles en ${time.label}.`; drawMap(); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function drawMap() { if (!state.map || !state.output) return; state.layer?.remove(); const features = state.output.features.filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); if (!features.length) return; try { state.layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: { color: '#5bd6a5', weight: 2, fillColor: '#5bd6a5', fillOpacity: .2 }, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#ffbf69', fillColor: '#ffbf69', fillOpacity: .9, weight: 2 }), onEachFeature: (feature, layer) => layer.bindPopup(`<pre>${escapeHtml(JSON.stringify(feature.properties || {}, null, 2))}</pre>`) }).addTo(state.map); const bounds = state.layer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); } catch { $('status').textContent += ' El mapa no pudo dibujar alguna geometría; la exportación sigue disponible.'; } }
  function stopPlayback() { if (state.timer) { clearInterval(state.timer); state.timer = null; } $('playBtn').textContent = '▶ Reproducir'; }
  function startPlayback() { if (state.timer) { stopPlayback(); return; } if (state.currentIndex >= state.times.length - 1) { state.currentIndex = 0; $('timeSlider').value = '0'; updateView(); } $('playBtn').textContent = '⏸ Pausar'; state.timer = setInterval(() => { if (state.currentIndex >= state.times.length - 1) { stopPlayback(); return; } state.currentIndex += 1; $('timeSlider').value = String(state.currentIndex); updateView(); }, 850); }
  function download(text, name) { const url = URL.createObjectURL(new Blob([text], { type: 'application/geo+json' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function readFile(file) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { $('timelinePanel').hidden = true; $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  $('fileInput').addEventListener('change', () => readFile($('fileInput').files?.[0])); $('exampleBtn').addEventListener('click', () => prepare(example, 'ejemplo-temporal-atlas.geojson')); $('timeField').addEventListener('change', () => { if (state.source) prepare(state.source, state.fileName); }); $('mode').addEventListener('change', updateView); $('timeSlider').addEventListener('input', () => { stopPlayback(); state.currentIndex = Number($('timeSlider').value); updateView(); }); $('playBtn').addEventListener('click', startPlayback); $('resetBtn').addEventListener('click', () => { stopPlayback(); state.currentIndex = 0; $('timeSlider').value = '0'; updateView(); }); $('downloadBtn').addEventListener('click', () => { if (state.output) download(JSON.stringify(state.output, null, 2), `${state.fileName.replace(/\.[^.]+$/, '')}-${currentTime()?.label || 'vista'}.geojson`); }); $('clearBtn').addEventListener('click', () => { stopPlayback(); state.source = null; state.features = []; state.entries = []; state.times = []; state.output = null; state.layer?.remove(); $('timelinePanel').hidden = true; $('status').textContent = 'Sin capa cargada'; }); initMap();
})();
