(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { items: [], map: null, layer: null };
  const sample = [{ name: 'campaña-01.jpg', size: 2840000, type: 'image/jpeg', lat: 40.4182, lon: -3.7045, hasGps: true }, { name: 'campaña-02.jpg', size: 3170000, type: 'image/jpeg', lat: 40.4271, lon: -3.6864, hasGps: true }, { name: 'sin-gps-03.jpg', size: 1950000, type: 'image/jpeg', lat: null, lon: null, hasGps: false }];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function u16(view, offset, little) { return view.getUint16(offset, little); }
  function u32(view, offset, little) { return view.getUint32(offset, little); }
  function entryValue(view, tiff, entryOffset, type, count, little) { const sizes = { 1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 7: 1, 9: 4, 10: 8 }; const size = sizes[type]; if (!size) return null; const total = size * count; const start = total <= 4 ? entryOffset + 8 : tiff + u32(view, entryOffset + 8, little); return { start, size, total }; }
  function readIfd(view, tiff, offset, little) { if (offset < 0 || offset + 2 > view.byteLength) return new Map(); const count = u16(view, offset, little), entries = new Map(); for (let index = 0; index < count; index += 1) { const entry = offset + 2 + index * 12; if (entry + 12 > view.byteLength) break; entries.set(u16(view, entry, little), { entry, type: u16(view, entry + 2, little), count }); } return entries; }
  function textValue(view, tiff, item, little) { const location = entryValue(view, tiff, item.entry, item.type, item.count, little); if (!location) return ''; let text = ''; for (let index = 0; index < location.total && location.start + index < view.byteLength; index += 1) text += String.fromCharCode(view.getUint8(location.start + index)); return text.replace(/\0/g, '').trim(); }
  function rationals(view, tiff, item, little) { const location = entryValue(view, tiff, item.entry, item.type, item.count, little); if (!location || item.type !== 5) return []; const values = []; for (let index = 0; index < item.count; index += 1) { const at = location.start + index * 8; if (at + 8 > view.byteLength) break; const denominator = u32(view, at + 4, little); values.push(denominator ? u32(view, at, little) / denominator : null); } return values; }
  function decimal(values, reference) { if (!values.length || values.some(value => !Number.isFinite(value))) return null; const result = values[0] + values[1] / 60 + values[2] / 3600; return /S|W|O/i.test(reference) ? -result : result; }
  function parseTiff(view, tiff) { if (tiff + 8 > view.byteLength) return null; const little = view.getUint8(tiff) === 0x49 && view.getUint8(tiff + 1) === 0x49; if (!little && !(view.getUint8(tiff) === 0x4d && view.getUint8(tiff + 1) === 0x4d)) return null; if (u16(view, tiff + 2, little) !== 42) return null; const ifd = readIfd(view, tiff, tiff + u32(view, tiff + 4, little), little), gpsItem = ifd.get(0x8825); if (!gpsItem) return null; const gpsOffset = entryValue(view, tiff, gpsItem.entry, gpsItem.type, gpsItem.count, little); if (!gpsOffset) return null; const gps = readIfd(view, tiff, tiff + u32(view, gpsOffset.start, little), little); const latRef = gps.get(1), lat = gps.get(2), lonRef = gps.get(3), lon = gps.get(4); const latitude = decimal(rationals(view, tiff, lat, little), textValue(view, tiff, latRef, little)); const longitude = decimal(rationals(view, tiff, lon, little), textValue(view, tiff, lonRef, little)); return Number.isFinite(latitude) && Number.isFinite(longitude) ? { lat: latitude, lon: longitude } : null; }
  async function readGps(file) { const buffer = await file.arrayBuffer(); const view = new DataView(buffer); if (view.byteLength < 4 || view.getUint16(0, false) !== 0xffd8) return null; let offset = 2; while (offset + 4 < view.byteLength) { if (view.getUint8(offset) !== 0xff) { offset += 1; continue; } while (offset < view.byteLength && view.getUint8(offset) === 0xff) offset += 1; const marker = view.getUint8(offset); if (marker === 0xda || marker === 0xd9) break; if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) { offset += 1; continue; } if (offset + 2 >= view.byteLength) break; const length = view.getUint16(offset + 1, false); const payload = offset + 3; if (marker === 0xe1 && length >= 8 && payload + 8 <= view.byteLength) { const signature = String.fromCharCode(...new Uint8Array(buffer, payload, 6)); if (signature === 'Exif\0\0') return parseTiff(view, payload + 6); } offset += 1 + length; } return null; }
  async function loadFiles(files) { if (!files.length) return; state.items = []; setStatus(`Leyendo ${files.length} fotografía${files.length === 1 ? '' : 's'}…`); for (const file of files) { try { const gps = await readGps(file); state.items.push({ name: file.name, size: file.size, type: file.type || 'image/jpeg', lat: gps?.lat ?? null, lon: gps?.lon ?? null, hasGps: Boolean(gps) }); } catch (_error) { state.items.push({ name: file.name, size: file.size, type: file.type || 'image/jpeg', lat: null, lon: null, hasGps: false }); } } render(); setStatus(`${state.items.filter(item => item.hasGps).length} de ${state.items.length} fotografías tienen coordenadas GPS.`); }
  function visibleItems() { return $('includeNoGps').checked ? state.items : state.items.filter(item => item.hasGps); }
  function render() { const visible = visibleItems(), gps = state.items.filter(item => item.hasGps), noGps = state.items.length - gps.length; $('photoBadge').textContent = visible.length + (visible.length === 1 ? ' foto' : ' fotos'); $('photoCount').textContent = state.items.length.toLocaleString('es-ES'); $('gpsCount').textContent = gps.length.toLocaleString('es-ES'); $('noGpsCount').textContent = noGps.toLocaleString('es-ES'); $('coverage').textContent = state.items.length ? `${Math.round(gps.length / state.items.length * 100)}%` : '—'; $('quality').textContent = state.items.length ? `${gps.length} localizadas` : 'Pendiente'; $('quality').className = state.items.length ? 'quality' : 'quality muted'; $('tableWrap').innerHTML = visible.length ? `<table><thead><tr><th>Archivo</th><th>Latitud</th><th>Longitud</th><th>Tamaño</th><th>Estado</th></tr></thead><tbody>${visible.map(item => `<tr><td>${esc(item.name)}</td><td>${item.hasGps ? item.lat.toFixed(6) : '—'}</td><td>${item.hasGps ? item.lon.toFixed(6) : '—'}</td><td>${(item.size / 1024 / 1024).toFixed(2)} MB</td><td class="${item.hasGps ? 'ok' : 'missing'}">${item.hasGps ? 'GPS leído' : 'Sin GPS'}</td></tr>`).join('')}</tbody></table>` : '<p class="empty">Carga fotografías para ver el informe EXIF.</p>'; renderMap(visible); $('geojsonBtn').disabled = gps.length === 0; $('csvBtn').disabled = state.items.length === 0; }
  function renderMap(items) { if (!state.layer) return; state.layer.clearLayers(); const bounds = []; items.filter(item => item.hasGps).forEach(item => { const marker = L.circleMarker([item.lat, item.lon], { radius: 7, color: '#fff', weight: 1, fillColor: '#72e3be', fillOpacity: .92 }).bindPopup(`<strong>${esc(item.name)}</strong><br>Latitud: ${item.lat.toFixed(6)}<br>Longitud: ${item.lon.toFixed(6)}<br>Tamaño: ${(item.size / 1024 / 1024).toFixed(2)} MB`); marker.addTo(state.layer); bounds.push([item.lat, item.lon]); }); if (bounds.length) state.map.fitBounds(bounds, { padding: [25, 25], maxZoom: 16 }); }
  function geojson() { return { type: 'FeatureCollection', name: 'photo-geotag-lab', features: state.items.filter(item => item.hasGps).map(item => ({ type: 'Feature', properties: { filename: item.name, size_bytes: item.size, mime_type: item.type, gps_source: 'EXIF' }, geometry: { type: 'Point', coordinates: [item.lon, item.lat] } })) }; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function csv() { const rows = [['filename', 'latitude', 'longitude', 'size_bytes', 'mime_type', 'gps']]; state.items.forEach(item => rows.push([item.name, item.lat ?? '', item.lon ?? '', item.size, item.type, item.hasGps ? 'true' : 'false'])); return rows.map(row => row.map(value => '"' + String(value).replace(/"/g, '""') + '"').join(',')).join('\n'); }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  $('files').addEventListener('change', event => loadFiles([...event.target.files || []])); $('includeNoGps').addEventListener('change', render); $('sampleBtn').addEventListener('click', () => { state.items = sample.map(item => ({ ...item })); render(); setStatus('Ejemplo cargado: simula dos fotos con GPS y una sin coordenadas.'); }); $('clearBtn').addEventListener('click', () => { state.items = []; $('files').value = ''; render(); setStatus('Selecciona fotografías para inspeccionar sus metadatos.'); }); $('geojsonBtn').addEventListener('click', () => download('fotografias-geolocalizadas.geojson', JSON.stringify(geojson(), null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', () => download('informe-fotografias-gps.csv', '\ufeff' + csv(), 'text/csv;charset=utf-8')); initMap(); render();
})();
