(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const els = { file: $('fileInput'), fileName: $('fileName'), demo: $('demoBtn'), status: $('status'), featureCount: $('featureCount'), fieldCount: $('fieldCount'), precision: $('precision'), precisionOut: $('precisionOut'), precisionMetric: $('precisionMetric'), geometryMetric: $('geometryMetric'), removeGeometry: $('removeGeometry'), stripZ: $('stripZ'), fieldList: $('fieldList'), allFields: $('allFields'), noFields: $('noFields'), previewNote: $('previewNote'), beforeSize: $('beforeSize'), afterSize: $('afterSize'), removedFields: $('removedFields'), rows: $('previewRows'), geojson: $('geojsonBtn'), audit: $('auditBtn') };
  const state = { name: '', original: null, fields: [], selected: new Set(), originalText: '' };
  const demo = { type: 'FeatureCollection', name: 'privacy-redactor-demo', features: [{ type: 'Feature', properties: { id: 'A-01', site: 'Sector norte', observacion: 'ejemplo', responsable: 'Equipo local' }, geometry: { type: 'Point', coordinates: [-3.70379, 40.41678, 667] } }, { type: 'Feature', properties: { id: 'A-02', site: 'Sector sur', observacion: 'ejemplo', responsable: 'Equipo local' }, geometry: { type: 'Point', coordinates: [-3.6891, 40.4012, 660] } }, { type: 'Feature', properties: { id: 'A-03', site: 'Ribera', observacion: 'ejemplo', responsable: 'Equipo local' }, geometry: { type: 'Point', coordinates: [-3.716, 40.425, 671] } }] };
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  const formatBytes = bytes => bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(2)} MB`;
  const download = (name, content, mime) => { const url = URL.createObjectURL(new Blob([content], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 800); };
  const clone = value => JSON.parse(JSON.stringify(value));
  const normalize = data => data?.type === 'FeatureCollection' ? data : data?.type === 'Feature' ? { type: 'FeatureCollection', features: [data] } : null;
  const collectFields = layer => [...new Set(layer.features.flatMap(feature => Object.keys(feature.properties || {})))].sort((a, b) => a.localeCompare(b, 'es'));
  function roundCoordinates(value, precision, stripZ) { if (!Array.isArray(value)) return value; if (typeof value[0] === 'number') return value.slice(0, stripZ ? 2 : value.length).map(number => Number(number.toFixed(precision))); return value.map(item => roundCoordinates(item, precision, stripZ)); }
  function redact() { if (!state.original) return null; const precision = Number(els.precision.value); return { ...clone(state.original), features: state.original.features.map(feature => ({ ...feature, properties: Object.fromEntries(Object.entries(feature.properties || {}).filter(([key]) => state.selected.has(key))), geometry: els.removeGeometry.checked || !feature.geometry ? null : { ...clone(feature.geometry), coordinates: roundCoordinates(feature.geometry.coordinates, precision, els.stripZ.checked) } })) }; }
  function renderFields() { if (!state.fields.length) { els.fieldList.innerHTML = '<p class="muted">No se detectaron propiedades.</p>'; return; } els.fieldList.innerHTML = state.fields.map((field, index) => `<label class="field-item"><input type="checkbox" data-field="${index}" ${state.selected.has(field) ? 'checked' : ''}><code>${field.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))}</code></label>`).join(''); els.fieldList.querySelectorAll('input').forEach(input => input.addEventListener('change', () => { const field = state.fields[Number(input.dataset.field)]; input.checked ? state.selected.add(field) : state.selected.delete(field); render(); })); }
  function render() { if (!state.original) return; const output = redact(); const originalText = JSON.stringify(state.original); const outputText = JSON.stringify(output); const removed = state.fields.filter(field => !state.selected.has(field)); els.featureCount.textContent = state.original.features.length.toLocaleString('es-ES'); els.fieldCount.textContent = state.fields.length.toLocaleString('es-ES'); els.precisionMetric.textContent = els.removeGeometry.checked ? '—' : els.precision.value; els.geometryMetric.textContent = els.removeGeometry.checked ? 'eliminada' : 'conservada'; els.precisionOut.textContent = els.precision.value; els.beforeSize.textContent = formatBytes(new Blob([originalText]).size); els.afterSize.textContent = formatBytes(new Blob([outputText]).size); els.removedFields.textContent = removed.length ? `${removed.length}` : 'ninguno'; els.previewNote.textContent = `${output.features.length} entidades · ${removed.length} campos fuera`; els.rows.innerHTML = output.features.slice(0, 12).map((feature, index) => { const coordinates = feature.geometry?.coordinates; const coordinateText = els.removeGeometry.checked || !coordinates ? '—' : JSON.stringify(Array.isArray(coordinates) ? coordinates[0] instanceof Array ? '[…]' : coordinates : '—'); return `<tr><td>${index + 1}</td><td>${feature.geometry?.type || 'sin geometría'}</td><td>${Object.keys(feature.properties || {}).join(', ') || '—'}</td><td>${coordinateText}</td></tr>`; }).join(''); els.geojson.disabled = els.audit.disabled = false; }
  function loadLayer(data, name, originalText = JSON.stringify(data)) { const layer = normalize(data); if (!layer || !Array.isArray(layer.features)) { setStatus('El archivo no contiene un Feature o FeatureCollection GeoJSON válido.', true); return; } state.name = name; state.original = layer; state.originalText = originalText; state.fields = collectFields(layer); state.selected = new Set(state.fields); els.fileName.textContent = name; renderFields(); render(); setStatus(`Capa cargada localmente · ${layer.features.length} entidades.`); }
  function makeDemo() { loadLayer(clone(demo), 'privacy-redactor-demo.geojson'); }
  function exportGeoJSON() { const output = redact(); download('geojson-redactado.geojson', JSON.stringify(output, null, 2), 'application/geo+json;charset=utf-8'); }
  function exportAudit() { const output = redact(); const removed = state.fields.filter(field => !state.selected.has(field)); const audit = { tool: 'Privacy Redactor', sourceFile: state.name, processedAt: new Date().toISOString(), inputFeatures: state.original.features.length, outputFeatures: output.features.length, keptFields: [...state.selected], removedFields: removed, coordinateDecimals: els.removeGeometry.checked ? null : Number(els.precision.value), geometryRemoved: els.removeGeometry.checked, zRemoved: els.stripZ.checked, localOnly: true, limitation: 'La minimización no garantiza anonimato absoluto frente a otras fuentes de datos.' }; download('geojson-redaction-audit.json', JSON.stringify(audit, null, 2), 'application/json;charset=utf-8'); }
  els.file.addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { loadLayer(JSON.parse(reader.result), file.name, reader.result); } catch { setStatus('No se pudo leer el JSON del archivo seleccionado.', true); } }; reader.readAsText(file); }); els.demo.addEventListener('click', makeDemo); els.precision.addEventListener('input', render); els.removeGeometry.addEventListener('change', render); els.stripZ.addEventListener('change', render); els.allFields.addEventListener('click', () => { state.selected = new Set(state.fields); renderFields(); render(); }); els.noFields.addEventListener('click', () => { state.selected.clear(); renderFields(); render(); }); els.geojson.addEventListener('click', exportGeoJSON); els.audit.addEventListener('click', exportAudit); makeDemo();
})();
