(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, features: [], result: null, map: null, cellLayer: null, lineLayer: null };
  const palettes = { ember: ['#fff0a6', '#f59b45', '#bb2e37'], ocean: ['#c6f3ff', '#5b9ee8', '#682d9e'], terrain: ['#d9f0a3', '#7da657', '#7a3f2b'] };
  const example = { type: 'FeatureCollection', features: [
    { type: 'Feature', properties: { nombre: 'Camino norte', clase: 'histórico' }, geometry: { type: 'LineString', coordinates: [[-3.742, 40.443], [-3.728, 40.438], [-3.715, 40.434], [-3.700, 40.431], [-3.682, 40.428]] } },
    { type: 'Feature', properties: { nombre: 'Camino sur', clase: 'histórico' }, geometry: { type: 'LineString', coordinates: [[-3.742, 40.407], [-3.727, 40.412], [-3.710, 40.415], [-3.692, 40.416], [-3.671, 40.420]] } },
    { type: 'Feature', properties: { nombre: 'Eje este', clase: 'actual' }, geometry: { type: 'LineString', coordinates: [[-3.735, 40.421], [-3.718, 40.421], [-3.701, 40.421], [-3.683, 40.421], [-3.661, 40.421]] } },
    { type: 'Feature', properties: { nombre: 'Eje oeste', clase: 'actual' }, geometry: { type: 'LineString', coordinates: [[-3.753, 40.432], [-3.735, 40.428], [-3.716, 40.426], [-3.697, 40.427]] } },
    { type: 'Feature', properties: { nombre: 'Transecto 1', clase: 'prospección' }, geometry: { type: 'LineString', coordinates: [[-3.725, 40.447], [-3.719, 40.435], [-3.712, 40.424], [-3.705, 40.411], [-3.700, 40.398]] } },
    { type: 'Feature', properties: { nombre: 'Transecto 2', clase: 'prospección' }, geometry: { type: 'LineString', coordinates: [[-3.690, 40.446], [-3.692, 40.434], [-3.690, 40.422], [-3.687, 40.410], [-3.683, 40.397]] } },
    { type: 'Feature', properties: { nombre: 'Río', clase: 'hidrología' }, geometry: { type: 'LineString', coordinates: [[-3.755, 40.414], [-3.741, 40.416], [-3.727, 40.419], [-3.715, 40.424], [-3.703, 40.432], [-3.691, 40.442]] } }
  ] };

  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
  function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function normalize(input) { if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.'); if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return input; if (input.type === 'Feature') return { type: 'FeatureCollection', features: [input] }; if (typeof input.type === 'string') return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: input }] }; throw new Error('Usa una capa FeatureCollection, Feature o geometría GeoJSON.'); }
  function lineParts(geometry, output = []) { if (!geometry || typeof geometry !== 'object') return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach((child) => lineParts(child, output)); return output; } if (geometry.type === 'LineString' && Array.isArray(geometry.coordinates)) output.push(geometry.coordinates); if (geometry.type === 'MultiLineString' && Array.isArray(geometry.coordinates)) geometry.coordinates.forEach((line) => output.push(line)); return output; }
  function validCoordinate(coordinate) { return Array.isArray(coordinate) && Number.isFinite(Number(coordinate[0])) && Number.isFinite(Number(coordinate[1])) && Number(coordinate[0]) >= -180 && Number(coordinate[0]) <= 180 && Number(coordinate[1]) >= -90 && Number(coordinate[1]) <= 90; }
  function haversine(a, b) { const rad = Math.PI / 180; const dLat = (b[1] - a[1]) * rad; const dLon = (b[0] - a[0]) * rad; const lat1 = a[1] * rad; const lat2 = b[1] * rad; const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return 6371008.8 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(Math.max(0, 1 - h))); }
  function midpoint(a, b, fraction = .5) { return [a[0] + (b[0] - a[0]) * fraction, a[1] + (b[1] - a[1]) * fraction]; }
  function projectSteps(coordinate, origin, steps) { const output = []; for (let i = 0; i < steps; i += 1) output.push({ coordinate: midpoint(origin.start, origin.end, (i + .5) / steps), length: origin.length / steps }); return output; }
  function bbox(lines) { const values = lines.flat().filter(validCoordinate); if (!values.length) return null; return values.reduce((box, coordinate) => ({ minLon: Math.min(box.minLon, Number(coordinate[0])), minLat: Math.min(box.minLat, Number(coordinate[1])), maxLon: Math.max(box.maxLon, Number(coordinate[0])), maxLat: Math.max(box.maxLat, Number(coordinate[1])) }), { minLon: Infinity, minLat: Infinity, maxLon: -Infinity, maxLat: -Infinity }); }
  function colorFor(value, maximum) { const [low, mid, high] = palettes[$('palette').value] || palettes.ember; const ratio = maximum > 0 ? Math.min(1, Math.max(0, value / maximum)) : 0; if (ratio < .5) return low; return ratio < .8 ? mid : high; }
  function calculate() {
    const cellSizeKm = Math.max(.1, Math.min(100, Number($('cellSize').value) || 1)); $('cellSize').value = cellSizeKm;
    const sourceLines = []; let featureCount = 0; state.features.forEach((feature, featureIndex) => { const parts = lineParts(feature.geometry).map((line) => line.filter(validCoordinate).map((coordinate) => [Number(coordinate[0]), Number(coordinate[1])])).filter((line) => line.length >= 2); if (parts.length) { featureCount += 1; parts.forEach((line) => sourceLines.push({ line, featureIndex })); } });
    if (!sourceLines.length) throw new Error('No se encontraron LineString o MultiLineString con al menos dos coordenadas.');
    const allCoordinates = sourceLines.flatMap((entry) => entry.line); const box = bbox(sourceLines.map((entry) => entry.line)); const referenceLat = (box.minLat + box.maxLat) / 2; const latStep = cellSizeKm * 1000 / 110540; const lonStep = cellSizeKm * 1000 / (111320 * Math.max(.15, Math.cos(referenceLat * Math.PI / 180))); const width = Math.ceil((box.maxLon - box.minLon) / lonStep) || 1; const height = Math.ceil((box.maxLat - box.minLat) / latStep) || 1; const gridCount = width * height; if (gridCount > 5000) throw new Error(`La extensión genera ${gridCount.toLocaleString('es-ES')} celdas; aumenta el tamaño de celda para mantener el navegador fluido.`);
    const cells = new Map(); let totalLengthM = 0; let sampleCount = 0; sourceLines.forEach(({ line, featureIndex }) => { for (let i = 1; i < line.length; i += 1) { const start = line[i - 1]; const end = line[i]; const length = haversine(start, end); if (!Number.isFinite(length) || length <= 0) continue; totalLengthM += length; const steps = Math.max(1, Math.min(1000, Math.ceil(length / (cellSizeKm * 1000 * .35)))); const samples = projectSteps(start, { start, end, length }, steps); samples.forEach((sample) => { sampleCount += 1; const x = Math.min(width - 1, Math.max(0, Math.floor((sample.coordinate[0] - box.minLon) / lonStep))); const y = Math.min(height - 1, Math.max(0, Math.floor((sample.coordinate[1] - box.minLat) / latStep))); const key = `${x}:${y}`; const cell = cells.get(key) || { x, y, lengthM: 0, features: new Set() }; cell.lengthM += sample.length; cell.features.add(featureIndex); cells.set(key, cell); }); } });
    const allCells = []; for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) { const key = `${x}:${y}`; const cell = cells.get(key) || { x, y, lengthM: 0, features: new Set() }; const minLon = box.minLon + x * lonStep; const minLat = box.minLat + y * latStep; const maxLon = x === width - 1 ? box.maxLon : minLon + lonStep; const maxLat = y === height - 1 ? box.maxLat : minLat + latStep; const areaKm2 = Math.max(.000001, (haversine([minLon, minLat], [maxLon, minLat]) / 1000) * (haversine([minLon, minLat], [minLon, maxLat]) / 1000)); const lengthKm = cell.lengthM / 1000; allCells.push({ ...cell, minLon, minLat, maxLon, maxLat, centerLon: (minLon + maxLon) / 2, centerLat: (minLat + maxLat) / 2, areaKm2, lengthKm, density: lengthKm / areaKm2 }); }
    const maxDensity = allCells.reduce((maximum, cell) => Math.max(maximum, cell.density), 0); const totalAreaKm2 = allCells.reduce((sum, cell) => sum + cell.areaKm2, 0); const output = allCells.map((cell, index) => ({ ...cell, id: index + 1, color: colorFor(cell.density, maxDensity) })); state.result = { cellSizeKm, box, width, height, featureCount, totalLengthKm: totalLengthM / 1000, sampleCount, maxDensity, totalAreaKm2, cells: output, sourceLines };
    $('summary').hidden = false; $('tablePanel').hidden = false; $('sizeLabel').textContent = `${cellSizeKm.toLocaleString('es-ES', { maximumFractionDigits: 1 })} km`; $('featureCount').textContent = featureCount.toLocaleString('es-ES'); $('totalLength').textContent = `${(totalLengthM / 1000).toLocaleString('es-ES', { maximumFractionDigits: 2 })} km`; $('cellCount').textContent = output.length.toLocaleString('es-ES'); $('maxDensity').textContent = `${maxDensity.toLocaleString('es-ES', { maximumFractionDigits: 2 })} km/km²`; $('areaCount').textContent = `${totalAreaKm2.toLocaleString('es-ES', { maximumFractionDigits: 2 })} km²`; $('sampleCount').textContent = sampleCount.toLocaleString('es-ES'); $('interpretation').textContent = `La malla tiene ${output.length.toLocaleString('es-ES')} celdas y concentra la mayor intensidad en ${maxDensity.toLocaleString('es-ES', { maximumFractionDigits: 2 })} km de línea por km². Las celdas vacías se conservan para que el mapa no oculte los corredores sin presencia.`; $('geojsonBtn').disabled = $('csvBtn').disabled = false; renderTable(); renderMap(); setStatus(`${featureCount} entidades lineales y ${(totalLengthM / 1000).toLocaleString('es-ES', { maximumFractionDigits: 2 })} km procesados en ${output.length} celdas.`);
  }
  function cellFeature(cell) { return { type: 'Feature', properties: { cell_id: cell.id, length_km: Number(cell.lengthKm.toFixed(6)), density_km_per_km2: Number(cell.density.toFixed(6)), cell_area_km2: Number(cell.areaKm2.toFixed(6)), line_count: cell.features.size, cell_size_km: state.result.cellSizeKm, center_lon: Number(cell.centerLon.toFixed(8)), center_lat: Number(cell.centerLat.toFixed(8)) }, geometry: { type: 'Polygon', coordinates: [[[cell.minLon, cell.minLat], [cell.maxLon, cell.minLat], [cell.maxLon, cell.maxLat], [cell.minLon, cell.maxLat], [cell.minLon, cell.minLat]]] } }; }
  function popup(cell) { return `<strong>Celda ${cell.id}</strong><div class="popup-stat">${cell.lengthKm.toFixed(3)} km · ${cell.density.toFixed(3)} km/km² · ${cell.features.size} líneas</div>`; }
  function renderTable() { $('resultsBody').innerHTML = [...state.result.cells].sort((a, b) => b.density - a.density).slice(0, 40).map((cell) => `<tr><td>${cell.id}</td><td>${cell.lengthKm.toFixed(3)}</td><td>${cell.density.toFixed(3)}</td><td>${cell.features.size}</td><td>${cell.centerLon.toFixed(5)}</td><td>${cell.centerLat.toFixed(5)}</td></tr>`).join(''); }
  function renderMap() { if (!state.map || !state.result) return; state.cellLayer?.remove(); state.lineLayer?.remove(); state.cellLayer = L.geoJSON({ type: 'FeatureCollection', features: state.result.cells.map(cellFeature) }, { style: (feature) => ({ color: '#ffffff', weight: 0.5, opacity: .35, fillColor: colorFor(feature.properties.density_km_per_km2, state.result.maxDensity), fillOpacity: feature.properties.density_km_per_km2 ? .68 : .06 }), onEachFeature: (feature, layer) => layer.bindPopup(popup(state.result.cells[feature.properties.cell_id - 1])) }); state.cellLayer.addTo(state.map); state.lineLayer = L.geoJSON(state.source, { style: { color: '#9ce6ff', weight: 2.5, opacity: .9 } }).addTo(state.map); const bounds = L.latLngBounds([[state.result.box.minLat, state.result.box.minLon], [state.result.box.maxLat, state.result.box.maxLon]]); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 15 }); }
  function prepare(input, filename = 'Ejemplo · líneas de referencia') { const normalized = normalize(input); if (!normalized.features.length) throw new Error('La capa no contiene entidades.'); state.source = normalized; state.features = normalized.features.filter(Boolean); $('fileName').textContent = filename; $('runBtn').disabled = false; calculate(); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function exportGeoJSON() { if (!state.result) return; download('line-density-lab-cells.geojson', JSON.stringify({ type: 'FeatureCollection', features: state.result.cells.map(cellFeature) }, null, 2), 'application/geo+json'); }
  function downloadCsv() { if (!state.result) return; const rows = [['cell_id', 'length_km', 'density_km_per_km2', 'cell_area_km2', 'line_count', 'center_lon', 'center_lat'], ...state.result.cells.map((cell) => [cell.id, cell.lengthKm, cell.density, cell.areaKm2, cell.features.size, cell.centerLon, cell.centerLat])]; download('line-density-lab.csv', rows.map((row) => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function reset() { state.source = null; state.features = []; state.result = null; $('fileInput').value = ''; $('fileName').textContent = 'Ningún archivo seleccionado'; $('runBtn').disabled = true; $('summary').hidden = true; $('tablePanel').hidden = true; $('geojsonBtn').disabled = $('csvBtn').disabled = true; state.cellLayer?.remove(); state.lineLayer?.remove(); state.cellLayer = state.lineLayer = null; setStatus('Carga líneas GeoJSON o usa el ejemplo.'); }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 11); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } try { prepare(JSON.parse(await file.text()), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer el GeoJSON.', true); } }); $('cellSize').addEventListener('change', () => { if (state.source) { try { calculate(); } catch (error) { setStatus(error.message, true); } } }); $('palette').addEventListener('change', () => { if (state.result) { renderMap(); } }); $('exampleBtn').addEventListener('click', () => { try { prepare(example); } catch (error) { setStatus(error.message, true); } }); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', () => { try { calculate(); } catch (error) { setStatus(error.message, true); } }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', downloadCsv);
  initMap();
})();
