(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const state = { width: 720, height: 460, sourceData: null, maskData: null, target: { r: 80, g: 150, b: 110 }, report: null };
  const modeNames = { brightness: 'brillo', red: 'dominancia roja', green: 'dominancia verde', blue: 'dominancia azul', saturation: 'saturación', distance: 'distancia al color' };

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function hsvSaturation(r, g, b) { const max = Math.max(r, g, b), min = Math.min(r, g, b); return max === 0 ? 0 : (max - min) / max * 100; }
  function metric(r, g, b, mode) { if (mode === 'brightness') return (r + g + b) / 3; if (mode === 'red') return r - (g + b) / 2 + 127.5; if (mode === 'green') return g - (r + b) / 2 + 127.5; if (mode === 'blue') return b - (r + g) / 2 + 127.5; return hsvSaturation(r, g, b); }
  function colorDistance(r, g, b) { return Math.sqrt((r - state.target.r) ** 2 + (g - state.target.g) ** 2 + (b - state.target.b) ** 2); }
  function drawExample() { const canvas = $('sourceCanvas'), context = canvas.getContext('2d'), gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height); gradient.addColorStop(0, '#153f5b'); gradient.addColorStop(.5, '#63b790'); gradient.addColorStop(1, '#e5a456'); context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height); [[170,150,100,'#b96b45'],[480,190,140,'#4d9c76'],[335,350,170,'#d3dc86']].forEach(([x,y,r,color]) => { context.beginPath(); context.arc(x,y,r,0,Math.PI*2); context.fillStyle=color; context.globalAlpha=.9; context.fill(); context.globalAlpha=1; }); const image = context.getImageData(0,0,canvas.width,canvas.height); state.width = canvas.width; state.height = canvas.height; state.sourceData = image; }
  function drawMask(maskData) { const canvas = $('maskCanvas'), context = canvas.getContext('2d'); context.putImageData(maskData, 0, 0); }
  function readImage(file) { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = $('sourceCanvas'), scale = Math.min(canvas.width / image.width, canvas.height / image.height), width = Math.max(1, Math.round(image.width * scale)), height = Math.max(1, Math.round(image.height * scale)), context = canvas.getContext('2d'); context.clearRect(0,0,canvas.width,canvas.height); context.fillStyle = '#07131c'; context.fillRect(0,0,canvas.width,canvas.height); context.drawImage(image, (canvas.width-width)/2, (canvas.height-height)/2, width, height); state.width = canvas.width; state.height = canvas.height; state.sourceData = context.getImageData(0,0,canvas.width,canvas.height); calculate(); }; image.onerror = () => setStatus('La imagen no se pudo decodificar en el navegador.', true); image.src = String(reader.result || ''); }; reader.onerror = () => setStatus('No se pudo leer la imagen local.', true); reader.readAsDataURL(file); }
  function calculate() { try { if (!state.sourceData) drawExample(); const mode = $('mode').value, lower = numberForMode($('lower').value, mode), upper = numberForMode($('upper').value, mode), tolerance = Math.max(0, Number($('targetTolerance').value) || 0), mask = new ImageData(state.width, state.height), source = state.sourceData.data; let matched = 0, minX = state.width, minY = state.height, maxX = -1, maxY = -1; for (let index = 0, pixel = 0; index < source.length; index += 4, pixel += 1) { const r = source[index], g = source[index + 1], b = source[index + 2], isEmpty = source[index + 3] < 10, value = mode === 'distance' ? colorDistance(r,g,b) : metric(r,g,b,mode), selected = !isEmpty && (mode === 'distance' ? value <= tolerance : value >= lower && value <= upper); if (selected) { matched += 1; const x = pixel % state.width, y = Math.floor(pixel / state.width); minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); mask.data[index] = 78; mask.data[index+1] = 221; mask.data[index+2] = 172; mask.data[index+3] = 255; } else { mask.data[index] = 7; mask.data[index+1] = 19; mask.data[index+2] = 28; mask.data[index+3] = 255; } } state.maskData = mask; state.report = { width: state.width, height: state.height, mode, modeLabel: modeNames[mode], lower, upper, tolerance, target: { ...state.target }, pixels: state.width * state.height, matched, percentage: matched / (state.width * state.height) * 100, bounds: matched ? { minX, minY, maxX, maxY, width: maxX - minX + 1, height: maxY - minY + 1 } : null }; drawMask(mask); updateTarget(); renderReport(); $('pngBtn').disabled = false; $('jsonBtn').disabled = false; $('csvBtn').disabled = false; $('quality').textContent = matched ? 'Listo' : 'Sin coincidencias'; $('quality').style.background = matched ? '#143747' : '#342c18'; $('quality').style.borderColor = matched ? '#346275' : '#725c2a'; $('quality').style.color = matched ? 'var(--accent)' : '#f4c56b'; setStatus(`${format(matched)} píxeles seleccionados (${format(state.report.percentage)}%). Todo el cálculo se ha ejecutado localmente.`); } catch (error) { setStatus(error.message || 'No se pudo crear la máscara.', true); } }
  function numberForMode(value, mode) { const max = mode === 'saturation' ? 100 : 255; return clamp(Number(value) || 0, 0, max); }
  function updateTarget() { $('targetSwatch').style.background = `rgb(${state.target.r},${state.target.g},${state.target.b})`; $('targetText').textContent = `Color objetivo: RGB ${state.target.r}, ${state.target.g}, ${state.target.b}`; }
  function renderReport() { const report = state.report; $('imageSize').textContent = `${report.width} × ${report.height}`; $('matchedPixels').textContent = format(report.matched, 0); $('matchedPercent').textContent = format(report.percentage) + '%'; $('maskBounds').textContent = report.bounds ? `${report.bounds.width} × ${report.bounds.height}` : '—'; $('activeMode').textContent = report.modeLabel; $('matchBadge').textContent = `${format(report.percentage)}%`; $('tableWrap').innerHTML = `<table><thead><tr><th>PARÁMETRO</th><th>VALOR</th></tr></thead><tbody><tr><td>Criterio</td><td>${report.modeLabel}</td></tr><tr><td>Rango</td><td>${report.mode === 'distance' ? 'tolerancia ' + format(report.tolerance) : format(report.lower) + ' – ' + format(report.upper)}</td></tr><tr><td>Píxeles totales</td><td>${format(report.pixels, 0)}</td></tr><tr><td>Color objetivo</td><td>RGB ${report.target.r}, ${report.target.g}, ${report.target.b}</td></tr><tr><td>Caja de coincidencias</td><td>${report.bounds ? `${report.bounds.minX},${report.bounds.minY} → ${report.bounds.maxX},${report.bounds.maxY}` : 'sin coincidencias'}</td></tr></tbody></table>`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportPng() { const link = document.createElement('a'); link.href = $('maskCanvas').toDataURL('image/png'); link.download = 'mascara-raster.png'; link.click(); }
  function exportJson() { download('informe-mascara-raster.json', JSON.stringify(state.report, null, 2), 'application/json;charset=utf-8'); }
  function csvCell(value) { const text = String(value ?? ''); return `"${text.replace(/"/g, '""')}"`; }
  function exportCsv() { const report = state.report, lines = ['parametro,valor', ['criterio', report.modeLabel], ['limite_inferior', report.lower], ['limite_superior', report.upper], ['tolerancia_color', report.tolerance], ['ancho_px', report.width], ['alto_px', report.height], ['pixeles_seleccionados', report.matched], ['porcentaje', report.percentage], ['color_objetivo_rgb', `${report.target.r},${report.target.g},${report.target.b}`], ['caja_pixeles', report.bounds ? `${report.bounds.minX},${report.bounds.minY},${report.bounds.maxX},${report.bounds.maxY}` : '']].map(row => row.map(csvCell).join(',')); download('resumen-mascara-raster.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  $('calculateBtn').addEventListener('click', calculate); $('sampleBtn').addEventListener('click', () => { $('sourceCanvas').width = 720; $('sourceCanvas').height = 460; drawExample(); calculate(); }); $('mode').addEventListener('change', calculate); $('lower').addEventListener('change', calculate); $('upper').addEventListener('change', calculate); $('targetTolerance').addEventListener('change', calculate);
  $('sourceCanvas').addEventListener('click', event => { const rect = $('sourceCanvas').getBoundingClientRect(), x = clamp(Math.floor((event.clientX - rect.left) / rect.width * state.width), 0, state.width - 1), y = clamp(Math.floor((event.clientY - rect.top) / rect.height * state.height), 0, state.height - 1), index = (y * state.width + x) * 4, data = state.sourceData.data; state.target = { r: data[index], g: data[index+1], b: data[index+2] }; updateTarget(); if ($('mode').value === 'distance') calculate(); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (file) readImage(file); }); $('pngBtn').addEventListener('click', exportPng); $('jsonBtn').addEventListener('click', exportJson); $('csvBtn').addEventListener('click', exportCsv); drawExample(); updateTarget(); calculate();
})();
