(() => {
  'use strict';
  const map = L.map('map').setView([40.32, -3.7], 5); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
  const state = { service: '', layers: [], selected: null, preview: null, response: null, click: null };
  const els = { service: document.getElementById('serviceInput'), inspect: document.getElementById('inspectBtn'), clear: document.getElementById('clearBtn'), demo: document.getElementById('demoBtn'), status: document.getElementById('status'), select: document.getElementById('layerSelect'), meta: document.getElementById('layerMeta'), format: document.getElementById('infoFormat'), mapTitle: document.getElementById('mapTitle'), mapStatus: document.getElementById('mapStatus'), info: document.getElementById('infoWrap'), json: document.getElementById('jsonBtn'), txt: document.getElementById('txtBtn') };
  const setStatus = (text, error = false) => { els.status.textContent = text; els.status.classList.toggle('error', error); };
  const textOf = (node, localName) => [...node.children].find(child => child.localName === localName)?.textContent?.trim() || '';
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const normaliseService = () => { const url = new URL(els.service.value.trim()); if (!['http:', 'https:'].includes(url.protocol)) throw new Error('La URL debe comenzar por http o https.'); url.hash = ''; return url; };
  function parseLayers(xml) { return [...xml.querySelectorAll('Layer')].map(node => { const childLayers = [...node.children].some(child => child.localName === 'Layer'), name = textOf(node, 'Name'); return { name, title: textOf(node, 'Title'), abstract: textOf(node, 'Abstract'), crs: textOf(node, 'SRS') || textOf(node, 'CRS'), queryable: node.getAttribute('queryable') === '1', leaf: !childLayers }; }).filter((layer, index, all) => layer.leaf && layer.name && all.findIndex(item => item.name === layer.name) === index); }
  function renderMeta() { const layer = state.layers.find(item => item.name === state.selected); els.meta.replaceChildren(); if (!layer) { const empty = document.createElement('span'); empty.textContent = 'El nombre y la capacidad de consulta aparecerán aquí.'; els.meta.appendChild(empty); return; } const title = document.createElement('b'); title.textContent = layer.title || layer.name; const name = document.createElement('p'); name.textContent = `Nombre WMS: ${layer.name}`; const queryable = document.createElement('p'); queryable.textContent = `GetFeatureInfo: ${layer.queryable ? 'disponible según capacidades' : 'no declarado'}`; const crs = document.createElement('p'); crs.textContent = `CRS: ${layer.crs || 'no indicado'}`; els.meta.append(title, name, queryable, crs); }
  function renderLayers() { els.select.replaceChildren(); if (!state.layers.length) { const option = document.createElement('option'); option.textContent = 'No hay capas descubiertas'; els.select.appendChild(option); els.select.disabled = true; return; } state.layers.forEach(layer => { const option = document.createElement('option'); option.value = layer.name; option.textContent = `${layer.title || layer.name}${layer.queryable ? ' · consultable' : ''}`; els.select.appendChild(option); }); els.select.disabled = false; state.selected = state.layers.find(layer => layer.queryable)?.name || state.layers[0].name; els.select.value = state.selected; renderMeta(); preview(); }
  async function inspect() { try { const service = normaliseService(), request = new URL(service); request.searchParams.set('service', 'WMS'); request.searchParams.set('request', 'GetCapabilities'); request.searchParams.set('version', '1.1.1'); els.inspect.disabled = true; setStatus('Consultando GetCapabilities…'); const response = await fetch(request, { headers: { Accept: 'application/vnd.ogc.wms_xml,application/xml,text/xml' } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const xml = new DOMParser().parseFromString(await response.text(), 'text/xml'); if (xml.querySelector('parsererror')) throw new Error('XML no válido'); state.service = service.toString(); state.layers = parseLayers(xml); if (!state.layers.length) throw new Error('No se encontraron capas hoja con nombre.'); renderLayers(); setStatus(`${state.layers.length} capas descubiertas; selecciona una y cárgala en el mapa.`); } catch (error) { state.layers = []; renderLayers(); setStatus(error.message === 'Failed to fetch' ? 'El navegador ha bloqueado la consulta CORS o el servicio no responde.' : `No se pudo leer el WMS: ${error.message}`, true); } finally { els.inspect.disabled = false; } }
  function preview() { const layer = state.layers.find(item => item.name === state.selected); if (!layer || !state.service) return; state.preview?.remove(); state.preview = L.tileLayer.wms(state.service, { layers: layer.name, format: 'image/png', transparent: true, version: '1.1.1', srs: 'EPSG:4326', opacity: .78, attribution: layer.title || layer.name }).addTo(map); els.mapTitle.textContent = layer.title || layer.name; els.mapStatus.textContent = `Capa ${layer.name} cargada. Haz clic para consultar.`; }
  function renderResponse(payload, contentType) { const isHtml = contentType.includes('html'), doc = isHtml ? new DOMParser().parseFromString(payload, 'text/html') : null; if (isHtml && doc?.querySelectorAll('table tr').length) { const rows = [...doc.querySelectorAll('table tr')].map(row => [...row.children].map(cell => cell.textContent.trim())); els.info.innerHTML = `<table class="result-table"><tbody>${rows.map(row => `<tr>${row.map((cell, index) => `<${index === 0 ? 'th' : 'td'}>${escapeHtml(cell)}</${index === 0 ? 'th' : 'td'}>`).join('')}</tr>`).join('')}</tbody></table>`; return; } els.info.innerHTML = `<pre>${escapeHtml(payload)}</pre>`; }
  async function identify(event) { const layer = state.layers.find(item => item.name === state.selected); if (!layer || !state.service) { setStatus('Lee las capas y selecciona una antes de consultar.', true); return; } try { const size = map.getSize(), point = map.latLngToContainerPoint(event.latlng), bounds = map.getBounds(), request = new URL(state.service); request.searchParams.set('service', 'WMS'); request.searchParams.set('version', '1.1.1'); request.searchParams.set('request', 'GetFeatureInfo'); request.searchParams.set('layers', layer.name); request.searchParams.set('query_layers', layer.name); request.searchParams.set('styles', ''); request.searchParams.set('srs', 'EPSG:4326'); request.searchParams.set('bbox', [bounds.getWest(), bounds.getSouth(), bounds.getEast(), bounds.getNorth()].join(',')); request.searchParams.set('width', String(size.x)); request.searchParams.set('height', String(size.y)); request.searchParams.set('x', String(Math.round(point.x))); request.searchParams.set('y', String(Math.round(point.y))); request.searchParams.set('info_format', els.format.value); request.searchParams.set('feature_count', '10'); setStatus('Consultando GetFeatureInfo en la posición clicada…'); const response = await fetch(request, { headers: { Accept: els.format.value } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const contentType = response.headers.get('content-type') || els.format.value, payload = await response.text(); state.click = { latitude: event.latlng.lat, longitude: event.latlng.lng, layer: layer.name, requestedFormat: els.format.value, responseType: contentType, requestedAt: new Date().toISOString(), url: request.toString() }; state.response = { metadata: state.click, payload }; document.getElementById('clickPosition').textContent = `${event.latlng.lat.toFixed(4)}, ${event.latlng.lng.toFixed(4)}`; document.getElementById('responseType').textContent = contentType.split(';')[0]; document.getElementById('responseTime').textContent = new Date().toLocaleTimeString('es-ES'); document.getElementById('resultBadge').textContent = payload.trim() ? 'Respuesta recibida' : 'Sin entidades'; renderResponse(payload || 'El servicio respondió sin entidades en esta posición.', contentType); els.json.disabled = false; els.txt.disabled = false; setStatus(payload.trim() ? 'Respuesta GetFeatureInfo recibida.' : 'El servicio respondió correctamente, pero no hay entidades en el píxel consultado.'); } catch (error) { setStatus(error.message === 'Failed to fetch' ? 'El navegador ha bloqueado GetFeatureInfo por CORS o el servicio no responde.' : `No se pudo consultar la entidad: ${error.message}`, true); } }
  function reset() { state.preview?.remove(); state.preview = null; state.layers = []; state.selected = null; state.response = null; renderLayers(); els.mapTitle.textContent = 'Mapa base'; els.mapStatus.textContent = 'Mapa base listo.'; els.info.innerHTML = '<p class="empty">Haz clic sobre una entidad de la capa para consultar sus atributos.</p>'; ['jsonBtn','txtBtn'].forEach(id => { document.getElementById(id).disabled = true; }); setStatus('Inventario limpiado.'); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  els.inspect.addEventListener('click', inspect); els.demo.addEventListener('click', () => { els.service.value = 'https://demo.mapserver.org/cgi-bin/wms'; inspect(); }); els.select.addEventListener('change', () => { state.selected = els.select.value; renderMeta(); preview(); }); els.clear.addEventListener('click', reset); map.on('click', identify); els.json.addEventListener('click', () => download('respuesta-wms-getfeatureinfo.json', JSON.stringify(state.response, null, 2), 'application/json;charset=utf-8')); els.txt.addEventListener('click', () => download('respuesta-wms-getfeatureinfo.txt', `${JSON.stringify(state.response.metadata, null, 2)}\n\n${state.response.payload}`, 'text/plain;charset=utf-8'));
  CartografiaPlaceSearch(map, { input: document.getElementById('placeQuery'), button: document.getElementById('placeSearchButton'), results: document.getElementById('placeResults'), status: document.getElementById('placeStatus'), zoom: 13 });
})();
