(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { map: null, layer: null, features: [], selected: null, collections: [] };
  function apiBase() { return $('apiUrl').value.trim().replace(/\/+$/, ''); }
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString('es-ES', { dateStyle: 'medium', timeStyle: 'short' }); }
  function formatNumber(value, digits = 1) { return Number.isFinite(Number(value)) ? Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }) : '—'; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  async function request(path, options = {}) { const response = await fetch(`${apiBase()}${path}`, { ...options, headers: { Accept: 'application/json', ...(options.headers || {}) } }); if (!response.ok) throw new Error(`El catálogo respondió HTTP ${response.status}. Comprueba la URL y CORS.`); return response.json(); }
  function parseBbox() { const values = ['west', 'south', 'east', 'north'].map((id) => Number($(id).value)); if (values.some((value) => !Number.isFinite(value)) || values[0] < -180 || values[2] > 180 || values[1] < -90 || values[3] > 90 || values[0] >= values[2] || values[1] >= values[3]) throw new Error('La caja debe ser W,S,E,N válida y estar dentro de lon/lat.'); return values; }
  async function loadCollections() { setStatus('Cargando colecciones STAC…'); try { const data = await request('/collections'); state.collections = data.collections || []; $('collectionSelect').innerHTML = '<option value="">Todas las colecciones</option>' + state.collections.map((collection) => `<option value="${escapeHtml(collection.id)}">${escapeHtml(collection.title || collection.id)}</option>`).join(''); setStatus(`${state.collections.length.toLocaleString('es-ES')} colecciones cargadas.`); } catch (error) { setStatus(error.message || 'No se pudieron cargar las colecciones.', true); } }
  function searchBody() { const body = { bbox: parseBbox(), limit: Math.max(1, Math.min(100, Number($('limit').value) || 50)), sortby: [{ field: 'properties.datetime', direction: $('sortSelect').value.endsWith(':asc') ? 'asc' : 'desc' }] }; const collection = $('collectionSelect').value; if (collection) body.collections = [collection]; const start = $('dateStart').value; const end = $('dateEnd').value; if (start || end) body.datetime = `${start || '..'}/${end || '..'}`; const cloud = Number($('cloudMax').value); if (Number.isFinite(cloud)) body.query = { 'eo:cloud_cover': { lte: Math.max(0, Math.min(100, cloud)) } }; return body; }
  function featureGeometry(feature) { return feature?.geometry && ['Polygon', 'MultiPolygon', 'Point'].includes(feature.geometry.type) ? feature.geometry : null; }
  function cloud(feature) { const value = feature?.properties?.['eo:cloud_cover'] ?? feature?.properties?.cloud_cover; return Number.isFinite(Number(value)) ? Number(value) : null; }
  function renderSummary() { const features = state.features; const collections = new Set(features.map((feature) => feature.collection).filter(Boolean)); const dated = features.filter((feature) => feature.properties?.datetime || feature.properties?.start_datetime).length; const geometry = features.filter(featureGeometry).length; $('summary').hidden = false; $('itemCount').textContent = features.length.toLocaleString('es-ES'); $('collectionCount').textContent = collections.size.toLocaleString('es-ES'); $('datedCount').textContent = dated.toLocaleString('es-ES'); $('geometryCount').textContent = geometry.toLocaleString('es-ES'); $('summaryBadge').textContent = features.length ? 'consulta completada' : 'sin resultados'; $('summaryText').textContent = features.length ? `Se han recibido ${features.length.toLocaleString('es-ES')} escenas. El catálogo puede devolver más resultados mediante paginación; esta vista conserva hasta ${$('limit').value} por consulta.` : 'No hay escenas que coincidan con la extensión y filtros indicados.'; $('mapBadge').textContent = `${geometry.toLocaleString('es-ES')} huellas`; $('resultsBadge').textContent = `${features.length.toLocaleString('es-ES')} escenas`; }
  function renderTable() { $('resultsPanel').hidden = false; $('resultsBody').innerHTML = state.features.length ? state.features.map((feature, index) => { const properties = feature.properties || {}; const assets = Object.keys(feature.assets || {}); const title = feature.properties?.title || feature.id || `Escena ${index + 1}`; const collection = feature.collection || '—'; const itemCloud = cloud(feature); return `<tr data-index="${index}"><th>${escapeHtml(title)}</th><td>${escapeHtml(collection)}</td><td>${escapeHtml(formatDate(properties.datetime || properties.start_datetime))}</td><td>${itemCloud === null ? '—' : `${formatNumber(itemCloud)} %`}</td><td>${assets.length.toLocaleString('es-ES')}</td></tr>`; }).join('') : '<tr><td colspan="5">No hay resultados.</td></tr>'; [...$('resultsBody').querySelectorAll('tr[data-index]')].forEach((row) => row.addEventListener('click', () => selectFeature(Number(row.dataset.index)))); }
  function selectFeature(index) { const feature = state.features[index]; if (!feature) return; state.selected = feature; $('detail').hidden = false; $('detailTitle').textContent = feature.properties?.title || feature.id || 'Escena STAC'; $('detailMeta').textContent = `${feature.collection || 'sin colección'} · ${formatDate(feature.properties?.datetime || feature.properties?.start_datetime)} · ${cloud(feature) === null ? 'nubosidad no disponible' : `nubosidad ${formatNumber(cloud(feature))} %`}`; $('assetList').innerHTML = Object.entries(feature.assets || {}).map(([key, asset]) => asset.href ? `<a href="${escapeHtml(asset.href)}" target="_blank" rel="noopener">${escapeHtml(key)}${asset.title ? ` · ${escapeHtml(asset.title)}` : ''}</a>` : '').join('') || '<span class="muted">La escena no publica enlaces de activos.</span>'; $('propertyDump').textContent = JSON.stringify({ id: feature.id, collection: feature.collection, properties: feature.properties, links: feature.links }, null, 2); state.map?.fitBounds(L.geoJSON(feature).getBounds(), { maxZoom: 13 }); }
  function renderMap() { if (!state.map) return; state.layer?.remove(); const features = state.features.filter(featureGeometry); state.layer = L.geoJSON({ type: 'FeatureCollection', features }, { style: (feature) => ({ color: feature === state.selected ? '#a33d50' : '#176b50', weight: feature === state.selected ? 4 : 2, fillColor: feature === state.selected ? '#e3a6b2' : '#7fc8a5', fillOpacity: .3 }), pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#176b50', fillColor: '#7fc8a5', fillOpacity: .72, weight: 2 }), onEachFeature: (feature, layer) => layer.on('click', () => selectFeature(state.features.indexOf(feature))) }).addTo(state.map); const bounds = state.layer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [30, 30], maxZoom: 12 }); }
  async function search() { try { const body = searchBody(); setStatus('Buscando escenas en el catálogo…'); const data = await request('/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); state.features = data.features || []; state.selected = null; renderSummary(); renderTable(); renderMap(); ['geoBtn', 'csvBtn', 'jsonBtn'].forEach((id) => $(id).disabled = !state.features.length); setStatus(`${state.features.length.toLocaleString('es-ES')} escenas recibidas.`); } catch (error) { setStatus(error.message || 'No se pudo completar la búsqueda.', true); } }
  function useMapExtent() { if (!state.map) return; const bounds = state.map.getBounds(); $('west').value = bounds.getWest().toFixed(5); $('south').value = bounds.getSouth().toFixed(5); $('east').value = bounds.getEast().toFixed(5); $('north').value = bounds.getNorth().toFixed(5); setStatus('Extensión visible copiada al formulario.'); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function geojson() { if (state.features.length) download('stac-search.geojson', JSON.stringify({ type: 'FeatureCollection', features: state.features }, null, 2), 'application/geo+json'); }
  function csv() { if (!state.features.length) return; const rows = [['id', 'collection', 'datetime', 'cloud_cover', 'geometry_type', 'asset_keys']]; state.features.forEach((feature) => rows.push([feature.id || '', feature.collection || '', feature.properties?.datetime || feature.properties?.start_datetime || '', cloud(feature) ?? '', feature.geometry?.type || '', Object.keys(feature.assets || {}).join('|')])); download('stac-search.csv', rows.map((row) => row.map((value) => /[",\n]/.test(String(value)) ? `"${String(value).replace(/"/g, '""')}"` : value).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function json() { if (state.features.length) download('stac-search.json', JSON.stringify({ type: 'FeatureCollection', features: state.features }, null, 2), 'application/json'); }
  function clear() { state.features = []; state.selected = null; state.layer?.remove(); state.layer = null; $('summary').hidden = $('resultsPanel').hidden = true; $('detail').hidden = true; ['geoBtn', 'csvBtn', 'jsonBtn'].forEach((id) => $(id).disabled = true); $('mapBadge').textContent = '—'; setStatus('Carga las colecciones o ejecuta una nueva búsqueda.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.4, -3.7], 6); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('collectionsBtn').addEventListener('click', loadCollections); $('searchBtn').addEventListener('click', search); $('mapExtentBtn').addEventListener('click', useMapExtent); $('clearBtn').addEventListener('click', clear); $('geoBtn').addEventListener('click', geojson); $('csvBtn').addEventListener('click', csv); $('jsonBtn').addEventListener('click', json); initMap();
})();
