(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { parsed: null, features: [], symbols: [], field: '', scale: '', map: null, layer: null, minValue: 0, maxValue: 0 };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function number(value) { const parsed = Number(String(value ?? '').replace(',', '.')); return Number.isFinite(parsed) ? parsed : null; }
  function parseSource(value) { const parsed = JSON.parse(value.trim()), features = parsed.type === 'FeatureCollection' ? parsed.features : parsed.type === 'Feature' ? [parsed] : [{ type: 'Feature', properties: {}, geometry: parsed }], valid = []; features.forEach((feature, index) => { if (feature?.geometry?.type === 'Point' && Array.isArray(feature.geometry.coordinates)) { const lon = number(feature.geometry.coordinates[0]), lat = number(feature.geometry.coordinates[1]); if (Number.isFinite(lon) && Number.isFinite(lat) && lon >= -180 && lon <= 180 && lat >= -90 && lat <= 90) valid.push({ feature, index, lon, lat, properties: feature.properties || {} }); } }); if (!valid.length) throw new Error('No se encontraron entidades Point válidas.'); return { parsed, features: valid }; }
  function fieldsFor(features) { const fields = new Set(); features.forEach(item => Object.keys(item.properties).forEach(field => fields.add(field))); return [...fields]; }
  function refreshFields(features) { const fields = fieldsFor(features), current = $('field').value, numericFields = fields.filter(field => features.some(item => number(item.properties[field]) !== null)); $('field').innerHTML = numericFields.map(field => `<option value="${esc(field)}">${esc(field)}</option>`).join(''); const preferred = numericFields.find(field => field === current) || numericFields.find(field => /valor|value|pobl|habit|count|cantidad|area|total/i.test(field)) || numericFields[0]; if (preferred) $('field').value = preferred; if (!numericFields.length) throw new Error('La capa no contiene atributos numéricos seleccionables.'); }
  function transform(value, min, max, mode) { if (max === min) return .5; const range = max - min; if (mode === 'linear') return (value - min) / range; if (mode === 'log') return Math.log(value - min + 1) / Math.log(range + 1); return Math.sqrt(Math.max(0, value - min) / range); }
  function calculate() { try { const parsed = parseSource($('source').value); refreshFields(parsed.features); const field = $('field').value, values = parsed.features.map(item => number(item.properties[field])).filter(value => value !== null), minValue = Math.min(...values), maxValue = Math.max(...values), minRadius = Math.max(1, Math.min(80, Number($('minRadius').value) || 5)), maxRadius = Math.max(minRadius + 1, Math.min(120, Number($('maxRadius').value) || 30)), scale = $('scale').value, symbols = parsed.features.map(item => { const value = number(item.properties[field]); const normalized = value === null ? 0 : transform(value, minValue, maxValue, scale); return { ...item, value, normalized, radius: value === null ? minRadius : minRadius + normalized * (maxRadius - minRadius) }; }); state.parsed = parsed.parsed; state.features = parsed.features; state.symbols = symbols; state.field = field; state.scale = scale; state.minValue = minValue; state.maxValue = maxValue; renderMap(); renderLegend(); renderTable(); updateStats(values); $('geojsonBtn').disabled = false; $('styleBtn').disabled = false; $('quality').textContent = values.length === parsed.features.length ? 'Listo' : 'Revisar nulos'; $('quality').style.background = values.length === parsed.features.length ? '#143747' : '#342c18'; $('quality').style.borderColor = values.length === parsed.features.length ? '#346275' : '#725c2a'; $('quality').style.color = values.length === parsed.features.length ? 'var(--accent)' : '#f4c56b'; setStatus(`${symbols.length} puntos simbolizados con el campo «${field}».`); } catch (error) { setStatus(error.message || 'No se pudo simbolizar la capa.', true); } }
  function initMap() { if (!window.L) return; state.map = L.map('map').setView([40.418, -3.703], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer) return; state.layer.clearLayers(); const color = $('fillColor').value, bounds = []; state.symbols.forEach((symbol, index) => { const marker = L.circleMarker([symbol.lat, symbol.lon], { radius: symbol.radius, color, fillColor: color, fillOpacity: .72, weight: 2 }); marker.bindPopup(`<strong>${esc(symbol.properties.nombre || symbol.properties.name || `Punto ${index + 1}`)}</strong><br>${esc(state.field)}: ${format(symbol.value)}<br>Radio: ${format(symbol.radius)} px`).addTo(state.layer); bounds.push([symbol.lat, symbol.lon]); }); if (bounds.length) state.map.fitBounds(bounds, { padding: [26, 26], maxZoom: 15 }); }
  function renderLegend() { const color = $('fillColor').value, mid = state.minValue + (state.maxValue - state.minValue) / 2; $('legend').innerHTML = `<div class="legend-title"><strong>${esc(state.field)}</strong><span>${esc(state.scale === 'sqrt' ? 'Raíz cuadrada' : state.scale === 'log' ? 'Logarítmica' : 'Lineal')}</span></div><div class="bubble-legend"><div class="bubble-wrap"><span class="bubble large" style="background:${esc(color)}"></span><span>${format(state.maxValue)}</span></div><div class="bubble-wrap"><span class="bubble medium" style="background:${esc(color)}"></span><span>${format(mid)}</span></div><div class="bubble-wrap"><span class="bubble small" style="background:${esc(color)}"></span><span>${format(state.minValue)}</span></div></div>`; }
  function renderTable() { $('tableWrap').innerHTML = `<table><thead><tr><th>#</th><th>ENTIDAD</th><th>VALOR</th><th>NORMALIZADO</th><th>RADIO</th></tr></thead><tbody>${state.symbols.map((symbol, index) => `<tr><td>${index + 1}</td><td>${esc(symbol.properties.nombre || symbol.properties.name || `Punto ${index + 1}`)}</td><td>${format(symbol.value)}</td><td>${format(symbol.normalized * 100)}%</td><td>${format(symbol.radius)} px</td></tr>`).join('')}</tbody></table>`; }
  function updateStats(values) { const sum = values.reduce((total, value) => total + value, 0); $('pointCount').textContent = state.symbols.length; $('sumValue').textContent = format(sum); $('meanValue').textContent = format(sum / values.length); $('minValue').textContent = format(state.minValue); $('maxValue').textContent = format(state.maxValue); $('pointBadge').textContent = `${state.symbols.length} puntos`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportGeoJSON() { const features = state.symbols.map(symbol => ({ ...symbol.feature, properties: { ...(symbol.feature.properties || {}), _symbol_field: state.field, _symbol_value: symbol.value, _symbol_scale: state.scale, _symbol_normalized: symbol.normalized, _symbol_radius_px: symbol.radius } })); download('capa-simbolos-proporcionales.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json;charset=utf-8'); }
  function exportStyle() { const specification = { type: 'cartografia-web-tools-proportional-symbols', field: state.field, scale: state.scale, minValue: state.minValue, maxValue: state.maxValue, minRadiusPx: Number($('minRadius').value), maxRadiusPx: Number($('maxRadius').value), color: $('fillColor').value }; download('estilo-simbolos-proporcionales.json', JSON.stringify(specification, null, 2), 'application/json;charset=utf-8'); }
  $('calculateBtn').addEventListener('click', calculate); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; calculate(); }); $('field').addEventListener('change', calculate); $('scale').addEventListener('change', calculate); $('minRadius').addEventListener('change', calculate); $('maxRadius').addEventListener('change', calculate); $('fillColor').addEventListener('input', () => { if (state.symbols.length) { renderMap(); renderLegend(); } });
  $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); calculate(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('styleBtn').addEventListener('click', exportStyle); initMap(); calculate();
})();
