(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const state = { width: 720, height: 460, sourceData: null, rois: [], draft: null, report: null };
  const colors = ['#73e0ba', '#ffd166', '#8ab4f8', '#f78fb3', '#c7f464', '#d3a7ff', '#ff9f68', '#71d7e6', '#f2b5d4', '#b5ead7', '#ffcb77', '#a0c4ff'];

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function drawExample() { const canvas = $('canvas'), context = canvas.getContext('2d'), gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height); gradient.addColorStop(0, '#132f55'); gradient.addColorStop(.42, '#45a777'); gradient.addColorStop(.73, '#d9bf68'); gradient.addColorStop(1, '#a95b4d'); context.fillStyle = gradient; context.fillRect(0, 0, canvas.width, canvas.height); [[145,145,82,'#e3df87'],[480,180,120,'#314d88'],[330,350,150,'#e18465']].forEach(([x,y,r,color]) => { context.beginPath(); context.arc(x,y,r,0,Math.PI*2); context.fillStyle=color; context.globalAlpha=.9; context.fill(); context.globalAlpha=1; }); state.width = canvas.width; state.height = canvas.height; state.sourceData = context.getImageData(0, 0, state.width, state.height); state.rois = []; state.draft = null; render(); setStatus('La imagen sintética está lista. Arrastra para crear la primera ROI.'); }
  function loadImage(file) { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = $('canvas'), context = canvas.getContext('2d'), scale = Math.min(canvas.width / image.width, canvas.height / image.height), width = Math.max(1, Math.round(image.width * scale)), height = Math.max(1, Math.round(image.height * scale)); context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#07131c'; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, (canvas.width - width) / 2, (canvas.height - height) / 2, width, height); state.width = canvas.width; state.height = canvas.height; state.sourceData = context.getImageData(0, 0, state.width, state.height); state.rois = []; state.draft = null; render(); setStatus('Imagen cargada localmente. Arrastra para añadir una ROI.'); }; image.onerror = () => setStatus('La imagen no se pudo decodificar en el navegador.', true); image.src = String(reader.result || ''); }; reader.onerror = () => setStatus('No se pudo leer la imagen local.', true); reader.readAsDataURL(file); }
  function canvasPoint(event) { const rect = $('canvas').getBoundingClientRect(); return { x: clamp((event.clientX - rect.left) / rect.width * state.width, 0, state.width), y: clamp((event.clientY - rect.top) / rect.height * state.height, 0, state.height) }; }
  function normalizeRect(a, b) { const x = Math.round(Math.min(a.x, b.x)), y = Math.round(Math.min(a.y, b.y)), width = Math.round(Math.abs(a.x - b.x)), height = Math.round(Math.abs(a.y - b.y)); return { x, y, width, height }; }
  function addRoi(rect, label = '') { const minimum = Math.max(2, Number($('minSize').value) || 8); if (rect.width < minimum || rect.height < minimum) { setStatus(`La ROI es demasiado pequeña. Usa al menos ${minimum} px por lado.`, true); return; } if (state.rois.length >= 12) { setStatus('Se ha alcanzado el máximo de 12 regiones para mantener la interacción fluida.', true); return; } state.rois.push({ id: state.rois.length + 1, label: label || `ROI ${state.rois.length + 1}`, ...rect }); render(); setStatus(`${state.rois.length} ROI preparada. Puedes añadir otra arrastrando sobre la imagen.`); }
  function statsFor(roi) { const data = state.sourceData.data, startX = roi.x, endX = Math.min(state.width, roi.x + roi.width), startY = roi.y, endY = Math.min(state.height, roi.y + roi.height); let pixels = 0, sumR = 0, sumG = 0, sumB = 0, sumL = 0, sumL2 = 0, minL = 255, maxL = 0; for (let y = startY; y < endY; y += 1) for (let x = startX; x < endX; x += 1) { const index = (y * state.width + x) * 4, alpha = data[index + 3]; if (alpha < 10 && $('alphaMode').value === 'skip') continue; const r = alpha < 10 ? 0 : data[index], g = alpha < 10 ? 0 : data[index + 1], b = alpha < 10 ? 0 : data[index + 2], luminance = (r + g + b) / 3; pixels += 1; sumR += r; sumG += g; sumB += b; sumL += luminance; sumL2 += luminance ** 2; minL = Math.min(minL, luminance); maxL = Math.max(maxL, luminance); } const mean = pixels ? sumL / pixels : 0; return { ...roi, pixels, meanR: pixels ? sumR / pixels : 0, meanG: pixels ? sumG / pixels : 0, meanB: pixels ? sumB / pixels : 0, meanBrightness: mean, stdBrightness: pixels ? Math.sqrt(Math.max(0, sumL2 / pixels - mean ** 2)) : 0, minBrightness: pixels ? minL : null, maxBrightness: pixels ? maxL : null }; }
  function render() { const canvas = $('canvas'), context = canvas.getContext('2d'); if (!state.sourceData) drawExample(); else context.putImageData(state.sourceData, 0, 0); state.report = state.rois.map(statsFor); state.rois.forEach((roi, index) => { context.fillStyle = `${colors[index]}22`; context.strokeStyle = colors[index]; context.lineWidth = 3; context.fillRect(roi.x, roi.y, roi.width, roi.height); context.strokeRect(roi.x + 1, roi.y + 1, Math.max(0, roi.width - 2), Math.max(0, roi.height - 2)); context.fillStyle = colors[index]; context.font = '700 14px system-ui'; context.fillText(roi.label, roi.x + 7, Math.max(17, roi.y + 17)); }); if (state.draft) { context.setLineDash([6, 4]); context.strokeStyle = '#fff'; context.lineWidth = 2; context.strokeRect(state.draft.x, state.draft.y, state.draft.width, state.draft.height); context.setLineDash([]); } renderReport(); }
  function renderReport() { const report = state.report || [], validPixels = report.reduce((sum, item) => sum + item.pixels, 0), mean = report.length ? report.reduce((sum, item) => sum + item.meanBrightness * item.pixels, 0) / Math.max(1, validPixels) : null; $('roiBadge').textContent = `${report.length} ROI`; $('imageSize').textContent = `${state.width} × ${state.height}`; $('roiCount').textContent = format(report.length, 0); $('pixelCount').textContent = format(validPixels, 0); $('meanBrightness').textContent = mean === null ? '—' : format(mean); $('quality').textContent = report.length ? 'Listo' : 'Pendiente'; $('quality').className = report.length ? 'quality ready' : 'quality'; $('jsonBtn').disabled = !report.length; $('csvBtn').disabled = !report.length; if (!report.length) { $('tableWrap').innerHTML = '<p class="empty">Crea una ROI para revisar sus estadísticas.</p>'; return; } $('tableWrap').innerHTML = `<table><thead><tr><th>ROI</th><th>ÁREA PX</th><th>MEDIA RGB</th><th>BRILLO MEDIO</th><th>DESV. BRILLO</th><th>RANGO BRILLO</th><th></th></tr></thead><tbody>${report.map((item, index) => `<tr><td><span class="table-swatch" style="background:${colors[index]}"></span>${item.label}<small>${item.x},${item.y} · ${item.width}×${item.height}</small></td><td>${format(item.pixels, 0)}</td><td>${format(item.meanR)}, ${format(item.meanG)}, ${format(item.meanB)}</td><td>${format(item.meanBrightness)}</td><td>${format(item.stdBrightness)}</td><td>${item.minBrightness === null ? '—' : format(item.minBrightness) + ' – ' + format(item.maxBrightness)}</td><td><button class="remove-btn" data-id="${item.id}" aria-label="Eliminar ${item.label}">×</button></td></tr>`).join('')}</tbody></table>`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportJson() { download('informe-roi-raster.json', JSON.stringify({ width: state.width, height: state.height, transparency: $('alphaMode').value, regions: state.report }, null, 2), 'application/json;charset=utf-8'); }
  function csvCell(value) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }
  function exportCsv() { const rows = [['roi','x_px','y_px','ancho_px','alto_px','pixeles','media_r','media_g','media_b','brillo_medio','desv_brillo','brillo_min','brillo_max'], ...state.report.map(item => [item.label, item.x, item.y, item.width, item.height, item.pixels, item.meanR, item.meanG, item.meanB, item.meanBrightness, item.stdBrightness, item.minBrightness, item.maxBrightness])]; download('estadisticas-roi-raster.csv', '\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  $('canvas').addEventListener('pointerdown', event => { if (!state.sourceData) return; $('canvas').setPointerCapture(event.pointerId); state.draft = { x: canvasPoint(event).x, y: canvasPoint(event).y, width: 0, height: 0 }; render(); }); $('canvas').addEventListener('pointermove', event => { if (!state.draft) return; state.draft = normalizeRect({ x: state.draft.x, y: state.draft.y }, canvasPoint(event)); render(); }); $('canvas').addEventListener('pointerup', event => { if (!state.draft) return; const draft = state.draft; state.draft = null; addRoi(draft); render(); }); $('canvas').addEventListener('pointercancel', () => { state.draft = null; render(); });
  $('sampleBtn').addEventListener('click', drawExample); $('sampleRoiBtn').addEventListener('click', () => { addRoi({ x: 55, y: 55, width: 150, height: 120 }, 'ROI ejemplo'); addRoi({ x: 390, y: 100, width: 170, height: 130 }, 'ROI contraste'); }); $('clearBtn').addEventListener('click', () => { state.rois = []; render(); setStatus('Se han borrado todas las ROI.'); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (file) loadImage(file); }); $('alphaMode').addEventListener('change', render); $('minSize').addEventListener('change', render); $('tableWrap').addEventListener('click', event => { const button = event.target.closest('.remove-btn'); if (!button) return; const id = Number(button.dataset.id); state.rois = state.rois.filter(roi => roi.id !== id).map((roi, index) => ({ ...roi, id: index + 1 })); render(); setStatus('ROI eliminada.'); }); $('jsonBtn').addEventListener('click', exportJson); $('csvBtn').addEventListener('click', exportCsv);
  drawExample();
})();
