(() => {
  const $ = id => document.getElementById(id);
  const sample = 'P1,40.4168,-3.7038\nP2,40.4182,-3.7001\nP3,40.4144,-3.6966\nP4,40.4120,-3.7015';
  const state = { points: [], segments: [], map: null, layer: null };
  const R = 6371008.8, rad = value => value * Math.PI / 180, deg = value => value * 180 / Math.PI;
  function parseRows(text, separator) { return text.trim().split(/\r?\n/).map(line => line.split(separator).map(value => value.trim())).filter(row => row.length >= 3 && row.some(Boolean)); }
  function detect(text) { const line = text.split(/\r?\n/).find(value => value.trim()) || ''; return [',',';','\t'].sort((a,b) => line.split(b).length - line.split(a).length)[0]; }
  function num(value) { const text = String(value ?? '').trim().replace(/\s/g,'').replace(',', '.'); return Number(text); }
  function distance(a,b) { const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*R*Math.asin(Math.min(1,Math.sqrt(h))); }
  function bearing(a,b) { const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lon-a.lon),value=deg(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))); return (value+360)%360; }
  function project(point, origin) { return { x:R*rad(point.lon-origin.lon)*Math.cos(rad(origin.lat)), y:R*rad(point.lat-origin.lat) }; }
  function formatMeters(value) { return value < 1000 ? value.toFixed(1)+' m' : (value/1000).toFixed(3)+' km'; }
  function setStatus(text,error=false) { $('status').textContent=text; $('status').classList.toggle('error',error); }
  function calculate() {
    const text=$('source').value.trim(); if(!text){setStatus('Introduce puntos antes de calcular.',true);return;}
    const sep=$('delimiter').value==='auto'?detect(text):$('delimiter').value, rows=parseRows(text,sep), points=[];
    rows.forEach((row,index)=>{const lat=num(row[1]),lon=num(row[2]); if(Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180)points.push({name:row[0]||'P'+(index+1),lat,lon});});
    if(points.length<2){setStatus('Se necesitan al menos dos filas con latitud y longitud válidas.',true);return;}
    state.points=points; state.segments=[]; let openTotal=0;
    for(let i=1;i<points.length;i+=1){const item={from:points[i-1],to:points[i],distance:distance(points[i-1],points[i]),bearing:bearing(points[i-1],points[i])}; state.segments.push(item);openTotal+=item.distance;}
    const close=$('closePolygon').checked&&points.length>2; const closing=close?{from:points[points.length-1],to:points[0],distance:distance(points[points.length-1],points[0]),bearing:bearing(points[points.length-1],points[0])}:null; if(closing){state.segments.push(closing);}
    const origin=points[0], projected=points.map(point=>project(point,origin)); let twiceArea=0; for(let i=0;i<projected.length;i+=1){const next=projected[(i+1)%projected.length];twiceArea+=projected[i].x*next.y-next.x*projected[i].y;} const area=close?Math.abs(twiceArea/2):0, perimeter=close?openTotal+(closing?.distance||0):openTotal, centroid=[points.reduce((sum,p)=>sum+p.lat,0)/points.length,points.reduce((sum,p)=>sum+p.lon,0)/points.length];
    $('totalDistance').textContent=formatMeters(openTotal); $('perimeter').textContent=close?formatMeters(perimeter):'abierto'; $('area').textContent=close?area.toLocaleString('es-ES',{maximumFractionDigits:0})+' m²':'—'; $('centroid').textContent=centroid[0].toFixed(5)+'°, '+centroid[1].toFixed(5)+'°'; $('pointBadge').textContent=points.length+' puntos'; $('quality').textContent=close?'Polígono cerrado':'Itinerario abierto'; $('quality').className='quality '+(close?'':'warn'); renderSegments(); renderMap(); $('geojsonBtn').disabled=false; $('csvBtn').disabled=false; setStatus(points.length+' puntos calculados localmente.'); state.metrics={openTotal,perimeter,area,centroid,close};
  }
  function renderSegments(){let html='<table><thead><tr><th>Tramo</th><th>Desde → hasta</th><th>Distancia</th><th>Rumbo</th></tr></thead><tbody>';state.segments.forEach((item,index)=>{const label=index===state.points.length-1?'cierre':index+1;html+='<tr><td>'+label+'</td><td>'+escapeHtml(item.from.name)+' → '+escapeHtml(item.to.name)+'</td><td><strong>'+formatMeters(item.distance)+'</strong></td><td>'+item.bearing.toFixed(1)+'°</td></tr>';});$('segments').innerHTML=html+'</tbody></table>';}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function initMap(){if(!window.L){$('map').hidden=true;$('mapFallback').hidden=false;return;}state.map=L.map('map').setView([40.4,-3.7],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(state.map);state.layer=L.layerGroup().addTo(state.map);}
  function renderMap(){if(!state.layer)return;state.layer.clearLayers();const latLngs=state.points.map(point=>[point.lat,point.lon]);L.polyline(latLngs,{color:'#72e3be',weight:4}).addTo(state.layer);if($('closePolygon').checked&&latLngs.length>2)L.polygon(latLngs,{color:'#ffd277',weight:2,fillColor:'#72e3be',fillOpacity:.12}).addTo(state.layer);state.points.forEach((point,index)=>L.marker([point.lat,point.lon],{icon:L.divIcon({className:'',html:'<span class="cogo-marker">'+(index+1)+'</span>',iconSize:[24,24],iconAnchor:[12,12]})}).bindPopup('<strong>'+escapeHtml(point.name)+'</strong><br>'+point.lat.toFixed(6)+'°, '+point.lon.toFixed(6)+'°').addTo(state.layer));if(latLngs.length)state.map.fitBounds(latLngs,{padding:[25,25],maxZoom:17});}
  function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  function exportGeoJson(){const coordinates=state.points.map(point=>[point.lon,point.lat]),features=state.points.map((point,index)=>({type:'Feature',geometry:{type:'Point',coordinates:[point.lon,point.lat]},properties:{name:point.name,order:index+1}}));features.push({type:'Feature',geometry:{type:$('closePolygon').checked?'Polygon':'LineString',coordinates:$('closePolygon').checked?[coordinates.concat([coordinates[0]])]:coordinates},properties:{name:'COGO '+($('closePolygon').checked?'polígono':'itinerario'),distance_m:state.metrics.openTotal,area_m2:state.metrics.area}});download('cogo-geometria.geojson',JSON.stringify({type:'FeatureCollection',features},null,2),'application/geo+json');}
  function exportCsv(){const lines=['tramo,desde,hasta,distancia_m,rumbo_grados'];state.segments.forEach((item,index)=>lines.push([index===state.points.length-1?'cierre':index+1,item.from.name,item.to.name,item.distance.toFixed(3),item.bearing.toFixed(3)].map(value=>'"'+String(value).replace(/"/g,'""')+'"').join(',')));download('cogo-segmentos.csv',lines.join('\n'),'text/csv;charset=utf-8');}
  $('calculateBtn').addEventListener('click',calculate);$('sampleBtn').addEventListener('click',()=>{$('source').value=sample;calculate();});$('closePolygon').addEventListener('change',calculate);$('delimiter').addEventListener('change',calculate);$('geojsonBtn').addEventListener('click',exportGeoJson);$('csvBtn').addEventListener('click',exportCsv);initMap();calculate();
})();
