(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { source: null, input: null, output: null, features: [], fileName: 'capa.geojson', inputVertices: 0, outputVertices: 0, geometryCount: 0, map: null, inputLayer: null, outputLayer: null };
  const depths = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 };

  const example = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { name: 'Línea de ejemplo' }, geometry: { type: 'LineString', coordinates: [[-3.72, 40.40], [-3.715, 40.405], [-3.71, 40.398], [-3.705, 40.412], [-3.70, 40.406], [-3.695, 40.418], [-3.69, 40.415], [-3.685, 40.425], [-3.68, 40.42]] } }, { type: 'Feature', properties: { name: 'Polígono de ejemplo' }, geometry: { type: 'Polygon', coordinates: [[[-3.74, 40.41], [-3.73, 40.412], [-3.725, 40.42], [-3.715, 40.425], [-3.70, 40.423], [-3.695, 40.415], [-3.705, 40.407], [-3.72, 40.405], [-3.74, 40.41]]] } }] };

  function isPosition(value) { return Array.isArray(value) && value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function parseInput(input) {
    if (!input || typeof input !== 'object') throw new Error('El documento no es un objeto JSON.');
    if (input.type === 'FeatureCollection' && Array.isArray(input.features)) return { features: input.features, root: 'FeatureCollection' };
    if (input.type === 'Feature') return { features: [input], root: 'Feature' };
    if (typeof input.type === 'string' && (depths[input.type] !== undefined || input.type === 'GeometryCollection')) return { features: [{ type: 'Feature', properties: {}, geometry: input }], root: 'Geometry' };
    throw new Error('Usa un FeatureCollection, Feature o una geometría GeoJSON reconocible.');
  }
  function countCoordinates(node, depth) { if (depth === 0) return isPosition(node) ? 1 : 0; return Array.isArray(node) ? node.reduce((total, child) => total + countCoordinates(child, depth - 1), 0) : 0; }
  function countGeometry(geometry) {
    if (!geometry || typeof geometry !== 'object') return { vertices: 0, geometries: 0 };
    if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).reduce((total, child) => { const count = countGeometry(child); return { vertices: total.vertices + count.vertices, geometries: total.geometries + count.geometries }; }, { vertices: 0, geometries: 0 });
    const depth = depths[geometry.type]; return depth === undefined ? { vertices: 0, geometries: 0 } : { vertices: countCoordinates(geometry.coordinates, depth), geometries: 1 };
  }
  function metric(position, referenceLat) { const cos = Math.max(0.15, Math.cos(referenceLat * Math.PI / 180)); return [Number(position[0]) * 111320 * cos, Number(position[1]) * 110540]; }
  function segmentDistanceSquared(point, start, end, referenceLat) {
    const p = metric(point, referenceLat), a = metric(start, referenceLat), b = metric(end, referenceLat); const dx = b[0] - a[0], dy = b[1] - a[1];
    if (!dx && !dy) return (p[0] - a[0]) ** 2 + (p[1] - a[1]) ** 2;
    const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy))); const x = a[0] + t * dx, y = a[1] + t * dy; return (p[0] - x) ** 2 + (p[1] - y) ** 2;
  }
  function simplifyLine(line, tolerance) {
    if (!Array.isArray(line) || line.length <= 2 || !line.every(isPosition)) return clone(line || []);
    const referenceLat = line.reduce((sum, position) => sum + Number(position[1]), 0) / line.length; const keep = new Uint8Array(line.length); keep[0] = 1; keep[line.length - 1] = 1; const stack = [[0, line.length - 1]]; const limit = tolerance * tolerance;
    while (stack.length) { const [start, end] = stack.pop(); let farthest = -1; let maximum = limit; for (let index = start + 1; index < end; index += 1) { const distance = segmentDistanceSquared(line[index], line[start], line[end], referenceLat); if (distance > maximum) { maximum = distance; farthest = index; } } if (farthest >= 0) { keep[farthest] = 1; stack.push([start, farthest], [farthest, end]); } }
    return line.filter((_position, index) => keep[index]).map((position) => [...position]);
  }
  function simplifyRing(ring, tolerance) {
    if (!Array.isArray(ring) || ring.length < 4 || !ring.every(isPosition)) return clone(ring || []);
    const closed = ring.length > 1 && Number(ring[0][0]) === Number(ring[ring.length - 1][0]) && Number(ring[0][1]) === Number(ring[ring.length - 1][1]); const open = closed ? ring.slice(0, -1) : ring.slice();
    if (open.length < 3) return clone(ring); const simplified = simplifyLine(open, tolerance); if (simplified.length < 3) return clone(ring); simplified.push([...simplified[0]]); return simplified;
  }
  function simplifyGeometry(geometry, tolerance) {
    if (!geometry || typeof geometry !== 'object') return geometry;
    if (geometry.type === 'GeometryCollection') return { ...clone(geometry), geometries: (geometry.geometries || []).map((child) => simplifyGeometry(child, tolerance)) };
    const next = clone(geometry); if (geometry.type === 'LineString') next.coordinates = simplifyLine(geometry.coordinates, tolerance); else if (geometry.type === 'MultiLineString') next.coordinates = (geometry.coordinates || []).map((line) => simplifyLine(line, tolerance)); else if (geometry.type === 'Polygon') next.coordinates = (geometry.coordinates || []).map((ring) => simplifyRing(ring, tolerance)); else if (geometry.type === 'MultiPolygon') next.coordinates = (geometry.coordinates || []).map((polygon) => (polygon || []).map((ring) => simplifyRing(ring, tolerance))); return next;
  }
  function toleranceValue() { const value = Number($('tolerance').value); return Number.isFinite(value) && value > 0 ? Math.min(value, 100000) : 5; }
  function prepare(input, fileName) { const parsed = parseInput(input); state.source = input; state.input = { type: 'FeatureCollection', features: clone(parsed.features) }; state.features = parsed.features; state.fileName = fileName || 'capa.geojson'; state.output = null; state.inputVertices = parsed.features.reduce((sum, feature) => sum + countGeometry(feature?.geometry).vertices, 0); state.geometryCount = parsed.features.reduce((sum, feature) => sum + countGeometry(feature?.geometry).geometries, 0); state.outputVertices = 0; $('summary').hidden = false; $('inputVertices').textContent = state.inputVertices.toLocaleString('es-ES'); $('geometryCount').textContent = state.geometryCount.toLocaleString('es-ES'); $('outputVertices').textContent = '—'; $('reduction').textContent = '—'; $('downloadBtn').disabled = true; $('status').textContent = `${state.fileName}: ${state.features.length} entidades listas para simplificar.`; drawMap(); }
  function process() { if (!state.input) return; const tolerance = toleranceValue(); state.output = { type: 'FeatureCollection', features: state.features.map((feature) => ({ ...clone(feature), geometry: simplifyGeometry(feature.geometry, tolerance) })) }; state.outputVertices = state.output.features.reduce((sum, feature) => sum + countGeometry(feature?.geometry).vertices, 0); const reduction = state.inputVertices ? ((1 - state.outputVertices / state.inputVertices) * 100) : 0; $('outputVertices').textContent = state.outputVertices.toLocaleString('es-ES'); $('reduction').textContent = `${Math.max(0, reduction).toFixed(1)} %`; $('status').textContent = `${state.fileName}: simplificada con tolerancia de ${tolerance.toLocaleString('es-ES')} m.`; $('downloadBtn').disabled = false; drawMap(); }
  function download(text, name) { const url = URL.createObjectURL(new Blob([text], { type: 'application/geo+json' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function geometryCanMap(geometry) { if (!geometry || typeof geometry !== 'object') return false; if (geometry.type === 'GeometryCollection') return (geometry.geometries || []).some(geometryCanMap); const depth = depths[geometry.type]; if (depth === undefined) return false; let valid = true; const walk = (node, level) => { if (level === 0) { valid = valid && isPosition(node) && Number(node[0]) >= -180 && Number(node[0]) <= 180 && Number(node[1]) >= -90 && Number(node[1]) <= 90; return; } if (!Array.isArray(node)) { valid = false; return; } node.forEach((child) => walk(child, level - 1)); }; walk(geometry.coordinates, depth); return valid; }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.4, -3.7], 6); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  function drawMap() { if (!state.map) return; state.inputLayer?.remove(); state.outputLayer?.remove(); const inputFeatures = (state.input?.features || []).filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); const outputFeatures = (state.output?.features || []).filter((feature) => feature?.type === 'Feature' && geometryCanMap(feature.geometry)); try { if (inputFeatures.length) state.inputLayer = L.geoJSON({ type: 'FeatureCollection', features: inputFeatures }, { color: '#9ea9bb', weight: 2, dashArray: '5 5', fillColor: '#9ea9bb', fillOpacity: .08, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 5, color: '#9ea9bb', fillOpacity: .7, weight: 1 }) }).addTo(state.map); if (outputFeatures.length) state.outputLayer = L.geoJSON({ type: 'FeatureCollection', features: outputFeatures }, { color: '#5bd6a5', weight: 3, fillColor: '#5bd6a5', fillOpacity: .22, pointToLayer: (_feature, latlng) => L.circleMarker(latlng, { radius: 6, color: '#5bd6a5', fillOpacity: .9, weight: 2 }) }).addTo(state.map); const layer = state.outputLayer || state.inputLayer; const bounds = layer?.getBounds(); if (bounds?.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 16 }); } catch { $('status').textContent += ' El mapa no pudo dibujar alguna geometría; la exportación sigue disponible.'; } }
  async function readFile(file) { if (!file) return; if (file.size > 120 * 1024 * 1024) { $('status').textContent = 'El archivo supera 120 MB; no se abre en esta herramienta local.'; return; } try { prepare(JSON.parse(await file.text()), file.name); process(); } catch (error) { $('summary').hidden = true; $('status').textContent = error.message || 'No se pudo leer el GeoJSON.'; } }
  $('fileInput').addEventListener('change', () => readFile($('fileInput').files?.[0])); $('exampleBtn').addEventListener('click', () => { prepare(example, 'ejemplo-vector-generalizer.geojson'); process(); }); $('processBtn').addEventListener('click', process); $('tolerance').addEventListener('change', process); $('downloadBtn').addEventListener('click', () => { if (state.output) download(JSON.stringify(state.output, null, 2), `${state.fileName.replace(/\.[^.]+$/, '')}-simplificado.geojson`); }); $('clearBtn').addEventListener('click', () => { state.source = null; state.input = null; state.output = null; state.features = []; state.inputLayer?.remove(); state.outputLayer?.remove(); $('summary').hidden = true; $('status').textContent = 'Sin capa cargada'; }); initMap();
})();
