(() => {
  const $ = id => document.getElementById(id);
  const fileInput = $('fileInput'), status = $('status'), summary = $('summary'), csvBtn = $('csvBtn');
  let data = null, map = null, layer = null, rows = [];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const features = geo => geo?.type === 'FeatureCollection' ? geo.features : geo?.type === 'Feature' ? [geo] : [{type:'Feature',properties:{},geometry:geo}];
  const walk = (coords, out=[]) => { if (!Array.isArray(coords)) return out; if (typeof coords[0] === 'number') out.push(coords); else coords.forEach(item => walk(item,out)); return out; };
  const flatFeatures = () => features(data).flatMap((feature, featureIndex) => walk(feature.geometry?.coordinates).map((coord, vertexIndex) => ({featureIndex, vertexIndex, lon:coord[0], lat:coord[1], altitude:coord[2] ?? '', properties:feature.properties || {}, type:feature.geometry?.type || 'Null'})));
  function initMap(){ if (map || !window.L) return; map=L.map('map'); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map); map.setView([40.4,-3.7],5); }
  function render(){
    initMap(); if (!data) return; if (layer) layer.remove(); layer=L.geoJSON(data,{style:{color:'#5bd6a5',weight:3},pointToLayer:(_,latlng)=>L.circleMarker(latlng,{radius:6,color:'#ffbf69',fillColor:'#5bd6a5',fillOpacity:.9})}).addTo(map); const bounds=layer.getBounds(); if(bounds.isValid()) map.fitBounds(bounds.pad(.12));
    const fs=features(data), verts=flatFeatures(); rows=verts; $('featureCount').textContent=fs.length; $('geometryCount').textContent=verts.length; const lats=verts.map(v=>v.lat), lons=verts.map(v=>v.lon); $('bbox').textContent=verts.length?`${Math.min(...lons).toFixed(4)}, ${Math.min(...lats).toFixed(4)} → ${Math.max(...lons).toFixed(4)}, ${Math.max(...lats).toFixed(4)}`:'—'; const counts=fs.reduce((m,f)=>(m[f.geometry?.type||'Null']=(m[f.geometry?.type||'Null']||0)+1,m),{}); $('types').innerHTML=Object.entries(counts).map(([k,v])=>`<span class="chip">${esc(k)} · ${v}</span>`).join(''); $('rowCount').textContent=`${fs.length} entidades`; $('featureTable').innerHTML=fs.slice(0,100).map((f,i)=>`<tr><td>${i+1}</td><td>${esc(f.geometry?.type||'Null')}</td><td class="props">${esc(JSON.stringify(f.properties||{}))}</td></tr>`).join('') || '<tr><td colspan="3">Sin entidades.</td></tr>'; summary.hidden=false; csvBtn.disabled=verts.length===0;
  }
  fileInput.addEventListener('change', async () => { const file=fileInput.files[0]; if(!file) return; status.textContent=`Leyendo ${file.name}…`; try { const parsed=JSON.parse(await file.text()); if(!parsed || !parsed.type) throw new Error('No parece GeoJSON válido'); data=parsed; status.textContent=`Cargado: ${file.name}`; render(); } catch(error){ data=null; summary.hidden=true; csvBtn.disabled=true; status.textContent=`No se pudo leer el archivo: ${error.message}`; } });
  csvBtn.addEventListener('click', () => { const header='feature,vertex,longitude,latitude,altitude,geometry_type,properties\n'; const body=rows.map(r=>[r.featureIndex+1,r.vertexIndex+1,r.lon,r.lat,r.altitude,r.type,JSON.stringify(r.properties)].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([header+body],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='geojson-vertices.csv'; a.click(); URL.revokeObjectURL(a.href); });
  initMap();
})();
