(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { zones: null, observations: [], output: null, map: null, layer: null };
  const zoneSample = $('zoneSource').value;
  const observationSample = $('observationSource').value;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection' && Array.isArray(parsed.features)) return parsed; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El documento no contiene GeoJSON reconocible.'); }
  function positions(geometry, output = []) { if (!geometry) return output; if (geometry.type === 'GeometryCollection') { (geometry.geometries || []).forEach(item => positions(item, output)); return output; } const walk = (node, depth) => { if (depth === 0) { if (Array.isArray(node) && Number.isFinite(Number(node[0])) && Number.isFinite(Number(node[1]))) output.push([Number(node[0]), Number(node[1])]); return; } if (Array.isArray(node)) node.forEach(child => walk(child, depth - 1)); }; const depth = { Point: 0, MultiPoint: 1, LineString: 1, MultiLineString: 2, Polygon: 2, MultiPolygon: 3 }[geometry.type]; if (depth !== undefined) walk(geometry.coordinates, depth); return output; }
  function representative(feature) { const points = positions(feature.geometry); if (!points.length) return null; const sum = points.reduce((total, point) => [total[0] + point[0], total[1] + point[1]], [0, 0]); return [sum[0] / points.length, sum[1] / points.length]; }
  function numericFields(features) { const fields = new Map(); features.forEach(feature => Object.entries(feature.properties || {}).forEach(([key, value]) => { const number = Number(value); if (value !== null && value !== '' && Number.isFinite(number)) fields.set(key, (fields.get(key) || 0) + 1); })); return [...fields.entries()].filter(([, count]) => count >= 1).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([key]) => key); }
  function refreshValueFields() { const fields = numericFields(state.observations.map(item => item.feature)); const current = $('valueField').value; $('valueField').innerHTML = '<option value="">(sin campo numérico)</option>' + fields.map(field => `<option value="${esc(field)}">${esc(field)}</option>`).join(''); $('valueField').value = fields.includes(current) ? current : fields[0] || ''; }
  function ringContains(point, ring) { let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const a = ring[previous], b = ring[index]; const crosses = ((b[1] > point[1]) !== (a[1] > point[1])) && point[0] < (a[0] - b[0]) * (point[1] - b[1]) / (a[1] - b[1]) + b[0]; if (crosses) inside = !inside; } return inside; }
  function geometryContains(geometry, point) { if (geometry?.type === 'Polygon') return Boolean(geometry.coordinates?.length && ringContains(point, geometry.coordinates[0]) && !(geometry.coordinates.slice(1).some(ring => ringContains(point, ring)))); if (geometry?.type === 'MultiPolygon') return geometry.coordinates.some(polygon => geometryContains({ type: 'Polygon', coordinates: polygon }, point)); return false; }
  function statsFor(values, count) { let sum = 0, min = values[0] ?? null, max = values[0] ?? null; values.forEach(value => { sum += value; if (min === null || value < min) min = value; if (max === null || value > max) max = value; }); return { count, valueCount: values.length, sum, mean: values.length ? sum / values.length : null, min, max }; }
  function calculate() {
    if (!state.zones) throw new Error('Carga una capa de zonas poligonales.');
    if (!state.observations.length) throw new Error('Carga una capa de observaciones con geometrías localizables.');
    const field = $('valueField').value; if (!field && $('metric').value !== 'count') throw new Error('Selecciona un campo numérico para calcular suma o media.');
    const zoneFeatures = state.zones.features.filter(feature => ['Polygon', 'MultiPolygon'].includes(feature.geometry?.type)); if (!zoneFeatures.length) throw new Error('La capa de zonas no contiene Polygon ni MultiPolygon.');
    const aggregates = zoneFeatures.map((feature, index) => ({ feature, index, values: [], count: 0 })); let assigned = 0;
    state.observations.forEach(observation => { const matches = aggregates.filter(zone => geometryContains(zone.feature.geometry, observation.point)); if (matches.length) assigned += 1; matches.forEach(zone => { zone.count += 1; if (field) { const value = Number(observation.feature.properties?.[field]); if (Number.isFinite(value)) zone.values.push(value); } }); });
    const metric = $('metric').value; const outputFeatures = aggregates.map(zone => { const stats = statsFor(zone.values, zone.count); const value = metric === 'count' ? stats.count : metric === 'sum' ? stats.sum : stats.mean; return { ...zone.feature, properties: { ...(zone.feature.properties || {}), zonal_count: stats.count, zonal_value_count: stats.valueCount, zonal_sum: Number(stats.sum.toFixed(6)), zonal_mean: stats.mean === null ? null : Number(stats.mean.toFixed(6)), zonal_min: stats.min, zonal_max: stats.max, zonal_metric: metric, zonal_field: field || null, zonal_value: value === null ? null : Number(value.toFixed(6)) } }; });
    state.output = { type: 'FeatureCollection', name: 'zonal-stats-lab', features: outputFeatures }; const outside = state.observations.length - assigned; $('zoneCount').textContent = outputFeatures.length.toLocaleString('es-ES'); $('observationCount').textContent = state.observations.length.toLocaleString('es-ES'); $('assignedCount').textContent = assigned.toLocaleString('es-ES'); $('outsideCount').textContent = outside.toLocaleString('es-ES'); $('zoneBadge').textContent = outputFeatures.length + (outputFeatures.length === 1 ? ' zona' : ' zonas'); $('quality').textContent = metric === 'count' ? 'Conteo espacial' : `${metric === 'sum' ? 'Suma' : 'Media'} de ${field}`; $('quality').className = 'quality'; renderTable(); renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${assigned} observaciones asignadas a una o más zonas; ${outside} fuera de zona.`); }
  function loadSources() { try { state.zones = normalize($('zoneSource').value); const observations = normalize($('observationSource').value); state.observations = observations.features.map((feature, index) => ({ feature, index, point: representative(feature) })).filter(item => item.point); refreshValueFields(); calculate(); } catch (error) { setStatus(error.message || 'No se pudieron preparar las capas.', true); } }
  function renderTable() { const metric = $('metric').value; const rows = state.output.features.map((feature, index) => `<tr><td>${index + 1}</td><td>${esc(feature.properties?.zona || feature.properties?.name || `Zona ${index + 1}`)}</td><td>${feature.properties?.zonal_count ?? 0}</td><td>${feature.properties?.zonal_value === null ? '—' : Number(feature.properties?.zonal_value ?? 0).toFixed(2)}</td><td>${feature.properties?.zonal_sum?.toFixed ? feature.properties.zonal_sum.toFixed(2) : (feature.properties?.zonal_sum ?? '—')}</td><td>${feature.properties?.zonal_mean === null ? '—' : Number(feature.properties?.zonal_mean ?? 0).toFixed(2)}</td></tr>`).join(''); $('tableWrap').innerHTML = `<table><thead><tr><th>#</th><th>Zona</th><th>Conteo</th><th>${metric === 'count' ? 'Valor mostrado' : 'Métrica'}</th><th>Suma</th><th>Media</th></tr></thead><tbody>${rows}</tbody></table>`; }
  function colorFor(value, min, max) { if (value === null || value === undefined || !Number.isFinite(Number(value))) return '#70879a'; const ratio = max === min ? .5 : (Number(value) - min) / (max - min); const hue = 218 - Math.max(0, Math.min(1, ratio)) * 190; return `hsl(${hue} 78% 58%)`; }
  function renderMap() { if (!state.layer || !state.output) return; state.layer.clearLayers(); const values = state.output.features.map(feature => Number(feature.properties?.zonal_value)).filter(Number.isFinite); let min = values[0] ?? 0, max = values[0] ?? 0; values.slice(1).forEach(value => { if (value < min) min = value; if (value > max) max = value; }); const geo = L.geoJSON(state.output, { style: feature => { const color = colorFor(feature.properties?.zonal_value, min, max); return { color, fillColor: color, fillOpacity: .68, weight: 2 }; }, onEachFeature: (feature, layer) => layer.bindPopup(`<strong>${esc(feature.properties?.zona || feature.properties?.name || 'Zona')}</strong><br>Observaciones: ${feature.properties?.zonal_count ?? 0}<br>Valor: ${feature.properties?.zonal_value === null ? '—' : feature.properties?.zonal_value}<br>Suma: ${feature.properties?.zonal_sum ?? '—'} · Media: ${feature.properties?.zonal_mean ?? '—'}`) }).addTo(state.layer); const bounds = geo.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [25, 25], maxZoom: 15 }); }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const lines = ['zone,count,value_count,value,sum,mean,min,max,name']; state.output.features.forEach((feature, index) => { const p = feature.properties || {}; lines.push([index + 1, p.zonal_count, p.zonal_value_count, p.zonal_value, p.zonal_sum, p.zonal_mean, p.zonal_min, p.zonal_max, p.zona || p.name || `Zona ${index + 1}`].map(value => '"' + String(value ?? '').replace(/"/g, '""') + '"').join(',')); }); download('estadisticas-zonales.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function bindFile(id, targetId) { $(id).addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } const reader = new FileReader(); reader.onload = () => { $(targetId).value = String(reader.result || ''); loadSources(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); }
  $('calculateBtn').addEventListener('click', () => { try { loadSources(); } catch (error) { setStatus(error.message || 'No se pudo calcular.', true); } }); $('sampleBtn').addEventListener('click', () => { $('zoneSource').value = zoneSample; $('observationSource').value = observationSample; $('metric').value = 'mean'; loadSources(); }); $('clearBtn').addEventListener('click', () => { state.zones = null; state.observations = []; state.output = null; state.layer?.clearLayers(); $('valueField').innerHTML = '<option value="">(sin campo numérico)</option>'; $('tableWrap').innerHTML = '<p class="empty">Calcula estadísticas para ver la tabla zonal.</p>'; ['zoneCount', 'observationCount', 'assignedCount', 'outsideCount'].forEach(id => $(id).textContent = '—'); $('zoneBadge').textContent = '0 zonas'; $('quality').textContent = 'Sin calcular'; $('quality').className = 'quality muted'; $('geojsonBtn').disabled = true; $('csvBtn').disabled = true; setStatus('Carga las capas para empezar.'); }); $('valueField').addEventListener('change', () => { try { calculate(); } catch (error) { setStatus(error.message, true); } }); $('metric').addEventListener('change', () => { try { calculate(); } catch (error) { setStatus(error.message, true); } }); bindFile('zoneFile', 'zoneSource'); bindFile('observationFile', 'observationSource'); $('zoneSource').addEventListener('change', loadSources); $('observationSource').addEventListener('change', loadSources); $('geojsonBtn').addEventListener('click', () => download('estadisticas-zonales.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', exportCsv); initMap(); loadSources();
})();
