(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const sampleKml = '<kml xmlns="http://www.opengis.net/kml/2.2"><Document><Placemark><name>Ruta KML de ejemplo</name><ExtendedData><Data name="tipo"><value>itinerario</value></Data></ExtendedData><LineString><coordinates>-3.71,40.416 -3.70,40.418 -3.69,40.415</coordinates></LineString></Placemark><Placemark><name>Área KML de ejemplo</name><Polygon><outerBoundaryIs><LinearRing><coordinates>-3.715,40.412 -3.702,40.412 -3.702,40.420 -3.715,40.420 -3.715,40.412</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Document></kml>';
  const sampleGeoJson = '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"nombre":"Punto de ejemplo"},"geometry":{"type":"Point","coordinates":[-3.7038,40.4168]}}]}';
  const state = { collection: null, rows: [], sourceFormat: '', map: null, layer: null };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const textOf = element => element ? String(element.textContent || '').trim() : '';
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function normalizeSource(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection') return { type: 'FeatureCollection', features: parsed.features || [] }; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El JSON no contiene una capa GeoJSON reconocible.'); }
  function localElements(root, name) { return Array.from(root?.getElementsByTagName?.('*') || []).filter(node => node.localName === name); }
  function firstLocal(root, name) { return localElements(root, name)[0] || null; }
  function parseCoordinates(value) { return String(value || '').trim().split(/\s+/).map(pair => pair.split(',').slice(0, 3).map(Number)).filter(pair => Number.isFinite(pair[0]) && Number.isFinite(pair[1]) && pair[0] >= -180 && pair[0] <= 180 && pair[1] >= -90 && pair[1] <= 90).map(pair => pair.length > 2 && Number.isFinite(pair[2]) ? pair : pair.slice(0, 2)); }
  function parseKmlGeometry(container) {
    const multi = firstLocal(container, 'MultiGeometry');
    if (multi) { const geometries = localElements(multi, 'Point').concat(localElements(multi, 'LineString'), localElements(multi, 'Polygon')).map(parseKmlGeometry).filter(Boolean); return geometries.length ? { type: 'GeometryCollection', geometries } : null; }
    const point = firstLocal(container, 'Point'); if (point) { const coords = parseCoordinates(textOf(firstLocal(point, 'coordinates'))); return coords[0] ? { type: 'Point', coordinates: coords[0] } : null; }
    const line = firstLocal(container, 'LineString'); if (line) { const coords = parseCoordinates(textOf(firstLocal(line, 'coordinates'))); return coords.length >= 2 ? { type: 'LineString', coordinates: coords } : null; }
    const polygon = firstLocal(container, 'Polygon'); if (polygon) { const rings = []; const outer = firstLocal(polygon, 'outerBoundaryIs'); const outerRing = outer ? firstLocal(outer, 'LinearRing') : null; const outerCoords = parseCoordinates(textOf(firstLocal(outerRing, 'coordinates'))); if (outerCoords.length >= 4) rings.push(outerCoords); localElements(polygon, 'innerBoundaryIs').forEach(boundary => { const ring = parseCoordinates(textOf(firstLocal(boundary, 'coordinates'))); if (ring.length >= 4) rings.push(ring); }); return rings.length ? { type: 'Polygon', coordinates: rings } : null; }
    return null;
  }
  function parseKml(value) { const xml = new DOMParser().parseFromString(value, 'application/xml'); if (xml.querySelector('parsererror')) throw new Error('El KML no es XML válido.'); const features = localElements(xml, 'Placemark').map((placemark, index) => { const properties = {}; localElements(placemark, 'Data').forEach(data => { const key = data.getAttribute('name'); const valueNode = firstLocal(data, 'value'); if (key) properties[key] = textOf(valueNode); }); localElements(placemark, 'SimpleData').forEach(data => { const key = data.getAttribute('name'); if (key) properties[key] = textOf(data); }); const name = textOf(firstLocal(placemark, 'name')); const description = textOf(firstLocal(placemark, 'description')); if (description) properties.description = description; const geometry = parseKmlGeometry(placemark); return geometry ? { type: 'Feature', properties: { ...(name ? { name } : {}), ...properties, source_format: 'KML' }, geometry } : null; }).filter(Boolean); if (!features.length) throw new Error('El KML no contiene Placemarks con geometrías compatibles.'); return { type: 'FeatureCollection', features }; }
  function detectDelimiter(line) { return [';', '\t', ','].sort((a, b) => line.split(b).length - line.split(a).length)[0]; }
  function parseCsvRows(value, delimiter) { const rows = []; let row = [], cell = '', quoted = false; for (let i = 0; i < value.length; i += 1) { const char = value[i], next = value[i + 1]; if (char === '"' && quoted && next === '"') { cell += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { row.push(cell.trim()); cell = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') i += 1; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = ''; } else cell += char; } row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows; }
  function parseCsv(value) { const firstLine = value.split(/\r?\n/).find(line => line.trim()) || ''; const rows = parseCsvRows(value.replace(/^\uFEFF/, ''), detectDelimiter(firstLine)); if (rows.length < 2) throw new Error('El CSV necesita una cabecera y al menos una fila.'); const headers = rows[0].map((header, index) => header || 'campo_' + (index + 1)); const normalize = text => String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, ''); const aliases = { lat: ['lat','latitude','latitud','y','coordy'], lon: ['lon','lng','longitude','longitud','x','coordx'] }; const findHeader = choices => headers.findIndex(header => choices.includes(normalize(header))); const latIndex = findHeader(aliases.lat), lonIndex = findHeader(aliases.lon); if (latIndex < 0 || lonIndex < 0) throw new Error('CSV no reconocido: necesita columnas lat/lon, latitude/longitude o equivalentes.'); const nameIndex = headers.findIndex(header => ['name','nombre','id','codigo'].includes(normalize(header))); const features = rows.slice(1).map((values, rowIndex) => { const lat = Number(String(values[latIndex] || '').trim().replace(',', '.')); const lon = Number(String(values[lonIndex] || '').trim().replace(',', '.')); if (!Number.isFinite(lat) || !Number.isFinite(lon) || lat < -90 || lat > 90 || lon < -180 || lon > 180) return null; const properties = {}; headers.forEach((header, index) => { if (index !== latIndex && index !== lonIndex) properties[header] = values[index] ?? ''; }); const name = values[nameIndex] || 'Fila ' + (rowIndex + 1); return { type: 'Feature', properties: { ...properties, name: properties.name || properties.nombre || name, source_format: 'CSV' }, geometry: { type: 'Point', coordinates: [lon, lat] } }; }).filter(Boolean); if (!features.length) throw new Error('El CSV no contiene coordenadas válidas.'); return { type: 'FeatureCollection', features }; }
  function convert(value) { const mode = $('format').value; const trimmed = value.trim(); if (!trimmed) throw new Error('Introduce una capa antes de convertir.'); const format = mode === 'auto' ? (trimmed.startsWith('<') ? 'kml' : trimmed.startsWith('{') || trimmed.startsWith('[') ? 'geojson' : 'csv') : mode; const collection = format === 'kml' ? parseKml(value) : format === 'csv' ? parseCsv(value) : normalizeSource(value); collection.features.forEach(feature => { feature.properties = { ...(feature.properties || {}), source_format: feature.properties?.source_format || format.toUpperCase() }; }); return { collection, format: format.toUpperCase() }; }
  function featureName(row, index) { const props = row.feature.properties || {}; return props.name || props.nombre || props.id || 'Entidad ' + (index + 1); }
  function read(value) { const result = convert(value); state.collection = result.collection; state.sourceFormat = result.format; state.rows = state.collection.features.map((feature, index) => ({ feature, index, name: featureName({ feature }, index), type: feature.geometry?.type || 'Sin geometría', properties: feature.properties || {} })); $('countBadge').textContent = state.rows.length + (state.rows.length === 1 ? ' entidad' : ' entidades'); $('featureCount').textContent = state.rows.length.toLocaleString('es-ES'); $('geometryCount').textContent = new Set(state.rows.map(row => row.type)).size.toLocaleString('es-ES'); $('fieldCount').textContent = new Set(state.rows.flatMap(row => Object.keys(row.properties))).size.toLocaleString('es-ES'); $('sourceFormat').textContent = result.format; $('formatBadge').textContent = 'Convertido a GeoJSON'; $('formatBadge').className = 'quality'; renderTable(); renderMap(); $('geojsonBtn').disabled = false; $('kmlBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${state.rows.length} entidades convertidas desde ${result.format} localmente.`); }
  function visibleRows() { const query = $('search').value.trim().toLowerCase(); return state.rows.filter(row => !query || (row.name + ' ' + JSON.stringify(row.properties)).toLowerCase().includes(query)); }
  function renderTable() { const rows = visibleRows(); if (!rows.length) { $('tableWrap').innerHTML = '<p class="empty">Ninguna entidad coincide con la búsqueda.</p>'; return; } $('tableWrap').innerHTML = '<table><thead><tr><th>#</th><th>Nombre</th><th>Geometría</th><th>Atributos</th></tr></thead><tbody>' + rows.slice(0, 300).map(row => `<tr data-index="${row.index}"><td>${row.index + 1}</td><td><strong>${esc(row.name)}</strong></td><td><span class="type-badge">${esc(row.type)}</span></td><td>${esc(Object.entries(row.properties).filter(([key]) => key !== 'source_format').slice(0, 4).map(([key, value]) => key + ': ' + value).join(' · '))}</td></tr>`).join('') + '</tbody></table>' + (rows.length > 300 ? `<p class="table-note">Se muestran 300 de ${rows.length}; la exportación incluye todas.</p>` : ''); }
  function popup(row) { return `<strong>${esc(row.name)}</strong><br><span>${esc(row.type)}</span><br>${esc(Object.entries(row.properties).filter(([key]) => key !== 'source_format').slice(0, 8).map(([key, value]) => key + ': ' + value).join(' · '))}`; }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4, -3.7], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer) return; state.layer.clearLayers(); const geo = L.geoJSON({ type: 'FeatureCollection', features: visibleRows().map(row => row.feature) }, { style: { color: '#72e3be', weight: 3, fillColor: '#72e3be', fillOpacity: .18 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#071b25', weight: 2, fillColor: '#72e3be', fillOpacity: .9 },), onEachFeature: (feature, layer) => { const row = state.rows.find(item => item.feature === feature); if (row) layer.bindPopup(popup(row)); } }).addTo(state.layer); if (geo.getLayers().length) state.map.fitBounds(geo.getBounds(), { padding: [22, 22], maxZoom: 16 }); }
  function escapeXml(value) { return String(value ?? '').replace(/[<>&'"]/g, char => ({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[char])); }
  function kmlGeometry(geometry) { if (!geometry) return ''; const coords = points => points.map(point => point.slice(0, 3).join(',')).join(' '); if (geometry.type === 'Point') return `<Point><coordinates>${coords([geometry.coordinates])}</coordinates></Point>`; if (geometry.type === 'LineString') return `<LineString><coordinates>${coords(geometry.coordinates)}</coordinates></LineString>`; if (geometry.type === 'Polygon') return `<Polygon><outerBoundaryIs><LinearRing><coordinates>${coords(geometry.coordinates[0] || [])}</coordinates></LinearRing></outerBoundaryIs>${geometry.coordinates.slice(1).map(ring => `<innerBoundaryIs><LinearRing><coordinates>${coords(ring)}</coordinates></LinearRing></innerBoundaryIs>`).join('')}</Polygon>`; if (geometry.type === 'GeometryCollection') return `<MultiGeometry>${geometry.geometries.map(kmlGeometry).join('')}</MultiGeometry>`; return ''; }
  function exportKml() { const placemarks = state.collection.features.map((feature, index) => { const props = feature.properties || {}; const name = props.name || props.nombre || props.id || 'Entidad ' + (index + 1); const entries = Object.entries(props).filter(([key]) => !['name','nombre','source_format','description'].includes(key)); const extended = entries.length ? `<ExtendedData>${entries.map(([key, value]) => `<Data name="${escapeXml(key)}"><value>${escapeXml(value)}</value></Data>`).join('')}</ExtendedData>` : ''; const description = props.description ? `<description>${escapeXml(props.description)}</description>` : ''; return `<Placemark><name>${escapeXml(name)}</name>${description}${extended}${kmlGeometry(feature.geometry)}</Placemark>`; }).join(''); download('capa-convertida.kml', `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>${placemarks}</Document></kml>`, 'application/vnd.google-earth.kml+xml;charset=utf-8'); }
  function csvCell(value) { let text = String(value ?? ''); if (/^[=+\-@]/.test(text)) text = "'" + text; return '"' + text.replace(/"/g, '""') + '"'; }
  function exportCsv() { const keys = [...new Set(state.rows.flatMap(row => Object.keys(row.properties).filter(key => key !== 'source_format')))]; const header = ['index','nombre','geometry_type','longitude','latitude',...keys]; const lines = [header.map(csvCell).join(',')]; state.rows.forEach(row => { const first = row.feature.geometry?.type === 'Point' ? row.feature.geometry.coordinates : ['', '']; lines.push([row.index + 1, row.name, row.type, first[0], first[1], ...keys.map(key => row.properties[key])].map(csvCell).join(',')); }); download('capa-convertida.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  $('convertBtn').addEventListener('click', () => { try { read($('source').value); } catch (error) { setStatus(error.message || 'No se pudo convertir la capa.', true); } }); $('sampleBtn').addEventListener('click', () => { $('format').value = 'kml'; $('source').value = sampleKml; read(sampleKml); }); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); if ($('format').value === 'auto') $('format').value = /\.kml$|\.xml$/i.test(file.name) ? 'kml' : /\.csv$|\.tsv$/i.test(file.name) ? 'csv' : 'geojson'; try { read($('source').value); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('search').addEventListener('input', () => { renderTable(); renderMap(); }); $('tableWrap').addEventListener('click', event => { const rowElement = event.target.closest('tr[data-index]'); if (!rowElement || !state.map) return; const row = state.rows[Number(rowElement.dataset.index)]; const layer = state.layer.getLayers().find(item => item.feature === row.feature); if (layer) { if (layer.getBounds) state.map.fitBounds(layer.getBounds(), { padding: [30, 30], maxZoom: 17 }); else if (layer.getLatLng) state.map.setView(layer.getLatLng(), 17); layer.openPopup(); } }); $('geojsonBtn').addEventListener('click', () => download('capa-convertida.geojson', JSON.stringify(state.collection, null, 2), 'application/geo+json;charset=utf-8')); $('kmlBtn').addEventListener('click', exportKml); $('csvBtn').addEventListener('click', exportCsv); initMap(); $('format').value = 'kml'; $('source').value = sampleKml; try { read(sampleKml); } catch (error) { setStatus(error.message || 'No se pudo cargar el ejemplo.', true); }
})();
