(() => {
  const $ = id => document.getElementById(id);
  const storageKey = 'cartografia-field-notes-v1';
  const types = { arqueologia: 'Arqueología', patrimonio: 'Patrimonio', vegetacion: 'Vegetación', geologia: 'Geología', incidencia: 'Incidencia', otro: 'Otro' };
  const map = L.map('map', { zoomControl: true }).setView([40.4, -3.7], 6);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '© OpenStreetMap contributors' }).addTo(map);
  L.control.scale({ imperial: false }).addTo(map);
  const markerLayer = L.layerGroup().addTo(map);
  let notes = readNotes(); let pending = null; let photoData = '';
  function readNotes() { try { const value = JSON.parse(localStorage.getItem(storageKey) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } }
  function saveNotes() { try { localStorage.setItem(storageKey, JSON.stringify(notes)); return true; } catch { setStatus('No hay espacio suficiente. Exporta y elimina notas antiguas.', true); return false; } }
  function setStatus(message, error = false) { $('status').textContent = message; $('status').classList.toggle('error', error); }
  function coord(value) { return Number(value).toFixed(6); }
  function safe(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function setPending(lat, lng) { pending = { lat: Number(lat), lng: Number(lng) }; $('pending').textContent = `${coord(lat)}, ${coord(lng)}`; map.panTo([lat, lng], { animate: true }); }
  function icon(type) { const glyph = { arqueologia: '✦', patrimonio: '⌂', vegetacion: '♣', geologia: '◆', incidencia: '!', otro: '•' }[type] || '•'; return L.divIcon({ className: `note-marker marker-${type}`, html: `<span>${glyph}</span>`, iconSize: [32, 32], iconAnchor: [16, 16], popupAnchor: [0, -17] }); }
  function popup(note) { const image = note.photo ? `<img src="${note.photo}" alt="Fotografía de ${safe(note.title)}" class="popup-photo">` : ''; return `<strong>${safe(note.title)}</strong><br><small>${safe(types[note.type] || 'Otro')} · ${coord(note.lat)}, ${coord(note.lng)}</small>${image}${note.description ? `<p>${safe(note.description)}</p>` : ''}`; }
  function render() {
    markerLayer.clearLayers(); notes.forEach(note => L.marker([note.lat, note.lng], { icon: icon(note.type), title: note.title }).bindPopup(popup(note)).addTo(markerLayer));
    $('count').textContent = `${notes.length} nota${notes.length === 1 ? '' : 's'}`; $('exportGeo').disabled = !notes.length; $('exportCsv').disabled = !notes.length;
    const sorted = [...notes].sort((a, b) => b.createdAt - a.createdAt);
    $('notesList').innerHTML = sorted.length ? sorted.map(note => `<article class="note-card">${note.photo ? `<img src="${note.photo}" alt="" class="note-thumb">` : ''}<b>${safe(note.title)}</b><small class="note-type">${safe(types[note.type] || 'Otro')} · ${coord(note.lat)}, ${coord(note.lng)}</small><small>${new Date(note.createdAt).toLocaleString('es-ES')}</small>${note.description ? `<p>${safe(note.description)}</p>` : ''}<button type="button" data-focus="${safe(note.id)}">Ver en mapa</button></article>`).join('') : '<p class="hint">Todavía no hay observaciones. Toca el mapa para fijar la primera posición.</p>';
    document.querySelectorAll('[data-focus]').forEach(button => button.addEventListener('click', () => { const note = notes.find(item => item.id === button.dataset.focus); if (note) { map.setView([note.lat, note.lng], Math.max(map.getZoom(), 15)); markerLayer.getLayers().find(marker => marker.options.title === note.title)?.openPopup(); } }));
  }
  function download(name, type, data) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([data], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 600); }
  function toGeoJSON() { return { type: 'FeatureCollection', features: notes.map(note => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [note.lng, note.lat] }, properties: { id: note.id, title: note.title, type: note.type, description: note.description, createdAt: new Date(note.createdAt).toISOString(), photoIncluded: Boolean(note.photo) } })) }; }
  function toCsv() { const quote = value => `"${String(value ?? '').replaceAll('"', '""')}"`; return `id,title,type,description,latitude,longitude,created_at\n${notes.map(note => [note.id, note.title, types[note.type] || note.type, note.description, note.lat, note.lng, new Date(note.createdAt).toISOString()].map(quote).join(',')).join('\n')}`; }
  async function compressPhoto(file) { const source = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); const image = await new Promise((resolve, reject) => { const item = new Image(); item.onload = () => resolve(item); item.onerror = reject; item.src = source; }); const scale = Math.min(1, 900 / image.width); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); return canvas.toDataURL('image/jpeg', .72); }
  map.on('click', event => { setPending(event.latlng.lat, event.latlng.lng); setStatus('Posición fijada. Completa la observación y guárdala.'); });
  $('locateBtn').addEventListener('click', () => { if (!navigator.geolocation) return setStatus('Este navegador no ofrece geolocalización.', true); $('locateBtn').disabled = true; setStatus('Solicitando posición…'); navigator.geolocation.getCurrentPosition(position => { setPending(position.coords.latitude, position.coords.longitude); $('locateBtn').disabled = false; setStatus(`GPS fijado con precisión aproximada de ${Math.round(position.coords.accuracy)} m.`); }, () => { $('locateBtn').disabled = false; setStatus('No se pudo obtener la posición. Comprueba el permiso.', true); }, { enableHighAccuracy: true, timeout: 12000, maximumAge: 30000 }); });
  $('photo').addEventListener('change', async event => { const file = event.target.files[0]; if (!file) { photoData = ''; $('photoPreview').hidden = true; return; } try { photoData = await compressPhoto(file); $('photoPreview').innerHTML = `<img src="${photoData}" alt="Vista previa de la fotografía">`; $('photoPreview').hidden = false; } catch { photoData = ''; setStatus('No se pudo leer la fotografía.', true); } });
  $('noteForm').addEventListener('submit', event => { event.preventDefault(); if (!pending) return setStatus('Fija primero una posición tocando el mapa o usando Mi ubicación.', true); const note = { id: `note-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, title: $('title').value.trim(), type: $('type').value, description: $('description').value.trim(), lat: pending.lat, lng: pending.lng, photo: photoData, createdAt: Date.now() }; notes.push(note); if (!saveNotes()) return; render(); map.setView([note.lat, note.lng], Math.max(map.getZoom(), 15)); $('noteForm').reset(); photoData = ''; pending = null; $('pending').textContent = 'Pulsa el mapa o localiza tu GPS'; $('photoPreview').hidden = true; setStatus(`Observación «${note.title}» guardada localmente.`); });
  $('exportGeo').addEventListener('click', () => download('field-notes.geojson', 'application/geo+json', JSON.stringify(toGeoJSON(), null, 2))); $('exportCsv').addEventListener('click', () => download('field-notes.csv', 'text/csv;charset=utf-8', toCsv()));
  $('clearBtn').addEventListener('click', () => { if (!notes.length || window.confirm('¿Vaciar todas las observaciones guardadas en este dispositivo?')) { notes = []; saveNotes(); render(); setStatus('Cuaderno vacío.'); } }); $('importBtn').addEventListener('click', () => $('importFile').click());
  $('importFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(reader.result); const features = data.type === 'FeatureCollection' ? data.features : []; const imported = features.map(feature => { const coordinates = feature.geometry?.coordinates || []; const props = feature.properties || {}; return { id: `import-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, title: String(props.title || props.name || 'Observación importada'), type: types[props.type] ? props.type : 'otro', description: String(props.description || ''), lat: Number(coordinates[1]), lng: Number(coordinates[0]), photo: '', createdAt: Date.now() }; }).filter(note => featurePoint(note)); notes.push(...imported); saveNotes(); render(); setStatus(`${imported.length} observación${imported.length === 1 ? '' : 'es'} importada${imported.length === 1 ? '' : 's'}.`); } catch { setStatus('El archivo no contiene un GeoJSON válido.', true); } }; reader.readAsText(file); });
  function featurePoint(note) { return Number.isFinite(note.lat) && Number.isFinite(note.lng); }
  CartografiaPlaceSearch(map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus'), zoom: 14, onLocate(place) { setPending(place.lat, place.lng); } }); render();
})();
