(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { mode: 'Point', draft: [], features: [], map: null, layer: null, draftLayer: null };
  const R = 6371008.8, rad = value => value * Math.PI / 180;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const num = value => Number(String(value ?? '').replace(',', '.'));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function nameForFeature() { return $('featureName').value.trim() || 'Elemento ' + (state.features.length + 1); }
  function validatePoint(lat, lon) { return Number.isFinite(lat) && Number.isFinite(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180; }
  function distance(a, b) { const p1 = rad(a[1]), p2 = rad(b[1]), dLat = p2 - p1, dLon = rad(b[0] - a[0]), h = Math.sin(dLat / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.min(1, Math.sqrt(h))); }
  function formatDistance(value) { return value >= 1000 ? (value / 1000).toLocaleString('es-ES', { maximumFractionDigits: 3 }) + ' km' : value.toLocaleString('es-ES', { maximumFractionDigits: 1 }) + ' m'; }
  function addVertex(lat, lon) { if (!validatePoint(lat, lon)) { setStatus('Latitud o longitud no válidas. Usa WGS84 en grados decimales.', true); return; } if (state.mode === 'Point') { state.features.push({ type: 'Feature', properties: { name: nameForFeature(), digitized_at: new Date().toISOString() }, geometry: { type: 'Point', coordinates: [lon, lat] } }); $('featureName').value = 'Elemento ' + (state.features.length + 1); setStatus('Punto añadido localmente.'); } else { state.draft.push([lon, lat]); setStatus(`${state.draft.length} vértices en la geometría actual.`); } updateControls(); renderDraft(); renderFeatures(); }
  function finish() { if (state.mode === 'LineString' && state.draft.length < 2) { setStatus('Una línea necesita al menos dos vértices.', true); return; } if (state.mode === 'Polygon' && state.draft.length < 3) { setStatus('Un polígono necesita al menos tres vértices.', true); return; } const coords = state.draft.slice(); if (state.mode === 'Polygon') coords.push(coords[0]); state.features.push({ type: 'Feature', properties: { name: nameForFeature(), vertex_count: state.draft.length, digitized_at: new Date().toISOString() }, geometry: { type: state.mode, coordinates: coords } }); state.draft = []; $('featureName').value = 'Elemento ' + (state.features.length + 1); setStatus(`${state.mode === 'Polygon' ? 'Polígono' : 'Línea'} finalizado localmente.`); updateControls(); renderDraft(); renderFeatures(); }
  function updateControls() { $('finishBtn').disabled = state.mode === 'Point' || state.draft.length === 0; $('undoBtn').disabled = state.draft.length === 0; $('clearBtn').disabled = state.features.length === 0 && state.draft.length === 0; $('geojsonBtn').disabled = state.features.length === 0; $('csvBtn').disabled = state.features.length === 0; $('vertexBadge').textContent = state.draft.length + ' vértices'; $('featureBadge').textContent = state.features.length + (state.features.length === 1 ? ' entidad' : ' entidades'); $('instructions').textContent = state.mode === 'Point' ? 'En modo punto, cada clic crea una entidad.' : `Añade ${state.mode === 'Polygon' ? 'tres' : 'dos'} vértices como mínimo y pulsa «Finalizar geometría».` ; }
  function renderDraft() { if (!state.draftLayer) return; state.draftLayer.clearLayers(); if (!state.draft.length) return; const latLngs = state.draft.map(point => [point[1], point[0]]); if (state.mode === 'Polygon' && latLngs.length >= 3) L.polygon(latLngs, { color: '#ffd47b', weight: 3, fillOpacity: .12, dashArray: '6 5' }).addTo(state.draftLayer); else if (state.mode === 'LineString') L.polyline(latLngs, { color: '#ffd47b', weight: 3, dashArray: '6 5' }).addTo(state.draftLayer); state.draft.forEach((point, index) => L.circleMarker([point[1], point[0]], { radius: 5, color: '#071b25', weight: 2, fillColor: '#ffd47b', fillOpacity: 1 }).bindTooltip(String(index + 1), { permanent: false }).addTo(state.draftLayer)); if (latLngs.length) state.map?.fitBounds(L.latLngBounds(latLngs), { padding: [25, 25], maxZoom: 17 }); }
  function popup(feature) { const props = feature.properties || {}; const coords = feature.geometry.type === 'Point' ? feature.geometry.coordinates : feature.geometry.coordinates.flat(feature.geometry.type === 'Polygon' ? 1 : 0)[0]; return `<strong>${esc(props.name)}</strong><br>${esc(feature.geometry.type)} · ${props.vertex_count || 1} vértices${coords ? '<br>' + Number(coords[1]).toFixed(6) + '°, ' + Number(coords[0]).toFixed(6) + '°' : ''}`; }
  function renderFeatures() { if (!state.layer) return; state.layer.clearLayers(); const geo = L.geoJSON({ type: 'FeatureCollection', features: state.features }, { style: { color: '#72e3be', weight: 3, fillColor: '#72e3be', fillOpacity: .18 }, pointToLayer: (feature, latlng) => L.circleMarker(latlng, { radius: 7, color: '#071b25', weight: 2, fillColor: '#72e3be', fillOpacity: .95 }), onEachFeature: (feature, layer) => layer.bindPopup(popup(feature)) }).addTo(state.layer); if (geo.getLayers().length) state.map?.fitBounds(geo.getBounds(), { padding: [25, 25], maxZoom: 17 }); const rows = state.features.map((feature, index) => { const coordinates = feature.geometry.type === 'Point' ? [feature.geometry.coordinates] : feature.geometry.type === 'LineString' ? feature.geometry.coordinates : feature.geometry.coordinates[0]; const length = coordinates.length > 1 ? coordinates.slice(1).reduce((sum, point, i) => sum + distance(coordinates[i], point), 0) : 0; return `<tr><td>${index + 1}</td><td><strong>${esc(feature.properties.name)}</strong></td><td>${feature.geometry.type}</td><td>${coordinates.length}</td><td>${length ? formatDistance(length) : '—'}</td></tr>`; }).join(''); $('tableWrap').innerHTML = rows ? `<table><thead><tr><th>#</th><th>Nombre</th><th>Tipo</th><th>Vértices</th><th>Longitud</th></tr></thead><tbody>${rows}</tbody></table>` : '<p class="empty">Tus entidades aparecerán aquí.</p>'; updateControls(); }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4168, -3.7038], 13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); state.draftLayer = L.layerGroup().addTo(state.map); state.map.on('click', event => addVertex(event.latlng.lat, event.latlng.lng)); }
  function output() { return { type: 'FeatureCollection', features: state.features }; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const lines = ['entidad,nombre,tipo,orden,longitud,latitud']; state.features.forEach((feature, featureIndex) => { const coordinates = feature.geometry.type === 'Point' ? [feature.geometry.coordinates] : feature.geometry.type === 'LineString' ? feature.geometry.coordinates : feature.geometry.coordinates[0]; coordinates.forEach((point, index) => lines.push([featureIndex + 1, feature.properties.name, feature.geometry.type, index + 1, point[0], point[1]].map(value => '"' + String(value).replace(/"/g, '""') + '"').join(','))); }); download('digitalizacion-vertices.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  document.querySelectorAll('.mode').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.mode').forEach(item => item.classList.remove('active')); button.classList.add('active'); state.mode = button.dataset.mode; state.draft = []; updateControls(); renderDraft(); })); $('addVertexBtn').addEventListener('click', () => addVertex(num($('lat').value), num($('lon').value))); $('finishBtn').addEventListener('click', finish); $('undoBtn').addEventListener('click', () => { state.draft.pop(); setStatus(state.draft.length ? `${state.draft.length} vértices en la geometría actual.` : 'Geometría actual vacía.'); updateControls(); renderDraft(); }); $('clearBtn').addEventListener('click', () => { state.features = []; state.draft = []; setStatus('Inventario limpiado localmente.'); renderDraft(); renderFeatures(); }); $('geojsonBtn').addEventListener('click', () => download('digitalizacion.geojson', JSON.stringify(output(), null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', exportCsv); initMap(); updateControls();
})();
