(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { sources: [], mosaic: null, map: null, overlay: null, footprints: null };
  const MAX_CELLS = 3200000;
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function format(value, digits = 3) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function quantile(values, q) { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return null; const p = (sorted.length - 1) * q; const base = Math.floor(p); const rest = p - base; return sorted[base + 1] === undefined ? sorted[base] : sorted[base] + rest * (sorted[base + 1] - sorted[base]); }
  function stats(values) { const valid = Array.from(values).filter(Number.isFinite); return valid.length ? { count: valid.length, min: Math.min(...valid), max: Math.max(...valid), mean: valid.reduce((sum, value) => sum + value, 0) / valid.length, p05: quantile(valid, .05), p95: quantile(valid, .95) } : { count: 0, min: null, max: null, mean: null, p05: null, p95: null }; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  function noDataValue(raw) { if (raw === null || raw === undefined || raw === '') return null; const value = Number(raw); return Number.isFinite(value) ? value : null; }
  function isValid(value, nodata) { return Number.isFinite(value) && (nodata === null || value !== nodata); }
  function extent(source) { const x0 = source.origin[0]; const y0 = source.origin[1]; const x1 = x0 + source.width * source.resolution[0]; const y1 = y0 + source.height * source.resolution[1]; return [Math.min(x0, x1), Math.min(y0, y1), Math.max(x0, x1), Math.max(y0, y1)]; }
  function geographic(extentValue) { return extentValue[0] >= -180 && extentValue[2] <= 180 && extentValue[1] >= -90 && extentValue[3] <= 90; }
  function syntheticSources() { const width = 92; const height = 76; const resolution = [.001, -.001]; const origins = [[-3.78, 40.48], [-3.70, 40.48], [-3.62, 40.48]]; return origins.map((origin, tile) => { const values = new Float32Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) values[y * width + x] = 105 + tile * 14 + x * .11 + y * .07 + 18 * Math.sin((x + tile * 12) / 15) + 12 * Math.cos(y / 13); return { name: `tesela_sintetica_${tile + 1}.tif`, width, height, resolution, origin, nodata: null, values, synthetic: true }; }); }
  async function readRaster(file) { if (!window.GeoTIFF) throw new Error('GeoTIFF.js no está disponible; revisa la conexión y vuelve a intentarlo.'); const tiff = await window.GeoTIFF.fromArrayBuffer(await file.arrayBuffer()); const image = await tiff.getImage(); const rasters = await image.readRasters({ interleave: false }); const origin = image.getOrigin?.(); const resolution = image.getResolution?.(); if (!origin || !resolution || !Number.isFinite(origin[0]) || !Number.isFinite(origin[1]) || !Number.isFinite(resolution[0]) || !Number.isFinite(resolution[1]) || resolution[0] === 0 || resolution[1] === 0) throw new Error(`${file.name}: falta georreferenciación o la resolución no es válida.`); const width = image.getWidth(); const height = image.getHeight(); const rawNoData = image.getGDALNoData?.(); return { name: file.name, width, height, origin, resolution, nodata: noDataValue(rawNoData), values: rasters[0], synthetic: false }; }
  function updateFileList() { $('fileList').innerHTML = state.sources.length ? state.sources.map((source) => `<div class="file-row"><strong title="${escapeHtml(source.name)}">${escapeHtml(source.name)}</strong><span>${source.width}×${source.height} · origen ${format(source.origin[0], 5)}, ${format(source.origin[1], 5)}</span></div>`).join('') : '<span class="muted">No hay teselas cargadas.</span>'; }
  function validateSources(sources) { if (sources.length < 2) throw new Error('Carga al menos dos GeoTIFF para construir un mosaico.'); const base = sources[0]; const problems = []; for (const source of sources) { if (Math.sign(source.resolution[0]) !== Math.sign(base.resolution[0]) || Math.sign(source.resolution[1]) !== Math.sign(base.resolution[1])) problems.push(`${source.name}: orientación de píxel distinta`); if (Math.abs(Math.abs(source.resolution[0]) - Math.abs(base.resolution[0])) > Math.abs(base.resolution[0]) * 1e-5 || Math.abs(Math.abs(source.resolution[1]) - Math.abs(base.resolution[1])) > Math.abs(base.resolution[1]) * 1e-5) problems.push(`${source.name}: resolución distinta`); } if (problems.length) throw new Error(`Las teselas no son compatibles: ${problems.slice(0, 3).join('; ')}.`); }
  function buildMosaic() { validateSources(state.sources); const base = state.sources[0]; const extents = state.sources.map(extent); const minX = Math.min(...extents.map((value) => value[0])); const minY = Math.min(...extents.map((value) => value[1])); const maxX = Math.max(...extents.map((value) => value[2])); const maxY = Math.max(...extents.map((value) => value[3])); const resX = base.resolution[0]; const resY = base.resolution[1]; const origin = [resX > 0 ? minX : maxX, resY > 0 ? minY : maxY]; const width = Math.round((maxX - minX) / Math.abs(resX)); const height = Math.round((maxY - minY) / Math.abs(resY)); const cells = width * height; if (!width || !height || cells > MAX_CELLS) throw new Error(`La malla de salida (${width}×${height}) es demasiado grande; reduce el número o tamaño de las teselas.`); const sums = new Float64Array(cells); const counts = new Uint16Array(cells); const values = new Float64Array(cells); values.fill(Number.NaN); const mode = $('overlapMode').value; for (const source of state.sources) { const colOffset = Math.round((source.origin[0] - origin[0]) / resX); const rowOffset = Math.round((source.origin[1] - origin[1]) / resY); for (let row = 0; row < source.height; row += 1) for (let column = 0; column < source.width; column += 1) { const value = Number(source.values[row * source.width + column]); if (!isValid(value, source.nodata)) continue; const targetColumn = column + colOffset; const targetRow = row + rowOffset; if (targetColumn < 0 || targetColumn >= width || targetRow < 0 || targetRow >= height) continue; const index = targetRow * width + targetColumn; counts[index] += 1; sums[index] += value; if (mode === 'first' && !Number.isFinite(values[index])) values[index] = value; if (mode === 'last') values[index] = value; } } if (mode === 'mean') for (let i = 0; i < cells; i += 1) values[i] = counts[i] ? sums[i] / counts[i] : Number.NaN; const valid = Array.from(values).filter(Number.isFinite); const outputStats = stats(valid); const covered = counts.reduce((sum, count) => sum + (count ? 1 : 0), 0); const overlap = counts.reduce((sum, count) => sum + Math.max(0, count - 1), 0); state.mosaic = { width, height, origin, resolution: [resX, resY], values, counts, stats: outputStats, covered, gaps: cells - covered, overlap, mode, extent: [minX, minY, maxX, maxY], geographic: geographic([minX, minY, maxX, maxY]) }; state.sources.forEach((source) => { source.stats = stats(Array.from(source.values).filter((value) => isValid(Number(value), source.nodata))); source.extent = extent(source); source.covered = source.stats.count; source.compatible = true; }); renderPreview(); renderResult(); renderMap(); }
  function color(value, low, high, palette) { if (!Number.isFinite(value)) return [0, 0, 0, 0]; const t = high === low ? .5 : Math.max(0, Math.min(1, (value - low) / (high - low))); if (palette === 'gray') { const c = Math.round(255 * t); return [c, c, c, 235]; } if (palette === 'terrain') { const stops = [[0, 35, 89, 168], [.35, 35, 128, 80], [.58, 210, 190, 90], [.78, 143, 96, 48], [1, 245, 245, 235]]; return interpolateStops(stops, t); } if (palette === 'diverging') { const stops = [[0, 42, 91, 192], [.5, 249, 250, 241], [1, 180, 42, 54]]; return interpolateStops(stops, t); } const stops = [[0, 68, 1, 84], [.25, 59, 82, 139], [.5, 33, 145, 140], [.75, 94, 201, 98], [1, 253, 231, 37]]; return interpolateStops(stops, t); }
  function interpolateStops(stops, t) { for (let i = 1; i < stops.length; i += 1) if (t <= stops[i][0]) { const a = stops[i - 1]; const b = stops[i]; const f = (t - a[0]) / (b[0] - a[0]); return [0, 1, 2].map((index) => Math.round(a[index + 1] + f * (b[index + 1] - a[index + 1]))).concat(235); } return stops.at(-1).slice(1).concat(235); }
  function renderPreview() { if (!state.mosaic) return; const mosaic = state.mosaic; const valid = Array.from(mosaic.values).filter(Number.isFinite); const low = quantile(valid, .02); const high = quantile(valid, Math.min(.999, Math.max(.5, Number($('highInput').value) / 100 || .98))); const maxWidth = 1400; const scale = Math.min(1, maxWidth / mosaic.width); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(mosaic.width * scale)); canvas.height = Math.max(1, Math.round(mosaic.height * scale)); const ctx = canvas.getContext('2d'); const image = ctx.createImageData(canvas.width, canvas.height); for (let y = 0; y < canvas.height; y += 1) for (let x = 0; x < canvas.width; x += 1) { const sourceX = Math.min(mosaic.width - 1, Math.floor(x / scale)); const sourceY = Math.min(mosaic.height - 1, Math.floor(y / scale)); const rgba = color(mosaic.values[sourceY * mosaic.width + sourceX], low, high, $('palette').value); const p = (y * canvas.width + x) * 4; image.data[p] = rgba[0]; image.data[p + 1] = rgba[1]; image.data[p + 2] = rgba[2]; image.data[p + 3] = rgba[3]; } ctx.putImageData(image, 0, 0); mosaic.rendered = canvas.toDataURL('image/png'); $('mapBadge').textContent = `${mosaic.width}×${mosaic.height}`; }
  function renderResult() { const m = state.mosaic; $('summary').hidden = $('detailPanel').hidden = false; $('sourceCount').textContent = state.sources.length.toLocaleString('es-ES'); $('gridSize').textContent = `${m.width}×${m.height}`; $('coveredCount').textContent = m.covered.toLocaleString('es-ES'); $('gapCount').textContent = m.gaps.toLocaleString('es-ES'); $('overlapCount').textContent = m.overlap.toLocaleString('es-ES'); $('globalMean').textContent = m.stats.mean === null ? '—' : format(m.stats.mean); $('summaryBadge').textContent = m.geographic ? 'lon/lat compatible' : 'extensión no WGS84'; $('detailBadge').textContent = `${state.sources.length} teselas`; $('interpretation').textContent = `${format(m.covered / (m.width * m.height) * 100, 1)} % de la malla tiene al menos un píxel válido; se detectan ${m.overlap.toLocaleString('es-ES')} contribuciones adicionales en zonas solapadas. La salida conserva la resolución y orientación de la primera tesela.`; $('detailBody').innerHTML = state.sources.map((source) => `<tr><th>${escapeHtml(source.name)}</th><td>${source.width}×${source.height}</td><td>${format(source.origin[0], 5)}, ${format(source.origin[1], 5)}</td><td>${format(source.resolution[0], 6)}, ${format(source.resolution[1], 6)}</td><td>${source.stats.count.toLocaleString('es-ES')}</td><td class="ok">Compatible</td></tr>`).join(''); ['pngBtn', 'csvBtn', 'reportBtn'].forEach((id) => $(id).disabled = false); }
  function sourceBounds(source) { const e = source.extent || extent(source); return [[e[1], e[0]], [e[3], e[2]]]; }
  function renderMap() { if (!state.map) return; state.overlay?.remove(); state.footprints?.remove(); const layers = []; state.sources.forEach((source, index) => { const color = ['#176b50', '#a33d50', '#3566a8', '#b77b18', '#6b3e8f'][index % 5]; layers.push(L.rectangle(sourceBounds(source), { color, weight: 2, fill: false }).bindPopup(`<strong>${escapeHtml(source.name)}</strong><br>${source.width}×${source.height}<br>Válidos: ${(source.stats?.count ?? 0).toLocaleString('es-ES')}`)); }); state.footprints = L.layerGroup(layers).addTo(state.map); if (state.mosaic?.rendered && state.mosaic.geographic) { const e = state.mosaic.extent; state.overlay = L.imageOverlay(state.mosaic.rendered, [[e[1], e[0]], [e[3], e[2]]], { opacity: .72 }).addTo(state.map); } const bounds = L.latLngBounds([]); state.sources.forEach((source) => bounds.extend(sourceBounds(source))); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [35, 35], maxZoom: 15 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function downloadPng() { if (state.mosaic?.rendered) { const link = document.createElement('a'); link.href = state.mosaic.rendered; link.download = 'raster-mosaic.png'; link.click(); } }
  function csv() { const m = state.mosaic; if (!m) return; const step = Math.max(1, Math.ceil(Math.sqrt((m.width * m.height) / 100000))); const rows = [['column', 'row', 'x', 'y', 'value', 'contributions']]; for (let row = 0; row < m.height; row += step) for (let column = 0; column < m.width; column += step) { const i = row * m.width + column; const value = m.values[i]; if (Number.isFinite(value)) rows.push([column, row, m.origin[0] + (column + .5) * m.resolution[0], m.origin[1] + (row + .5) * m.resolution[1], value, m.counts[i]]); } download('raster-mosaic-sample.csv', rows.map((row) => row.join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function report() { const m = state.mosaic; if (!m) return; download('raster-mosaic-report.json', JSON.stringify({ tool: 'Raster Mosaic Lab', assumptions: { first_band_only: true, reprojection: false, output_crs: 'same as first GeoTIFF', overlap: m.mode, no_data: 'excluded from valid pixels', maximum_output_cells: MAX_CELLS }, output: { width: m.width, height: m.height, origin: m.origin, resolution: m.resolution, extent: m.extent, statistics: m.stats, covered_cells: m.covered, gap_cells: m.gaps, overlap_contributions: m.overlap }, sources: state.sources.map((source) => ({ name: source.name, width: source.width, height: source.height, origin: source.origin, resolution: source.resolution, nodata: source.nodata, extent: source.extent, valid_pixels: source.stats?.count ?? null })), generated_at: new Date().toISOString() }, null, 2), 'application/json'); }
  function loadExample() { state.sources = syntheticSources(); updateFileList(); state.mosaic = null; $('summary').hidden = $('detailPanel').hidden = true; ['pngBtn', 'csvBtn', 'reportBtn'].forEach((id) => $(id).disabled = true); renderMap(); setStatus('Mosaico sintético cargado. Pulsa «Construir mosaico».'); }
  function clearAll() { state.sources = []; state.mosaic = null; state.overlay?.remove(); state.footprints?.remove(); state.overlay = state.footprints = null; $('fileInput').value = ''; $('summary').hidden = $('detailPanel').hidden = true; ['pngBtn', 'csvBtn', 'reportBtn'].forEach((id) => $(id).disabled = true); updateFileList(); setStatus('Carga dos o más GeoTIFF comparables o usa el ejemplo.'); renderMap(); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('fileInput').addEventListener('change', async () => { const files = [...($('fileInput').files || [])]; if (!files.length) return; setStatus(`Leyendo ${files.length} GeoTIFF…`); try { const sources = []; for (const file of files) sources.push(await readRaster(file)); state.sources = sources; state.mosaic = null; updateFileList(); $('summary').hidden = $('detailPanel').hidden = true; ['pngBtn', 'csvBtn', 'reportBtn'].forEach((id) => $(id).disabled = true); renderMap(); setStatus(`${sources.length.toLocaleString('es-ES')} teselas leídas. Pulsa «Construir mosaico».`); } catch (error) { state.sources = []; updateFileList(); setStatus(error.message || 'No se pudieron leer las teselas.', true); } });
  $('exampleBtn').addEventListener('click', loadExample); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { buildMosaic(); setStatus(`${state.mosaic.width}×${state.mosaic.height} celdas construidas; ${state.mosaic.covered.toLocaleString('es-ES')} cubiertas.`); } catch (error) { setStatus(error.message || 'No se pudo construir el mosaico.', true); } }); ['palette', 'highInput'].forEach((id) => $(id).addEventListener('change', () => { if (state.mosaic) { renderPreview(); renderMap(); } })); $('pngBtn').addEventListener('click', downloadPng); $('csvBtn').addEventListener('click', csv); $('reportBtn').addEventListener('click', report); updateFileList(); initMap();
})();
