(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { images: [], result: null, map: null, overlay: null };
  function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--danger)' : ''; }
  function format(value, digits = 3) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function quantile(values, q) { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return null; const p = (sorted.length - 1) * q; const base = Math.floor(p); const rest = p - base; return sorted[base + 1] === undefined ? sorted[base] : sorted[base] + rest * (sorted[base + 1] - sorted[base]); }
  function stat(values) { const valid = values.filter(Number.isFinite); return valid.length ? { count: valid.length, min: Math.min(...valid), max: Math.max(...valid), mean: valid.reduce((sum, value) => sum + value, 0) / valid.length, p05: quantile(valid, .05), p95: quantile(valid, .95) } : { count: 0, min: null, max: null, mean: null, p05: null, p95: null }; }
  function parseDate(name, fallback) { const match = String(name).match(/(19|20)\d{2}(?:[-_]?([01]\d)(?:[-_]?([0-3]\d))?)?/); if (!match) return new Date(Date.UTC(2000 + fallback, 0, 1)); const year = Number(match[0].slice(0, 4)); const month = Number(match[2] || 1); const day = Number(match[3] || 1); return new Date(Date.UTC(year, month - 1, day)); }
  function geographic(image) { if (!image.origin || !image.resolution) return false; const west = image.origin[0]; const north = image.origin[1]; const east = west + image.width * image.resolution[0]; const south = north + image.height * image.resolution[1]; return [west, east, south, north].every(Number.isFinite) && west >= -180 && east <= 180 && south >= -90 && north <= 90 && Math.abs(image.resolution[0]) < 2 && Math.abs(image.resolution[1]) < 2; }
  function syntheticImages() { const width = 160; const height = 110; return [0, 1, 2, 3].map((time) => { const values = new Float32Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) { const base = 100 + 28 * Math.sin(x / 16) + 18 * Math.cos(y / 13); const signal = time * (12 * Math.exp(-((x - 88) ** 2 + (y - 54) ** 2) / 1300) - 5 * Math.exp(-((x - 36) ** 2 + (y - 75) ** 2) / 850)); values[y * width + x] = base + signal; } return { width, height, values, origin: [-3.75, 40.46], resolution: [.001, -.001], date: new Date(Date.UTC(2020 + time, 0, 1)), source: `sintetico_${2020 + time}.tif`, nodata: null, samples: 1 }; }); }
  function updateFileList() { $('fileList').innerHTML = state.images.length ? state.images.map((image) => `<div><strong>${escapeHtml(image.source)}</strong><span>${image.width}×${image.height} · ${image.date.toISOString().slice(0, 10)}</span></div>`).join('') : 'No hay imágenes cargadas.'; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
  async function readFile(file, index) { if (!window.GeoTIFF) throw new Error('GeoTIFF.js no está disponible; revisa la conexión y vuelve a intentarlo.'); const tiff = await window.GeoTIFF.fromArrayBuffer(await file.arrayBuffer()); const image = await tiff.getImage(); const rasters = await image.readRasters({ interleave: false }); const rawNoData = image.getGDALNoData?.(); const nodataValue = rawNoData === null || rawNoData === undefined || rawNoData === '' ? null : Number(rawNoData); return { width: image.getWidth(), height: image.getHeight(), values: rasters[0], origin: image.getOrigin?.() || null, resolution: image.getResolution?.() || null, date: parseDate(file.name, index), source: file.name, nodata: Number.isFinite(nodataValue) ? nodataValue : null, samples: image.getSamplesPerPixel() }; }
  function renderFileListMessage() { updateFileList(); setStatus(`${state.images.length} imagen(es) listas. Comprueba que comparten malla y calcula.`); }
  function analyze() { if (state.images.length < 2) throw new Error('Carga al menos dos imágenes.'); const first = state.images[0]; if (!state.images.every((image) => image.width === first.width && image.height === first.height)) throw new Error('Las imágenes no comparten dimensiones.'); if (!state.images.every((image) => geographic(image) === geographic(first))) throw new Error('Las imágenes no comparten una georreferenciación compatible.'); const sorted = [...state.images].sort((a, b) => a.date - b.date); const size = first.width * first.height; const metrics = { mean: new Float32Array(size), first: new Float32Array(size), last: new Float32Array(size), change: new Float32Array(size), trend: new Float32Array(size) }; const changeValues = []; const validCounts = new Uint32Array(size); for (let index = 0; index < size; index += 1) { const samples = sorted.map((image) => { const value = image.values[index]; return Number.isFinite(value) && (image.nodata === null || value !== image.nodata) ? value : null; }); const valid = samples.map((value, timeIndex) => value === null ? null : { value, time: sorted[timeIndex].date.getTime() / 31557600000 }); const usable = valid.filter(Boolean); if (!usable.length) { metrics.mean[index] = metrics.first[index] = metrics.last[index] = metrics.change[index] = metrics.trend[index] = NaN; continue; } const mean = usable.reduce((sum, item) => sum + item.value, 0) / usable.length; const firstValue = usable[0].value; const lastValue = usable[usable.length - 1].value; const mx = usable.reduce((sum, item) => sum + item.time, 0) / usable.length; const my = mean; const denominator = usable.reduce((sum, item) => sum + (item.time - mx) ** 2, 0); const slope = denominator ? usable.reduce((sum, item) => sum + (item.time - mx) * (item.value - my), 0) / denominator : 0; metrics.mean[index] = mean; metrics.first[index] = firstValue; metrics.last[index] = lastValue; metrics.change[index] = lastValue - firstValue; metrics.trend[index] = slope; validCounts[index] = usable.length; changeValues.push(lastValue - firstValue); } const imageStats = sorted.map((image) => ({ source: image.source, date: image.date.toISOString(), stats: stat(Array.from(image.values).filter((value) => Number.isFinite(value) && (image.nodata === null || value !== image.nodata))) })); state.images = sorted; state.result = { width: first.width, height: first.height, origin: first.origin, resolution: first.resolution, metrics, validCounts, changeStats: stat(changeValues), imageStats, sourceDates: sorted.map((image) => image.date.toISOString()) }; render(); ['pngBtn', 'csvBtn', 'reportBtn'].forEach((id) => $(id).disabled = false); setStatus(`${sorted.length} imágenes comparadas; ${changeValues.length.toLocaleString('es-ES')} píxeles con cambio calculable.`); }
  function color(value, min, max, diverging) { const t = Math.max(0, Math.min(1, (value - min) / Math.max(1e-12, max - min))); if (diverging) { const neutral = .5; if (t < neutral) { const q = t / neutral; return [Math.round(45 + q * 210), Math.round(94 + q * 150), Math.round(180 + q * 65)]; } const q = (t - neutral) / neutral; return [Math.round(255), Math.round(244 - q * 180), Math.round(244 - q * 190)]; } return [Math.round(40 + t * 200), Math.round(120 + t * 115), Math.round(95 - t * 55)]; }
  function render() { const r = state.result; $('summary').hidden = false; $('imageCount').textContent = state.images.length; $('validCount').textContent = r.changeStats.count.toLocaleString('es-ES'); $('meanChange').textContent = format(r.changeStats.mean); $('p05Change').textContent = format(r.changeStats.p05); $('p95Change').textContent = format(r.changeStats.p95); $('period').textContent = `${state.images[0].date.getUTCFullYear()}–${state.images[state.images.length - 1].date.getUTCFullYear()}`; $('summaryBadge').textContent = `${r.width}×${r.height}`; $('interpretation').textContent = `El cambio es última imagen menos primera (${state.images[state.images.length - 1].source} − ${state.images[0].source}). La pendiente se calcula en unidades por año usando todas las observaciones válidas del píxel.`; $('viewBadge').textContent = `${state.images.length} fechas`; $('timelineBody').innerHTML = r.imageStats.map((item) => `<div class="timeline-row"><strong>${escapeHtml(item.source)}</strong><span>${item.date.slice(0, 10)} · n=${item.stats.count.toLocaleString('es-ES')} · media ${format(item.stats.mean)}</span></div>`).join(''); renderPreview(); renderMap(); }
  function selectedMetric() { return state.result.metrics[$('metricSelect').value]; }
  function renderPreview() { const r = state.result; const canvas = $('preview'); const rect = canvas.getBoundingClientRect(); const width = Math.max(1, Math.round(rect.width)); const height = Math.max(1, Math.round(rect.height)); canvas.width = width; canvas.height = height; const values = Array.from(selectedMetric()).filter(Number.isFinite); const low = quantile(values, Math.max(0, Math.min(.49, Number($('lowInput').value) / 100 || .02))); const high = quantile(values, Math.min(1, Math.max(.51, Number($('highInput').value) / 100 || .98))); const diverging = ['change', 'trend'].includes($('metricSelect').value); const off = document.createElement('canvas'); off.width = r.width; off.height = r.height; const ctx = off.getContext('2d'); const image = ctx.createImageData(r.width, r.height); selectedMetric().forEach((value, index) => { const rgb = Number.isFinite(value) ? color(value, low, high, diverging) : [0, 0, 0]; const target = index * 4; image.data[target] = rgb[0]; image.data[target + 1] = rgb[1]; image.data[target + 2] = rgb[2]; image.data[target + 3] = Number.isFinite(value) ? 255 : 0; }); ctx.putImageData(image, 0, 0); const out = canvas.getContext('2d'); out.clearRect(0, 0, width, height); out.imageSmoothingEnabled = false; out.drawImage(off, 0, 0, width, height); state.result.rendered = canvas.toDataURL('image/png'); $('previewFallback').textContent = `${$('metricSelect').selectedOptions[0].text} · estiramiento ${format(low)}–${format(high)}.`; }
  function renderMap() { if (!state.map || !state.result) return; state.overlay?.remove(); if (!geographic(state.images[0])) { $('mapBadge').textContent = 'sin huella WGS84'; return; } const west = state.result.origin[0]; const north = state.result.origin[1]; const east = west + state.result.width * state.result.resolution[0]; const south = north + state.result.height * state.result.resolution[1]; const bounds = [[Math.min(south, north), Math.min(west, east)], [Math.max(south, north), Math.max(west, east)]]; state.overlay = L.imageOverlay(state.result.rendered, bounds, { opacity: .76 }).addTo(state.map); state.map.fitBounds(bounds, { padding: [30, 30], maxZoom: 15 }); $('mapBadge').textContent = $('metricSelect').value; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function downloadPng() { if (!state.result?.rendered) return; const link = document.createElement('a'); link.href = state.result.rendered; link.download = 'raster-time-series.png'; link.click(); }
  function csv() { const r = state.result; if (!r) return; const rows = [['column', 'row', 'x_or_lon', 'y_or_lat', 'mean', 'first', 'last', 'change', 'trend_per_year']]; const step = Math.max(1, Math.ceil(Math.sqrt((r.width * r.height) / 10000))); for (let row = 0; row < r.height; row += step) for (let column = 0; column < r.width; column += step) { const index = row * r.width + column; const x = r.origin ? r.origin[0] + (column + .5) * r.resolution[0] : column; const y = r.origin ? r.origin[1] + (row + .5) * r.resolution[1] : row; rows.push([column, row, x, y, r.metrics.mean[index], r.metrics.first[index], r.metrics.last[index], r.metrics.change[index], r.metrics.trend[index]]); } download('raster-time-series-sample.csv', rows.map((row) => row.map((value) => /[",\n]/.test(String(value)) ? `"${String(value).replace(/"/g, '""')}"` : value).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function report() { const r = state.result; if (!r) return; download('raster-time-series-report.json', JSON.stringify({ assumptions: { first_band_only: true, change: 'last minus first', trend: 'linear regression units per year', coordinate_system: 'source GeoTIFF, map overlay only when geographic WGS84-like' }, grid: { width: r.width, height: r.height, origin: r.origin, resolution: r.resolution }, images: r.imageStats, change_statistics: r.changeStats }, null, 2), 'application/json'); }
  function loadExample() { state.images = syntheticImages(); updateFileList(); state.result = null; $('summary').hidden = true; ['pngBtn', 'csvBtn', 'reportBtn', 'renderBtn'].forEach((id) => $(id).disabled = false); setStatus('Serie sintética cargada. Pulsa «Calcular serie».'); }
  function clearAll() { state.images = []; state.result = null; state.overlay?.remove(); state.overlay = null; $('fileInput').value = ''; $('summary').hidden = true; ['pngBtn', 'csvBtn', 'reportBtn', 'renderBtn'].forEach((id) => $(id).disabled = true); updateFileList(); $('viewBadge').textContent = $('mapBadge').textContent = '—'; setStatus('Carga al menos dos GeoTIFF de la misma malla o usa el ejemplo.'); }
  function initMap() { if (!window.L) return; state.map = L.map('map', { preferCanvas: true }).setView([40.42, -3.70], 12); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors' }).addTo(state.map); if (window.CartografiaPlaceSearch) CartografiaPlaceSearch(state.map, { input: $('placeQuery'), button: $('placeSearchButton'), results: $('placeResults'), status: $('placeStatus') }); }
  $('exampleBtn').addEventListener('click', loadExample); $('clearBtn').addEventListener('click', clearAll); $('runBtn').addEventListener('click', () => { try { analyze(); } catch (error) { setStatus(error.message || 'No se pudo calcular la serie.', true); } }); $('fileInput').addEventListener('change', async () => { const files = [...($('fileInput').files || [])]; if (!files.length) return; if (files.length > 24) { setStatus('Selecciona como máximo 24 imágenes para mantener el cálculo local manejable.', true); return; } setStatus(`Leyendo ${files.length} GeoTIFF…`); try { state.images = []; for (let i = 0; i < files.length; i += 1) state.images.push(await readFile(files[i], i)); updateFileList(); renderFileListMessage(); } catch (error) { setStatus(error.message || 'No se pudieron leer las imágenes.', true); } }); $('renderBtn').addEventListener('click', () => { if (state.result) { renderPreview(); renderMap(); } }); $('metricSelect').addEventListener('change', () => { if (state.result) { renderPreview(); renderMap(); } }); ['lowInput', 'highInput'].forEach((id) => $(id).addEventListener('change', () => { if (state.result) { renderPreview(); renderMap(); } })); $('pngBtn').addEventListener('click', downloadPng); $('csvBtn').addEventListener('click', csv); $('reportBtn').addEventListener('click', report); window.addEventListener('resize', () => { if (state.result) { renderPreview(); renderMap(); } }); initMap();
})();
