(() => {
  'use strict';

  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { points: [], order: [], legs: [], map: null, layer: null, returnStart: false };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
  const radius = 6371008.8, rad = value => value * Math.PI / 180;

  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function format(value, digits = 2) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: digits }); }
  function number(value) { const parsed = Number(String(value ?? '').trim().replace(',', '.')); return Number.isFinite(parsed) ? parsed : null; }
  function distance(a, b) { const dLat = rad(b.lat - a.lat), dLon = rad(b.lon - a.lon), q = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2; return radius * 2 * Math.atan2(Math.sqrt(q), Math.sqrt(1 - q)); }
  function csvRows(value) { return value.trim().split(/\r?\n/).map(line => line.split(/[,;\t]/).map(item => item.trim().replace(/^"|"$/g, ''))).filter(row => row.some(Boolean)); }
  function parseJson(parsed) {
    const features = parsed.type === 'FeatureCollection' ? parsed.features : parsed.type === 'Feature' ? [parsed] : Array.isArray(parsed) ? parsed : [];
    if (!features.length) throw new Error('El JSON no contiene una FeatureCollection, un Feature ni una lista de puntos.');
    return features.map((item, index) => { if (item.type === 'Feature') { const coordinates = item.geometry?.coordinates, props = item.properties || {}; return { name: props.nombre || props.name || props.title || `Punto ${index + 1}`, lat: number(coordinates?.[1]), lon: number(coordinates?.[0]), properties: props }; } return { name: item.nombre || item.name || `Punto ${index + 1}`, lat: number(item.lat ?? item.latitude ?? item.y), lon: number(item.lon ?? item.lng ?? item.longitude ?? item.x), properties: item }; });
  }
  function parseCsv(value) {
    const rows = csvRows(value); if (!rows.length) return []; const first = rows[0].map(item => item.toLowerCase()), hasHeader = first.some(item => /nombre|name|lat|lon|long|x|y/.test(item)), header = hasHeader ? first : ['nombre', 'lat', 'lon'], data = hasHeader ? rows.slice(1) : rows;
    const find = patterns => { const index = header.findIndex(item => patterns.some(pattern => pattern.test(item))); return index < 0 ? null : index; }; const nameIndex = find([/nombre/, /^name$/, /title/]), latIndex = find([/^lat/, /^y$/]), lonIndex = find([/^lon/, /long/, /^x$/]); if (latIndex === null || lonIndex === null) throw new Error('El CSV necesita columnas lat/lon o y/x.');
    return data.map((row, index) => ({ name: row[nameIndex ?? -1] || `Punto ${index + 1}`, lat: number(row[latIndex]), lon: number(row[lonIndex]), properties: {} }));
  }
  function parseSource(value) { const text = value.trim(); let points; try { points = /^[\[{]/.test(text) ? parseJson(JSON.parse(text)) : parseCsv(text); } catch (error) { throw new Error(error.message || 'No se pudo leer la capa de puntos.'); } const clean = points.filter(point => Number.isFinite(point.lat) && Number.isFinite(point.lon) && point.lat >= -90 && point.lat <= 90 && point.lon >= -180 && point.lon <= 180); if (clean.length < 2) throw new Error('Se necesitan al menos dos puntos con latitud y longitud válidas.'); return clean.map((point, index) => ({ ...point, id: index })); }

  function pathDistance(points, order, close) { let total = 0; for (let index = 1; index < order.length; index++) total += distance(points[order[index - 1]], points[order[index]]); if (close && order.length > 1) total += distance(points[order[order.length - 1]], points[order[0]]); return total; }
  function nearestNeighbor(points, start, end) { const remaining = new Set(points.map((_, index) => index)); remaining.delete(start); const order = [start]; while (remaining.size) { const current = order[order.length - 1]; let next = null; for (const candidate of remaining) if (next === null || distance(points[current], points[candidate]) < distance(points[current], points[next])) next = candidate; if (next === end && remaining.size > 1) { const alternatives = [...remaining].filter(candidate => candidate !== end); next = alternatives.sort((a, b) => distance(points[current], points[a]) - distance(points[current], points[b]))[0]; } order.push(next); remaining.delete(next); } if (end !== null && order[order.length - 1] !== end) { const index = order.indexOf(end); order.splice(index, 1); order.push(end); } return order; }
  function twoOpt(points, order, close) { let best = order.slice(), improved = true; while (improved) { improved = false; for (let i = 1; i < best.length - 2; i++) for (let j = i + 1; j < best.length - (close ? 0 : 1); j++) { const candidate = best.slice(0, i).concat(best.slice(i, j + 1).reverse(), best.slice(j + 1)); if (pathDistance(points, candidate, close) + .01 < pathDistance(points, best, close)) { best = candidate; improved = true; } } } return best; }
  function originalDistance(points, close) { return pathDistance(points, points.map((_, index) => index), close); }
  function populateStartEnd(points) { const previousStart = $('startPoint').value, previousEnd = $('endPoint').value; $('startPoint').innerHTML = points.map(point => `<option value="${point.id}">${esc(point.name)}</option>`).join(''); $('endPoint').innerHTML = '<option value="auto">Automático</option>' + points.map(point => `<option value="${point.id}">${esc(point.name)}</option>`).join(''); if (points.some(point => String(point.id) === previousStart)) $('startPoint').value = previousStart; if (points.some(point => String(point.id) === previousEnd)) $('endPoint').value = previousEnd; }

  function calculate() {
    try {
      const points = parseSource($('source').value); populateStartEnd(points); const start = Number($('startPoint').value) || 0, requestedEnd = $('endPoint').value === 'auto' ? null : Number($('endPoint').value), close = $('returnStart').checked, initial = nearestNeighbor(points, start, requestedEnd), order = twoOpt(points, initial, close), total = pathDistance(points, order, close), baseline = originalDistance(points, close), legs = [];
      for (let index = 1; index < order.length; index++) legs.push({ order: index, from: points[order[index - 1]], to: points[order[index]], distance: distance(points[order[index - 1]], points[order[index]]) }); if (close && order.length > 1) legs.push({ order: legs.length + 1, from: points[order[order.length - 1]], to: points[order[0]], distance: distance(points[order[order.length - 1]], points[order[0]]) });
      state.points = points; state.order = order; state.legs = legs; state.returnStart = close; renderMap(); renderTable(); updateStats(total, baseline, legs); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; $('quality').textContent = 'Listo'; $('quality').style.background = '#143747'; $('quality').style.borderColor = '#346275'; $('quality').style.color = 'var(--accent)'; setStatus(`${points.length} puntos ordenados localmente en ${legs.length} tramos.`);
    } catch (error) { setStatus(error.message || 'No se pudo optimizar la ruta.', true); }
  }
  function updateStats(total, baseline, legs) { const speed = Math.max(0, number($('speed').value) ?? 0), savings = baseline > 0 ? (1 - total / baseline) * 100 : 0; $('pointCount').textContent = state.points.length.toLocaleString('es-ES'); $('distance').textContent = format(total / 1000) + ' km'; $('savings').textContent = format(savings) + '%'; $('duration').textContent = speed ? format(total / 1000 / speed) + ' h' : 'sin velocidad'; $('legCount').textContent = legs.length.toLocaleString('es-ES'); $('pointBadge').textContent = `${state.points.length} puntos`; }
  function initMap() { if (!window.L) return; state.map = L.map('map').setView([40.418, -3.703], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer) return; state.layer.clearLayers(); const line = state.order.map(index => [state.points[index].lat, state.points[index].lon]); if (state.returnStart && line.length) line.push(line[0]); L.polyline(line, { color: '#75d6c4', weight: 4, opacity: .92 }).addTo(state.layer); const bounds = []; state.order.forEach((pointIndex, index) => { const point = state.points[pointIndex], isStart = index === 0, marker = L.circleMarker([point.lat, point.lon], { radius: isStart ? 9 : 7, color: isStart ? '#f7c86b' : '#75d6c4', fillColor: isStart ? '#f7c86b' : '#75d6c4', fillOpacity: .95, weight: 2 }); marker.bindTooltip(String(index + 1), { permanent: true, direction: 'center', className: 'route-number' }).bindPopup(`<strong>${esc(point.name)}</strong><br>Orden: ${index + 1}<br>${point.lat.toFixed(5)}, ${point.lon.toFixed(5)}`).addTo(state.layer); bounds.push([point.lat, point.lon]); }); if (bounds.length) state.map.fitBounds(bounds, { padding: [28, 28], maxZoom: 15 }); }
  function renderTable() { $('tableWrap').innerHTML = `<table><thead><tr><th>TRAMO</th><th>ORDEN</th><th>DESDE → HASTA</th><th>DISTANCIA</th></tr></thead><tbody>${state.legs.map(leg => `<tr><td>${leg.order}</td><td>${state.order.indexOf(leg.from.id) + 1} → ${state.order.indexOf(leg.to.id) + 1}</td><td>${esc(leg.from.name)} → ${esc(leg.to.name)}</td><td>${format(leg.distance)} m</td></tr>`).join('')}</tbody></table><p class="table-foot">${state.legs.length} tramos · el cierre aparece como último tramo cuando se ha activado.</p>`; }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function csvCell(value) { const text = String(value ?? ''); return `"${text.replace(/"/g, '""')}"`; }
  function exportCsv() { const lines = ['tramo,orden,desde,hasta,lat_desde,lon_desde,lat_hasta,lon_hasta,distancia_m']; state.legs.forEach(leg => lines.push([leg.order, `${state.order.indexOf(leg.from.id) + 1}-${state.order.indexOf(leg.to.id) + 1}`, leg.from.name, leg.to.name, leg.from.lat, leg.from.lon, leg.to.lat, leg.to.lon, leg.distance].map(csvCell).join(','))); download('ruta-optimizada.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function exportGeoJSON() { const coordinates = state.order.map(index => [state.points[index].lon, state.points[index].lat]); if (state.returnStart) coordinates.push(coordinates[0]); const features = state.order.map((pointIndex, index) => { const point = state.points[pointIndex]; return { type: 'Feature', properties: { nombre: point.name, orden_visita: index + 1, id_origen: point.id }, geometry: { type: 'Point', coordinates: [point.lon, point.lat] } }; }); features.push({ type: 'Feature', properties: { nombre: 'Ruta optimizada', orden: state.order.length, regreso_inicio: state.returnStart }, geometry: { type: 'LineString', coordinates } }); download('ruta-optimizada.geojson', JSON.stringify({ type: 'FeatureCollection', features }, null, 2), 'application/geo+json;charset=utf-8'); }

  $('calculateBtn').addEventListener('click', calculate); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; $('returnStart').checked = false; calculate(); }); $('startPoint').addEventListener('change', calculate); $('endPoint').addEventListener('change', calculate); $('returnStart').addEventListener('change', calculate); $('speed').addEventListener('change', calculate);
  $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); calculate(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', exportGeoJSON); $('csvBtn').addEventListener('click', exportCsv); initMap(); calculate();
})();
