(() => {
  'use strict';

  const state = { geojson: null, bbox: null, tiles: [], levels: [], map: null, tileLayer: null, bboxLayer: null, output: null };
  const $ = (id) => document.getElementById(id);
  const els = { fileInput: $('fileInput'), fileName: $('fileName'), bbox: $('bbox'), template: $('template'), zoomMin: $('zoomMin'), zoomMax: $('zoomMax'), exampleBtn: $('exampleBtn'), clearBtn: $('clearBtn'), runBtn: $('runBtn'), status: $('status'), zoomSummary: $('zoomSummary'), tileCount: $('tileCount'), widthSummary: $('widthSummary'), heightSummary: $('heightSummary'), geojsonBtn: $('geojsonBtn'), csvBtn: $('csvBtn'), map: $('map'), mapFallback: $('mapFallback'), resultBody: $('resultBody'), tableHint: $('tableHint') };

  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function round(value, digits = 4) { const factor = 10 ** digits; return Math.round(value * factor) / factor; }
  function setStatus(message, error = false) { els.status.textContent = message; els.status.classList.toggle('error', error); }
  function positionsOf(value, output = []) { if (!Array.isArray(value)) return output; if (value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) { output.push([Number(value[0]), Number(value[1])]); return output; } value.forEach((child) => positionsOf(child, output)); return output; }
  function extentOf(input) { const features = input.type === 'FeatureCollection' ? input.features : input.type === 'Feature' ? [input] : input.coordinates ? [{ geometry: input }] : []; const positions = features.flatMap((feature) => positionsOf(feature.geometry && feature.geometry.coordinates)).filter(([lon, lat]) => lon >= -180 && lon <= 180 && lat >= -85.051128 && lat <= 85.051128); if (!positions.length) throw new Error('El GeoJSON no contiene coordenadas WGS84 válidas.'); return [Math.min(...positions.map((point) => point[0])), Math.min(...positions.map((point) => point[1])), Math.max(...positions.map((point) => point[0])), Math.max(...positions.map((point) => point[1]))]; }
  function parseBbox() { const values = els.bbox.value.split(',').map((value) => Number(value.trim())); if (values.length !== 4 || values.some((value) => !Number.isFinite(value))) throw new Error('La caja debe tener cuatro números: oeste,sur,este,norte.'); const [west, south, east, north] = values; if (west >= east || south >= north || west < -180 || east > 180 || south < -85.051128 || north > 85.051128) throw new Error('La caja no es válida o supera los límites de Web Mercator.'); return values; }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function tileX(lon, zoom) { return clamp(Math.floor((lon + 180) / 360 * (2 ** zoom)), 0, (2 ** zoom) - 1); }
  function tileY(lat, zoom) { const rad = lat * Math.PI / 180; const raw = Math.floor((1 - Math.asinh(Math.tan(rad)) / Math.PI) / 2 * (2 ** zoom)); return clamp(raw, 0, (2 ** zoom) - 1); }
  function tileLongitude(x, zoom) { return x / (2 ** zoom) * 360 - 180; }
  function tileLatitude(y, zoom) { const n = Math.PI - (2 * Math.PI * y) / (2 ** zoom); return 180 / Math.PI * Math.atan(Math.sinh(n)); }
  function tileUrl(z, x, y) { return els.template.value.trim().replaceAll('{z}', z).replaceAll('{x}', x).replaceAll('{y}', y); }
  function formatCount(value) { return new Intl.NumberFormat('es-ES').format(value); }
  function popup(title, properties) { return `<div class="popup-title">${escapeHtml(title)}</div><div class="popup-data">${escapeHtml(JSON.stringify(properties || {}, null, 2))}</div>`; }
  function initMap() { if (!window.L) { els.map.hidden = true; els.mapFallback.hidden = false; return; } try { state.map = L.map(els.map, { zoomControl: true }).setView([40.4168, -3.7038], 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' }).addTo(state.map); } catch (error) { els.map.hidden = true; els.mapFallback.hidden = false; setStatus('El índice funciona, pero el mapa no pudo inicializarse.', true); } }
  function clearLayers() { [state.tileLayer, state.bboxLayer].forEach((layer) => { if (layer && state.map) state.map.removeLayer(layer); }); state.tileLayer = state.bboxLayer = null; }
  function renderMap() { if (!state.map || !state.output) return; clearLayers(); const selectedZoom = state.levels.length ? state.levels[state.levels.length - 1].zoom : 0; const visible = state.tiles.filter((tile) => tile.z === selectedZoom); state.tileLayer = L.geoJSON({ type: 'FeatureCollection', features: visible.map((tile) => tile.feature) }, { style: { color: '#ffd071', weight: 1, fillColor: '#ffd071', fillOpacity: .18 }, onEachFeature: (feature, layer) => layer.bindPopup(popup(`z${feature.properties.z} / x${feature.properties.x} / y${feature.properties.y}`, feature.properties)) }).addTo(state.map); const [west, south, east, north] = state.bbox; state.bboxLayer = L.rectangle([[south, west], [north, east]], { color: '#6ee0b1', weight: 2, dashArray: '6 5', fill: false }).addTo(state.map); const bounds = state.tileLayer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [20, 20], maxZoom: 15 }); else state.map.fitBounds([[south, west], [north, east]], { padding: [20, 20], maxZoom: 15 }); }
  function generate() { try { const bbox = state.geojson ? extentOf(state.geojson) : parseBbox(); const zoomMin = Number(els.zoomMin.value); const zoomMax = Number(els.zoomMax.value); if (!Number.isInteger(zoomMin) || !Number.isInteger(zoomMax) || zoomMin < 0 || zoomMax > 20 || zoomMin > zoomMax) throw new Error('Los niveles de zoom deben ser enteros entre 0 y 20, con inicial ≤ final.'); const [west, south, east, north] = bbox; const tiles = []; const levels = []; let total = 0; for (let zoom = zoomMin; zoom <= zoomMax; zoom += 1) { const xMin = tileX(west, zoom); const xMax = tileX(east, zoom); const yMin = tileY(north, zoom); const yMax = tileY(south, zoom); const count = (xMax - xMin + 1) * (yMax - yMin + 1); if (total + count > 50000) throw new Error('El índice superaría 50.000 teselas. Reduce el rango de zoom o la extensión.'); const level = { zoom, xMin, xMax, yMin, yMax, count }; levels.push(level); total += count; for (let x = xMin; x <= xMax; x += 1) for (let y = yMin; y <= yMax; y += 1) { const westTile = tileLongitude(x, zoom); const eastTile = tileLongitude(x + 1, zoom); const northTile = tileLatitude(y, zoom); const southTile = tileLatitude(y + 1, zoom); const feature = { type: 'Feature', properties: { z: zoom, x, y, url: tileUrl(zoom, x, y) }, geometry: { type: 'Polygon', coordinates: [[[westTile, southTile], [eastTile, southTile], [eastTile, northTile], [westTile, northTile], [westTile, southTile]]] } }; tiles.push({ z: zoom, x, y, feature }); } } state.bbox = bbox; state.levels = levels; state.tiles = tiles; state.output = { type: 'FeatureCollection', features: tiles.map((tile) => tile.feature), properties: { bbox, zoom_min: zoomMin, zoom_max: zoomMax, template: els.template.value.trim() } }; els.zoomSummary.textContent = `${zoomMin}–${zoomMax}`; els.tileCount.textContent = formatCount(total); els.widthSummary.textContent = `${round(east - west, 4)}°`; els.heightSummary.textContent = `${round(north - south, 4)}°`; els.geojsonBtn.disabled = els.csvBtn.disabled = false; els.tableHint.textContent = `${formatCount(total)} teselas · vista cartográfica en z${zoomMax}`; els.resultBody.innerHTML = levels.map((level) => `<tr><td>${level.zoom}</td><td>${level.xMin}–${level.xMax}</td><td>${level.yMin}–${level.yMax}</td><td>${level.xMax - level.xMin + 1} × ${level.yMax - level.yMin + 1}</td><td>${formatCount(level.count)}</td></tr>`).join(''); renderMap(); setStatus(`Índice completado: ${formatCount(total)} teselas en ${levels.length} niveles.`); } catch (error) { setStatus(error.message, true); } }
  function readFile(file) { const reader = new FileReader(); reader.onload = () => { try { state.geojson = JSON.parse(reader.result); const bbox = extentOf(state.geojson); els.bbox.value = bbox.map((value) => round(value, 6)).join(','); els.fileName.textContent = `${file.name} · extensión calculada`; setStatus('Extensión cargada desde GeoJSON. Revisa el zoom y genera el índice.'); } catch (error) { setStatus(error.message, true); } }; reader.onerror = () => setStatus(`No se pudo leer ${file.name}.`, true); reader.readAsText(file); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  function csvValue(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function downloadCsv() { const rows = [['z', 'x', 'y', 'west', 'south', 'east', 'north', 'url']]; state.tiles.forEach((tile) => rows.push([tile.z, tile.x, tile.y, tile.feature.geometry.coordinates[0][0][0], tile.feature.geometry.coordinates[0][1][1], tile.feature.geometry.coordinates[0][1][0], tile.feature.geometry.coordinates[0][2][1], tile.feature.properties.url])); download('tile-index.csv', rows.map((row) => row.map(csvValue).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
  function loadExample() { state.geojson = null; els.fileName.textContent = 'Ejemplo · caja de Madrid'; els.bbox.value = '-3.78,40.38,-3.64,40.46'; els.zoomMin.value = '12'; els.zoomMax.value = '14'; els.template.value = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'; setStatus('Ejemplo cargado. Generando índice…'); generate(); }
  function clearAll() { state.geojson = null; state.bbox = null; state.tiles = []; state.levels = []; state.output = null; els.fileInput.value = ''; els.fileName.textContent = 'Ningún archivo seleccionado'; ['tileCount', 'zoomSummary', 'widthSummary', 'heightSummary'].forEach((id) => $(id).textContent = '—'); els.geojsonBtn.disabled = els.csvBtn.disabled = true; els.resultBody.innerHTML = '<tr><td colspan="5" class="empty">Todavía no hay resultados.</td></tr>'; els.tableHint.textContent = 'Genera un índice para ver la lista.'; clearLayers(); setStatus('Introduce una caja WGS84 o carga un GeoJSON.'); }
  els.fileInput.addEventListener('change', (event) => { const file = event.target.files[0]; if (file) readFile(file); }); els.exampleBtn.addEventListener('click', loadExample); els.clearBtn.addEventListener('click', clearAll); els.runBtn.addEventListener('click', generate); els.geojsonBtn.addEventListener('click', () => download('tile-index.geojson', JSON.stringify(state.output, null, 2), 'application/geo+json;charset=utf-8')); els.csvBtn.addEventListener('click', downloadCsv); initMap();
})();
