const $ = id => document.getElementById(id);
const state = { before: null, after: null, output: null, width: 640, height: 400 };
function setStatus(text) { $('status').textContent = text; }
function makeDemo(after) {
  const canvas = document.createElement('canvas'); canvas.width = state.width; canvas.height = state.height; const context = canvas.getContext('2d');
  const gradient = context.createLinearGradient(0, 0, state.width, state.height); gradient.addColorStop(0, after ? '#174e54' : '#234b4c'); gradient.addColorStop(.55, after ? '#6a8b55' : '#6d9358'); gradient.addColorStop(1, after ? '#bd9b58' : '#a9874e'); context.fillStyle = gradient; context.fillRect(0, 0, state.width, state.height);
  context.globalAlpha = .22; context.fillStyle = '#d9e9bd'; for (let i = 0; i < 18; i += 1) { context.beginPath(); context.arc(30 + (i * 83) % 620, 35 + (i * 47) % 360, 18 + i % 4 * 11, 0, Math.PI * 2); context.fill(); } context.globalAlpha = 1;
  context.strokeStyle = '#d9d3a966'; context.lineWidth = 8; context.beginPath(); context.moveTo(-20, 330); context.bezierCurveTo(150, 220, 280, 360, 430, 245); context.bezierCurveTo(520, 180, 600, 225, 680, 95); context.stroke();
  context.strokeStyle = '#3b5c5599'; context.lineWidth = 2; for (let i = 0; i < 9; i += 1) { context.beginPath(); context.moveTo(0, 55 + i * 39); context.bezierCurveTo(170, 20 + i * 42, 380, 90 + i * 18, 660, 45 + i * 39); context.stroke(); }
  if (after) { context.fillStyle = '#b83e45cc'; context.fillRect(382, 102, 126, 82); context.fillStyle = '#e4c45d'; context.fillRect(416, 285, 142, 26); context.strokeStyle = '#523e48'; context.lineWidth = 5; context.strokeRect(382, 102, 126, 82); context.strokeRect(416, 285, 142, 26); }
  return context.getImageData(0, 0, state.width, state.height);
}
function loadImage(file, target) {
  const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = state.width; canvas.height = state.height; const context = canvas.getContext('2d'); context.drawImage(image, 0, 0, state.width, state.height); state[target] = context.getImageData(0, 0, state.width, state.height); setStatus('Imagen ' + (target === 'before' ? 'anterior' : 'actual') + ' cargada: ' + file.name + '.'); render(); }; image.onerror = () => setStatus('No se pudo interpretar la imagen.'); image.src = reader.result; }; reader.readAsDataURL(file);
}
function render() {
  const canvas = $('canvas'); const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; const width = Math.max(320, rect.width); const height = Math.max(240, width * .625); canvas.width = width * dpr; canvas.height = height * dpr; canvas.style.height = String(height) + 'px'; const context = canvas.getContext('2d'); context.setTransform(dpr, 0, 0, dpr, 0, 0);
  if (!state.before || !state.after) { context.fillStyle = '#0b202b'; context.fillRect(0, 0, width, height); context.fillStyle = '#9ab8c4'; context.font = '16px system-ui'; context.fillText('Carga dos imágenes para comparar.', 24, 42); $('metrics').innerHTML = ''; $('export').disabled = true; return; }
  const before = state.before.data; const after = state.after.data; const output = new ImageData(state.width, state.height); const threshold = Number($('threshold').value) * 2.55; const mix = Number($('mix').value) / 100; let changed = 0; let total = 0;
  for (let index = 0; index < before.length; index += 4) { const red = Math.abs(before[index] - after[index]); const green = Math.abs(before[index + 1] - after[index + 1]); const blue = Math.abs(before[index + 2] - after[index + 2]); const difference = (red + green + blue) / 3; total += difference; const isChanged = difference >= threshold; if (isChanged) changed += 1; let rgb; if ($('mode').value === 'before') rgb = [before[index], before[index + 1], before[index + 2]]; else if ($('mode').value === 'after') rgb = [after[index], after[index + 1], after[index + 2]]; else if ($('mode').value === 'blend') rgb = [before[index] * (1 - mix) + after[index] * mix, before[index + 1] * (1 - mix) + after[index + 1] * mix, before[index + 2] * (1 - mix) + after[index + 2] * mix]; else { const intensity = Math.min(255, difference * 2.7); rgb = isChanged ? [Math.min(255, intensity + 50), Math.max(30, 220 - intensity), 65] : [12 + difference * .3, 38 + difference * .6, 48 + difference * .7]; } output.data[index] = rgb[0]; output.data[index + 1] = rgb[1]; output.data[index + 2] = rgb[2]; output.data[index + 3] = 255; }
  state.output = output; const buffer = document.createElement('canvas'); buffer.width = state.width; buffer.height = state.height; buffer.getContext('2d').putImageData(output, 0, 0); context.drawImage(buffer, 0, 0, width, height); const pixels = state.width * state.height; $('metrics').innerHTML = [['Cambio detectado', (changed / pixels * 100).toLocaleString('es-ES', { maximumFractionDigits: 1 }) + '%'], ['Diferencia media', (total / pixels / 2.55).toLocaleString('es-ES', { maximumFractionDigits: 1 })], ['Resolución', state.width + ' × ' + state.height], ['Umbral activo', $('threshold').value]].map(item => '<div class="metric"><b>' + item[1] + '</b><span>' + item[0] + '</span></div>').join(''); $('export').disabled = false;
}
function demo() { state.before = makeDemo(false); state.after = makeDemo(true); setStatus('Ejemplo generado: una transformación de cobertura y una nueva infraestructura.'); render(); }
function download() { const link = document.createElement('a'); link.href = $('canvas').toDataURL('image/png'); link.download = 'raster-change-lab.png'; link.click(); }
$('beforeFile').addEventListener('change', event => { const file = event.target.files[0]; if (file) loadImage(file, 'before'); }); $('afterFile').addEventListener('change', event => { const file = event.target.files[0]; if (file) loadImage(file, 'after'); }); $('demo').addEventListener('click', demo); $('clear').addEventListener('click', () => { state.before = null; state.after = null; state.output = null; $('beforeFile').value = ''; $('afterFile').value = ''; setStatus('Carga dos imágenes o genera el ejemplo.'); render(); }); $('mode').addEventListener('change', render); $('threshold').addEventListener('input', () => { $('thresholdValue').textContent = $('threshold').value; render(); }); $('mix').addEventListener('input', () => { $('mixValue').textContent = $('mix').value + '%'; render(); }); $('export').addEventListener('click', download); window.addEventListener('resize', render); demo();
