(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const sample = $('source').value;
  const state = { collection: null, lines: [], stations: [], map: null, layer: null };
  const R = 6371008.8, rad = value => value * Math.PI / 180, deg = value => value * 180 / Math.PI;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function setStatus(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
  function formatDistance(value) { return value >= 1000 ? (value / 1000).toLocaleString('es-ES', { maximumFractionDigits: 3 }) + ' km' : value.toLocaleString('es-ES', { maximumFractionDigits: 1 }) + ' m'; }
  function normalize(value) { const parsed = typeof value === 'string' ? JSON.parse(value) : value; if (parsed?.type === 'FeatureCollection') return parsed; if (parsed?.type === 'Feature') return { type: 'FeatureCollection', features: [parsed] }; if (parsed?.type && parsed.coordinates) return { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: parsed }] }; throw new Error('El documento no contiene GeoJSON reconocible.'); }
  function validPoint(point) { return Array.isArray(point) && Number.isFinite(Number(point[0])) && Number.isFinite(Number(point[1])) && Number(point[0]) >= -180 && Number(point[0]) <= 180 && Number(point[1]) >= -90 && Number(point[1]) <= 90; }
  function distance(a, b) { const p1 = rad(a[1]), p2 = rad(b[1]), dLat = p2 - p1, dLon = rad(b[0] - a[0]), h = Math.sin(dLat / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.min(1, Math.sqrt(h))); }
  function bearing(a, b) { const p1 = rad(a[1]), p2 = rad(b[1]), dLon = rad(b[0] - a[0]), value = deg(Math.atan2(Math.sin(dLon) * Math.cos(p2), Math.cos(p1) * Math.sin(p2) - Math.sin(p1) * Math.cos(p2) * Math.cos(dLon))); return (value + 360) % 360; }
  function positionAt(line, target, cumulative) { if (target <= 0) return { point: line[0], bearing: bearing(line[0], line[1] || line[0]) }; for (let i = 1; i < line.length; i += 1) { const start = cumulative[i - 1], segment = cumulative[i] - start; if (target <= cumulative[i] || i === line.length - 1) { const fraction = segment ? Math.max(0, Math.min(1, (target - start) / segment)) : 0; return { point: [line[i - 1][0] + (line[i][0] - line[i - 1][0]) * fraction, line[i - 1][1] + (line[i][1] - line[i - 1][1]) * fraction], bearing: bearing(line[i - 1], line[i]) }; } } return { point: line[line.length - 1], bearing: bearing(line[line.length - 2], line[line.length - 1]) }; }
  function lineParts(feature) { if (feature.geometry?.type === 'LineString') return [feature.geometry.coordinates]; if (feature.geometry?.type === 'MultiLineString') return feature.geometry.coordinates; return []; }
  function calculate(collection) { const lineFeatures = collection.features.filter(feature => ['LineString', 'MultiLineString'].includes(feature.geometry?.type)); if (!lineFeatures.length) throw new Error('La capa no contiene LineString ni MultiLineString.'); const interval = Number($('interval').value); if (!Number.isFinite(interval) || interval <= 0) throw new Error('El intervalo debe ser mayor que cero.'); const stations = [], lines = []; let lineNumber = 0, totalLength = 0; lineFeatures.forEach(feature => { lineParts(feature).forEach((raw, partIndex) => { const line = raw.filter(validPoint).map(point => [Number(point[0]), Number(point[1])]); if (line.length < 2) return; lineNumber += 1; const cumulative = [0]; for (let i = 1; i < line.length; i += 1) cumulative.push(cumulative[i - 1] + distance(line[i - 1], line[i])); const length = cumulative[cumulative.length - 1]; totalLength += length; const targets = []; if ($('includeEnds').checked) targets.push(0); for (let target = interval; target < length - 0.01; target += interval) targets.push(target); if ($('includeEnds').checked && length > 0.01) targets.push(length); targets.forEach((chainage, index) => { const positioned = positionAt(line, chainage, cumulative); stations.push({ id: stations.length + 1, line: lineNumber, part: partIndex + 1, station: index + 1, chainage, point: positioned.point, bearing: positioned.bearing, sourceName: feature.properties?.name || feature.properties?.nombre || 'Línea ' + lineNumber }); }); lines.push({ id: lineNumber, feature, partIndex, line, length, name: feature.properties?.name || feature.properties?.nombre || 'Línea ' + lineNumber }); }); }); if (!stations.length) throw new Error('No se pudieron generar estaciones con las geometrías válidas.'); state.collection = collection; state.lines = lines; state.stations = stations; $('lineCount').textContent = lines.length.toLocaleString('es-ES'); $('lengthTotal').textContent = formatDistance(totalLength); $('stationCount').textContent = stations.length.toLocaleString('es-ES'); $('intervalReadout').textContent = formatDistance(interval); $('stationBadge').textContent = stations.length + (stations.length === 1 ? ' estación' : ' estaciones'); $('quality').textContent = $('includeEnds').checked ? 'Incluye extremos' : 'Intervalos interiores'; $('quality').className = 'quality'; renderTable(); renderMap(); $('geojsonBtn').disabled = false; $('csvBtn').disabled = false; setStatus(`${stations.length} estaciones generadas sobre ${lines.length} líneas localmente.`); }
  function renderTable() { const rows = state.stations.map(item => `<tr><td>${item.id}</td><td>${esc(item.sourceName)}</td><td>${item.line}.${item.part}</td><td>${formatDistance(item.chainage)}</td><td>${item.point[1].toFixed(6)}°</td><td>${item.point[0].toFixed(6)}°</td><td>${item.bearing.toFixed(1)}°</td></tr>`).join(''); $('tableWrap').innerHTML = `<table><thead><tr><th>#</th><th>Línea</th><th>Tramo</th><th>Km acumulado</th><th>Latitud</th><th>Longitud</th><th>Rumbo</th></tr></thead><tbody>${rows}</tbody></table>`; }
  function stationCollection() { return { type: 'FeatureCollection', features: state.stations.map(item => ({ type: 'Feature', properties: { name: item.sourceName + ' · estación ' + item.station, line: item.line, part: item.part, station: item.station, chainage_m: Number(item.chainage.toFixed(3)), bearing_deg: Number(item.bearing.toFixed(3)) }, geometry: { type: 'Point', coordinates: item.point } })) }; }
  function popup(item) { return `<strong>${esc(item.sourceName)}</strong><br>Estación ${item.station} · tramo ${item.line}.${item.part}<br>Km acumulado: ${formatDistance(item.chainage)}<br>Rumbo: ${item.bearing.toFixed(1)}°`; }
  function initMap() { if (!window.L) { $('map').hidden = true; $('mapFallback').hidden = false; return; } state.map = L.map('map').setView([40.4168, -3.7038], 13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map); }
  function renderMap() { if (!state.layer) return; state.layer.clearLayers(); const lineGeo = L.geoJSON({ type: 'FeatureCollection', features: state.lines.map(line => line.feature) }, { style: { color: '#72e3be', weight: 4, opacity: .85 } }).addTo(state.layer); state.stations.forEach(item => L.circleMarker([item.point[1], item.point[0]], { radius: 6, color: '#071b25', weight: 2, fillColor: '#ffd47b', fillOpacity: .95 }).bindPopup(popup(item)).addTo(state.layer)); if (lineGeo.getBounds().isValid()) state.map.fitBounds(lineGeo.getBounds(), { padding: [25, 25], maxZoom: 16 }); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
  function exportCsv() { const lines = ['id,line,part,station,chainage_m,latitude,longitude,bearing_deg,name']; state.stations.forEach(item => lines.push([item.id, item.line, item.part, item.station, item.chainage.toFixed(3), item.point[1].toFixed(8), item.point[0].toFixed(8), item.bearing.toFixed(3), item.sourceName].map(value => '"' + String(value).replace(/"/g, '""') + '"').join(','))); download('estaciones-lineales.csv', '\ufeff' + lines.join('\n'), 'text/csv;charset=utf-8'); }
  function run() { try { calculate(normalize($('source').value)); } catch (error) { setStatus(error.message || 'No se pudieron generar estaciones.', true); } }
  $('calculateBtn').addEventListener('click', run); $('sampleBtn').addEventListener('click', () => { $('source').value = sample; $('interval').value = 500; $('includeEnds').checked = true; run(); }); $('interval').addEventListener('change', run); $('includeEnds').addEventListener('change', run); $('file').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { $('source').value = String(reader.result || ''); run(); }; reader.onerror = () => setStatus('No se pudo leer el archivo local.', true); reader.readAsText(file); }); $('geojsonBtn').addEventListener('click', () => download('estaciones-lineales.geojson', JSON.stringify(stationCollection(), null, 2), 'application/geo+json;charset=utf-8')); $('csvBtn').addEventListener('click', exportCsv); initMap(); run();
})();
